### ISSUE TITLE
Unable to verify repo 

### ISSUE THREAD

**Issue by Pjryes** [wstyres/Zebra#10]
Sources.list couldn’t be copied I don have permission to access documents. 

**Expected behavior**

**Screenshots

 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - AUPM Version [e.g. 1.0~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Which iOS version are you on?

**Comment by wstyres** [comment]
Could you also update to beta 2 and if you have Filza installed, press the "Open Documents Directory" button and once you're there take a screenshot?

**Comment by Pjryes** [comment]
I open Filza went to documents and then gave write acces permissions to the group and it worked

**Comment by Pjryes** [comment]
I’m on iOS 12.1.1 b3

**Comment by wstyres** [comment]
Could you list the full path of the Documents Directory?

**Comment by Pjryes** [comment]
/var/mobile/Documents then I changed the acces permissions. Here some screenshots  
https://photos.app.goo.gl/xnE81uznwrUTXMjw5

**Comment by wstyres** [comment]
Ah ok, this folder is in the wrong location. I'll see if I can get a fix out because changing the permissions in /var/mobile/Documents is a bit of a security issue

**Comment by wstyres** [comment]
@Pjryes could you set the permissions of /var/mobile/Documents back to what they were before(Read/Write/Execute, Read/Execute, Read/Execute) then update to the latest beta (1.0~beta3) and see if the problem still occurs? If it does, could you try pressing the button that opens the documents directory again and see if there is a new folder?

**Comment by Pjryes** [comment]
New folder was created, adding repo manually works however need to specify if it a “https//:” or “http//:” otherwise repo wont be able to verify, if I try to transfer repos from Cydia for some reason repos wont show unless you manually pull to refresh and transferring will take longer than beta2 maybe it’s nothing but you will have to go to sources and pull to refresh

**Comment by Pjryes** [comment]
But good job fixing the adding repos problem! 👏🏻

**Comment by wstyres** [comment]
Perfect, I’ll be adding something to not wait so long on repos that are down in the future. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
