### ISSUE TITLE
unable to modify package

### ISSUE THREAD

**Issue by xi7i6** [wstyres/Zebra#1004]
**Describe the bug**
I could not modify a package that needs to be either upgrading or downgrading, zebra only shows me remove button in the meanwhile Cydia can show me that modify button easily. 

**To Reproduce**
Steps to reproduce the behavior: try some paid packages that have DRM on its repository 

**Expected behavior**
I can modify the package if there is an update for it not only showing me a remove button.

**Screenshots**
![FDBC02FA-B185-4FC1-B356-6296A3CA0261](https://user-images.githubusercontent.com/55637002/77861448-a5d46680-721d-11ea-9492-0a2f5fd460ce.jpeg)
![7CE55475-2B6D-4D65-9954-CB62F9000117](https://user-images.githubusercontent.com/55637002/77861451-aa008400-721d-11ea-9bb5-4bdfb78a7bdf.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.3 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Latest
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Prevented this as of dcbf715aca8fa77db12574635b2d5eb8cdc68444
