### ISSUE TITLE
Dark mode not applying in Source Sections

### ISSUE THREAD

**Issue by qnblackcat** [wstyres/Zebra#1006]
**Describe the bug**
Darkmode doesnt work well on my Phone 

**To Reproduce**
It happens when you view any repo 

**Expected behavior**
Please fix it

**Screenshots**
https://imgur.com/P03MLTy
https://imgur.com/mbVThpB

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.1~beta3-1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**

**Additional context**

**Comment by aabosh** [comment]
Fixed in 10128bb2. Will be available in the next beta.
