### ISSUE TITLE
Search function is not showing all result

### ISSUE THREAD

**Issue by huyle0406** [wstyres/Zebra#1007]
**Describe the bug**
When I typed in search box in previous build and tap return key, It was showing all the result related to that keyword and in all repos. But in latest build it just showing result from some repo like packix or bigboss. I tried clean repo cache but it didn’t help anything.

**To Reproduce**
Use search function

**Screenshots**
Zebra Ver 1.1 beta 2
![D3587AFE-0667-40ED-87CB-83D19BC8C74D](https://user-images.githubusercontent.com/25667775/77882495-41e88700-728b-11ea-9e86-4118d96655f0.png)

Zebra ver 1.1 beta 3-1
![DE183E83-AFE5-4F2D-87E7-59438F430A1F](https://user-images.githubusercontent.com/25667775/77882532-59277480-728b-11ea-892b-6413bae85877.png)

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 3-1
 - Device Type [e.g. iPhone or iPad]: iPhone 8+
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
Fixed as of 9030742c.
