### ISSUE TITLE
Add a progress bar while downloading packages

### ISSUE THREAD

**Issue by aizoule** [wstyres/Zebra#101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PoomSmart** [comment]
For visibility, progress bar support for Zebra is being worked on progress-bar branch of this fork: https://github.com/PoomSmart/Zebra/tree/progress-bar

**Comment by wstyres** [comment]
Implemented by @PoomSmart and will be in the next beta
