### ISSUE TITLE
Verified clipboard url issue

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1016]
**Describe the bug**
The popup is still displayed when it is not a source url. #591 

https://github.com/wstyres/Zebra/issues/591#issuecomment-604562142

**Screenshots**
![0F69ACF5-EBBA-451A-897B-7540BF3C44F9](https://user-images.githubusercontent.com/40632436/78158672-838c5400-747c-11ea-9202-1765e30c20dd.png)

**Comment by PoomSmart** [comment]
Zebra should do the source verification in background for this issue to be eliminated.

**Comment by wstyres** [comment]
Was fixed by #1057. Seemed that the problem was that some sites could report 200 codes for URLs that didn't exist, possibly by design. @absidue's PR checks for a valid MIMEType when verifying repos.

**Comment by worldlydev** [comment]
Can confirm that this is fixed
