### ISSUE TITLE
Cannot remove author from filter

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1018]
**Describe the bug**
As the title says. Can add author to the filter but cannot remove

**To Reproduce**
Add any author and then swipe press remove. Nothing.

**Expected behavior**
Remove author from filter

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta4
 - Device Type [e.g. iPhone or iPad]: iphone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by PoomSmart** [comment]
Fixed as of e45e879eaf2d9d4a39074d3f0f079f8e10575714

**Comment by worldlydev** [comment]
Can confirm that this is fixed
