### ISSUE TITLE
Text color for dark mode in change language

### ISSUE THREAD

**Issue by rkycyku** [wstyres/Zebra#1019]
**Describe the bug**
The text color doesn’t change on darkmode for the change language future.

**Screenshots**
![910EFB21-B451-4BE5-B4CE-1B18554D7749](https://user-images.githubusercontent.com/48863882/78159468-e660f980-7442-11ea-8cfe-8b0d1f9b6ba0.png)
![CFE561EC-E019-4C97-8BBC-1FD1BC783C44](https://user-images.githubusercontent.com/48863882/78159475-e8c35380-7442-11ea-8892-ecaad93f5d8a.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta4
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by rkycyku** [comment]
![Uploading EB73E193-DD74-4244-947D-3B53E68AEF27.png…]()

Same for the section tab on filters

**Comment by wstyres** [comment]
Fixed sections color in bcd820046787b0e310bc2a4b21cf8e6d1c07660c.

Fixed language color in 167298972ba5673d8037ba4efdd24c77a031f36b.
