### ISSUE TITLE
Installation Bug

### ISSUE THREAD

**Issue by B0kCh01** [wstyres/Zebra#102]
**Describe the bug**
When doing a standard install of Filza from BigBoss, there is a red error message from Filza’s post-install uicache. Also, the installer bugs out and there is no respring button.

**To Reproduce**
1) Download Filza with all of its dependencies

**Expected behavior**
A clear and concise description of what you expected to happen:

Supposed to quickly install everything and *might* do a uicache  by Filza. After everything is done, a reprint button. Should appear.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue. No crashes

**Additional context**

**Comment by wstyres** [comment]
A screenshot of the read text would be helpful to solve the issue

**Comment by B0kCh01** [comment]
https://drive.google.com/file/d/1Tf3NJOjMPYJf8fRCYQ6KTHFmVPKRUUyB/view?usp=drivesdk

Worst way to send a screen shot but I’m on my phone

**Comment by wstyres** [comment]
That is odd, are you using Chimera by chance?

**Comment by B0kCh01** [comment]
Unc0ver 3.0.1 - I can update and test out the installation again

**Comment by B0kCh01** [comment]
Looks like updating fixed the red messages :/ but still stuck at finished importing local packages. Red errors was probably because of my human error by downloading the deps with chimera repo.

**Comment by Amplespencer** [comment]
this is an issue with filza’s installer and not one with zebra itself (I think)

**Comment by PoomSmart** [comment]
Closed due to inactivity.
