### ISSUE TITLE
[Bug] Incorrect title text color in Section Filter

### ISSUE THREAD

**Issue by yllshahini** [wstyres/Zebra#1021]
**Describe the bug**
If Zebra theme is set to Dark and Pure Black Mode you can't see which Section you're selecting to filter out until you tap it.

**To Reproduce**
Set Zebra display theme to Dark and Pure Black Mode.

**Expected behavior**
Section title to change color according to display theme.

**Screenshots**
![315C7679-81F2-48EA-AEBC-B0645D496C0C](https://user-images.githubusercontent.com/39761205/78161777-460cd400-7446-11ea-9ef3-bdf4a23132f0.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.0.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta4
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 3.8.0~b1

**Crash Log or System Log**
Bug does not result in crash.

**Additional context**

**Comment by yllshahini** [comment]
![53FC2309-A6F0-49A9-B70C-92CD0FCB5427](https://user-images.githubusercontent.com/39761205/78177916-28983400-745f-11ea-9f1c-9a5bf91da892.png)

Wish List also seems to be bugged.

**Comment by PoomSmart** [comment]
Any dark mode or theming tweaks installed?

**Comment by yllshahini** [comment]
I have Eclipse installed ,but it's not enabled for Zebra, and Blackout which darkens Springboard stuff.

**Comment by wstyres** [comment]
Fixed as of ffef3dbdc73d79d8b82f9bed14198efd8c691472.
