### ISSUE TITLE
Crash when importing sources from notes

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#1023]
**Describe the bug**

Title says it all

**To Reproduce**

^

**Expected behavior**

No crash

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 4
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

https://ghostbin.co/paste/vs25x

**Additional context**

**Comment by worldlydev** [comment]
Not really sure if this is a Zebra problem so just close it if it isn't.

**Comment by worldlydev** [comment]
Update:

To replicate this use the new erase sources button in Zebra's settings and then import your sources.list file into Zebra. Make sure to not reopen Zebra between those steps.

**Comment by worldlydev** [comment]
My sources.list file:

deb https://repo.xsf1re.kr/ ./
deb http://cydia.zodttd.com/repo/cydia/ stable main
deb https://poomsmart.github.io/repo/ ./
deb https://spicat.github.io/ ./
deb https://manolzrepo.github.io/ios/ ./
deb https://akusio.github.io/ ./
deb https://creaturesurvive.github.io/ ./
deb https://chr0nict.github.io/Nepeta-Mirror/ ./
deb https://limneos.net/repo/ ./
deb https://beta.apptapp.me/ ./
deb https://cokepokes.github.io/ ./
deb https://revulate.dev ./
deb http://repo.pixelomer.com/ ./
deb http://apt.thebigboss.org/repofiles/cydia/ stable main
deb https://pr0crustes.github.io/repo/ ./
deb https://repo.chariz.com/ ./
deb https://yungspecht.github.io/ ./
deb https://skitty.xyz/repo/ ./
deb http://getdelta.co/ ./
deb https://gilesgc.github.io/repo/ ./
deb https://repo.incendo.ws/ ./
deb https://shepgoba.me/repo/ ./
deb https://thisrepo.justsucksass.com/ ./
deb https://apt.bingner.com/ ios/1674.10 main
deb https://repo.packix.com/ ./
deb http://qwertyuiop1379.com/ ./
deb http://apt.modmyi.com/ stable main
deb https://getzbra.com/beta/ ./
deb https://xtm3x.github.io/repo/ ./
deb https://repo.twickd.com/ ./
deb https://getzbra.com/repo/ ./
deb https://apt.alfhaily.me/ ./
deb https://ib-soft.net/cydia/ ./
deb https://repo.supercharge.app/ ./
deb http://repo.bonventre.ch/ ./
deb https://creaturecoding.com/repo/ ./
deb https://sparkdev.me/ ./
deb https://julioverne.github.io/ ./
deb https://rpetri.ch/repo/ ./
deb https://kingmehu.yourepo.com/ ./
deb https://samgisaninja.github.io/ ./
deb https://ryleyangus.com/repo/ ./
deb https://repo.dynastic.co/ ./
deb https://cokepokes.github.io ./
deb https://captinc.github.io/ ./

# Added at 2020-04-01 16:35:56 +0000
deb https://apt.htv123.com/ ./

**Comment by wstyres** [comment]
How fast are you doing this? There is a period of time between zebra closing and it actually exiting. If you’re doing this quick enough you’ll be opening the app before it exits.

**Comment by worldlydev** [comment]
https://imgur.com/a/HblfKzL

But it keeps happening after that.

Even after opening the app normally after it crashes once from the repo import it keep crashing. I have to kill the app in the app switcher to make it work again.

**Comment by wstyres** [comment]
Should be fixed as of 4786f0422c64d2d0e1397842a7f63baadc6a75ff.

**Comment by wstyres** [comment]
@worldlydev any confirmation?

**Comment by eve0415** [comment]
Can confirm its fixed
