### ISSUE TITLE
No section icon in section filters

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#1024]
**Describe the bug**

For sections without section icons in Zebra the icon section blank in the section filters.

**Expected behavior**

I expect it to show an icon if some sort. Either of these would do:
![343BC202-5662-4772-85AC-CE613C04DF0B](https://user-images.githubusercontent.com/51668635/78168658-97ba5c00-7450-11ea-93c2-d46a64dddc18.jpeg)
![60481232-1E14-4044-B762-0202306941AB](https://user-images.githubusercontent.com/51668635/78168664-99841f80-7450-11ea-980d-775872b0789a.jpeg)

**Screenshots**

![A885405F-66A9-4E7F-BB9A-213CE8612F36](https://user-images.githubusercontent.com/51668635/78168677-a143c400-7450-11ea-8d37-99a83689da8e.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 4
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by c939984606** [comment]
Describe the bug：
If the icon path is “Cydia:///Aplication/........”  zebra can not dispaly the icon ,cydia can
if the icon path is "http:// ...../...../icon.png"   cydia can not dispaly the icon ,zebra can.

Screenshots：
http://image.abcdl.cn/IMG_0056.PNG
http://image.abcdl.cn/IMG_0055.PNG

- iOS Version [ 13.3
- Zebra Version : 1.1 beta 4
- Device Type : iPhone 11 pro ,8plus 6plus  ipad pro ipad mini2.
- Jailbreak Type : Uncover and checkra1n

**Comment by eve0415** [comment]
> If the icon path is “Cydia:///Aplication/........” zebra can not dispaly the icon ,cydia can

https://github.com/wstyres/Zebra/wiki/Repositories#custom-section-icons
Zebra works different way, if I read it correctly

**Comment by c939984606** [comment]
> I read it correctly

OK，thanks 。

**Comment by c939984606** [comment]
may i ask how did the zebra show the package icon in Depiction page.

http://image.abcdl.cn/IMG_0309.PNG

**Comment by absidue** [comment]
@c939984606 `Icon: https://yoururl.com/image.png`

**Comment by wstyres** [comment]
Should be fixed as of 33ec49a3.

**Comment by worldlydev** [comment]
Can confirm that this is fixed in the latest beta.
