### ISSUE TITLE
Filter Missing Authors

### ISSUE THREAD

**Issue by tdadvocate** [wstyres/Zebra#1036]
**Describe the bug**
Many authors on the Packix repo appear to be missing after the change to emails in beta 4. Authors like mostafa and unalkuru for example. 

**To Reproduce**
Just try to filter authors in the settings by these two names and they will not populate on the list. 

**Expected behavior**
Should show up in list to be filtered out of the changes tab. 

**Device Information (please complete the following information):**
 - iOS Version: 13.4
 - Zebra Version: 1.1~beta4
 - Device Type: iPhone X
 - Jailbreak Type: checkra1n 0.10.0 

**Additional context**
While I could filter out these authors in 1.1~beta3, it appears that however the new list system works, some authors are missed.

**Comment by PoomSmart** [comment]
Closed in favour of #1034
