### ISSUE TITLE
Blocking Packages/Authors From Depictions

### ISSUE THREAD

**Issue by tdadvocate** [wstyres/Zebra#1037]
**Is your feature request related to a problem? Please describe.**
With the upcoming filter feature in 1.1 and the presence of the bug with some authors not being able to be filtered out in 1.1~beta4 it would be nice to have this. It’s also just future proofing so people wouldn’t always have to remember names as they went between the changes tab the whole way into settings for filters. 

**Describe the solution you'd like**
Inside of the depiction view you could long press on the package identifier or author name and the option to add these items to their respective filter would pop up with a yes/no options. 

**Describe alternatives you've considered**
Perhaps a left to right swipe on the package in the changes tab to present “filter package/author” options similar to the right to left swipe for the “downgrade/install” options.

**Comment by wstyres** [comment]
Added in the 1.2 beta
