### ISSUE TITLE
queue label doesn’t clear in the search tab

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1038]
**Describe the bug**
As the title says. 

**To Reproduce**
1. Search anything.
2. Queue
3. Clear Queue

**Expected behavior**
remove the queue label

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta4
 - Device Type [e.g. iPhone or iPad]: iphone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by PoomSmart** [comment]
Fixed as of 4e5632902e9360747dd3e9d1ba67e10a3747b915
