### ISSUE TITLE
Zebra crashes when I try to go inside the "Filters" section

### ISSUE THREAD

**Issue by elvergal** [wstyres/Zebra#1040]
**Describe the bug**
Explained on the title

**To Reproduce**
Steps to reproduce the behavior: Not being able to go inside "Filters" settings

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 b4
 - Device Type [e.g. iPhone or iPad]: iPhone XS Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**

https://ghostbin.co/paste/8y7af

**Additional context**
Not many tweaks installed

**Comment by PoomSmart** [comment]
Prevented as of 51df15dbbf1d6e719a6e6f2fd825a0ef42865c1a

**Comment by mwoolweaver** [comment]
I was having the same issue but since I updated to Zebra 1.1-beta5 I noticed this behavior:

App crashes when trying to access filters until you reset Zebras' setting and re-add the filters then the filters section no longer cause app to crash. 


iPhone 8 Plus
Zebra 1.1-beta5
checkra1n
