### ISSUE TITLE
Some elements remain in the OLED dark mode state when turned to normal dark mode

### ISSUE THREAD

**Issue by async1wake** [wstyres/Zebra#1041]
**Describe the bug**
If you enable Pure OLED mode and disable it and go back to the normal dark mode, there are elements that still stay in the pure black state

**To Reproduce**
Enable dark mode, then enable and disable Pure OLED mode

**Expected behavior**
For it to show a darker grey for the background element. (As displayed below in the settings screenshot)

**Screenshots**

OLED elements still active: https://i.imgur.com/Zu6wvFP.jpg

What it “should” be: https://i.imgur.com/0WyJt5M.jpg

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: **13.3**
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: **1.1~beta 4**
 - Device Type [e.g. iPhone or iPad]: **iPhone X (iPhone 10,1)**
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: **checkra1n**

**Crash Log or System Log**
n/a

**Comment by wstyres** [comment]
Duplicate of #1020
