### ISSUE TITLE
Bizarre are spacing of device information on the homepage

### ISSUE THREAD

**Issue by async1wake** [wstyres/Zebra#1042]
**Describe the bug**
Very minor, but the spacing at the bottom of the home page between the device info seems to be static causing weird results when tweaks like Saw cut down on the bottom space between the tab bar, and screen

**To Reproduce**
Steps to reproduce the behavior: Install Saw, and scroll to the device info part of the home page

**Expected behavior**
For the spacing to be “dynamic” and compress down when tweaks like saw are enabled, such as the way Cydia handles it: https://i.imgur.com/VLBNgxX.png

**Screenshots**
With UDID (Cropped for censorship purposes): https://i.imgur.com/w2snouU.jpg

Without UDID: https://i.imgur.com/0FjfRQW.jpg

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: **13.3**
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: **1.1~beta 4**
 - Device Type [e.g. iPhone or iPad]: **iPhone X (iPhone 10,1)**
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: **checkra1n**

**Crash Log or System Log**
n/a

**Comment by wstyres** [comment]
This isn't a bug, your screen is larger than the amount of content on Zebra's homepage.
