### ISSUE TITLE
Better repo adding, instead of having a pop up every time you have a copied URL

### ISSUE THREAD

**Issue by async1wake** [wstyres/Zebra#1043]
**Is your feature request related to a problem? Please describe.**
Whenever you go to your sources tab and you happen to have a full url copied to your clipboard, zebra always opens a prompt to add that url. This is fine until you no longer have repo URL’s copied and it begins prompting to add random sites that are obviously not apt based repos: https://i.imgur.com/1eFW5De.png

**Describe the solution you'd like**
Instead have a small menu appear when you hit the “+” button in the top left corner that asks if you would like to add from clipboard, url, or multiple URL’s (Apologies in advance for the incredibly crude mockup): https://i.imgur.com/Yn5YX73.jpg

**Describe alternatives you've considered**
Have some other way of activation to have Zebra scan your clipboard. (But I like the idea of a menu personally)

**Comment by wstyres** [comment]
The current behavior of the clipboard pop up is a bug, it is only supposed to show up if there is a valid repo URL in your clipboard which negates the need for a menu.
