### ISSUE TITLE
0 sources

### ISSUE THREAD

**Issue by jack2247** [wstyres/Zebra#1045]
One day suddenly all the sources from zebra disappeared and it’s not showing any sources even after I add them from community sources or manually. Already tried rootfs and then jailbreak again still the issue persists. Tried using and older version but that also didn’t help. 

In the photos i tried to install bigboss repository and it showed me like this.
![BE8F3D75-3C6B-4E75-8456-0CB8EB87089D](https://user-images.githubusercontent.com/56305771/78465874-a2a71200-7718-11ea-96e4-629c80d1b63a.png)
![4F7EBECF-99B6-4F91-97CA-2BC27A19E4D5](https://user-images.githubusercontent.com/56305771/78465880-a6d32f80-7718-11ea-96e2-ab54132bacc2.png)

iOS version - 13.3
Zebra version - 1.0.7
Device - iPhone 6s
Jailbreak - uncover 4.3.1

**Comment by eve0415** [comment]
try "drop table" in the setting

**Comment by jack2247** [comment]
> try "drop table" in the setting

Tried it, still the issue persists

**Comment by jack2247** [comment]
> You might have to delete Zebra's database entirely and open the app again in order for it to reset. Your sources look like they're still accessible in Zebra's sources.list.

Okay, I was also thinking of reseting the app but wasn’t able to find a way to do it, so can you please tell me. Thanks in advance.

**Comment by eve0415** [comment]
Open Zebra’s document directory from the setting and remove zebra.db

**Comment by jack2247** [comment]
> Open Zebra’s document directory from the setting and remove zebra.db

That worked like a charm, I am really grateful to you, thanks a lot man.
