### ISSUE TITLE
Swiped option inside of repository & make repo don’t have icon, put one 🤷‍♂️

### ISSUE THREAD

**Issue by kelvin1300** [wstyres/Zebra#1046]
I request that inside of repo were said **ABC & DATE** we can swipe left to right to go to those options..!!! 
![07457E85-78AC-4789-B7A8-356235EDAE77](https://user-images.githubusercontent.com/55414105/78499735-62e42880-7720-11ea-91d1-2c2900cd3313.png)

Another option maybe...
Outside of repo that doesn’t have images just like this one 
![41586636-5F30-4FEA-9856-C4AB0F623F6E](https://user-images.githubusercontent.com/55414105/78499695-3cbe8880-7720-11ea-91c9-71b453403a91.jpeg)
put the Zebra icon normally and remove this sign of "(?)"

**Comment by wstyres** [comment]
The "ABC" and "Date" headers will be removed at some point in the future in favor of a better UI so since we already have plans to change it adding new behavior isn't preferable.
