### ISSUE TITLE
Add slider at the right of the screen for easy navigation on sources and tweaks

### ISSUE THREAD

**Issue by T-K0** [wstyres/Zebra#105]
**Is your feature request related to a problem? Please describe.**
It would be easier to navigate through sources and tweaks by their first letter rather than just have to scroll all the way to the letter

**Describe the solution you'd like**
Add the little bar on the right side of the screen to scroll through tweaks and sources by their first letter like in cydia. I just don’t wanna swipe through all the tweaks, it will be useful and just locate easier.

**Additional context**
![1C24EFC3-CDDC-499B-8F0F-476DBCE83B1E](https://user-images.githubusercontent.com/49242929/58019171-e7ab6100-7ad2-11e9-909e-e8b9af10dfc4.jpeg)

**Comment by aabosh** [comment]
Added in the [latest commits](https://github.com/wstyres/Zebra/commit/963b2a58781f6db674b30ee42cf59083ca60c926).
