### ISSUE TITLE
Haptic touch hides depiction

### ISSUE THREAD

**Issue by MartinsZar** [wstyres/Zebra#1058]
**Describe the bug**
If I haptic touch a link or image in a depiction and then scroll it hides the depiction.

**To Reproduce**
1. Open a package with depiction
2. Haptic touch a image or link
3. Dismiss the haptic touch interface
4. Scroll

**Expected behavior**
It shouldn't hide.

**Screenshots**
https://drive.google.com/file/d/1gAQH-b_n7LKZVvGMSi_zY7NHZTDg3dsS/view?usp=drivesdk

**Device Information (please complete the following information):**
 - iOS Version:  13.3
 - Zebra Version:  1.1~beta4
 - Device Type: iPhone
 - Jailbreak Type:  unc0ver

**Comment by wstyres** [comment]
I'll have to look at this more, whats the repo that this is occurring on?

**Comment by MartinsZar** [comment]
The repo that is in the screen recording and where it constantly happens is: https://martinszar.github.io/
But it also happens on Dynastic, Twickd and even the Zebra repo. Packix blocks haptic touch (I think?) and it only allows me to copy the image, so Packix isn't affected.

**Comment by PoomSmart** [comment]
Can confirm it does it with an image inside a depiction from Chariz.

**Comment by PoomSmart** [comment]
This issue has been eliminated in the beta version of Zebra: 1.2b
