### ISSUE TITLE
Lines missing

### ISSUE THREAD

**Issue by MartinsZar** [wstyres/Zebra#1059]
**Is your feature request related to a problem? Please describe.**
When viewing a depiction a few separator lines are missing. One below the icon and name and one below "Installed Files" (if a package isn't installed it obviously shows"More by this Developer", which has a line below it) I also show that in the screenshots below. 

**Describe the solution you'd like**
Add the lines. At top full width and at the bottom either full width or with a small blank space at the left.

**Describe alternatives you've considered**
I think that the above solution is easy enough. It doesn't have to be added, but it could be cool.  

**Additional context**
Screenshot 1:
![85347EA7-2423-4D79-81FF-1A12CD550524](https://user-images.githubusercontent.com/46902701/78938860-ad1c2f80-7abb-11ea-8005-43d1effdb462.png)
Screenshot 2:
![D8C2F148-9B19-46C3-A561-7FD6D8EACB7E](https://user-images.githubusercontent.com/46902701/78938893-bc02e200-7abb-11ea-928e-d5ef3cf0eb17.png)

**Comment by wstyres** [comment]
I suppose this is likely due to there being extra table cells above and below them. Since we're redesigning the depictions in 1.2 I don't think that we'll fix such a small bug unless it appears again in the redesign.
