### ISSUE TITLE
Need better list file validation and error handling/reporting when importing list files via share sheet actions.

### ISSUE THREAD

**Issue by mwoolweaver** [wstyres/Zebra#1067]
**Describe the bug**

App crashes when importing (via share sheet action) a .list file that is not formatted properly. 

1. Save file at the bottom of this comment.
2. Attempt to add via share sheet action.
3. ???
4. Zebra crashes

**Expected behavior**
App opens and produces an error message informing user of what is wrong.

**Device Information (please complete the following information):**

 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.4>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1-beta4>
 - Device Type [e.g. iPhone or iPad]: <iPhone 8 Plus>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <checkra1n>

**Crash Log or System Log**

Please provide a Crash Log to help us solve the issue.
[crash log](https://github.com/wstyres/Zebra/files/4468147/text.txt) as reported by cr4shed

**Additional context**

[not correctly formatted .list file](https://github.com/wstyres/Zebra/files/4468144/mobilesubstrate.txt) 

It should look like this 
`deb https://checkra.in/assets/mobilesubstrate/ ./`

But it looks like this 

` deb https://checkra.in/assets/mobilesubstrate/ . `

More info on .list file formatting [here](https://wiki.debian.org/SourcesList#sources.list_format)

**Comment by PoomSmart** [comment]
Mitigation (crash prevention) implemented in 820ca1b5102e6ab35b2c409f204d6632c63da087

**Comment by mwoolweaver** [comment]
Zebra 1.1-beta5 fixed this issue but there’s still a few things not exactly right


1. the app will still crash (when it should show a not valid source) if there is nothing after the url. Ex: `deb https://checkra.in/assets/mobilesubstrate/ `

2. It still validates the url if there’s only a (.) after the url. Ex: `deb https://checkra.in/assets/mobilesubstrate/ .`

**Comment by PoomSmart** [comment]
Improved in dbcc96d565fb39bdb48e09d56b6245e3e3fba35e
