### ISSUE TITLE
Warning for pirate repos

### ISSUE THREAD

**Issue by relisiuol** [wstyres/Zebra#107]
**Is your feature request related to a problem? Please describe.**
=> Zebra should display a warning message when someone try to add a pirate repo URL, even with a list.

**Describe the solution you'd like**
=> Why not use CoolStar API? https://github.com/Sileo/FlaggedRepoAPI

**Describe alternatives you've considered**
=> Alternatively, I can write an API with ios-repo-updates.com (it's my website) and I can add some trusted developers as managers on my backend to flag new pirate urls. My cron script check all repos with CoolStar API each 15 mins and I have my own flag system to not display pirate repos on my website. I track pirate repos because I use ios-repo-updates.com database to take down piracy on yourepo.com (it's also my website) by using MD5sums or SHA256 hashs as Content-ID.

**Comment by dezqo** [comment]
I disagree... I believe that adding a warning message when a user adds a certain repository makes no sense, regardless of the packages being served.
After all It is the responsibility of the user to add repositories that they trust and not up to the maintainer of this app to curate a list of "blacklisted" repositories.

It would make more sense to display a disclaimer about the risks of adding new repositories when a user first opens the "Sources" tab.

The principle of "flagging" a repo in general should be thoroughly discussed, I personally believe that users should be free in adding whatever repositories they want, after all they should be aware of the risks that come with that.

**Comment by Amplespencer** [comment]
@dezqo I agree, kinda like the thing that shows up when you first open an ios app

**Comment by Amplespencer** [comment]
“adding sources you don’t trust is dangerous and it is recommended you only add repos other people confirm are not malicious or have a malicious intent” (fullscreen ios like alert)


I understand (blue button at bottom)

the page then swipes down when you press the button

**Comment by wstyres** [comment]
This will probably make its way into the "first open" dialog that we will have when Zebra is a bit farther along but I don't think that it will be done in a way where it will alert the user every time.

**Comment by Amplespencer** [comment]
that’s what I meant, but show it on the sources tab (one time) or add it to
the main dialogue
