### ISSUE TITLE
Featured packages from 'source featured' don't display

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#1077]
**Describe the bug**

Featured packages don't display on the homepage when featured packages are featured by the source. They display when they are random.

**To Reproduce**

🤷‍♂️

**Expected behavior**

I expect the featured packages to always display when enabled.

**Screenshots**

![AC0B2CE4-3EA9-4BF4-BF6D-A25B2D66EE3F](https://user-images.githubusercontent.com/51668635/79165903-5e84d300-7de4-11ea-8586-21646474b4ab.png)

Screen recording:
https://imgur.com/a/4BNYSis

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 5-1
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by worldlydev** [comment]
![61781348-853A-4B4C-8658-98432FA2E58B](https://user-images.githubusercontent.com/51668635/79166075-b9b6c580-7de4-11ea-8e8c-4e8e85ad9456.png)

**Comment by CanerKaraca23** [comment]
It's working when I switched to random packages. But sources featured isn't working.

**Comment by wstyres** [comment]
As a debug step, could you delete featured.plist from Zebra's documents directory?

**Comment by worldlydev** [comment]
> As a debug step, could you delete featured.plist from Zebra's documents directory?

Doing this actually fixed the issue.
![463BBA13-B6E8-4304-A84B-7011B57DB7AA](https://user-images.githubusercontent.com/51668635/79706109-6519bb80-82b8-11ea-9a9d-3204de794259.png)

**Comment by wstyres** [comment]
Thought so, mitigation for this in 144ee6171f582bfa00e9f7373faedf3f9408204e but I'll add in some extra downloads to ensure it doesn't empty again.

**Comment by wstyres** [comment]
Featured packages are now cached when viewing an individual source page as of acd0d84c0869072b88295e05780cca298aa02d1a. Issue should be fixed.
