### ISSUE TITLE
Cannot change the icon from zebra’s setting

### ISSUE THREAD

**Issue by LK1105** [wstyres/Zebra#1078]
Unable to change zebra’s icon from setting. Every time changed icon, it will be reset to default one.

**Comment by worldlydev** [comment]
Do you have a theme applied with a theming engine?

**Comment by wstyres** [comment]
Could you post a screen recording of the issue?

**Comment by LK1105** [comment]
Yes https://drive.google.com/file/d/1blQmWCNjcfj6Oi4-qjDeQPKKP4bCFuGk/view?usp=drivesdk

**Comment by LK1105** [comment]
> Do you have a theme applied with a theming engine?

No, I didn’t apply theme

**Comment by wstyres** [comment]
Can you try running the `uicache` command and try changing the icon again? Sometimes Zebra doesn't have the proper permissions to change its icon because it was installed improperly.

**Comment by LK1105** [comment]
Ok, I tried and it worked:) thank you. But previous version can change instantly
