### ISSUE TITLE
Cannot cancel authentication when trying to buy paid package

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1079]
**Describe the bug**
As the title says.

**To Reproduce**
Press “Install” or the cost of the paid package to proceed to authentication

**Expected behavior**
Cancel

**Screenshots**

https://cdn.discordapp.com/attachments/572784833714192395/699388604807381083/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.3>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <beta5-1>
 - Device Type [e.g. iPhone or iPad]: <iPhone>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <checkra1n>

**Comment by wstyres** [comment]
Another instance of this occuring: https://discordapp.com/channels/566255609251364864/572784833714192395/700129718074212474

**Comment by wstyres** [comment]
Should be fixed as of e9aa09c9d37615c70c48cec1340473bbc825503f.
