### ISSUE TITLE
Cannot cancel action in console

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1081]
**Describe the bug**
In the console, while Zebra is downloading package or doing any action, I cannot cancel the operation. 

**To Reproduce**
Try to install (mainly) / remove any package 
In the console, press cancel. (while downloading or not)
The console says "Done".
After a few seconds , it says Done downloading *package*
(Install Complete)

**Expected behavior**
Cancel the operation

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.1>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <beta5-1>
 - Device Type [e.g. iPhone or iPad]: <iPhone>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <checkra1n>

**Comment by PoomSmart** [comment]
@wstyres We should just uncomment this line.. https://github.com/wstyres/Zebra/blob/c074d25471bda88372a5f53ec60c12446597df49/Zebra/Console/ZBConsoleViewController.m#L397

**Comment by wstyres** [comment]
Fixed as of 45a35578b299f68f74ff8ba2d6814dd6bd949e4a.
