### ISSUE TITLE
Might have found something you've been looking for. An APT flag to remove essential packages.

### ISSUE THREAD

**Issue by mwoolweaver** [wstyres/Zebra#1084]
https://github.com/wstyres/Zebra/blob/e460563a9fe94d41902abc96b47f72c17ccc0afc/Zebra/Queue/ZBQueue.m#L244

I found the flag/option you were looking for in `apt` and confirmed it works on `apt 1.8.2` found on https://apt.bingner.com

[--allow-remove-essential](https://manpages.debian.org/unstable/apt/apt-get.8.en.html#OPTIONS)

  > Force yes; this is a dangerous option that will cause apt to continue without prompting if it is removing essentials. It should not be used except in very special situations. Using it can potentially destroy your system! Configuration Item: APT::Get::allow-remove-essential. Introduced in APT 1.1.

so the end command would look like:

`apt --allow-remove-essential remove [package_name]`

Hopefully I implemented this correctly in #1085. 

cc @wstyres 

![7985B383-2DDA-4DD9-B933-9C8AC1578174](https://user-images.githubusercontent.com/5729320/79211077-568c5980-7e0b-11ea-82ce-71269c2f660d.jpeg)

**Comment by wstyres** [comment]
Closing this to move the discussion to #1085
