### ISSUE TITLE
No upgrade option in Modify of new beta5

### ISSUE THREAD

**Issue by netuserxda** [wstyres/Zebra#1087]
**Describe the bug**

Updated zebra to new beta 5 yesterday and I have no upgrade option in modify menu when and upgrade is available 

**To Reproduce**

check above

**Expected behavior**

**Screenshots**
![9387F96E-B255-4C90-9E6F-5E5E8D2DAD51](https://user-images.githubusercontent.com/7758573/79293172-0069f580-7ea1-11ea-83ea-2b204b512790.png)
![F1ED7339-9EF5-4D2D-B83B-57982DB178CF](https://user-images.githubusercontent.com/7758573/79293203-1677b600-7ea1-11ea-92c2-c349e7bd9aed.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta5-1
 - Device Type [e.g. iPhone or iPad]: iphone xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by yur1xpp** [comment]
There’s no upgrade in slide over menu too on “Changes” tab, but available on “Package ” tab. https://i.imgur.com/moRHWjp.png

**Comment by absidue** [comment]
@yur1xpp From a UX standpoint I think makes sense to keep the upgrade in only the packages tab.

**Comment by yur1xpp** [comment]
Personally, no. It complicated the usage. Now while browsing what's new package coming up and if there's new update, instead of just swipe and upgrade from the changes tab, user will now have to take the extra mile to either go inside the depiction to upgrade, or go to package tab to do so. Besides, I believe majority of users only go to the "Package" to remove some tweaks.

**Comment by wstyres** [comment]
Should be fixed as of 1873eeadc0e81ae5852d8a849852d064658658c6.

**Comment by wstyres** [comment]
Can this still be reproduced?

**Comment by eve0415** [comment]
Can confirm that it has been fixed in beta 6
