### ISSUE TITLE
Minor search UI bug

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#1090]
**Describe the bug**
When searching for something and scrolling to the bottom, it cuts off the last option. 

**To Reproduce**
1. Search for anything in the search tab (as long as it has enough packages to fill up the screen)
2. Scroll all the way to the bottom 
3. Scroll up to see there is still one extra package available. 

**Expected behavior**
To show the last package on the screen without having to scroll up a little bit. 

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/699939642832715826/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta 5-1
 - Device Types: XS Max
 - Jailbreak Type: unc0ver 4.3.1

**Additional context**
It does only happen in the Search tab. Not in any of the other tabs.

**Comment by JakeValenzuela** [comment]
I want to note that this is because you have packages queued to install. This does not occur otherwise.

**Comment by Greigh** [comment]
I should've added that. Thanks.

**Comment by wstyres** [comment]
Should be fixed as of 495df9a61061af5534128fdb19da3cfc7ce35223.
