### ISSUE TITLE
Tap on tab bar icons to scroll back up to top

### ISSUE THREAD

**Issue by CanerKaraca23** [wstyres/Zebra#1093]
**Is your feature request related to a problem? Please describe.**
No, it's only a feature request.

**Describe the solution you'd like**
Tapping the icons on the sections to send to the top of the page like AppStore and other apps. It's a useful feature I think.

**Comment by wstyres** [comment]
Implemented in 69ef7795affc1fc20d5f72852768cc1504d9158a.
