### ISSUE TITLE
Search History Issue

### ISSUE THREAD

**Issue by CanerKaraca23** [wstyres/Zebra#1097]
**Describe the bug**
When I click on the search history, there is no result.

**To Reproduce**
Search any tweak and click search again on history.

**Expected behavior**
Fix

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/700359463512571924/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <12.4.6>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1 beta5-2>
 - Device Type [e.g. iPhone or iPad]: <iPhone 5s>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <checkra1n>

**Crash Log or System Log**
-

**Additional context**
And you can see my keyboard is in light mod on dark mode Zebra.

**Comment by PoomSmart** [comment]
I myself have iOS 12.4 device but cannot reproduce the issue.

**Comment by CanerKaraca23** [comment]
> I myself have iOS 12.4 device but cannot reproduce the issue.

I'm not using instant search. May be because of this.

**Comment by wstyres** [comment]
Fixed as of 6f518b567c66f8e786b4c31d767aeb1050210cd9.

**Comment by wstyres** [comment]
@CanerKaraca23 See if you can reproduce this, If not please close the issue.

**Comment by CanerKaraca23** [comment]
I can confirm its fixed on latest beta. Closed.
