### ISSUE TITLE
In Repo Search

### ISSUE THREAD

**Issue by CanerKaraca23** [wstyres/Zebra#1101]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Only in repo search feature. Example Packix is a very big repo and its very hard to find any tweak. But I don't wanna search same tweaks from other repos.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by wstyres** [comment]
#630 also suggests this so I'll close this issue.
