### ISSUE TITLE
Repo not showing packages 

### ISSUE THREAD

**Issue by thedozo** [wstyres/Zebra#1102]
**Describe the bug**
When I refresh sources and check for changes, it not showing packages from all repo, manual check for package list in individual repo(s) showing 0 packages 

**To Reproduce**
Open zebra, refresh sources and check for changes

**Expected behavior**
Proper refresh and all repo packages need to be shown 

**screenshots**
Added below.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.8
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Checkra1n

**Crash Log or System Log**
N/A

**Additional context**

**Comment by thedozo** [comment]
Screenshots are added.
First one is from zebra, showing no packages
But second one from Cydia is showing packages 
Repo name: poomsmart
![B574B7DC-81DE-483F-8423-3772D8203BE9](https://user-images.githubusercontent.com/55230761/79637868-39a5ac80-81a4-11ea-94d2-4e14377caff6.jpeg)
![81434A3C-BBF1-42A3-9CD7-03FB92BDF98C](https://user-images.githubusercontent.com/55230761/79637884-4de9a980-81a4-11ea-8f33-5425b2ea9f68.jpeg)

**Comment by wstyres** [comment]
What is the URL of the repo?

**Comment by wstyres** [comment]
I am able to see all of the package's on PoomSmart's GitHub repo. Have you tried updating to the beta?

![Simulator Screen Shot - iPhone 11 Pro - 2020-04-18 at 11 58 20](https://user-images.githubusercontent.com/19736790/79642511-eadc2080-816b-11ea-83ab-26b99bb8a8a4.png)

**Comment by thedozo** [comment]
> I am able to see all of the package's on PoomSmart's repo. Have you tried updating to the beta?
> 
> ![Simulator Screen Shot - iPhone 11 Pro - 2020-04-18 at 11 58 20](https://user-images.githubusercontent.com/19736790/79642511-eadc2080-816b-11ea-83ab-26b99bb8a8a4.png)

Upgrade to beta solved the issue. Thanks.
