### ISSUE TITLE
Count of installed dylibs

### ISSUE THREAD

**Issue by samwllson9478** [wstyres/Zebra#1104]
**Is your feature request related to a problem? Please describe.**
No just an extra feature that counts the Dylibs and shows it in your downloaded section like tweak count on cydia
**Describe the solution you'd like**
A dylib counter from all the tweaks you downloaded to see how many you have effecting your phone. I like that more than a normal tweak counter because this counts the Dublin's
**Describe alternatives you've considered**
Anything like what I described above
**Additional context**

**Comment by wstyres** [comment]
We're going to implement an installed package count in #956. I think that would be more useful than a count of installed dylibs.
