### ISSUE TITLE
“More by this developer” feature not working in the latest Zebra beta.

### ISSUE THREAD

**Issue by Garydunlop00** [wstyres/Zebra#1105]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Which package or which developer you are able to reproduce this issue? Also, please update your issue with detailed information.

**Comment by wstyres** [comment]
Should be fixed as of f1510d43fcf8cbae9d6d3d5d144733ad9616a623.
