### ISSUE TITLE
Keep the screen on while refreshing sources

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#1107]
**Is your feature request related to a problem? Please describe.**
I usually open Zebra if there's new package/update, and not sure why lately with the latest beta, the refreshing of sources take minutes to complete, almost on par with Cydia. Put that aside, sometime when I didn't open Zebra for a long time, the refreshing will take quite some time to finish too, and I'll have to keep touching the screen for refreshing to continue.

**Describe the solution you'd like**
To keep the screen on while Zebra refreshing sources, like how it keeps the screen on while console is displaying.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by wstyres** [comment]
Could you go into settings > reset and press "clear sources cache" maybe we can see which source is taking so long?

**Comment by yur1xpp** [comment]
hah, as you suggested, it was **_apt.golddavid.com_**. Didn't know I could see that in "clear sources cache", thank you.

Btw, is it possible to add a disable feature to added sources? For example in my this particular case right now, apt.golddavid.com is essential for some developing tool, but it take too long to load, so I might want to disable it for now. So that next time when I wanted to get some tweak from there I don't have to search for the source on reddit again.

**Comment by wstyres** [comment]
Yeah right now clear sources cache clears updates too, I'll see if I can shift things around in order to prevent that from happening.

As for the disable feature I'm not sure, if we can figure out a good UI solution for it then I'll implement it but maybe the best solution right now is to lower the timeout time.
