### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#1108]
**Describe the bug**
Zebra is not finding the dependency that is in a repo I already have installed. 

**To Reproduce**
1. Try to install TSSSaver 2 from https://g0ldsn0w.github.io/. Make sure you have https://rovert.me/apt/ already installed. 

**Expected behavior**
Zebra should be able to find the (most up to date) dependency package(s) from any repo. 

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/701840794339770408/image0.png

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1 beta 6
 - Device Type: XS Max
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
I just checked this out and it doesn't look like TSSSaver has anything except for substrate listed as a dependency.

<img width="247" alt="Screen Shot 2020-04-24 at 8 50 49 PM" src="https://user-images.githubusercontent.com/19736790/80267076-4a0acb00-866d-11ea-89dd-03d98a31398f.png">

**Comment by wstyres** [comment]
@Greigh does this issue still occur?

**Comment by wstyres** [comment]
Actually, it looks like this is a repo maintainer issue. The package in the repo listings does not contain the dependency for `net.limneos.libbulletin` as seen in the screenshot above but when downloading the package, the control file lists it as a dependency which is why Zebra cannot calculate the dependencies properly.

**Comment by wstyres** [comment]
Cydia also has troubles downloading these files because the hashes are mismatched. I would suggest contacting the repo maintainer to fix this issue.

**Comment by Greigh** [comment]
@wstyres Will do. Thanks.
