### ISSUE TITLE
Search Package Depiction UI Issue

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#1109]
**Describe the bug**
White lines showing when ONLY searching for a package in the package depiction. 

**To Reproduce**
Search for a package and open it. 

**Expected behavior**
No white lines on the side. 

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/701842564789305414/image0.png

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1 beta 6
 - Device Type: XS Max
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
This is a very odd issue. Seems to only occur on screen sizes larger than 4.7" (so the 11, Xr, Max and + phones). Are there any more details you can provide? We can't seem to track down why this is occurring.

**Comment by Greigh** [comment]
It started happening in beta 5, I believe. It could’ve been beta 6 though. White shows up on the sides on every package depiction when searching including packages that use dark theming depictions.

It goes down throughout the depiction. 

Here’s a screen record. 

https://cdn.discordapp.com/attachments/572784833714192395/704050806038724628/video0.mp4

**Comment by wstyres** [comment]
Should be fixed as of 91ab468ca3e3094137d04965ac936244470e913f (Screenshot from XS Max on 12.4)
![Simulator Screen Shot - iPhone Xs Max - 2020-04-26 at 16 01 50](https://user-images.githubusercontent.com/19736790/80318306-3f6c4500-87d7-11ea-8c81-63893c525ff1.png)
