### ISSUE TITLE
Add option to make zebra the primary manager

### ISSUE THREAD

**Issue by samwllson9478** [wstyres/Zebra#1114]
**Is your feature request related to a problem? Please describe.**
I know you changed it with the beta release but an option to toggle it on and off would be awesome
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wstyres** [comment]
Unfortunately we have no control on which package manager a jailbreak provides, if you'd like Zebra to be included in a jailbreak I would suggest contacting the makers of that jailbreak or filing an issue on their GitHub.
