### ISSUE TITLE
Theme header and User-Agent issues

### ISSUE THREAD

**Issue by eskimo** [wstyres/Zebra#1115]
**Describe the bug**
Theme header and user-agent don't change along with theme changes on newest beta. Seems to always send "Pure-Black".

**To Reproduce**
Steps to reproduce the behavior: Change the theme, and look at the headers sent along with depiction requests.

**Expected behavior**
Should use the correct header and user-agent?

**Screenshots**
![51d1acae](https://user-images.githubusercontent.com/12444228/79806787-3c84d680-8337-11ea-9189-4396fccb3f2d.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1\~beta6
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
N/A

**Additional context**
None needed.

**Comment by wstyres** [comment]
I'll take a look, I did change the theming headers from what they were in 1.0 but was not aware they will broken.

**Comment by wstyres** [comment]
Looks like I missed some breaks in my switch statement for sending the headers, will be fixed in the next beta. 

1.1 now sends `Light`, `Dark`, or `Pure-Black` in the `Theme` header as well as the User-Agent.

**Comment by eskimo** [comment]
Woot woot. Thanks :)
