### ISSUE TITLE
Pressing “Upgrade all” second time does not open queue

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1116]
**Describe the bug**
As the title says. Pressing once, it does put in queue. Pressing second time, it does NOT open queue.

**To Reproduce**
Press “Upgrade all”

**Expected behavior**
Open queue when pressed second time.

Edit: Happens on beta 6

**Comment by wstyres** [comment]
Should be fixed as of fd9d47a72cecfb8932bcac45bfa1fc4b8d7f244a.

**Comment by eve0415** [comment]
Sorry, I’ll just reopen this.

As of beta 7, pressing “Upgrade all” once seems to open queue (not when pressing second time)

Also, I found that pressing install second time on package depiction doesn’t open queue.

**Comment by wstyres** [comment]
I can't reproduce not being able to open Upgrade All

**Comment by eve0415** [comment]
https://cdn.discordapp.com/attachments/572784833714192395/704097614051803256/video0.mp4

**Comment by wstyres** [comment]
It looks like you are simply just trying to open the Queue too quickly after clearing it, the animation is not quite complete so it cannot present again. This wouldn't come up in normal use case so I don't think it is that much of an issue. 

As for the install page, what do you mean "pop up" after clicking install twice? Do you mean present as the full Queue? If that's the case then that was never a feature I don't think.

**Comment by eve0415** [comment]
Well, not really as it happens for the first time when after opening zebra.

https://discordapp.com/channels/566255609251364864/572784833714192395/704180545894219797

https://twitter.com/hlokel1/status/1254507851634130951?s=20

**Comment by wstyres** [comment]
It looks to be opening both times, what are you demonstrating in the video?

**Comment by eve0415** [comment]
Look, this was how it behaved when in beta1 or below; https://discordapp.com/channels/566255609251364864/572784833714192395/704182054564397086

From beta3, this (package depiction) "Install" button was changed to "Modify", which we couldn't press install in first place. However, pressing "Upgrade All" second time did open queue;

In beta5, "modify" button has change back to "install" in package depiction, but cannot open queue pressing second time. Still, pressing "Upgrade All" second time did open queue;

Now, in beta7, pressing "upgrade all" opens queue when pressing for the first time.

Please compare the videos I send above. I think you will notice the different as my English is very bad at telling these things

**Comment by wstyres** [comment]
Ah ok I think I see what you mean. The expected behavior is for the button (when pressed twice) to open the queue?

**Comment by eve0415** [comment]
Yes, that is what I wanted to say

**Comment by wstyres** [comment]
Fixed as of 809301f410f0c77bca2483217d71a88ccb1f4d1e.

**Comment by eve0415** [comment]
Confirm that this is fixed in beta8
