### ISSUE TITLE
Haptic-touching any package causes the back button to be hidden

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#1119]
**Describe the bug**

Haptic-touching any package will open the external package manager. This goes for the featured packages on the homepage, recent in changes, packages in packages tab and search results in the search tab.

**To Reproduce**

^

**Expected behavior**

I expect the normal peek-and-pop action.

**Screenshots**

Screen recording:
https://imgur.com/a/NRNSBQg
Screenshot:
![33D080B9-91BD-4969-A890-B67107E7C453](https://user-images.githubusercontent.com/51668635/79856577-cd59c180-83cc-11ea-89c6-1e8f23019d05.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 6
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
Should be fixed as of 4d60664ae8c62b76712c9bbf194e752b48fc3cba.

**Comment by worldlydev** [comment]
Can confirm that the issue is fixed in the latest beta.
