### ISSUE TITLE
Cannot change language

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1120]
**Describe the bug**
As the title says. Changing to any language does not seems to work.

**To Reproduce**
1. Disable "Use system language"
2. Choose any language
3. Apply and re-open
4. Find Zebra still uses system language ("Use system language" option are disabled)

**Expected behavior**
Change language

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta6
 - Device Type [e.g. iPhone or iPad]: iPhone

**Additional context**
Tried re-installing Zebra and removing plist file.
Checked plist file and notice that `AppleLanguages` is missing. Adding manually does not fix and re-opening Zebra seems to remove it.

**Comment by wstyres** [comment]
Not able to reproduce on iOS 13, could it be a 12 only issue?

**Comment by eve0415** [comment]
Could be, but I don’t know for sure. I only heard this issue from one person.

**Comment by wstyres** [comment]
Are you able to reproduce on 13?

**Comment by eve0415** [comment]
Nope

**Comment by absidue** [comment]
I don't think iOS 13 allows changing the language that easily so it would need a custom implementation.

**Comment by wstyres** [comment]
I was just able to change the language on iOS 12.4 in the simulator, I'll try on device.

**Comment by wstyres** [comment]
Just tested on a device running iOS 12.4 on Chimera, cannot reproduce the issue.

**Comment by wstyres** [comment]
Also verified that this isn't an issue that exists before 12.1, tried on iOS 11.4 on the simulator and it worked as intended.

**Comment by absidue** [comment]
Well now I look stupid

**Comment by Kyogre** [comment]
@wstyres @PoomSmart hi, guys! Can we reopen this bug?
I am suffering from it on Zebra 1.1.22 (iphone 12 mini, ios 14.2.1, system language - Russian). I am trying to change language from Russian to English. AppleLanguages and AppleLanguages.back are here in plist, but if I change them to "en" or "en-US" or "en-GB" that doesn't help.

**Comment by Kyogre** [comment]
Nevermind. I found two ways to fix it:
First way: delete Cydown (not just disable! but delete the tweak completely!);
Second way: go to Cydown and change language via option named "Cydia Language" (apparently it applies to Zebra too).
