### ISSUE TITLE
Crash when opening Bingner repo

### ISSUE THREAD

**Issue by rctfan929** [wstyres/Zebra#1124]
Zebra crashes when opening Bingner repo from sources tab.

1. Choose sources tab
2. Choose Bingner repo

 - iOS 12.4
 - Zebra 1.1-beta6
 - iPhone 6s
 - unc0ver 3.4.1

[Cr4shed log](https://pastebin.com/s5p03WqX)

**Comment by eve0415** [comment]
Different clash log but duplicate of #1123
