### ISSUE TITLE
cannot unselect repos to be featured.

### ISSUE THREAD

**Issue by MustyAslan99** [wstyres/Zebra#1126]
**Describe the bug**
cannot unselect repos to be featured..

**To Reproduce**
I unselect unwanted repos from the list then after respring or closing app when I see first page I see packages from unwanted and when going to settings it is selected which I didn't not want.

**Expected behavior**
to be unselected how I wanted it

**Screenshots**
should know it of how I described it.

**Device Information (please complete the following information):**
 - iOS Version: 13.4
 - Zebra Version: 1.1-beta6
 - Device Type: iPhone 8
 - Jailbreak Type: checkra1n

**Crash Log or System Log**
not a crash.

**Comment by PoomSmart** [comment]
Most likely you did go back from the source selection page without tapping "Add" button (on the right side). This is one confusion in the current design. We will see what to do about it.

**Comment by PoomSmart** [comment]
Redesigned to prevent confusion in c1278cc16bc914b54354e238f14a07828a0df272

**Comment by eve0415** [comment]
@MustyAslan99 Just a small question. What featured type did you choose? Repo Featured or Random

**Comment by MustyAslan99** [comment]
> Most likely you did go back from the source selection page without tapping "Add" button (on the right side). This is one confusion in the current design. We will see what to do about it.

yes I just realised that and gave me a bit confusing of adding a new repo or something 😂

**Comment by MustyAslan99** [comment]
> @MustyAslan99 What featured type did you choose?

repo featured I guess as a default.

**Comment by eve0415** [comment]
If I remembered it correctly, I think we cannot unselect any repos when using repo featured. Selecting repo for featured package was for “Random” and I think that is a another UI bug... I’ll open another issue for this.

**Comment by wstyres** [comment]
@eve0415 is right on this one, the source blacklist should not be shown for repo featured, only for the random packages as we only check the blacklist for random packages

**Comment by MustyAslan99** [comment]
@eve0415  well I figured it out when tapping add which meant apply but it causes misunderstanding of what the button does until someone figures it out.
