### ISSUE TITLE
UI freezes in filter page after scrolled down to the end

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#1127]
**Describe the bug**
Zebra freezes after reached the end of the view table in filter page.

**To Reproduce**
Open filter page and scroll down to the end.

**Expected behavior**
UI not freezing.

**Screenshots**
https://imgur.com/a/bKfQqDg

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Latest beta 6
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
Possibly related to #977? Hard to tell, will try to reproduce later today.

**Comment by wstyres** [comment]
Wondering if this has to do with the number of sections filtered?

**Comment by eve0415** [comment]
Like how many exactly? I just filtered about 55 sections (not source section) but no lag

**Comment by wstyres** [comment]
I might have solved this in 34ca547e5e4f63fa848acb912de2b9311396c12b but I'm not sure, please test in next beta.

**Comment by CanerKaraca23** [comment]
I'm having this issue sometimes. Waiting next beta.

**Comment by yur1xpp** [comment]
will try it once it's out on the repo, thanks wstyres!

**Comment by wstyres** [comment]
Any updates for beta 7?

**Comment by yur1xpp** [comment]
With beta7, I didn't notice any freeze so far.
