### ISSUE TITLE
Getting 2 different errors while trying to install packages

### ISSUE THREAD

**Issue by rctfan929** [wstyres/Zebra#1128]
I get one of two errors while trying to install packages.

**Screenshots**
![0C85C376-1D99-4240-850F-D51FB0529EC9](https://user-images.githubusercontent.com/46878212/80056917-5b2fcc80-84f3-11ea-87ed-f37ddb464b5b.png)
![183E856B-EC8F-4271-A1B3-3B21CC725AF2](https://user-images.githubusercontent.com/46878212/80056919-5bc86300-84f3-11ea-8ecc-d425ddd5b042.png)

 - iOS 12.4
 - Zebra 1.1-beta6
 - iPhone 6s
 - unc0ver 3.4.1

**Comment by wstyres** [comment]
The second picture, does it happen every time?

**Comment by wstyres** [comment]
I don't think the first message is anything to be concerned about, just a false coloring of errors.

**Comment by rctfan929** [comment]
Second picture doesn’t happen every time. For right now it’s not happening.

**Comment by wstyres** [comment]
Ok, I don't think those CoreFoundation messages are related to Zebra so I will close the issue.

**Comment by rctfan929** [comment]
I don’t get the CoreFoundation when install the same thing through Cydia.
