### ISSUE TITLE
cy.cpu.arm64 get renamed to cy.cpu.arm for an unknown reason

### ISSUE THREAD

**Issue by Cimmerian-Iter** [wstyres/Zebra#1130]
**Describe the bug**
When installing Zebra in chimera/chimera1n, the status file get edited and cy.cpu.arm64 got renamed into cy.cpu.arm

this bug : https://www.reddit.com/r/jailbreak/comments/cz7cxx/help_sileo_error_depends_cycpuarm64/
reddit

**To Reproduce**
Steps to reproduce the behavior: installing zebra

**Expected behavior**
To not have that rename

**Device Information (please complete the following information):**
 - iOS Version happened in 12.4, now happen in 13.4
 - Zebra Version : 1.1 (also happened on previous version)
 - Device Type : Iphone 7
 - Jailbreak Type : happen both in chimera and chimera1n. Affect the chimera bootstrap

**Comment by eve0415** [comment]
Does this happen in version 1.0.8?

**Comment by Cimmerian-Iter** [comment]
sorry, i thought 1.1 was the stable version.

Yeah it happen in 1.0.8

**Comment by eve0415** [comment]
How about beta 6?

**Comment by wstyres** [comment]
Are you testing it on 1.0.8 or 1.1~beta6? This issue should have been fixed with the new firmware.sh implementation.

**Comment by Cimmerian-Iter** [comment]
I had tested it on 1.0.8
Fixed the issue.
Deleted zebra and installed zebra beta and it didn't do it again so I guess it has been fixed
