### ISSUE TITLE
Hello there, my WhatsApp isn’t works properly with unc0ver V 4.3.1 cannot send media and stickers, only receive (iOS 13.3).. how could I fix it?! Thank yoy

### ISSUE THREAD

**Issue by Passsenger57** [wstyres/Zebra#1132]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
I don’t think this is the right place to report a bug about WhatsApp nor unc0ver.

**Comment by wstyres** [comment]
This isn't the place to report bugs about WhatsApp or unc0ver. Try some other community places like /r/jailbreak on reddit or the /r/jailbreak Discord.
