### ISSUE TITLE
Cannot use context menus on packages in account page

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1134]
**Describe the bug**
As the title say. Context menu does not open 
in store page in the home tab.

**To Reproduce**
1. Select home tab
2. Open store page
3. Choose any repo that you have logged in and have paid package
4. 3-D touch on any package

**Expected behavior**
Open context menu

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: beta6
 - Device Type: iPhone
 - Jailbreak Type: checkra1n

**Comment by wstyres** [comment]
Fixed as of d425681590a6b41168b6810375c5f6e954a22958.
