### ISSUE TITLE
UI bug in setting page, home section

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1136]
**Describe the bug**
As the title say. And see screenshots below

**To Reproduce**
Open setting and change how the packages are going to be featured.

**Screenshots**
- When “Featured Packages” is off, we don’t need to set “Feature Type”
![B9774C78-130E-4CF7-976E-587816BDC358](https://user-images.githubusercontent.com/40632436/80282464-ae508c00-874c-11ea-82b5-dcd07dc1c977.png)

- When “Featured Package” is on AND feature type is “repo featured”, we don’t need to set “select repos to be featured. (If I remembered it correctly, this was for random feature.
![59DF1654-B157-4A67-9687-17F33FB02853](https://user-images.githubusercontent.com/40632436/80282510-e6f06580-874c-11ea-94f0-a3c919b19d39.png)

- When “Featured Package” is on and also feature type is “random”, automatic refresh get double.
![6A890961-D04A-4639-AD9D-61D2FB654E0E](https://user-images.githubusercontent.com/40632436/80282573-0e473280-874d-11ea-8bfd-47d3e2452c78.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 6
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n 

**Additional context**
I don’t know exactly but I think this bug was introduced when filtering function became available. 
And also fix #1126  I guess

**Comment by wstyres** [comment]
Fixed as of 47ae64cd17b1b46f622b148d8d4c0f2894c987e3.
