### ISSUE TITLE
Ability to customize URL of frontpage/featured page

### ISSUE THREAD

**Issue by xPazz** [wstyres/Zebra#114]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to have a specific site to show me featured packages etc.

**Describe the solution you'd like**
A preference to choose the URL.

**Describe alternatives you've considered**
A separate tweak to change it.

**Comment by wstyres** [comment]
I don't really think this is necessary. Zebra's homepage as it is right now is temporary and it will be replace with another design at a later date. If you want to change the homepage, you can do so with a tweak for the time being.
