### ISSUE TITLE
(null) tag for dependency package when upgrading a package

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#1140]
**Describe the bug**
When upgrading a package the dependency package is displayed as "(null)" instead on "upgrade" subtitle/tag.

**To Reproduce**
Upgrade a package with dependency, in my case, Watusi.

**Expected behavior**
A tag of "upgrade" for dependency package (If I'm not mistaken, stable version behave this way)

**Screenshots**
https://i.imgur.com/Xa6mF5c.png

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta6
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1

**Comment by eve0415** [comment]
More information for this:
If the dependencies need to be Install / Update, the label gets marked as (null)
Installing package that make conflicts to be removed, the label gets marked as (null)

Removing package that makes depends to be removed as well, the label are marked correctly, “remove”

**Comment by wstyres** [comment]
Fixed by @eve0415 in #1141.
