### ISSUE TITLE
Inconsistent text size in settings

### ISSUE THREAD

**Issue by absidue** [wstyres/Zebra#1144]
**Describe the bug**

The text size on the first settings view is inconsistent with the other views.

**To Reproduce**

1. In Settings navigate to Display & Brightness > Text Size and set the text size to the lowest possible value.
2. Open Zebra's settings

**Expected behavior**

The text size to be the Dynamic Type text size specified in the Settings app.

**Screenshots**

![AF187C6F-ACB6-4D04-8FD8-324B7A43CE8B](https://user-images.githubusercontent.com/48293849/80313024-c8d84300-87e8-11ea-8b05-73dc38265f97.jpeg)
![6207378C-EB2F-40D8-BBA7-B78523C825BB](https://user-images.githubusercontent.com/48293849/80313030-d261ab00-87e8-11ea-9fc3-8240f22634c1.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta7
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
Fixed in c33a6fbe25c550e051d175300c6bef45d968c714.
