### ISSUE TITLE
The text is incomplete in home -> stores

### ISSUE THREAD

**Issue by hassan2x7** [wstyres/Zebra#1145]
![CB85F5F1-7CE9-463A-9EA7-E03971790FDE](https://user-images.githubusercontent.com/64375844/80316357-0c8d7580-8806-11ea-8eaf-8dd8d97d04a6.jpeg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Going to merge this over to #1146 since it has a complete description
