### ISSUE TITLE
Package names cut off in account page

### ISSUE THREAD

**Issue by Ngsaints29** [wstyres/Zebra#1146]
**Describe the bug** 
Names are cut off when viewing them in store purchases. 

**To Reproduce**
Go into purchases and look at the names of the tweaks you have bought. 
**Expected behavior**
Names of the tweaks should be clear and not cut off. 

**Screenshots**
![A296FFEF-B1D6-4D47-8DB8-C3320817C4CF](https://user-images.githubusercontent.com/51883775/80316641-e1d2fb00-87cc-11ea-81af-fc20a9c73126.png)

**Device Information (please complete the following information):**
 - iOS Version- iOS 13.3 
 - Zebra Version- 1.1 beta 7 
 - Device Type - iPhone 11
 - Jailbreak Type - Unc0ver

**Comment by wstyres** [comment]
Fixed in 37b0f85f9710bad7e4a4e9998e13c62d25d5f674.
