### ISSUE TITLE
Cannot access Package from featured packages

### ISSUE THREAD

**Issue by CanerKaraca23** [wstyres/Zebra#1147]
**Describe the bug**
I'm having issue with this package only I take a look from featured. Its ok when I look from searching.

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/704085520342581378/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <12.4.6>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <Latest Beta>
 - Device Type [e.g. iPhone or iPad]: <iPhone 5s>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <checkra1n>

**Comment by wstyres** [comment]
It might be that Dark Google photos can't be found anymore in your sources. Can you try searching for the package?

**Comment by CanerKaraca23** [comment]
![948ADF71-DF94-46C2-8884-95FF063DC035](https://user-images.githubusercontent.com/37447503/80321026-a236fe00-8822-11ea-95af-8f0d45c5a861.png)
Its still here and still occurs. I refreshed.

**Comment by wstyres** [comment]
What repo is Dark Google Photos from?

**Comment by eve0415** [comment]
YouRepo

I think its more likely because of repo maintainers; they have wrong package id in the featured list.
![F84FA076-9E01-4176-B0FB-DD7F2C2321F9](https://user-images.githubusercontent.com/40632436/80321838-6bc9a500-885b-11ea-949a-1733879bd126.png)

Maybe, adding a filter to check if Zebra can find a package or not to show users will reduce this issues to be opened, but still contacting YouRepo’s maintainers are faster

**Comment by wstyres** [comment]
Yeah that is what I thought, I'll try to check if the package is available if it isn't too slow but the assumption is that the packages that a repo is featuring actually exist :p

**Comment by CanerKaraca23** [comment]
So this issue occurs because of YouRepo maintainers?

**Comment by wstyres** [comment]
Likely, the package ID of the actual package looks like `com.foxfort.darkgooglephotos` but the package ID that is listed in the featured packages is `com.yourepo.foxfort.darkgooglephotos`. Not sure the workings of YouRepo but I would suggest contacting either the package author or the yourepo maintainers.

**Comment by CanerKaraca23** [comment]
I'm not using any tweaks from YouRepo. I only created this topic for this bug. If this issue isn't because of Zebra, topic can close if you want. Thanks for everything.

**Comment by wstyres** [comment]
Fixed as of 40d7070698a12956ba898ec849925d201d338f8b.
