### ISSUE TITLE
Customisable depictions (sileo or custom url)

### ISSUE THREAD

**Issue by xPazz** [wstyres/Zebra#115]
**Is your feature request related to a problem? Please describe.**
I'd like to see screenshots and a more detailed description or even changelog of the tweak.

**Describe the solution you'd like**
A proper depiction "window" on packages. Optionally customisable source such as the web depiction, sileo depiction, or a custom source. (would have a custom URL with placeholder for package ID)

**Describe alternatives you've considered**
Using a different package manager with support.

**Comment by xPazz** [comment]
turns out depictions were just bugged for me and not showing up, they're showing up now.. the latter part of the suggestion is still there though.

**Comment by wstyres** [comment]
Duplicate of #7. Modern Depiction support is planned.
