### ISSUE TITLE
Queue label does not update in certain conditions

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1150]
**Describe the bug**
As the title says. Queue label does not update when pressing, “upgrade all”, and when putting some package in queue from account page

**To Reproduce**
Press upgrade all
Or, go to account page, install some paid package

**Expected behavior**
Update queue label

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta7
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
Fixed as of f901fac285a8df15b4c62c90735ffcec8814bcc5.

**Comment by eve0415** [comment]
Most are fixed in beta8, but queue labels in account page won’t be removed when clearing from queue. And I think this is the last bug for queue label.

**Comment by PoomSmart** [comment]
Fixed the last bug as of 9bff5e18d597d9784e16164d60b66c9bc6450fd7

**Comment by eve0415** [comment]
Can confirm it’s fixed as of beta9
