### ISSUE TITLE
Some settings from 1.0.x not transferring to 1.1

### ISSUE THREAD

**Issue by wstyres** [wstyres/Zebra#1151]
User report from Discord

**Describe the bug**
Old settings do not transfer over to 1.1 when upgrading

**To Reproduce**
- I began the process by erasing all settings and sources (in 1.1).
- I then downgraded to 1.0.8 from another package manager (being Cydia). The downgrade worked fine. 
- I changed some settings in 1.0.8 (attached below) and added back my sources.
- I upgraded to 1.1 from Zebra.
- The only setting that was transferred to 1.1 from 1.0.8 was “Swipe Actions Display As,” which I changed to “Icons” in 1.0.8. The other settings I changed in 1.0.8, which can be seen below, are “Accent Color” and “Dark Mode Style.” I can understand why the accent color didn’t transfer, as the accent color settings are significantly different in 1.1. However, I expected the dark mode style to transfer to 1.1, which it did not. Sources did successfully transfer

**Expected behavior**
Settings from 1.0.x to transfer over to 1.1

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/704075828044234792/image0.png

https://cdn.discordapp.com/attachments/572784833714192395/704075828404682822/image1.png

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: Unknown
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta7
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unknown

**Comment by eve0415** [comment]
Wish list also will be removed when upgrading / downgrading

**Comment by worldlydev** [comment]
> Wish list also will be removed when upgrading / downgrading

Came here to say the same thing

**Comment by wstyres** [comment]
I've fixed the tint color settings above I believe but the wishlist problem I can't reproduce, I added a package to my wishlist in 1.0.8 and it transferred over fine to 1.1.

**Comment by wstyres** [comment]
@eve0415 @worldlydev Let me know if you can provide more information, I'll mark this issue as scheduled for now.

**Comment by eve0415** [comment]
@wstyres Just double checked and the wishlist will be removed when downgrading to 1.0.8 but not updating to 1.1betas; sorry for the wrong information!
