### ISSUE TITLE
[BUG] Zebra doesn't show update notification properly

### ISSUE THREAD

**Issue by SeMoOoR** [wstyres/Zebra#1156]
**Describe the bug**
Title. When there is a package update, Zebra will show an icon that an update is present. When force closed, Zebra will continue to show the update notification on its icon. But, when launched, all notifications will be reset until you go to packages page and invoke the notifications again.

**To Reproduce**
- make sure there is a package update.
- go to sources page or any page other than packages.
- force close Zebra.
- Zebra will no longer show the notification.

**Expected behavior**
Zebra notification shall be consistent even after force closing the app.

**Screenshots**
1-
![F3BBE1EE-D8CF-482B-9D77-E0E719ADC075](https://user-images.githubusercontent.com/25428973/80396774-d14e7d80-88bd-11ea-80cc-a9bb171cf9a0.png)

2-
![57896BD4-1799-4255-95F0-22EFF12047F1](https://user-images.githubusercontent.com/25428973/80396955-212d4480-88be-11ea-9f38-99468e2c1348.png)

3-
![D97FD719-3808-40C0-98BD-80F96FAD7CCF](https://user-images.githubusercontent.com/25428973/80396989-2f7b6080-88be-11ea-8e16-e38580fc1710.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3

 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta7
 - Device Type [e.g. iPhone or iPad]: iPhone 12,5
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by eve0415** [comment]
Should be fixed as of 2793329066f5843ce7034032f47f9a2950d5d181 (#1439 )
