### ISSUE TITLE
"Installed files" not hierarchicaly organized on RTL languages

### ISSUE THREAD

**Issue by Aransh** [wstyres/Zebra#1158]
**Describe the bug**
When opening the "Installed files" menu in a tweak's depiction, it will not be hierarchicaly organized if you are on an RTL language, but just on the most right.

![image](https://user-images.githubusercontent.com/11724502/80422867-9c572080-88e7-11ea-86ec-c975ce590927.png)

**To Reproduce**
Open an Installed tweak's depiction and choose "installed files"

**Expected behavior**
Hierarchy organization like in English. 
![image](https://user-images.githubusercontent.com/11724502/80422917-b264e100-88e7-11ea-87c0-0ea68ede7096.png)

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta7
 - Device Type: iPhone X🅂 Max
 - Jailbreak Type: Unc0ver

**Comment by aabosh** [comment]
Fixed in 00c2af37, will be available in the next beta.
