### ISSUE TITLE
Cydia postinst errors showing up in Zebra

### ISSUE THREAD

**Issue by ojh6781** [wstyres/Zebra#1161]
**Describe the bug**
It seems that the tweak is crashing while installing the any tweaks. tweak is a-font and video swipe. when I stop the a-font and video swipe with icleaner, They are disappeared. I think it happend after rocketbootstrap update. I hope this will be fixed. 

**To Reproduce**

**Expected behavior**
error message appear

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [13.3]: <INSERT-HERE>
![KakaoTalk_20200429_004238297](https://user-images.githubusercontent.com/64468302/80508869-8c0c7780-89b3-11ea-8318-ec93ed849269.jpg)

 - Zebra Version [1.1~beta7-1]
 - Device Type [iphone 11 pro]
 - Jailbreak Type [ unc0ver,]

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
These are some various messages from a post install script from the pacakge running after Cydia's scripts, there isn't really any harm in these messages but I don't know why they are erroring like this. I'll just hide the messages.

**Comment by wstyres** [comment]
Should be fixed as of 115c67c734591c04d4e4a9c90eb83797ad893db5.

**Comment by ojh6781** [comment]
now it works perfectly. Thank you for caring about the little things. Thank
you for your consideration, and I always support your development.

2020년 5월 1일 (금) 오전 1:09, Wilson Styres <notifications@github.com>님이 작성:
