### ISSUE TITLE
kcferrordomaincfnetwork error 303

### ISSUE THREAD

**Issue by DAAKING** [wstyres/Zebra#1162]
I have an kcferrordomaincfnetwork error 303 dont know what to do 

Iphone x 
Ios 13.3

**Comment by wstyres** [comment]
Could you elaborate a little more on the issue? Which source is experiencing this issue? Which version of Zebra are you on? If you're not on the beta, can you update to the beta at https://getzbra.com/beta/ and see if the issue still occurs?

**Comment by dannyvoid** [comment]
I've started getting this error yesterday. Happens every time I refresh my sources, but errors out with a different repo each time. 

![81Vwb_Ag](https://user-images.githubusercontent.com/12226555/80556896-baca2400-899a-11ea-8c01-1a8226ad0183.png)

**Comment by wstyres** [comment]
What version are you on? Have you tried the beta version?

**Comment by dannyvoid** [comment]
Latest stable. Will give the beta a try.

**Comment by DAAKING** [comment]
Its with the zebra repo and i can’t install or delete tweaks the tweaks gets downloaded and it says done and it doesn’t get in my phone and it doesn’t tell me to respring either

**Comment by eve0415** [comment]
@DAAKING Could you post the screenshots or video of what the console says?

**Comment by DAAKING** [comment]
![zebra](https://user-images.githubusercontent.com/37983951/80624894-05a87200-8a55-11ea-87f4-dd62e66e0be8.jpg)

**Comment by wstyres** [comment]
@DAAKING I would suggest upgrading to the beta for the time being. It has fixed the issue for users in the past. Unfortunately we cannot reproduce the issue on our end so we cannot fix it. 

Beta Repo: https://getzbra.com/beta/
