### ISSUE TITLE
Languages don't start with a capital letter

### ISSUE THREAD

**Issue by gkeep** [wstyres/Zebra#1163]
**Screenshot:**
<img src="https://user-images.githubusercontent.com/20600053/80510607-a29ada80-8983-11ea-9392-e5cffc339d7e.jpeg" width=50%>

**Device Information:**
 - Zebra Version: 1.1~beta7

Also, see https://github.com/wstyres/Zebra/issues/881#issuecomment-620711197.

**Comment by worldlydev** [comment]
Maybe take inspiration from the language selector in iOS?

![105759BA-2AB5-4B3A-AE48-7AC0877A2AAD](https://user-images.githubusercontent.com/51668635/80518207-7896e780-8986-11ea-85a5-70f695b5bd30.png)

It has a search bar and also displays the language names in both the native language and the language currently in use.

**Comment by wstyres** [comment]
That's exactly what I've done, I haven't implemented a language selector as there are so few languages though.
![Simulator Screen Shot - iPhone 5s - 2020-04-28 at 13 46 33](https://user-images.githubusercontent.com/19736790/80519941-c267d980-8956-11ea-9b76-c2ad61976156.png)

**Comment by wstyres** [comment]
Fixed as of df4f422c97ea4a328053bcf63b05f90abeee7445.

**Comment by worldlydev** [comment]
That looks awesome
