### ISSUE TITLE
Packages on Changes tab loosing source information

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#1165]
**Describe the bug**
Package is saying I have installed something when I haven’t. It gives me the option to remove, reinstall, etc. 

**To Reproduce**
1. Open Zebra
2. Refresh repos
3. See if package is installed in changes

It hasn’t happened every time for me unfortunately. 

**Expected behavior**
Allow you purchase and/or install the package instead of reinstall or remove. 

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/704858892856983694/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1 beta 7-1
 - Device Type: XS MAX
 - Jailbreak Type: u0

**Additional context**
Like I mentioned above, it isn’t happening all of the time. And it seems to be only the first package. I noticed it started happening in 7-1.

**Comment by Greigh** [comment]
I have notified that it is only when new packages are added to a repo.

**Comment by wstyres** [comment]
This looks related to #1005. I'll see if I can implement a better fix.

**Comment by wstyres** [comment]
Used the steps in #1005 to reproduce, I put a fix in in 7884e416768d67f4e85cf5bd882a0d5037c6b97b which will look up source information if the source is nil for some reason.

**Comment by Greigh** [comment]
Yeah, unfortunately, I am getting this issue again too. I can’t find the way to reproduce it. I will be trying to see when I get it as repos update packages because this seems to be the reason but I don’t get it every time is the issue.

**Comment by wstyres** [comment]
Did you try with the steps in #1005? @eve0415 said they were experiencing the issue last beta with those steps but cannot reproduce it as of beta 8

**Comment by Greigh** [comment]
Ah yes. His steps he gave does reproduce this error.

**Comment by wstyres** [comment]
And you have updated to beta 8 correct?

**Comment by Greigh** [comment]
Correct.

**Comment by wstyres** [comment]
Does the Source cell on the depiction still display incorrect information?

**Comment by eve0415** [comment]
https://imgur.com/a/Om6rEd6

**Comment by wstyres** [comment]
Yeah I also noticed the strange source cell in the original video so that is what I was looking for when reproducing the bug, if the cell is displaying that way then that means the source is nil. @Greigh If you could post a video of you reproducing the steps and then trying to purchase a package that would be great.
