### ISSUE TITLE
Sources are refreshing very slow. iPhone X iOS 13.3 checkra1n jailbreak. Zebra version 1.1-beta7-1

### ISSUE THREAD

**Issue by TomerKILLer** [wstyres/Zebra#1167]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Might be related to #1162, have you tried resetting your sources to see which repo is causing the issue?

**Comment by CanerKaraca23** [comment]
The model of your device, your internet speed and any repo slowness may be due to slow refreshing.
