### ISSUE TITLE
Live search and full search result of the same tweak show differently version

### ISSUE THREAD

**Issue by huyle0406** [wstyres/Zebra#1168]
**Describe the bug**
As the title say.
**Expected behavior**
Show latest version

**Screenshots**
https://imgur.com/gallery/t8diU8J

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 7-1
 - Device Type [e.g. iPhone or iPad]: Iphone 8 plus
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
Should be fixed as of 3a1a9821a37e9120181f766e1148f295d8eed0a8.
