### ISSUE TITLE
Copy Repo from Depiction view

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#1169]
**Is your feature request related to a problem? Please describe.**
Sometimes I would like to share the repo of a package, but it is hard to find the exact repo the package is located on with a large number of repos. 

**Describe the solution you'd like**
I think it would be awesome for me to be able to copy the repo of a package in the depiction view of the package by holding down on the “Source” section and tapping copy. 

**Describe alternatives you've considered**
I’m sure there are other option that I can’t think of at the moment but I believe mine would be the best way to implement the feature. 

**Additional context**
https://cdn.discordapp.com/attachments/572784833714192395/705391878446514196/image0.png

**Comment by PoomSmart** [comment]
Implemented in 980ea9bbfc708111ceb9e7e80a881204d7f44b7e
