### ISSUE TITLE
Repo title issue with special characters

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#1170]
**Describe the bug**
Repos with special characters are showing up as unknown. 

**To Reproduce**
Add https://repo.litten.love/ and possibly even http://itsjafer.com/repo/. 

**Expected behavior**
Show the repo name like it does in Sileo/Cydia. 

**Screenshots**
Zebra: https://cdn.discordapp.com/attachments/572784833714192395/705394838115450910/image0.png

Sileo: https://cdn.discordapp.com/attachments/572784833714192395/705394838417178654/image1.jpg

Cydia: https://cdn.discordapp.com/attachments/572784833714192395/705395575994056785/image0.png

**Device Information (please complete the following information):**
 - iOS Version: iOS 13.3
 - Zebra Version: 1.1 beta 7-1
 - Device Type: XS Max
 - Jailbreak Type: unc0ver

**Additional context**
This may have to do with the old issue with the correction you made with the repos not working on general with special characters.

**Comment by Greigh** [comment]
Edit: I added screenshots from Cydia/Sileo.

**Comment by PoomSmart** [comment]
Fixed as of a3c54395c55a4d618c09d6d38b446cd7538c40b8
Note that it may have nothing to do with special characters. Zebra failed to parse the sources for which its name is defined as `Label:<name>`. Note that there is not a white space after `:` here.
