### ISSUE TITLE
New filter for Basic/Experimantal users on packages section

### ISSUE THREAD

**Issue by CanerKaraca23** [wstyres/Zebra#1171]
**Describe the solution you'd like**
Adding a filter for Basic/Experimantal users on packages section like in Cydia-Packages.

**Additional context**
In Cydia: https://cdn.discordapp.com/attachments/570982745195675651/705448062277124107/image0.png

**Comment by gkeep** [comment]
Duplicate of https://github.com/wstyres/Zebra/issues/678

**Comment by CanerKaraca23** [comment]
Oh thanks, sorry. Closing...
