### ISSUE TITLE
[BUG] Fix blur/translucency of Package Queue bar

### ISSUE THREAD

**Issue by SeMoOoR** [wstyres/Zebra#1172]
**Describe the bug**
Package Queue bar loses its blur and translucency when the package depiction page is open. It is functioning elsewhere. 

**To Reproduce**

- Queue a package .
- enter any package page.

**Expected behavior**
consistent package queue bar blur/translucency.

**Screenshots**

1-
![3E732E47-4F0F-4EA6-94EE-8CEE44E6791C](https://user-images.githubusercontent.com/25428973/80749844-c4d15b80-8b2f-11ea-806b-a954dd62b3a5.png)

2-
![BD9B84DE-18B7-4C67-BA97-1A8FC5F332F1](https://user-images.githubusercontent.com/25428973/80749858-ca2ea600-8b2f-11ea-9583-b56ef4f5f85e.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta8
 - Device Type [e.g. iPhone or iPad]: iPhone 12,5
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by wstyres** [comment]
Related to #1155

**Comment by SeMoOoR** [comment]
Actually this is not related. Issue #1155 is resolved in beta 8 which was broken dark mode while searching a package and entering the depiction page from the search menu vs the changes/packages menu. 

The issue above is in regard to the blur effect of iOS13 (glass-like effect). Zebra shows this effect all over but not inside the depiction page. 

Below image shows the difference (notice menu bar and queue bar right and left) left is the glass-like effect where is right is the bug in my opinion.

![DF6589AE-9CFB-446B-8DEF-15FB3B1569F6](https://user-images.githubusercontent.com/25428973/80754664-154cb700-8b38-11ea-9c15-dcd9e62e409c.png)
