### ISSUE TITLE
No payment required when there are multiple version of paid package

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1179]
**Describe the bug**
Mostly same as #843 #739 
Zebra does not authenticate to buy a paid package but will put in queue.
It does not affect in package depiction page, but will when from swipe actions and from context menu.

**To Reproduce**
Try to install a paid package that has access to multiple version from the source via swipe menu or context menu

**Expected behavior**
Authentication

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta9
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
Should be fixed as of 978a8c9572a53ebe0aca8f30f836b4872b58dd5d.

**Comment by wstyres** [comment]
Fixed in beta 9-1, please give it a try.

**Comment by eve0415** [comment]
confirm it was fixed, thanx
