### ISSUE TITLE
Display the repo with the packages' names and depictions

### ISSUE THREAD

**Issue by blanxd** [wstyres/Zebra#118]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Would be nice to see from which repo a package is from. Ie. on the depiction pages and the lists (Search tab and Packages tab).

**Additional context**
This is something I really hate about _S_ (compared to _C_ ) that you never know where you're downloading stuff from. Some repos put something on the bottom of the depictions so you can sort of guess the repo, but still especially for the search results lists, I'd like to know where is the software coming from.

**Comment by wstyres** [comment]
Will be implemented partially in the next beta, it will show "Local Package" for packages that are installed but we will work on a way to determine from which repository a package was installed from so that it can be visible on the depiction.

**Comment by PoomSmart** [comment]
This is implemented in the latest commits.
