### ISSUE TITLE
Zebra crashes when trying to buy a tweak

### ISSUE THREAD

**Issue by async1wake** [wstyres/Zebra#1180]
**Describe the bug**
Zebra crashes when trying to buy a tweak

**To Reproduce**
Try hitting the button that displays the cost to forward to the payment WebView

**Expected behavior**
For it to scan FaceID and continue to the WebView where you can finalize purchasing the tweak

**Screen Recording** https://youtu.be/2s0AioV19fo

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: **13.4.1**
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: **1.1~beta9-1**
 - Device Type [e.g. iPhone or iPad]: **iPhone X (iPhone 10,1)**
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: **checkra1n**

**Crash Log or System Log**
https://pastebin.com/Qbpt92mK

**Comment by wstyres** [comment]
Can't reproduce with this specific tweak, does it happen with every tweak?

Also, are you signed in to the source?

**Comment by async1wake** [comment]
Signed out and signed back into Packix (It was signed in properly before), and the problem seems to be solved
