### ISSUE TITLE
Wish List not updating after adding package

### ISSUE THREAD

**Issue by mattp12** [wstyres/Zebra#1183]
Is your feature request related to a problem? Please describe.
N/A

Describe the solution you'd like:
Currently, you can have the wish list open on the home tab and navigate away to other tabs. If you were to add a package to the wish list with the wish list tab already open, it won't update until you leave the wish list section and reenter it. Although this is not a huge deal at all, I think having a pull to refresh/refresh button would make this experience smoother.

Describe alternatives you've considered:
Leaving wish list section and reentering. 

Additional context:
N/A

**Comment by wstyres** [comment]
This is more of a bug that the wishlist isn't updating, it is supposed to update automatically when you view it.

**Comment by PoomSmart** [comment]
Fixed in d9ef7930475c56e035fb2eb90de86c906fc467df
