### ISSUE TITLE
Make tapping the share button in the wish list when it is empty display an error, instead of doing nothing

### ISSUE THREAD

**Issue by mattp12** [wstyres/Zebra#1184]
Is your feature request related to a problem? Please describe:
N/A

Describe the solution you'd like:
Instead of the share button doing nothing when you tap it when in the wish list has no packages, display an error. Although the button doing nothing when there are no packages can be expected behavior, I feel like an error displaying would be a cleaner alternative.

Describe alternatives you've considered:
N/A

Additional context:
N/A

**Comment by PoomSmart** [comment]
Or gray it out?

**Comment by mattp12** [comment]
> Or gray it out?

Yeah, that also could work

**Comment by PoomSmart** [comment]
So grayed it out in c16b08d2dcb0d032b74115971520638769987dbb
