### ISSUE TITLE
Add trigger to scan clipboard for Source URLs

### ISSUE THREAD

**Issue by gkeep** [wstyres/Zebra#1188]
Right now, Zebra scans clipboard for URLs only on launch. It would be nice to have a trigger for this. 

For example, double tap on Sources tab or when pressing the '+' button on the Sources page.

**Comment by wstyres** [comment]
The popup in Zebra 1.1 should trigger automatically when it detects a new URL in your clipboard when visiting the sources page. An additional trigger could be added when you tap the "+" button in Sources but is the add popup not working properly? That would be a separate bug

**Comment by gkeep** [comment]
> The popup in Zebra 1.1 should trigger automatically when it detects a new URL in your clipboard when visiting the sources page.

Oh yeah. That works. never noticed it.

Not sure if I should create a separate issue about it, but I'm pretty sure scan should also trigger when opening Zebra via 3D/Haptic Touch option 'Add Source' (it just opens the input box right now).

Also, if you open Zebra via said 3D Touch option, the trigger doesn't work when you jump between tabs.

**Comment by wstyres** [comment]
What do you mean by jump between tabs?

**Comment by gkeep** [comment]
Like, opening another tab quickly, multiple times.

Here's a video of what I'm talking about: https://i.imgur.com/Ws5QA4c.mp4/

**Comment by p0358** [comment]
It could perhaps autofill the textbox when pressing "+"

Also, a separate suggestion:
Once someone pastes something into the textbox next to what's there by default, they can end up with "https://https://" beginning of the url (or the latter being http://). The suggestion is to detect that and automatically remove the first "https://", so the user doesn't have to swipe and delete that manually
