### ISSUE TITLE
Hide Updates isn't working

### ISSUE THREAD

**Issue by Aransh** [wstyres/Zebra#1189]
**Describe the bug**
Tapping "Hide updates" in a package's depiction does nothing, tapping "Modify" again still shows "hide Updates" (and not "show updates", meaning it wasn't applied), and the update still shows up.

**To Reproduce**
Open an Installed package's depiction, tap "Modify" and choose "Hide Updates".

**Expected behavior**
Said package will not show any pending updates, not will it count in the app's badge.

**Screenshots**
Video demo:
https://vimeo.com/414795318

**Device Information (please complete the following information):**

 - iOS Version: 13.3
 - Zebra Version: 1.1~beta9-1
 - Device Type: iPhone
 - Jailbreak Type: Unc0ver

**Additional context**
There Velox version I have installed in the video is a private build I got from the developer as a deb (so, installed from "local repository" while the update is from Chariz), but while I thought this might cause the problem, I'm getting the same issue with DockX.

**Comment by wstyres** [comment]
Was fixed already, will be available in the 1.1 release
