### ISSUE TITLE
Viewing all packages and scrolling down in BigBoss causes a crash

### ISSUE THREAD

**Issue by midnightchip** [wstyres/Zebra#119]
When viewing all packages in repos with large amounts of packages, if you scroll down Zebra will crash

**To Reproduce**
Add BigBoss or packix, view all packages and begin scrolling

**Expected behavior**
not to crash

 - iOS 12.1.1
 - Beta 11
 - iPhone 7

https://pastebin.com/eACPUrRy

**Comment by blanxd** [comment]
My testing suggests it depends on the resources available on the device.

With an ip8(12.1.2,Unc0ver), it does get a bit sketchy once I reach the letter U or so, but it's able to go all the way to the end (BigBoss, ~16.7k pkgs).

With an ip5s(11.4.1,Electra) it crashed with Packix (~800pkgs) not getting to the letter B, then again after a fresh reboob/jb I got to the letter T with BigBoss's 16k list when it really started slowing down.

**Comment by Muirey03** [comment]
@midnightchip Do you think you could chuck in a Cr4shed report? You can see `objc_exception_throw` in that report meaning a Cr4shed report should have been generated.

**Comment by Muirey03** [comment]
@midnightchip Do you think you could throw in a CrashReporter report. There's a bug in Cr4shed that I haven't been able to figure out yet which is that it cannot symbolicate the binary it is injected into, which is why you see `Zebra + 68412` instead of symbol names.

**Comment by midnightchip** [comment]
@Muirey03 Sure thing

**Comment by PoomSmart** [comment]
Package batch load has been implemented to counter excessive memory footprint for large repos. See if the next beta solved this.
