### ISSUE TITLE
"Installed file" with local package depiction when not installed

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1194]
**Describe the bug**
"Installed file" are shown in local package depiction page, that is still not installed. Pushing this tab will make Zebra freezes and unresponsive until I restart Zebra.

**To Reproduce**
1. Try to install local package using Zebra.
2. Tap "Installed file"

**Expected behavior**
Hide "Installed file" tab

**Device Information (please complete the following information):**
***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
Fixed in 49efa317d004d1e849f574e956044ec1d33da71f.
