### ISSUE TITLE
search bar scrolls up when the queue bar shows up

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1195]
**Describe the bug**
As the title says, when the queue bar is present, search bar scrolls up and will be hidden so that user are impossible to search anything

**To Reproduce**
1. Put any package in queue
2. Open search tab

**Expected behavior**
Don't scroll?

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/707161274420559902/image0.png

**Device Information (please complete the following information):**
***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS10.3.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1
 - Device Type [e.g. iPhone or iPad]: iPhone 5

**Additional context**
It doesn't happens on iOS 13 so this might be an issue with iOS 10

**Comment by Akatsuki-dev** [comment]
Hello. Akatsuki (the one that reported this bug) here. I just discovered that not only does this problem occur when the queue bar appears.
I sent the video in Discord,please watch it.

**Comment by eve0415** [comment]
https://cdn.discordapp.com/attachments/572784833714192395/708593552841637898/video0.mp4

**Comment by PoomSmart** [comment]
Workaround as of 8c83dc267736b44736b328b838de38ef4f6007cb
