### ISSUE TITLE
OLED dark mode elements still show when disabled

### ISSUE THREAD

**Issue by async1wake** [wstyres/Zebra#1197]
**Describe the bug**
When dark mode is enabled on my iPhone X, there are still OLED elements active even though I don’t have Pure OLED enabled.

**To Reproduce**
Enabled dark mode on an OLED device. (I think?)

**Expected behavior**
For the dark mode elements to look more like this: https://imgur.com/a/7MDvk4G

Instead of this: https://imgur.com/a/RCGIQbB

**Screenshots**
See above.

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: **13.4.1 (12.4 iP8 for the “proper” screenshot)**
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: **1.1**
 - Device Type [e.g. iPhone or iPad]: **iPhone X (iPhone 10,1)**
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: **checkra1n**

**Comment by wstyres** [comment]
This is intended design and is an iOS 13 feature, for a system example go into the Settings app or the App Store. You'll see that the background is pure black. If you go into a menu (in the App Store, press your account page in the top right) you'll see that the background of the pages presented on top is slightly lighter. Zebra uses the same style.
