### ISSUE TITLE
Let users give repositories client-side 'nicknames', to make the list clearer and more consistent.

### ISSUE THREAD

**Issue by DroneBetter** [wstyres/Zebra#1202]
Also, possibly allow notes for each repository, so you can explain to your future self which tweaks you use them for.

**Comment by shadowscott** [comment]
I'll also add in here the feature request of what #Installed/Package Count adds for Cydia.
https://www.reddit.com/r/jailbreak/comments/g0bsjm/release_installed_show_number_of_installed/
http://moreinfo.thebigboss.org/moreinfo/depiction.php?file=packagecountDp

**Comment by wstyres** [comment]
The UX for doing "notes" for the sources is a little complicated, we looked at it and we don't think there is a very nice way to do it right now, as for the installed packages count, that is a duplicate of #956
