### ISSUE TITLE
QOL features for the sources tab

### ISSUE THREAD

**Issue by Proaxel** [wstyres/Zebra#1204]
**Is your feature request related to a problem? Please describe.**
I have a large amount of sources added now, to the point where I regularly lose track of what I've already added. I would regularly waste trying to add a source only to get the message saying that I've already added it. There are a couple features that can be added to help solve this:

**Describe the solution you'd like**

- Add a search bar to the top of the sources tab, that lets you search by typing a part of the source's URL, or the source's name itself.

- Add an second button to the "you've already added this source" message, to view said source. This skips having to find said source in the potentially long source list afterwards.

**Comment by wstyres** [comment]
We're planning on adding a search bar to the sources tab in 1.2 (there is another issue that already requested this) but I think the scroll to source feature would be useful. I'll look into adding it.

**Comment by Proaxel** [comment]
Thanks, I look forward to seeing it added!

**Comment by worldlydev** [comment]
Working awesomely in the latest release (1.1.3)

**Comment by Proaxel** [comment]
@wstyres Thanks for adding these! One more small thing, when a new source is successfully added, could you make it (or give the option to) automatically open said source?
