### ISSUE TITLE
Zebra freezes on startup after adding some repos

### ISSUE THREAD

**Issue by Akatsuki-dev** [wstyres/Zebra#1205]
**Describe the bug**
As the title says,if you open Zebra after adding repos,it freezes.

**To Reproduce**
1.Add repos
2.Close Zebra and open it again

**Expected behavior**
It doesn't freeze the app?

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
10.3.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: H3lix?

**Comment by wstyres** [comment]
Which repositories have you added to Zebra?

**Comment by Akatsuki-dev** [comment]
> Which repositories have you added to Zebra?

I only add the repositories on the community sources tab.It freezes after i coming back with a few repositories i got.

**Comment by wstyres** [comment]
Do you know if you had featured packages enabled in Zebra?  Random or Repo Featured? Any blacklisted repos?

**Comment by wstyres** [comment]
Might be fixed as of b492791adddc56b5c0f678a21ea16251e9b6776d. Please check if the issue still occurs in 1.1.4 when it is released.
