### ISSUE TITLE
Option to use normal respring instead of sbreload?

### ISSUE THREAD

**Issue by LebsterFace** [wstyres/Zebra#1218]
Sometimes when I respring with zebra my icons flicker, and I have heard this is to do with sbreload. So maybe add an option to respring normally?

**Comment by wstyres** [comment]
`sbreload` is the safest and quickest way that we can respring on iOS 11 and up, any other ways like killing backboardd or SpringBoard have some unintended side-effects on newer iOS versions. Could you describe more about what is happening with your icons when you respring? This is more of a problem with `sbreload` itself that should be fixed than with Zebra.

**Comment by CanerKaraca23** [comment]
Custom respring icons doesn't working on you called "sbreload"

**Comment by wstyres** [comment]
Again, this is more of a fallacy with sbreload instead of Zebra and both issues should probably be reported to the maintainer of sbreload for whichever jailbreak you are using.
