### ISSUE TITLE
Can’t use Zebra Latest version!

### ISSUE THREAD

**Issue by AhmedAlNeaimy** [wstyres/Zebra#1219]
When trying to install any tweaks, i got this error message “Deprecated Method” i don’t know why, it’s the same issue with previous version, and it’s forced me to downgrade to Zebra 1.0.8

![72C02642-47AD-4DD4-8EEB-F62B79C92D10](https://user-images.githubusercontent.com/16979870/81627954-fee00e80-9407-11ea-9fb2-a6816024ef54.png)

**Comment by eve0415** [comment]
You have some tweaks that hook Zebra and that needs an update. Contact those tweak's developer, and meantime I prefer you to remove that tweaks that hooks Zebra so you can use 1.1 and up or just continue to use 1.0.8 until developer push a fix.

**Comment by wstyres** [comment]
This is not a Zebra bug, this is a problem with a tweak you have installed. If this alert was not there, Zebra would crash without any more information. You need to contact the developer of whatever Zebra tweak you have installed (could be CyDown) and ask them to update it.

**Comment by AhmedAlNeaimy** [comment]
Hi Wilson,

Thanks for your reply .. you’re right it’s because Cydown

The newest version is really clean and fast, I’d like to suggest adding a new feature for Push Notifications for the new tweaks updates, new packages “it’ll be great”.

Thanks again,
I really like Zebra .. keep it up♥️

**Comment by wstyres** [comment]
We plan on adding push notifications in the future
