### ISSUE TITLE
Crash when signing into Dynastic Repo

### ISSUE THREAD

**Issue by rubrdcky** [wstyres/Zebra#123]
**Describe the bug**
Signing into the Dynastic repo causes a crash (at least when trying to install Gesto)

**To Reproduce**
Attempt to sign in from a tweaks depiction 

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Beta 11
 - Device Type [e.g. iPhone or iPad]: iPhone 8

**Crash Log or System Log**

[Zebra-2019-05-25-211907.txt](https://github.com/wstyres/Zebra/files/3219901/Zebra-2019-05-25-211907.txt)

**Additional context**

**Comment by midnightchip** [comment]
Its Gesto,  the lowercase vs uppercase package ID

**Comment by rubrdcky** [comment]
Ok thanks! Im glad you know of the issue

Im not sure if I should create a new issue or not but I also just noticed that libCSPreferences shows up as an update in Cydia but not Zebra. It looks like Zebra is still only seeing the package from CreatureCoding and not BigBoss.

**Comment by midnightchip** [comment]
Make a new issue for that, I might not remember

**Comment by midnightchip** [comment]
I haven’t been able to cause a crash with the newest commits, I believe this is fixed
