### ISSUE TITLE
Getting error updating zebra 

### ISSUE THREAD

**Issue by Ducksucc1337** [wstyres/Zebra#1234]
**Describe the bug**
Gives me an error message when trying to update zebra
**To Reproduce**
Steps to reproduce the behavior: update zebra 

**Expected behavior**
Finish updating 

**Screenshots**
![41AB3254-C1A4-470E-9319-C78487DA82C2](https://user-images.githubusercontent.com/61001759/82093444-c454cb00-96c0-11ea-90f5-fecc905b5b45.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <12.4>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1 beta 7-1 trying to update to 1.1.4>
 - Device Type [e.g. iPhone or iPad]: <Iphone>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <Unc0ver >

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
I would say it’s an issue with 1.1 beta 7 we might not know about but we are not supposed to push a fix to 1.1 beta 7 so that it can be updated to the latest version. Could you upgrade Zebra from other package manager instead?
