### ISSUE TITLE
Show which source loading forever or loading timeout configurable

### ISSUE THREAD

**Issue by huyle0406** [wstyres/Zebra#1235]
**Is your feature request related to a problem?
Yesterday, the openpack repo has a problem that took very long time to load, but I just found out after reset caches because there is no notice or warning about that if you just refresh like normal.

**Describe the solution you'd like**
I would like Zebra to always show the loading animation if the source isn’t finished loading. One more feature is loading time-out configurable.

Ps: Sorry, English is not my native language.

**Comment by Infinitay** [comment]
This would be nice. I would like to add to this request by asking for a feature to show the logging/output of source refreshing, similar to when you click reset all sources and a window appears showing you what's happening.

To add to the sources not loading issue OP mentioned, I tried updating through Cydia so I could get more information. I think it's a problem with timeouts and auth?

![FEF1DE43-4E54-46F4-BCB2-75706F5C27EB](https://user-images.githubusercontent.com/6964154/82141373-477e3a00-9803-11ea-9f28-d32cf4d87868.png)

It hanged on me for about one minute and 20 seconds after it outputted "Done." for repo.kritanta.me.

Video of reset: https://streamable.com/3xt6iw

**Comment by Infinitay** [comment]
I would like to confirm that as of Zebra 1.1.6, as OP requested, sources now have loading icons near them when refreshing, as well as my issue has been solved as well as a window popping up indicating which sources have issues.

Thank you Zebra team.
