### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by aestheticsglowexe** [wstyres/Zebra#1242]
**Describe the bug**
I can't find certain (if not half) of the tweaks i search for.

**To Reproduce**
Go to search tab and search for a couple tweaks and you'll notice some of them don't show up.

**Expected behavior**
The tweak you searched for doesn't show up in the search page.

**Screenshots**
![image](https://user-images.githubusercontent.com/40965557/82133865-02e9a300-97f1-11ea-9448-f811fa718cfd.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: version 1.1.4 (not beta)
 - Device Type [e.g. iPhone or iPad]: iPhone 8 Plus
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
//

**Additional context**
//

**Comment by eve0415** [comment]
Which repo does it happens?

**Comment by absidue** [comment]
According to iOS Repo Updates the package was taken down: https://www.ios-repo-updates.com/repository/twickd/package/com.twickd.firethefried.debugify/
