### ISSUE TITLE
(e.g uncover, Chimera, checka1n

### ISSUE THREAD

**Issue by trompas-max** [wstyres/Zebra#1243]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by trompas-max** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Device Information (please complete the following information):**
> 
> _**Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.**_
> 
> * iOS Version [e.g. 12.1.2 or 10.3.3]:
> * Zebra Version [e.g. 1.0~beta1 or beta1]:
> * Device Type [e.g. iPhone or iPad]:
> * Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]:
> 
> **Crash Log or System Log**
> Please provide a Crash Log to help us solve the issue.
> 
> **Additional context**
> Add any other context about the problem here.

How I install and start use

**Comment by eve0415** [comment]
You mean you want to know how to install and use?

[https://getzbra.com/repo/](https://getzbra.com/repo/)

Add this repo, install Zebra.
