### ISSUE TITLE
Crash when trying to import sources list for the first time

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1244]
**Describe the bug**
Zebra will crash when trying to import `sources.list`, when Zebra is opened for the first time.
(I hope people will do this when trying to restore jailbreak)

**To Reproduce**
1. Install Zebra (clean install, there shouldn't be `zebra.db` and `sources.list`)
2. Try to import `sources.list` to Zebra

**Expected behavior**
Initialize Zebra before trying to open import view.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 and up
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
https://pastebin.com/Xud7jrS8

**Comment by wstyres** [comment]
Not the same issue but this is the same bug and crash as #1023
