### ISSUE TITLE
Several bugs in console

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1245]
**Describe the bug**
1. When downloading package and the request time out, Zebra will just finish downloading at 100% and do nothing. 
2. Almost same as 1 but when Zebra lost its connection with Internet, Zebra do nothing. The progress bar doesn't move, it just said, `Downloading: lu%`.
3. While Zebra is refreshing all sources and after Zebra finished installing package, the console is full of downloading or parsing sources. This log pop up after the console writes `Installing local package` and cannot finish unless Zebra finishes refreshing sources.

**To Reproduce**
1. Dunno.
2. Kill Internet.
3. Open Zebra and when Zebra is refreshing entire sources, try to install any package quickly

**Expected behavior**
1. To finish up or just return to queue
2. Return to queue.
3. To not use the same console?

**Screenshots**
1. 
![1D2F50DF-E434-46A2-8995-A2B077892FD0](https://user-images.githubusercontent.com/40632436/82142104-eee78500-9874-11ea-9a71-af0542bc72e3.jpeg)

2. 
![441BBFE7-1A3B-4E30-BD7B-AD386D75887A](https://user-images.githubusercontent.com/40632436/82142092-e42cf000-9874-11ea-8b04-b961a0af072f.jpeg)

3. 
![3C0E0D65-C558-44F1-85D4-C3F8587DB91C](https://user-images.githubusercontent.com/40632436/82142098-e8f1a400-9874-11ea-9814-7e6ac8cf36cf.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.4
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
I think 1 and 2 are fixed as of b419da5709a4486a0743b339a1f2eb257c74a9d4 but I'm not sure about 3, could you elaborate a bit more on it?

**Comment by wstyres** [comment]
Possibly put in a fix for 3 in c5bf68c79703a1f8d9d9932313470b5289bf39ca.

**Comment by wstyres** [comment]
@eve0415 any confirmation?

**Comment by eve0415** [comment]
Can confirm 2 is fixed and I'll test 3 after 30 minutes

**Comment by eve0415** [comment]
3 is also fixed, thanx
