### ISSUE TITLE
For http sources, suggest users to change them to https

### ISSUE THREAD

**Issue by PoomSmart** [wstyres/Zebra#1248]
**Is your feature request related to a problem? Please describe.**
It is a matter of securing ourselves by adding https version of the sources whenever possible. Zebra will have some exceptions (have to be http) for some major sources like BigBoss.

Definition of _whenever possible_: The source URL in https can be resolved successfully.

**Describe the solution you'd like**
An indicator in a source cell to convey insecurity of it and either a swipe action or a button inside the cell to **change** the source URL to be https.

**Describe alternatives you've considered**

**Additional context**

**Comment by p0358** [comment]
`The source URL in https can be resolved successfully.`
And by that we should mean that some key file(s) like Release or Packages is downloaded from https and if it's equal to the one from http, then we are certain that https is supported and that the upgrade should be conducted. Or if Packages/Release exist at all. As 200 OK at `/` path is not enough, a host can be misconfigured and serve a different document root on https port, something I came across many times for many pages...
