### ISSUE TITLE
Zebra not showing all package updates

### ISSUE THREAD

**Issue by rubrdcky** [wstyres/Zebra#125]
**Describe the bug**
libCSPreferences shows up as an update in Cydia but not Zebra. It looks like Zebra is still only seeing the package from the CreatureCoding repo and not BigBoss.

**To Reproduce**
have the CreatureCoding and BigBoss repo installed?

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 11
 - Device Type [e.g. iPhone or iPad]: iPhone 8

**Comment by wstyres** [comment]
What version is Cydia trying to upgrade you to and which version do you have installed?

**Comment by rubrdcky** [comment]
man you guys are on your game tonight, 1.0.4 is the latest version showing in Zebra. 1.1.6 in Cydia. I now have 1.1.6 installed since I just upgraded it through Cydia

**Comment by PoomSmart** [comment]
This is apparently fixed in the latest commits of Zebra. To ensure this, I first installed libCSPreferences 1.0.4, after this Zebra just shows that there is an update to version 1.1.6

**Comment by rubrdcky** [comment]
Alright sounds good. I'm having a lot of fun with this project, you guys are doing a hell of a job!

**Comment by wstyres** [comment]
Closing at it appears to be fixed already
