### ISSUE TITLE
Custom Timeout Length

### ISSUE THREAD

**Issue by Mignif** [wstyres/Zebra#1262]
**Is your feature request related to a problem? Please describe.**
With the 1.1.6 update on Zebra, sources seem to time out incredibly often as I have a large amount of sources. This problem is only made worse with my bad internet connection where I live. 

**Describe the solution you'd like.**
It would be nice to be able to set a custom time out duration so that it works better with slower connections. 

**Describe alternatives you've considered**
It may also be possible to simply slightly extend the timeout period (find some form of middle ground?)

**Comment by wstyres** [comment]
Timeouts were set too low on 1.1.6, an update will be out to extend them again. I don't really think a user configurable option is the best situation for this right now.
