### ISSUE TITLE
Duplicate bingner's source

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1264]
**Describe the bug**
As the title says. When user have updated their ios, kCFCoreFoundationVersionNumber will change. When users restore sources.list that have exported, Zebra will add bingner's and some others that uses kCFCoreFoundationVersionNumber with an old number. This will make import another binger's source from community list and via other package manager (Cydia).

**To Reproduce**
Add bingner's source with old kCFCoreFoundationVersionNumber
Now, you can import another bingner's source via community sources

**Expected behavior**
When importing from sources list, try to ignore kCFCoreFoundationVersionNumber that is written so that Zebra can import with new kCFCoreFoundationVersionNumber

Or, maybe try to update kCFCoreFoundationVersionNumber instead of adding another

**Screenshots**
![image](https://user-images.githubusercontent.com/40632436/82527840-64ec3480-9b72-11ea-9001-547df10ed488.jpeg)

![image](https://user-images.githubusercontent.com/40632436/82527847-69b0e880-9b72-11ea-86b4-0fedfde32f91.jpeg)

![image](https://user-images.githubusercontent.com/40632436/82527859-6fa6c980-9b72-11ea-8a59-3fc8f915785a.jpeg)

**Device Information (please complete the following information):**
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.x

**Comment by Greigh** [comment]
Could this be related to my issue #1267?

**Comment by PoomSmart** [comment]
> Could this be related to my issue #1267?

Nope.

**Comment by absidue** [comment]
To add on to this the Community Sources view seems to always allow you to add Bingner/Elucubratus source, even if you have already added it.

**Comment by wstyres** [comment]
Should be fixed as of 807a649de6894d87eb151ad709159de37b8de759.
