### ISSUE TITLE
Impossible to load any source.

### ISSUE THREAD

**Issue by pitichou** [wstyres/Zebra#1265]
**Describe the bug**
Impossible to load any source. Everything is in red. There is a little « H » at the top and on the right...

**To Reproduce**
Just load the app

**Expected behavior**
View all new packages

**Screenshots**
![image](https://user-images.githubusercontent.com/10462202/82543917-95bd7100-9b54-11ea-8e1c-7fe9b2188dd3.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]:
13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:
1.1.6
 - Device Type [e.g. iPhone or iPad]: 
iPhone 7
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 4.3.1

**Crash Log or System Log**
Nothing

**Additional context**
Nothing

**Comment by wstyres** [comment]
Do you have any steps to reproduce this? It looks like your database somehow got corrupted. I would try going into Zebra's settings and "Reset Source Cache".

**Comment by pitichou** [comment]
Already done, nothing.
App deleted and installed again nothing.
Deleted all sources and added them one by one, nothing.
😭

**Comment by wstyres** [comment]
If you have Filza installed, I would try going to "Open Zebra Documents Directory" in Zebra's settings and deleting zebra.db

**Comment by pitichou** [comment]
It works !
