### ISSUE TITLE
Duplicate repos just without / at end

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#1267]
**Describe the bug**
Zebra allows you to have two similar repos with and without the / at the end when adding with multiple sources. Also works with http(s). 

**To Reproduce**
1. Add a repo with a / and without a / in MULTIPLE SOURCES
2. Also works when trying to add http(s) repos. 

**Expected behavior**
Detect with and without a / at the end to see if it exists or http(s)

**Screenshots**
![IMG_1748](https://user-images.githubusercontent.com/57759540/82561701-d1027480-9b41-11ea-9b73-096e9a2c926b.jpg)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version: iOS 13.3
 - Zebra Version: 1.1.6
 - Device Type: iPhone XS Max
 - Jailbreak Type: unc0ver 4.3.1

**Additional context**
I cannot reproduce with the http(s) for some reason, but I am continuously seeing it with the /.

**Comment by wstyres** [comment]
How did you manage to add these sources? If you attempt to add a source into Zebra without the / on the end, Zebra will add it for you.

**Comment by Greigh** [comment]
![image](https://user-images.githubusercontent.com/57759540/82588742-361d9080-9b69-11ea-87b6-4370777d9f8d.jpeg)
![image](https://user-images.githubusercontent.com/57759540/82588675-2605b100-9b69-11ea-8364-69f27e167b25.jpeg)
![image](https://user-images.githubusercontent.com/57759540/82588700-2c942880-9b69-11ea-972a-2209014befed.jpeg)

I found three more. What all of these have in common is I added them all through the “copy-add” detection. It was either that or sometimes I notice the detection doesn’t work, so I add and paste in a link manually. I’ll have to mess with it.

**Comment by wstyres** [comment]
Ah ok these all appear from the clipboard popup?

**Comment by Greigh** [comment]
At this point, I assume so.

**Comment by PoomSmart** [comment]
URLs from clipboard will now have "/" appended correctly. 44c0ce5750ce744d8f153c745345ae8d630b116d
