### ISSUE TITLE
Twickd repo weird behaviour 

### ISSUE THREAD

**Issue by lewis0917** [wstyres/Zebra#1269]
**Describe the bug**
When accessing a package in the Twickd repo the loading bar never loads fully and I am thus unable to scroll through the description. But what’s weirder is that I am able to repeatedly double tap the bottom of the description screen for it to scroll bit by bit.  

**To Reproduce**

**Expected behavior**
To work like it does in Cydia, among all my various other repos. 

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <11.2>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1.7>
 - Device Type [e.g. iPhone or iPad]: <iPhone>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <unc0ver>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
Been happening ever since I began using Zebra from beta to stable.

**Comment by wstyres** [comment]
Could you show a video of this or a package this is reproducible on? Is it possible to downgrade to an earlier version of Zebra to fix the issue?

**Comment by lewis0917** [comment]
How bizarre — it appears to have fixed itself after all this time (same setup)! Maybe Twickd made a server side change…
