### ISSUE TITLE
URL not found for “Changelog” and “Report Bug”

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#1272]
**Describe the bug**
The page for viewing change log and report bug inside zebra depiction page is not working.

**To Reproduce**
Open either of those in zebra depiction page.

**Expected behavior**
Working

**Screenshots**
https://imgur.com/a/TVIO5HM

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]:  13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.7
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: c1

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
Can you open [Report a Bug](https://getzbra.com/repo/depictions/xyz.willy.Zebra/bug_report.html) on safari?

**Comment by yur1xpp** [comment]
Yep I could? Any idea why?

**Comment by eve0415** [comment]
Then I don't know why you couldn't open those two pages on Zebra because I could.
Can you see if you can open page from home tab. There is a button to report a bug and to see changelog. All of them uses same URL.

**Comment by yur1xpp** [comment]
From the homepage I could open changelog, but not report a bug. Hmmm..

**Comment by PoomSmart** [comment]
From the in-app browser, can you try tapping Safari button at the bottom-right and see if it can land?

**Comment by yur1xpp** [comment]
I guess this is what you mean? 
https://imgur.com/a/s1ftXL9
Seems like the url is again not found if opens from zebra

**Comment by PoomSmart** [comment]
From Safari, can you copy the URL in the address bar and post here?

**Comment by yur1xpp** [comment]
Here: https://github.com/wstyres/Zebra/releases&deluminator_src=xyz.willy.Zebra

I have no idea why is “deluminator” is there, I’m using that tweak for dark depiction on zebra, disabling it seems to solve it.

**Comment by PoomSmart** [comment]
Can you contact the developer of Deluminator about this?

**Comment by yur1xpp** [comment]
I'll, thanks for assisting.
