### ISSUE TITLE
Zebra keeps saying "Downloading Packages"

### ISSUE THREAD

**Issue by Akatsuki-dev** [wstyres/Zebra#1273]
**Describe the bug**
This happened today.After I upgrade Zebra, I can't download tweaks. It just says "Downloading Packages" 

**To Reproduce**
Just install the tweaks like normal.

**Expected behavior**
The tweak will be able to install but no.

**Screenshots**
I will send this on Discord.

**Device Information:**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 10.3.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.7
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: H3lix

**Comment by nicobonii** [comment]
i have the same problem, you fixed it??

**Comment by wstyres** [comment]
Could you provide more information about this issue? What package you are downloading, what source, does this happen on all packages? A screen recording? Without more information we're not able to reproduce the issue or fix it.

**Comment by madhvan-g** [comment]
Same issue faced
iOS 13.3.1 iPhone X
Zebra 1.1.7
Any package any repo, download gets stuck on zero progress with “Downloading Packages”
![image](https://user-images.githubusercontent.com/58142294/82735229-c3b1d980-9d3d-11ea-8049-1fe541593fa3.jpeg)

**Comment by ivanchau14** [comment]
Have the same issue, I think the update broke it. Can’t install anything, have to use cydia or installer now

**Comment by nicobonii** [comment]
I have a fix, you have to downgrade the zebra version on cydia.

**Comment by wstyres** [comment]
@madhvan-g @nicobonii @ivanchau14 Could any of you provide a tweak list that you have installed?

**Comment by ivanchau14** [comment]
> @madhvan-g @nicobonii @ivanchau14 Could any of you provide a tweak list that you have installed?

7-zip (POSIX): 16.02-1
AdaptiveDarkMode: 1.0.1
AirPay: 1.0
AirPort (iOS 13): 1.0
AlbumHider: 0.0~beta3
Alderis Color Picker: 1.0
Apollo Profile Pictures for ShortLook: 1.0.1
AppList: 1.5.16
Apps Manager: 1.5.1-10
AppStore++: 0.9.10
AppSync Unified: 76.0
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
AudioRecorder XS (iOS 12/13): 3.5-5k
AutoUnlockX: 1.0.12
Base Structure: 1-5
Batchomatic: 4.3.1
Berkeley DB: 6.2.32-1
Berry: 1.6
BetterSettings Fix: 1.0
BetterSettings: 0.1.3
BetterWidgets: 1.3-1+debug
BigBoss Icon Set: 1.0
BottomToolBar: 1.5.1
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CallBar XS (iOS 12/13): 3.2-143
CaptureTheFlag: 1.0.2
Cask 2: 1.1.1
CCModules Pro: 1.1.1k
CCSupport: 1.2.2
Cephei: 1.15
Cercube for YouTube: 5.1.18
ChargeAnimations: 3.0.6
ChatHeads Messenger Support: 1.0
ChatHeads Telegram Support: 1.0
ChatSpeaker: 2.1
Choicy: 1.2
CircleSettings: 1.0.1
ColorBanners 3 Rus: 1.0.1
ColorBoard: 0.0.4
ColorFlow 5 (iOS 13): 1.0.4
ColorScroll: 1.0.1
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
CoronaCount: 3
CracksHelper: 100.3
CrackTool4 (iOS 12): 4.0~beta9c
CrashReporter (SparkDev): 1.17.2
cURL: 7.65.0-1
Cydia Installer: 1.1.33
Cydia Translations: 1.1.32~b1
CyDown: 7.1.0
DarkAlertsPls: 1.0
DarkPapers Pack 10: 1.0.0
DarkPapers Pack 1: 1.0.0
DarkPapers Pack 2: 1.0.0
DarkPapers Pack 3: 1.0.0
DarkPapers Pack 4: 1.0.0
DarkPapers Pack 5: 1.0.0
DarkPapers Pack 6: 1.0.0
DarkPapers Pack 7: 1.0.0
DarkPapers Pack 8: 1.0.0
DarkPapers Pack 9: 1.0.0
DarkPapers: 1.0.1
Darwin CC Tools: 927.0.2-1
Darwin Tools: 1.1-1
Dayn: 0.1.6.3
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
DeleteCut: 0.4
Detector: 1.4-j-Beta-3
DictMojiX: 1.4.4
Diff Utilities: 3.6-1
Discord Profile Pictures for ShortLook: 1.0.1
diskdev-cmds: 593.221.1-1
DockX: 1.2.0.1
DontStopMyCall: 1.3
DopeSettings: 0.1.0-1
dotto+: 1.0.1
DragEnabler: 1.0
DynaWall: 2.1
EmojiFontManager: 0.0.7.1
EmojiLibrary: 1.1.3
Facebook Messenger Profile Pictures for ShortLook: 1.0.2
file: 5.35-2
Filza File Manager: 3.7.4-14k
Find Utilities: 4.6.0-2
Flame: 1.3
Flex 3: 3~EarlyAccess4
FloatingDockPlus13 Rus: 1.1.7
FlyJB: 0.2.4.1
gettext: 0.19.8-1
Glyphy: 2.5.7
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
GoodWiFi: 0.0~beta5a
grep: 3.1-1
GrooveTube: 1.0
Groovify: 1.4
gzip: 1.9-1
Harmony: 2.0.1
HYI Repo Icons: 8.0.4
iCleaner Pro: 7.8.2
IconState: 0.1.0
Instagram Profile Pictures for ShortLook: 1.0.2
Instagram Show Likes Free: 1.0
InstaLauncher 2: 1.3
Installer: 5.0.3-2
iNutt: 1.2.0-2
iOS Firmware: 13.3
iPhone Firmware (/sbin): 0-1
iPicMyContactsX: 0.9-7
iTransmission: 5.40
Jailbreak Resources: 1.0~rc1
jbctl: 0.2.3-1
Jellyfish Free: 1.3.3
JoyPixels: 1.0
Juice TA style pack: 1.0
Juice Theme Pack v2: 1.3
Juice: 1.0.1
JuulPods (iOS 13) (AirPort Animation): 2.0
Kaleidoscope: 1.0.1
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
ld64: 450.3-1
ldRun: 0.0.4
LetMeBlock: 0.0.7.1
Liaca Glyphs: 2.7
libbulletin: 0.1-153
libChatHeads13: 1.0
libclang-cpp10: 10.0.0~svn-20191106+dcaf932-1
libcrashreport (SparkDev): 1.1.2
libCSColorPicker: 1.0.3
libCSPreferences: 1.3.9
libidn2: 6.1.2-1
libimagepicker: 1.0.4
libllvm10: 10.0.0~svn-20191106+dcaf932-1
liblto10: 10.0.0~svn-20191106+dcaf932-1
libMRYIPC: 1.0
libnghttp2-14: 1.38.0-1
libpackageinfo (SparkDev): 1.1.4
libplist: 2.0.0-2
libSparkAppList: 1.0.8
libsparkcolourpicker: 1.0.0
libSparkMessage: 1.0.0
libssh2: 1.8.0-2
libswift4: 4.2.1-2
libsymbolicate (SparkDev): 1.9.2
libtapi10: 10.0.0~svn-20191106+dcaf932-1
libtasn1: 4.13-1
libunistring: 0.9.10-1
libxml2: 2.6.32-1
Limneosos: 2.0.2
Link Identity Editor: 2:2.1.2+g5420cb5-1
Locale Profiles in UTF-8: 1.0-1
LocalIAPStore13: 0.0.2
LowBatteryBanner [Public]: 1.0.2
Lune 🌙: 1.5
Lynx Rus: 1.2.7
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Magma Evo Rus: 2.0.1
Maple 2: 1.3
Mega UHB IPv4+6 - iOS 9/10/11/12 - MUHB IPv4+6 (Mega Untrusted Hosts Blocker IPv4 and IPv6): 2.1.1
Messenger No Ads: 3.4.0
MImport: 0.0~beta37
Navale: 2.2.4-1
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
NewTerm (iOS 10 – 13): 2.4
NextUp 2 (iOS 12 & 13): 1.3.4-1
No2Theft3: 1.3k
NoMoreSmallApps: 2.0.1
Notchification: 2.1-1
OpenSSL 1.0 Libraries: 1.0.2s-1
OpenSSL 1.1.1 Libraries: 1.1.1c-1
OpenURLPrompt: 0.0.2-51+debug
p11-kit: 0.23.12-1
PasteAndGo2: 1.0.0
PhotoInfo: 1.0
PicaHide: 1.2.2
PokeCall: 1.3.0
PreferenceLoader: 2.2.4
PrefixUI: 1.2.6
Profile Directory: 0-1
Prysm DevyCC: 1.9.1
Prysm: 1.7.5
Quart: 1.1.3
readline: 8.0-1
Reddit Profile Pictures for ShortLook: 1.1.1
Relocate Application: 0.1.0
Relocate: 0.1.11
ReProvision: 0.5.2~EOL
Rocket for Instagram: 3.6.16
RocketBootstrap: 1.0.9
Rose 🌹: 6.0.2
rsync: 3.1.3-2
Ruby Beta 1: 0.1
Scorpion: 1.3
ScreenshotActions: 1.1.1
sed: 4.5-1
Sential: 1.3
shell-cmds: 118-8
ShortLook: 1.0.17
shuffle: 1.2.8
Siliqua 2: 2.5.2
SimpleActivationActions: 0.1-1
SmartRotate: 1.3.6
Snapchat Bitmoji for ShortLook: 1.0.4.1
SnowBoard Settings Icons Extension: 1.0.18~Beta1
SnowBoard UI Extension: 1.0.31~Beta2
SnowBoard: 1.0.3~Beta2
SnowBoard: 1.2.94~Beta2
Spoke: 1.1.0-1
Sposify: 8.5.52
Substitute Support Package: 0.1~b4
Substrate Safe Mode: 0.9.6003
System Info: 2.7.2
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework (SparkDev): 1.5.2
TFDidThatSay?: 1.3.2
TikTok God: 1.2.0
TikTok Profile Pictures for ShortLook: 1.0.0
TimeToUnlock: 1.0.9
TouchFlow: 1.0.6
Trolldrop: 1.0.0
Trust Cache Injector: 0.4~b5
TTJB Icon Repo: 3.0
TweakReviewsDB: 0.6
Twitch Profile Pictures for ShortLook: 1.0.1
Twitter No Ads: 0.0.2
Twitter No Ads: 0.0.2
Twitter Profile Pictures for ShortLook: 1.0.2
UHB - iOS 9/10/11/12 (Untrusted Hosts Blocker): 1.7.1
UIKit Tools: 1.1.15-2
Ultrasound Rus: 1.2.13
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
URLSchemer: 1.0-0
UUID Generator: 1.6.2-1
VideoSwipes: 1.4.2
Viola Glyphs: 1.2
Viola: 1.9.5
VoiceChanger XS (iOS 11/12/13): 2.2-51
VPN Proxy Master++: 5.1.1-1+debug
VPNStatus: 1.0
WallpaperLoader: 1.0
WeChat Profile Pictures for ShortLook: 1.0.2
wget: 1.19.5-2
WhatsApp Profile Pictures for ShortLook: 1.2.0
Whoops: 1.1.0
WiFiQR: 1.0
Wraith: 0.0.6
XAR: 1.6.1-2
XeonTA-Themes: 2.0
XZ Utils: 5.2.4-4
Y-ThemeXone: 3.0
YouTube Video Thumbnails for ShortLook: 1.0.1
Zebra: 1.1.7
Zenumbra: 1.0.1
zip: 2.32-1

**Comment by wstyres** [comment]
I believe the cause of the issue is CyDown, could you temporarily uninstall it and try out downloading packages again?

**Comment by ivanchau14** [comment]
> I believe the cause of the issue is CyDown, could you temporarily uninstall it and try out downloading packages again?

CyDown was the problem. I turned it off for free and paid tweaks, so I’m not sure why it was being affected

**Comment by wstyres** [comment]
Alright, not sure why it was still affecting it. I will likely release an update that attempts to fix this issue.

**Comment by wstyres** [comment]
Zebra 1.1.8 is out now, please try it out and see if the issue was resolved.

**Comment by ivanchau14** [comment]
Fixed, thanks

**Comment by ivanchau14** [comment]
@wstyres happening again on Zebra 1.2 ~ beta1b

**Comment by eve0415** [comment]
Remove `CyDown` please

**Comment by ivanchau14** [comment]
> Remove `CyDown` please

It works without cydown but I was hoping he could fix it again

**Comment by absidue** [comment]
It will stay broken on 1.2 unless CyDown receives an update to fix it. CyDown uses old bits of code that have been removed on 1.2 and will stay removed. If you can't live without CyDown downgrade to a 1.1.x version.
