### ISSUE TITLE
Cant install /upgrade

### ISSUE THREAD

**Issue by malamalamala** [wstyres/Zebra#1281]
**Describe the bug**
Can’t install anything because of an error(see screenshot)

**To Reproduce**
Steps to reproduce the behavior: install a package 

**Expected behavior**
Normal package installation 
**Screenshots**

https://imgur.com/a/nVMRjvr

**Device Information:** iPhone XS Max, u0, 13.5
 - iOS Version: iOS 13.5
 - Zebra Version: 1.1.8
 - Device Type iPhone 
 - Jailbreak Type unc0ver

**Crash Log or System Log**
No crash log

**Comment by wstyres** [comment]
hm, that is odd. does this only occur with these packages or any package?

**Comment by ImpetuousRacer** [comment]
Getting the same issue. Worked fine on iOS 13.3. Issue started occurring on iOS 13.5.

Tried deleting all sources and reset cache and settings. Close zebra and respring. Did not fix.
Each time this occurs, I had to delete Zebra and reinstall to fix. Seems to randomly occur. Not sure what is causing the issue but definitely related to iOS 13.5.

**Comment by malamalamala** [comment]
Same here. 13.5. 13.3 was ok. And I have this error with every package

**Comment by PoomSmart** [comment]
1.1.9
