### ISSUE TITLE
Crash when trying to Satine theme

### ISSUE THREAD

**Issue by VanishingTacos** [wstyres/Zebra#1282]
**Describe the bug**
Keep getting a crash whenever I try to pull up the the theme Satine 

**To Reproduce**
Steps to reproduce the behavior: Look up Satine in Twickd. Click package name. Crash. 

**Expected behavior**
Should not crash on package page. 

**Device Information (please complete the following information):**

 - iOS Version: 13.5
 - Zebra Version: 1.1.8
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
https://pastebin.com/mv1ta9Td

**Comment by PoomSmart** [comment]
Fixed as of 130ede69b9d51906a22f69bed2a5a139bf9adefb

**Comment by VanishingTacos** [comment]
> Fixed as of [130ede6](https://github.com/wstyres/Zebra/commit/130ede69b9d51906a22f69bed2a5a139bf9adefb)

Awesome 😬

**Comment by PoomSmart** [comment]
1.1.9
