### ISSUE TITLE
cannot log in to Twickd

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1283]
**Describe the bug**
Zebra are not properly handling Twickd repo. Zebra does not save Twickd account even though I logged in from store page.

**To Reproduce**
1. Add Twickd source
2. Try to log in
3. Log in and come back to see you are not logged in

**Expected behavior**
Log in properly

**Screenshots**
https://discordapp.com/channels/566255609251364864/643127818850402325/714011808909754459

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.8
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by wstyres** [comment]
Looks like that isn't the proper URL to be logging in from. Are you experiencing this issue as well?

**Comment by eve0415** [comment]
Yes, I’m already logged in via Zebra’s in-app browser but does not make me log in to Zebra

**Comment by wstyres** [comment]
I've reported the issue to Twickd, I can't reproduce the issue myself and since Zebra is following the API for logging in (as all the other repositories work) I suspect that it is a Twickd issue.

**Comment by eve0415** [comment]
Looks like it was fixed from Twickd’s side just like #1269
