### ISSUE TITLE
cfbundleexecutable defined but missing for trustme app

### ISSUE THREAD

**Issue by ImpetuousRacer** [wstyres/Zebra#1285]
**Describe the bug**
When trying Tom install apps receiving error. Did not have in 13.3

**To Reproduce**
Install app. Seemed it started happening at one point.

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):** iOS 13.5 unc0ver 5.0

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.5>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1.9>
 - Device Type [e.g. iPhone or iPad]: <iPhone 11 Pro Max>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <Unc0ver>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
Example of other user with same issue...
https://www.reddit.com/r/jailbreak/comments/gpha17/question_cfbundleexecutable_defined_but_missing/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
![9E1433F4-2029-45A0-B765-3E3F7EE8804D](https://user-images.githubusercontent.com/40928051/82757711-297e7f80-9d97-11ea-8274-beaeeae4342d.png)

**Comment by PoomSmart** [comment]
The thread implies to me that this happens also on Cydia. Can you confirm that as well?

**Comment by ImpetuousRacer** [comment]
No error in Cydia
![769C8307-4D49-4310-B426-8EE0E2870B7D](https://user-images.githubusercontent.com/40928051/82758017-d9a0b800-9d98-11ea-9b09-a8a4fed784e9.png)

**Comment by wstyres** [comment]
There’s an issue that exists on 13.5 that TrustMe.app doesn’t have an executable on some devices for some reason. This is apparently an Apple issue that has to be fixed. 

As for the issue that occurs in Zebra, it’s a result of a package (in this case Filza) running `uicache` in its postinst script (which refreshes all of the icon caches). Because the executable is missing, the cache refresh fails.

So this isn’t an issue unique to Zebra and you’ll see it  if you run in the command line as well. I’ve been told that this will probably require an update to uikittools to exclude the TrustMe.app until Apple fixes this in a future version.

**Comment by ImpetuousRacer** [comment]
Thanks for the details. So this doesn’t show in Cydia because zebra  offers more transparency.

**Comment by wstyres** [comment]
Yes, I'm going to keep the issue open and pin it in case someone else experiences the same problem. If it turns out that this is a Zebra unique problem then I'll look into it more but for the time being I think an update of UIKitTools is required.

**Comment by absidue** [comment]
UIKitTools has received an update to fix this issue. @ImpetuousRacer Does the error still appear for you after updating UIKitTools?

**Comment by ImpetuousRacer** [comment]
> UIKitTools has received an update to fix this issue. @ImpetuousRacer Does the error still appear for you after updating UIKitTools?

@absidue updated UIKitTools and removed Filza and reinstalled. Everything installed without error now. 

Thanks everyone for all the help, even with this not being Zebra specific.
