### ISSUE TITLE
Error mkstemp when installing tweaks

### ISSUE THREAD

**Issue by beemills1** [wstyres/Zebra#1292]
![C9F6A587-B461-4A6A-BFE0-5E74FF8D7549](https://user-images.githubusercontent.com/37351881/82774286-050fbb00-9e0a-11ea-8bf9-70a4b9708b3a.png)
It’s not downloading certain apps
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Use Zebra 1.1.9 and update unc0ver to 5.0.1
