### ISSUE TITLE
Mkstemp Error when Installing Tweak

### ISSUE THREAD

**Issue by rajatravel** [wstyres/Zebra#1293]
Halo,
I have error with my Zebra when process installing tweak, i get mkstemp error...

Please check on attachment
![EDF1CD38-0E74-4546-BDB9-323668E5D285](https://user-images.githubusercontent.com/41901836/82775216-438c9080-9e71-11ea-9d81-fc448c3855d1.png)

**Comment by wstyres** [comment]
Have you updated to the latest version of Zebra or unc0ver?

**Comment by beemills1** [comment]
I have the same issue don’t know what it is

**Comment by rajatravel** [comment]
[SOLVED]

Just Reinstall Zebra guys,
This issue may effect after Re-JB u0 5.0.1 😬
