### ISSUE TITLE
Batchomatic tweak doesn't show up in zebra search

### ISSUE THREAD

**Issue by jamesafk** [wstyres/Zebra#1294]
**Describe the bug**
When I download the batchomatic tweak it is meant to show a little steering wheel in the search tab but from 1.0.8 and up it doesnt appear there. It shows up in cydia fine but just not in zebra.
**To Reproduce**
1. Download + install batchomatic
2. Tap on the search icon
3. The batchomatic logo will not appear
**Expected behavior**
The batchomatic logo is meant to appear just above where it says search
**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.5>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1.9>
 - Device Type [e.g. iPhone or iPad]: <iPhone>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <unc0ver>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
Batchomatic is not part of Zebra. The developer of Batchomatic has said they are working on adding support for Zebra 1.1.x

**Comment by jbjimmy** [comment]
> Batchomatic is not part of Zebra. The developer of Batchomatic has said they are working on adding support for Zebra 1.1.x

Ok thank you
