### ISSUE TITLE
Shorter timeout for downed repo

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#1298]
**Is your feature request related to a problem? Please describe.**
Repo refreshing took very long for downed repo (especially Karen's repo as of writing this)

**Describe the solution you'd like**
To timeout the downed repo faster.

**Describe alternatives you've considered**
-

**Additional context**
I did try "Clear Sources Cache" and it still took very long, the console stuck add downed repo forever

EDIT: It’s not done yet resetting 15 minutes later...I’m not sure to report this as bug or feature request anymore..

EDIT: 30 minutes later still not done. I’m killing it now, it makes my phone hot.

EDIT: the repos that makes it refreshing eternally:
https://cydia.akemi.ai/
http://cydia.kemmis.info/
http://ryleyangus.com/repo/

Add these repos then you should be able to know what I’m talking about. This is zebra 1.1.9.

**Comment by buitim** [comment]
I know it was mentioned in #1262 (IIRC) that a custom timeout wouldn't be the best decision at this time, but I think it actually might be. Just have a default and allow us to change the timeout (unless there are circumstances, then that's understandable). In the meantime, I've temporarily switched to a different package manager just to check for updates faster.

**Comment by wstyres** [comment]
I've made the timeout configurable as of c9a53d164a42e7f3649de448c13f72a928b64d20.

![Simulator Screen Shot - iPhone 11 Pro - 2020-05-26 at 16 28 57](https://user-images.githubusercontent.com/19736790/82947413-00fcae00-9f6e-11ea-9f7c-ac5db7609071.png)

**Comment by buitim** [comment]
Thank you @wstyres! ☺️

**Comment by yur1xpp** [comment]
Thanks @wstyres, but I'm curios what it means "This timer will reset every time Zebra receives new information from a source"? Does that means the timer is not actually persistent?

**Comment by wstyres** [comment]
No, if you're downloading a file it is a continuous stream of bytes. If you get one byte, the timer resets. You have to receive no new information for the amount of time the user specifies before the source will time out.

**Comment by yur1xpp** [comment]
Okay that's actually very clever way to overcome the not responding repo while still make all other repos extremely fast!

**Comment by yur1xpp** [comment]
@wstyres this isssue still occur on 1.1.10 with timeout set to 5 seconds. The refreshing took indefinitely until I tap cancel, then this pop-up: https://imgur.com/a/ykgUTwh
I think the root cause is this:
>  it is a continuous stream of bytes. If you get one byte, the timer resets
Karen's repo is not actually down, but very very slow, the timer keeps resetting each time and make it in indefinitely fetching the data.
