### ISSUE TITLE
Zebra crashes upgrading packages iOS 13.5

### ISSUE THREAD

**Issue by nak0604** [wstyres/Zebra#1301]
**Describe the bug**
Anytime I have tried to update packages in zebra it crashes on iOS 13.5. 

**To Reproduce**
While viewing the package details on a package that has an update tap the modify to upgrade the package.
**Expected behavior**
A list of remove, reinstall, upgrade, and downgrade show up.

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.9
 - Device Type [e.g. iPhone or iPad]: iPhone 12,5
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 5.0.0

**Crash Log or System Log**
[Crash Log](https://pastebin.com/T8xhsAdL) 

**Additional context**

**Comment by sandhoners123** [comment]
I can not reproduce this issue, maybe try upgrading to unc0ver 5.0.1

**Comment by nak0604** [comment]
Can't upgrade unc0ver to 5.0.1 I tried that already and that version sends
my device into a bootloop and I couldnt restore rootFS either. Had to
restore my iphone to get back on 5.0.0
Nate

**Comment by wstyres** [comment]
@nak0604 Could you post a screen recording of the issue? we're not able to reproduce it.

**Comment by nak0604** [comment]
[Recording](https://drive.google.com/file/d/1qHxzkgAa-I1RxiAizoSHbToZLMk0dsDJ/view?usp=sharing)

**Comment by wstyres** [comment]
So does this only occur when purchasing that package? Does it occur with every paid package from Twickd? Does this happen for packages from other repos?

**Comment by nak0604** [comment]
Every paid package on every repo

**Comment by wstyres** [comment]
Are you signed in to these repos?

**Comment by nak0604** [comment]
Yes I am

**Comment by wstyres** [comment]
We can't reproduce this on our end, I put in a preventative measure in 5b1d1d7cd11036d0459e767f052668093417b914. I would recommend signing out of your sources and signing back in. After that, try to purchase the package again.
