### ISSUE TITLE
Crash When Importing Sources From Sileo

### ISSUE THREAD

**Issue by iAdam1n** [wstyres/Zebra#1303]
When I tried to go to "Community Sources" and tap Sileo on the list to transfer sources, it causes Zebra (1.1.9) to crash. This is with an iPhone SE (iPhone8,4) on iOS 13.5 using checkra1n. I've attached the crash log.

[Zebra.log](https://github.com/wstyres/Zebra/files/4682485/Zebra.log)

**Comment by wstyres** [comment]
Could I see a list of your sileo.sources file as well?

**Comment by iAdam1n** [comment]
Sure. Had to upload as a zip.
[sileo.sources.zip](https://github.com/wstyres/Zebra/files/4682594/sileo.sources.zip)

**Comment by wstyres** [comment]
Looks like there were some issues when importing from a .sources format. I've fixed these in 6ee3411b688cca8f96cd75b83cecc7748ca02344.

**Comment by iAdam1n** [comment]
Amazing thanks!
