### ISSUE TITLE
I have a bug problem

### ISSUE THREAD

**Issue by mohdaljarmal** [wstyres/Zebra#1306]
![586B87C6-D2EA-416C-A93F-30D7067410B3](https://user-images.githubusercontent.com/66002127/82990433-df023a80-a004-11ea-9317-d1b3e912f186.png)

**Comment by absidue** [comment]
The error says you have already installed Zebra from HackYouriPhone, please remove that version and then install Zebra from the official source: https://getzbra.com/repo

**Comment by wstyres** [comment]
As @absidue said, please uninstall the version of Zebra from HackYouriPhone and install it from the official source https://getzbra.com/repo.
