### ISSUE TITLE
1.2 beta prompts to update already up to date packages

### ISSUE THREAD

**Issue by nyuszika7h** [wstyres/Zebra#1310]
**Describe the bug**
The new Zebra 1.2 beta prompts me to update `diskdev-cmds` and `system-cmds` from Bingner’s repo, even though they’re already up to date according to APT when I try to go through with it.

**To Reproduce**
Not sure, it just started happening after the update.

**Expected behavior**
The packages are already up to date, so obviously I shouldn’t be asked to update them.

**Screenshots**
![image](https://user-images.githubusercontent.com/482367/83080990-e7e42200-a07f-11ea-9ecc-6089a7c60c6a.png)
![image](https://user-images.githubusercontent.com/482367/83081001-edda0300-a07f-11ea-8d26-adedb43fb58c.png)

**Device Information (please complete the following information):**

 - iOS Version: 13.3
 - Zebra Version: 1.2~beta1a
 - Device Type: iPhone XR
 - Jailbreak Type: unc0ver 5.0.1

**Comment by eve0415** [comment]
Another bug
![D2B70EE8-BB2E-4445-B862-5872FCC609C6](https://user-images.githubusercontent.com/40632436/83081221-1af7d700-a0bb-11ea-8b07-3015df9a403e.png)
The button shows us “get” but should be “modify”

**Comment by Greigh** [comment]
Also present on iOS 13.5, unc0ver, A12.

**Comment by SnakeGucci** [comment]
I also encounter this bug on
•iOS 13.5
•1.2~beta1a
•Iphone 11 Pro Max
•unc0ver 5.0.1

Removing this repo https://apt.bingner.com/ somehow fix the problem but of course by removing it you cant install any tweaks from that repo.

**Comment by seannymurrs** [comment]
I see this same bug. 

•iOS 13.5
•1.2~beta1a
•Iphone 11 Pro
•unc0ver 5.0.1

**Comment by FreddieDev** [comment]
Same issue here:
•iOS 13.5
•1.2~beta1a
•iPhone X Global
•unc0ver 5.0.1

**Comment by RuTiC** [comment]
![5F874166-5622-4F03-BB78-915DDF8FC89F](https://user-images.githubusercontent.com/55456982/83234251-a6936580-a198-11ea-8e0b-56e9b2ff28c9.png)

also when ur trying to search tweaks nothing appears until u hit the search button

**Comment by eve0415** [comment]
@RuTiC #1313
