### ISSUE TITLE
When using darkmode, buttons‘ text is invisible

### ISSUE THREAD

**Issue by Ofdas-23** [wstyres/Zebra#1311]
As seen in the picture, when using darkmode (I used iOS built-in darkmode) the text in the button is not visible. Turning off darkmode and re-opening Zebra fixes the issue. 
-iOS 13.5
-iPhone 11
-Zebra 1.2~beta1a

![B5C2EE69-7CF3-4159-88F4-F3D798A6A857](https://user-images.githubusercontent.com/59630231/83081100-2843a000-a080-11ea-8532-9883d371f403.jpeg)

**Comment by AntFleming0** [comment]
Change the Accent Colour by going to: Home, settings (Top right), Display.

**Comment by aabosh** [comment]
Fixed in a596ef96. Will be available in the next beta. Marking as scheduled.
