### ISSUE TITLE
Unable to upgrade Tweaks.

### ISSUE THREAD

**Issue by AntFleming0** [wstyres/Zebra#1312]
**Describe the bug**
When trying to upgrade the tweak, it states is yellow text, unable to mkstemp.

**To Reproduce**
Simply upgrade a tweak. 

**Expected behavior**
Tweak to be upgraded.
**Screenshots**
![A1CDC25A-659E-499C-A8DC-CEE6E7E4F2C4](https://user-images.githubusercontent.com/66041878/83081821-7ef9ab80-a079-11ea-814c-b14298fce834.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.5>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.2\~beta1>
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by eve0415** [comment]
try reinstall via Cydia. Most of the people was fixed by doing this.

**Comment by AntFleming0** [comment]
Thanks, that solved it!
