### ISSUE TITLE
Live search doesn’t work on beta

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1313]
**Describe the bug**
As the title says.

**To Reproduce**
Search

**Expected behavior**
Live search

**Device Information (please complete the following information):**
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta1a

**Comment by absidue** [comment]
Fixed in 07fb17f3

**Comment by aabosh** [comment]
Fixed is merged, now marking this as scheduled.
