### ISSUE TITLE
„Start“-Tab‘s UI remained the old, all others changed

### ISSUE THREAD

**Issue by Ofdas-23** [wstyres/Zebra#1315]
After updating Zebra to 1.2~beta1a, the UI changed everywhere except for the „start“-tab.

-use Zebra Version 1.2~beta1a
-Lauch Zebra
-Look at the UI from tabs except „start“
-look at the UI from „start“
—start remained old

I expected for the „start“-tab to change as well, well it didn’t.

![AFB510C7-AC35-4BF3-84DC-D8F486453F26](https://user-images.githubusercontent.com/59630231/83082446-d00e9d00-a083-11ea-87d6-94cf8e6b3eab.png)

-iOS 13.5
-Zebra 1.2~beta1a
-iPhone 11
-unc0ver

Note:
I am not sure if this issue applies to everyone and every device, nor I am not sure, if this is really counted as an issue, sorry, if not.

**Comment by aabosh** [comment]
Do you mean the corners of the cells aren't rounded like the other pages? If so, this isn't really a bug. We're planning to redesign the Home page in a later update 😄

**Comment by aabosh** [comment]
Closing for now. If what I said above isn't the case, I'll reopen.
