### ISSUE TITLE
Zebra changed from German to partly English

### ISSUE THREAD

**Issue by Ofdas-23** [wstyres/Zebra#1319]
Hello, using Zebra 1.2~beta1a, the button‘s Text to install the tweak changed to „Get“. 

To reproduce, you should update to Zebra 1.2~beta1a and use its German version.
-launch Zebra
-Swipe for more on a package
-button‘s text is „Get“

„Installieren“ instead of „Get“. 
A simple „+“ would also look good in my opinion :)

![FED8CA7C-C65A-4A00-963D-355D1BE13AAA](https://user-images.githubusercontent.com/59630231/83083127-963e9600-a085-11ea-800e-f37ef78ff1de.png)

-iOS 13.5
-Zebra 1.2~beta1a
-iPhone 11
-unc0ver

**Comment by absidue** [comment]
New strings in 1.2 won't be translated yet as a lot is still changing

**Comment by aabosh** [comment]
@absidue is correct. We won't be translating beta strings until a later date, once we're more confident that the changes are final. Closing this issue.
