### ISSUE TITLE
More Options Crash Zebra

### ISSUE THREAD

**Issue by WenaWindows** [wstyres/Zebra#1321]
**Describe the bug**
Zebra crash on more options menu

**To Reproduce**
1- Click on any tweak
2- Click on the option menu (tree dots button)

**Expected behavior**
When you click it, it shows a menu with options for downgrade a tweak or reinstall it 

**Screenshots**
![3748AD3C-FEC8-4402-9000-254EEBF2E8A6](https://user-images.githubusercontent.com/65914817/83085267-75604b80-a059-11ea-8172-4ef6da65cb60.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta1a
 - Device Type [e.g. iPhone or iPad]: Ipad pro 2019
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by aabosh** [comment]
Can you provide a crash log please?

**Comment by WenaWindows** [comment]
[CrashLog Zebra.txt](https://github.com/wstyres/Zebra/files/4693981/CrashLog.Zebra.txt)

**Comment by Co2333** [comment]
You don’t need crash log, it is easy to tell. The same issue as checkra1n loader. You used the UIAlertViewController with style action sheet in iPad which is not allowed. 

![A6254BA0-C062-4DCF-B48E-411B21CCB025](https://user-images.githubusercontent.com/25259084/83180214-ade54f80-a155-11ea-938d-edd51cfb8f5f.png)

**Comment by aabosh** [comment]
This has been fixed in 1d55d179. Thanks for the report! It will be fixed in the next beta. Marking this as scheduled.
