### ISSUE TITLE
Changing to the new zebra icons aren’t working

### ISSUE THREAD

**Issue by TomerKILLer** [wstyres/Zebra#1324]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta1a
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Do you have a theme applied? Have you tried running `uicache -a`

**Comment by TomerKILLer** [comment]
yea i figured it thx

‫בתאריך יום ב׳, 22 ביוני 2020 ב-18:17 מאת ‪Wilson Styres‬‏ <‪
notifications@github.com‬‏>:‬
