### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by aestheticsglowexe** [wstyres/Zebra#1332]
**Describe the bug**
Tweaks won't start downloading.

**To Reproduce**
try downloading a tweak.

**Expected behavior**
the console will stuck on "downloading packages. . .".

**Screenshots**
![image](https://user-images.githubusercontent.com/40965557/83196714-a9f90380-a13c-11ea-936c-e724069e71a3.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta1a
 - Device Type [e.g. iPhone or iPad]: iphone 8 plus
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver v5.0.1

**Crash Log or System Log**
//

**Additional context**
I don't really know if the problem caused by a tweak i just thought I'd report this.

**Comment by aestheticsglowexe** [comment]
I tried this in safe mode and it started downloading so it's definitely caused by a tweak or smth.

**Comment by absidue** [comment]
Remove CyDown of you have it installed

**Comment by aestheticsglowexe** [comment]
> Remove CyDown of you have it installed

yeah i figured but still tho im getting that new error ![image](https://user-images.githubusercontent.com/40965557/83202664-5b516680-a148-11ea-9e9b-b62e2c73130b.jpeg)

**Comment by eve0415** [comment]
reinstall from cydia

**Comment by aestheticsglowexe** [comment]
> reinstall from cydia

omg thank you that worked!
