### ISSUE TITLE
一直显示正在下载软件包

### ISSUE THREAD

**Issue by KrisWuuuu** [wstyres/Zebra#1334]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by terry3041** [comment]
英文都不會打開什麼issue？

**Comment by terry3041** [comment]
Can you please use English to clearly describe your issue using the above template?

**Comment by KrisWuuuu** [comment]
In the latest beta edition，installing tweaks will stuck in downloading. But I resolve the problem by reinstalling the old version in cydia. I thought you could use “translate” so I type in Chinese .
 Sorry！

**Comment by terry3041** [comment]
@KrisWuuuu 因為作者只會看英文啊，而且翻譯的用字有時候會不準確。
如果你有裝 Cydown 的話，可以刪掉。
因為最新版本的 Zebra 和 Cydown 有衝突。

**Comment by KrisWuuuu** [comment]
I just noticed the same situation in issue. 
Sorry to be a pest
