### ISSUE TITLE
[1.2] Request to have depiction in package view respect app theme (dark mode)

### ISSUE THREAD

**Issue by MoTem** [wstyres/Zebra#1338]
**Is your feature request related to a problem? Please describe.**
This is not exactly related to 1.2 but when the depiction is loaded up it is pure white, while my zebra app is in dark mode. Since the package viewer is being redesigned I suggest this should be looked at.

**Describe the solution you'd like**
The depiction inside the package view have its colors inverted so it follows the dark theme.

**Describe alternatives you've considered**
No solutions I could explore

**Additional context**
Screenshot attached
![1441](https://user-images.githubusercontent.com/49055655/83219276-fabd2c00-a13d-11ea-975a-61b801cd33f7.jpg)

**Comment by p0358** [comment]
https://github.com/wstyres/Zebra/wiki/Repositories#depictions

That information is provided in headers and also in user-agent field for convenience (in case of static pages). It's up to the repo to support the dark mode. It does work with my repo for instance.
