### ISSUE TITLE
[BUG] Community Repo auto detection 

### ISSUE THREAD

**Issue by SeMoOo** [wstyres/Zebra#134]
I noticed that after the beta12 update, community repo section failed to identify which repo to load or which jailbreak I am using to avoid JB conflicts.

I am running Chimera 1.0.7, iPhone 11,6, iOS 12.1.2

Thank you for this awesome package manager.

**Comment by PoomSmart** [comment]
We acknowledged that, this is a known bug that has been fixed in the latest commit, and will be in the next beta.

**Comment by SeMoOo** [comment]
Thank you. 👍

**Comment by PoomSmart** [comment]
Let us open this issue so that others with the same problem will see and won't create another post for it.
