### ISSUE TITLE
Cydown Issues

### ISSUE THREAD

**Issue by K9Paradox** [wstyres/Zebra#1340]
**Describe the bug**
The tweak cydown once again is causing an issue when attempting to install packages. If the tweak is enabled, when downloading a package, it will only say "Downloading Packages..." and will never advance.

**To Reproduce**
Have Zebra version 1.2~beta1a and Cydown 7.1.0 installed. With the Zebra option enabled in Cydowns settings

**Expected behavior**
For packages to download as they normally would, without issues.

**Screenshots**
N?A

**Device Information (please complete the following information):**
 - iOS Version 13.5
 - Zebra Version  1.2~beta1a
 - Device Type iPhone X
 - Jailbreak Type Unc0ver

**Crash Log or System Log**
N/A

**Comment by eve0415** [comment]
CyDown is NOT a feature of Zebra. Please contact developer of CyDown if you want it to support Zebra 1.1 and up. I think there is no reason to have compatibility with ANY tweaks that hooks Zebra. The developer should make the tweak compatible to Zebra not the way around.

**Comment by K9Paradox** [comment]
> CyDown is NOT a feature of Zebra. Please contact developer of CyDown if you want it to support Zebra 1.1 and up. I think there is no reason to have compatibility with ANY tweaks that hooks Zebra. The developer should make the tweak compatible to Zebra not the way around.

Why was it once updated before to fix the issue then?
https://github.com/wstyres/Zebra/issues/1273#issuecomment-633109484

**Comment by eve0415** [comment]
I hope that is because many people are saying its a bug with Zebra that is not. Thus, if you can see this commit, https://github.com/wstyres/Zebra/commit/43b121ad0e04571cb239d48314f28db774e6b2b5, it is told that all kind of these **duplicate** methods will be removed in 1.2.

It is more faster that you will not use this tweaks or ask the developer to update their tweaks for future Zebra updates

**Comment by wstyres** [comment]
We're not fixing anything related to CyDown. Ask the developer of CyDown to update it or uninstall the tweak.
