### ISSUE TITLE
Installing Screen w/ "Restart Springboard" Persists After Installing

### ISSUE THREAD

**Issue by IsThatEazy** [wstyres/Zebra#1342]
Every time I install a tweak(s). After hitting restart springboard & open up zebra the downloading screen w/ the option to restart springboard appears again.

**Comment by wstyres** [comment]
Could you provide more information such as a screen recording?

**Comment by IsThatEazy** [comment]
The most recent beta update fixed the problem. If it does reappear I’ll open another ticket.
