### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by pq70pq** [wstyres/Zebra#1348]
I can't install any tool and the screen stops loading
![862F5103-FFE1-4BD1-B106-146C6D650D77](https://user-images.githubusercontent.com/66190379/83342993-d9a33980-a2fd-11ea-84a5-cc15723ef5da.png)

**Comment by eve0415** [comment]
Remove `CyDown` if you have it installed

**Comment by pq70pq** [comment]
Assignment-3.html

**Comment by pq70pq** [comment]
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link rel="stylesheet" href="css/bootstrap.min.css" >
    <link rel="stylesheet" href="css/style3.css">

    <title>mod-3-Assignment</title>
  </head>
  
<body>
<div class="container">
<nav class="navbar navbar-light  nav-css">
     <span class="navbar-brand mb-0 h1">Food, LLC</span>
     <button type="button"  class="navbar-toggler" data-toggle="collapse" data-target="#myMenu">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="myMenu">
                <ul class="navbar-nav bg-light text-center">
                  <li class="nav-item"><a class="nav-link" href="#menu1">Chicken</a></li>
                  <li class="nav-item"><a class="nav-link" href="#menu2">Beef</a></li>
                  <li class="nav-item"><a class="nav-link" href="#menu3">Sushi</a></li>
                </ul>
              </div>
</nav>
<h1 class="text-center my-5">Our Menu</h1>
<div class="row ">
    <div class="col-xs-12 col-sm-6 col-md-4 item "id="menu1"> 
            <p class="text-center menu-title" >Chicken</p> <p >Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sed ipsa totam iusto blanditiis aliquid laboriosam quae odio dolores accusantium? Eaque odit asperiores beatae temporibus vel placeat iste, explicabo 
                    blanditiis aliquid laboriosam quae odio dolores accusantium? Eaque odit asperiores beatae temporibus vel placeat iste, 
                    blanditiis aliquid laboriosam quae odio dolores accusantium? Eaque odit asperiores beatae temporibus vel placeat iste, explicabo explicabo dolore repellendus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam molestiae earum dolore dolores sapiente unde inventore perferendis sunt, numquam, fuga aliquam nesciunt. Quos, ipsam corrupti? Inventore nam minima ut esse? ore sunt, numquam, </p> </div>

    <div  class="col-xs-12 col-sm-6 col-md-4 item " id="menu2"> <p  class="text-center menu-title" >Beef</p>  <p >Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sed ipsa totam iusto blanditiis aliquid laboriosam quae odio dolores accusantium? Eaque odit asperiores beatae temporibus 
            blanditiis aliquid laboriosam quae odio dolores accusantium? Eaque odit asperiores beatae temporibus vel placeat iste, explicabo vel placeat iste, explicabo dolore repellendus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam molestiae earum dolore 
            blanditiis aliquid laboriosam quae odio dolores accusantium? Eaque odit asperiores beatae temporibus vel placeat iste, explicabo dolores sapiente unde inventore perferendis sunt, numquam, fuga aliquam nesciunt. Quos, ipsam corrupti? Inventore nam minima ut esse ore   </p>  <a href="#">Back to Top</a> </div>
    <div class="col-xs-12 col-sm-12 col-md-4 item" id="menu3"   > <p  class="text-center menu-title">Sushi</p> <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sed ipsa totam iusto blanditiis aliquid laboriosam quae odio dolores accusantium? Eaque odit asperiores beatae temporibus
            blanditiis aliquid laboriosam quae odio dolores accusantium? Eaque odit asperiores beatae temporibus vel placeat iste, explicabo
            blanditiis aliquid laboriosam quae odio dolores accusantium? Eaque odit asperiores beatae temporibus vel placeat iste, explicabo   vel placeat iste, explicabo dolore repellendus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam molestiae earum dolore dolores sapiente unde inventore perferendis sunt, numquam, fuga aliquam nesciunt. Quos, ipsam corrupti? Inventore nam minima ut esse? ore  </p>  </div>
</div>

 </div>







    
    <!-- jQuery first, t
