### ISSUE TITLE
Ignored updates are not saving after sources refresh

### ISSUE THREAD

**Issue by Insaneous** [wstyres/Zebra#135]
**Describe the bug**
Ignored updates are not saving after sources refresh

**To Reproduce**
1. Ignore updates on any package
2. Refresh sources
3. Return to Packages tab

**Expected behavior**
Ignored updates should save after sources refresh.

**Screenshots**
https://streamable.com/yyeeu

**Device Information (please complete the following information):**
 - iOS Version: 11.3.1
 - Zebra Version: beta12
 - Device Type: iPhone

**Crash Log or System Log**
Not a crash so ¯\\\_(ツ)_/¯

**Comment by PoomSmart** [comment]
Should be fixed in the latest commits and should we have this fix on beta 13.

**Comment by Insaneous** [comment]
Thank you! Closing the issue now.

**Comment by PoomSmart** [comment]
Let us open it for visibility so others don't report the same bug.

**Comment by PoomSmart** [comment]
Beta 13 has been released, close this until any unexpected adverse effects came up.
