### ISSUE TITLE
Strange error when installing packages

### ISSUE THREAD

**Issue by seanie86** [wstyres/Zebra#1359]
**Describe the bug**
Not sure if it's a bug but an error or what might be an error that shows when I install packages.

**To Reproduce**
I'm not sure how I would reproduce the bug 
**Expected behavior**
Just expect nothing to show up in the red text.

**Screenshots**
I have a screenshot I can add.

**Device Information (please complete the following information):**
I'm on an 8 plus running 13.4.1 using checkrain 1.0.1. And I'm using zebra 1.2 Beta b that was released on Sunday may 31 2020 but this error has been showing for about a week or so.
***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [13.4.1]
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.2beta 1b>
 - Device Type [e.g. iPhone or iPad]: <iphone 8 plus>
 - Jailbreak Type [, checkra1n, etc.]: <checkrain
![C1368AA6-7A95-42BE-92EB-364DEB16492C](https://user-images.githubusercontent.com/41923151/83371404-40186e00-a377-11ea-8863-ba5da5a1e8a5.png)
![62FD51F1-21F4-496A-B43B-5EE4E1C1C190](https://user-images.githubusercontent.com/41923151/83371417-4d355d00-a377-11ea-8201-b79b2d7db10d.png)

>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Does this happen on Cydia too?

**Comment by seanie86** [comment]
No it only happens with zebra

**Comment by wstyres** [comment]
This is not an error, it is a problem with a package you're trying to install and dpkg is reporting it as an error. There is nothing to worry about.
