### ISSUE TITLE
Repo 

### ISSUE THREAD

**Issue by motoissa** [wstyres/Zebra#136]
**Describe the bug**
When you press on a repo and press on purchase it crashes 
**To Reproduce**
Press on a repo and then press purchase
**Expected behavior**
No idea I didn’t know that it was an option 
**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
12.1.2
1.0 beta 12
iPhone 7 Plus 
**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Most likely you tapped the login/purchase button of an unsupported repo. The button should not be there and the fix has already been implemented. Should we see it fixed on beta 13.

**Comment by motoissa** [comment]
Ok thanks   
  

  
  

  
  
>
