### ISSUE TITLE
Can’t install more than one package at a time

### ISSUE THREAD

**Issue by BaddestAssasin** [wstyres/Zebra#1361]
**Describe the bug**
![C7CAFD42-1243-4180-A510-290E15F92DA1](https://user-images.githubusercontent.com/49458831/83414873-2f560f80-a3ec-11ea-832b-2655adc11e9e.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
This is more of some other package manager is accessing a file Zebra meant to have an exclusive access.
