### ISSUE TITLE
Stuck on „downloading packages“

### ISSUE THREAD

**Issue by trismegis7os** [wstyres/Zebra#1365]
**Describe the bug**
Since a couple of days I’m unable to download or update any packages. As the title says, the console only appears to say “downloading packages” to afterwards time out, without having made any progress. 

**To Reproduce**
Install or update package independent from source. 

**Expected behavior**
To actually install or update the package requested. 

**Screenshots**

![503F4A1F-7E8E-4E94-ADBD-553EA258BA08](https://user-images.githubusercontent.com/66309280/83514405-e11c3b80-a4d3-11ea-8935-f74a4e8534f8.jpeg)

**Device Information (IPhone 11,6):**

 - iOS Version: <13.5>
 - Zebra Version: <Zebra 1.2~beta1a>
 - Jailbreak Type: unc0ver

**Comment by eve0415** [comment]
Remove CyDown please

**Comment by trismegis7os** [comment]
> Remove CyDown please

Thanks a lot, that has resolved the problem. I’m Curious, could you explain me how this problem was correlated to CyDown?

**Comment by eve0415** [comment]
CyDown uses methods that is deprecated from Zebra 1.1. CyDown needs an update to support future Zebra updates.

**Comment by trismegis7os** [comment]
Thanks eve, I understand.
