### ISSUE TITLE
Background App Refresh for sources, push notifications for new updates

### ISSUE THREAD

**Issue by Aransh** [wstyres/Zebra#1367]
**Describe the solution you'd like**
Use iOS's background app refresh to refresh sources in the background, and send a Push notification if an installed package has an update.

**Additional context**
Maybe be able to set interval
Have an "only on WiFi" toggle
Also a little Label somewhere in the changes tab indicating when was to last sources refresh will be nice.

**Comment by wstyres** [comment]
Duplicate of #595
