### ISSUE TITLE
Broke tweaks

### ISSUE THREAD

**Issue by hcm77** [wstyres/Zebra#1370]
Hi dear I want to report an issue with the last update of zebra that brok tweak reviewsDB 
Can you try to fix it please 
![02C9EE5B-A655-43E2-9748-F1F9ED30E740](https://user-images.githubusercontent.com/63616738/83574921-1f971200-a537-11ea-8c78-11f35545949e.jpeg)

**Comment by absidue** [comment]
TweakReviewsDB is not part of Zebra. Please contact the developer of TweakReviewsDB instead. Please keep in mind that you are using a beta version of Zebra so the developer may not update their tweak until 1.2 is out of beta.

If you need TweakReviewsDB please downgrade Zebra to version 1.1.10 which is the most recent stable version.
