### ISSUE TITLE
Keyboard iPhone 6, iOS 12.4.7

### ISSUE THREAD

**Issue by JeffMoon21** [wstyres/Zebra#1376]
**Describe the bug**
When typing something in the search section it goes with lag the keyboard, it doesn’t go real time 

**To Reproduce**
Conduct a search 
**Expected behavior**
When typing something in the search section it goes with lag the keyboard, it doesn’t go real time 
**Screenshots**

**Device Information (please complete the following information):**
IPhone 6 
iOS 22.4.7
***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <12.4.7>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <iPhone>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <checkra1n> 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by CanerKaraca23** [comment]
I have iPhone 5S. I'm having this issue too. But this isn't a Zebra bug. iPhone 5S and 6 have 1GB RAM and this isn't good value to run Zebra more fast.

**Comment by eve0415** [comment]
How about disabling `live search`
