### ISSUE TITLE
No content menus (Haptic touch)

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#1377]
**Describe the bug**

It is no longer possible to haptic touch packages in the packages tab, search tab, changes tab or wishlist. It is no longer possible to haptic touch Reddit articles. It is no longer possible to haptic touch featured packages on the homepage.

**To Reproduce**

^

**Expected behavior**

I expect context menus to display when the said elements are haptic touched. The features implemented in #942 and #943 should be working.

**Screenshots**

N/A

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2 - beta 1b
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by absidue** [comment]
This is a known bug: https://github.com/wstyres/Zebra/releases/tag/v1.2-beta1a

**Comment by worldlydev** [comment]
> This is a known issue as stated in the changelog: https://github.com/wstyres/Zebra/releases/tag/v1.2-beta1a

Oh, oops. Thought it was weird since it only affected these instances but not for example 3d-touch in individual sources.

**Comment by absidue** [comment]
It was temporarily disabled.
