### ISSUE TITLE
Crashing On Sources Tab

### ISSUE THREAD

**Issue by aizoule** [wstyres/Zebra#138]
**Describe the bug**

**To Reproduce**
-Installed the latest beta.
-Touched the “Sources” tab.
-Crashes instantly.

**Expected behavior**
-Show repos I have.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
https://pastebin.com/xsUCjMQa

**Additional context**
Source List: https://pastebin.com/LQjw4n6N

**Comment by wstyres** [comment]
Has this issue occurred on an earlier beta or is it only since upgrading today?

**Comment by aizoule** [comment]
Its new. I didnt get any error before that. Also, now it is crashing while opening the app.

https://streamable.com/la2il

**Comment by PoomSmart** [comment]
Based on crashing, this is most likely the app crashing due to a repo with no `origin` value. Could you try removing the source file and adding one-by-one to see which repo is problematic? @aizoule

**Comment by Dadoum** [comment]
I had error, I fixed it by deleting /var/mobile/Documents/xyz.willy.Zebra for resetting Zebra.
