### ISSUE TITLE
Connection 

### ISSUE THREAD

**Issue by kmokhtar79** [wstyres/Zebra#1382]
The issue I have is that the pop up for wireless data permission never appears after installing Zebra and opening the app for the first time. To fix this, I have to install a tweak - network disabler, and enable WiFi access for zebra, from the tweak. Then Zebra can connect normally right away.

**Comment by wstyres** [comment]
Is this on a device purchased in China?

**Comment by kmokhtar79** [comment]
Right

**Comment by wstyres** [comment]
Duplicate of #1356
