### ISSUE TITLE
Import/sync repos with cydia

### ISSUE THREAD

**Issue by FrankHeijden** [wstyres/Zebra#1384]
It would be a great feature to import all current sources from cydia over to zebra, or have them be “synced” over.

**Comment by worldlydev** [comment]
> It would be a great feature to import all current sources from cydia over to zebra, or have them be “synced” over.

This is already possible. Go to home > community sources > transfer sources

**Comment by FrankHeijden** [comment]
I see, must have missed that, thanks!
