### ISSUE TITLE
Add missing features from 1.1 to the 1.2 beta

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#1389]
***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2 - beta 1b
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Comment by worldlydev** [comment]
Extra padding in console:
1.1:
![7A53E37C-C7CE-4171-AEC5-E5E0ECBE8D55](https://user-images.githubusercontent.com/51668635/83795558-ee862100-a69f-11ea-911e-2c9d3905f840.jpeg)
1.2:
![586DA26F-A88C-4022-878F-3799017D8A36](https://user-images.githubusercontent.com/51668635/83795578-f5ad2f00-a69f-11ea-8226-b7d3d48fa12c.jpeg)

**Comment by worldlydev** [comment]
Download timeout:
![D9E46B14-4C37-4EE0-8DE3-857941604389](https://user-images.githubusercontent.com/51668635/83795698-21c8b000-a6a0-11ea-8e25-c661860b404e.jpeg)

**Comment by wstyres** [comment]
These are not bugs, the features simply have not been merged into the 1.2 version yet and there has not been a beta released since 1.1.10 for us to put them in.
