### ISSUE TITLE
Download error zebra 

### ISSUE THREAD

**Issue by Agui109** [wstyres/Zebra#1391]
**Describe the bug
When downloading packages, the download won’t continue. Stuck in downloading 0% 

**To Reproduce**
Download some package 
**Expected behavior**
I’ve expected it to download and install a package without any issues 

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.5>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.2~beta1b>
 - Device Type [e.g. iPhone or iPad]: <IPhone>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <unc0ver>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
Remove `CyDown`please
