### ISSUE TITLE
Batchomatic

### ISSUE THREAD

**Issue by PEAR5EY** [wstyres/Zebra#1393]
**Describe the bug**
Install Batchomatic. 
No steering wheel in search.
Works on Cydia.

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.10 (most up to date for 5 June)
 - Device Type [e.g. iPhone or iPad]: iPhone XR
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 5.0.1

**Comment by eve0415** [comment]
Batchomatic is not updated to support Zebra 1.1 and up.
I’ve updated for myself and pull requested.
If you want please compile it for yourself. But the best is to wait for the developer to update. Also, there is a comment on the last message with the reason why he is not updated for now.
https://github.com/captinc/Batchomatic/pull/6

**Comment by PEAR5EY** [comment]
Thanks for your time answering this 👍🏻

Thanks,

Lee

On 5 Jun 2020, at 2:39 pm, eve0415 <notifications@github.com> wrote:

﻿
Batchomatic is not updated to support Zebra 1.1 and up.
I’ve updated for myself and pull requested.
If you want please compile it for yourself. But the best is to wait for the developer to update. Also, there is a comment on the last message with the reason why he is not updated for now.
captinc/Batchomatic#6
