### ISSUE TITLE
Multiple Repos

### ISSUE THREAD

**Issue by Lettucecake** [wstyres/Zebra#14]
I’m sorry if I’m requesting a feature that many others have requested too, but it IS pretty painful to add every repo one at a time. Is it possible to do something like the tweak Flame, where you copy all of your repos, and then Zebra will add all of them.
P.S. I’m not angry that the following feature is not there, but a built in backup feature, where it sends all of your tweaks to your email or saves it in notes would be amazing. Love your work though, works like a dream, 12.0.1

**Comment by wstyres** [comment]
For now all that is available is a "Transfer from Cydia" option under the "Community Sources" page which will import all of your repos from Cydia. I can look into a separate backup/import function though.

**Comment by wstyres** [comment]
#29 has been merged into Zebra and I'll finish the UI up and get it into the next beta

**Comment by wstyres** [comment]
Implemented in Zebra 1.0~beta9
