### ISSUE TITLE
Store Purchases

### ISSUE THREAD

**Issue by dohmsalex** [wstyres/Zebra#1403]
Can’t add the dynastic repo and open up purchases to link account. It’s simply not there.
**To Reproduce**
Steps to reproduce the behavior: add dynastic and try to access your purchases.

**Expected behavior**
I could download the scorpion tweak I had purchased through Cydia.

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.5.1>
 - Zebra Version [e.g. 1beta1]: <1.1.10>
 - Device Type [e.g. iPhone or iPad]: <iPhoneX>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <Checkra1n >

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Make sure you have properly added the dynastic repo using `https` and if that does not solve the problem, try removing Dynastic and re-adding it.

**Comment by dohmsalex** [comment]
That totally worked, thank you!

Best,
Alexander Dohms
