### ISSUE TITLE
Please enhance to make the animation of the refresh and the animation after the refresh is completed more smooth.

### ISSUE THREAD

**Issue by w6511** [wstyres/Zebra#1416]
**Is your feature request related to a problem? Please describe.**
Please strengthen the smoothness of the drop-down refresh and the top rebound animation after the refresh is completed.

![20200613-052942000-iOS](https://user-images.githubusercontent.com/65994118/84560956-2a457880-ad7b-11ea-9620-786d3b063303.gif)

**Describe the solution you'd like**
The animation of the top rebound after the pull-down refresh and refresh both smooth.

**Additional context**
Zebra v1.1.10, iPhone 8, iOS 13.5

**Comment by wstyres** [comment]
The refresh animation is provided by iOS, we can't really do anything to make it smoother.
