### ISSUE TITLE
Zebra crash when clear sources cache

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#1420]
**Describe the bug**
Crash when clear sources cache

**To Reproduce**
Reset-Clear Sources Cache

**Expected behavior**
Not crash

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.10
 - Device Type [e.g. iPhone or iPad]: iPad 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
https://pastebin.com/W7Z92wYv 

**Additional context**

**Comment by wstyres** [comment]
Is this reproducible? Would be very helpful in finding a fix.

**Comment by wstyres** [comment]
Can you still reproduce this? Will close if you can't.

**Comment by yur1xpp** [comment]
Sorry for the late reply, I haven't visit Github for quite some time now. I think it can be closed for now, since I haven't notice this issue anymore for (though I didn't frequently reset cache).
