### ISSUE TITLE
Not totally removing tweaks 

### ISSUE THREAD

**Issue by Oliverkiller** [wstyres/Zebra#1435]
**Describe the bug**
When I remove tweaks using zebra it didn’t get removed totally 

**To Reproduce**
Uninstall a tweak then open cydia an error message pops saying that a tweak isn’t fully removed

**Expected behavior**
The tweak uninstalled 

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.5>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1.10>
 - Device Type [e.g. iPhone or iPad]: <iPhone 6s >
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <unc0ver>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**A tweak like gimp is not totally removed and it gave me an error in cydia

**Comment by eve0415** [comment]
What tweak did you try to remove?

**Comment by Oliverkiller** [comment]
I removed gump from kurrt repo

**Comment by wstyres** [comment]
Could you post a screen recording of the issue? This could be a problem with the package itself.

**Comment by Oliverkiller** [comment]
> Could you post a screen recording of the issue? This could be a problem with the package itself.

I did actually find that the tweak left some files after searching in filza so it is not zebra that has the problem. Thanks for trying to help. I forgot to record it.
