### ISSUE TITLE
Retro Icon on iPad

### ISSUE THREAD

**Issue by hnlkaitan** [wstyres/Zebra#1437]
**Bug**
The retro-style icon can’t be set as the app icon on iPads. Looking in `/Applications/Zebra.app` shows the APUM has no APUM~ipad@[2/3]x.png files, and attempting to put my own there do nothing, and this icon is the only one to do nothing and exit the icon picker

**To Reproduce**

1. On an iPad, open Zebra
2. Click on Settings gear
3. Click on App Icon
4. Click on Retro

**Expected behavior**
Normally, a pop-up should say “You have changed the icon for “Zebra”.” and exit back to the main Settings page - with the Retro icon there is no pop-up and it goes back to the main Settings page without changing the icon

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.10
 - Device Type [e.g. iPhone or iPad]: iPad mini 5
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by wstyres** [comment]
Should be fixed as of 8ded1993577ae4893f5cdf620740c6c49f6767db.
