### ISSUE TITLE
Sources all showing empty and package page blank

### ISSUE THREAD

**Issue by tuskiie** [wstyres/Zebra#1440]
**Describe the bug**
All of my sources are showing as having 0 packages installed and my packages page is blank.
I have rejailbroke, reinstalled Zebra, downgraded multiple times, cleared cache, and of course refreshed sources.

**Screenshots**
https://imgur.com/a/Uo8xQgp

**Device Information**

 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta1b
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

Apologies if this is the wrong way to report an issue.

**Comment by DaniWinter** [comment]
Still having this issue, zebra is unusable for me right now.

**Comment by absidue** [comment]
> Still having this issue, zebra is unusable for me right now. 

@DaniWinter Try the reset sources cache option in the reset section of Zebra's settings

**Comment by DaniWinter** [comment]
> > Still having this issue, zebra is unusable for me right now.
> 
> @DaniWinter Try the reset sources cache option in the reset section of Zebra's settings

That fixes it, but when I refresh sources everything is empty again.

**Comment by absidue** [comment]
Which version of Zebra are you using?

**Comment by DaniWinter** [comment]
> Which version of Zebra are you using?

1.1.10

**Comment by absidue** [comment]
> > Which version of Zebra are you using?
> 
> 
> 
> 1.1.10

Try increasing the sources timeout setting.

**Comment by DaniWinter** [comment]
> > > Which version of Zebra are you using?
> > 
> > 
> > 1.1.10
> 
> Try increasing the sources timeout setting.

I already have it set to max. (60 seconds)

**Comment by absidue** [comment]
Are you getting any errors after thee refresh?
