### ISSUE TITLE
Can no longer disable. 

### ISSUE THREAD

**Issue by dmnchild** [wstyres/Zebra#1441]
**Describe the bug**
I can no longer disable the plugin from settings. It’s always displaying regardless of enable toggle. 
**To Reproduce**
Turn Enable setting to on or off, it’s always on lock screen. 
**Expected behavior**
After toggling enable you off, it should no longer be visible. 
**Screenshots**

**Device Information (please complete the following information):**
***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: iPhone XS Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Is this a bug report for Zebra? I'm not sure which toggle or lock screen feature you're talking about.

**Comment by dmnchild** [comment]
My apologies, I apparently didn’t pay attention and clicked the wrong support. It was for Kai not Zebra.
