### ISSUE TITLE
Crash when quickly cancelling package download that requires authorization

### ISSUE THREAD

**Issue by Aransh** [wstyres/Zebra#1442]
**Describe the bug**
Was able to reproduce, I have a single update, cancelling the download after it starts crashes the app.

**To Reproduce**
(On packages tab)
Update all (2x)
OK
Cancel
*Crash*

**Expected behavior**
No crashing

**Screenshots**
[https://streamable.com/0ald1i](https://streamable.com/0ald1i)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2-beta1b
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

[https://pastebin.com/mnkrfr0A](https://pastebin.com/mnkrfr0A)

**Additional context**

**Comment by PoomSmart** [comment]
Fixed as of b934d4babc88bfa02ceba8335946b6fdb4bd4ff8
