### ISSUE TITLE
BatchOMatic Wont Work

### ISSUE THREAD

**Issue by TuranBey** [wstyres/Zebra#1452]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by TuranBey** [comment]
iOS Ver 13.5 
JB with Unc0ver 5.2.0
iPhone 11,8 128 GB
Zebra Lastest Stable build

**Comment by absidue** [comment]
Batchomatic hasn't received an update those versions. An update is in the works on their side.

**Comment by eve0415** [comment]
Please ask the developer of Batchomatic.
