### ISSUE TITLE
Local Xcode installation plug-in, cannot be displayed in the list of software

### ISSUE THREAD

**Issue by FantasticSkyBaby** [wstyres/Zebra#1454]
**Describe the bug**
Locally installed plug-ins do not show up in installed packages in a timely manner, require a global refresh, and are too time-consuming to source

**To Reproduce**
Local Xcode installation plug-in, cannot be displayed in the list of software

**Expected behavior**
In a timely manner according to

**Screenshots**
**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version 13.5
 - Zebra Version latest
 - Device Type  iPhone
 - Jailbreak Type unc0ver

**Crash Log or System Log**
**Additional context**

**Comment by wstyres** [comment]
Could you provide more details? What "Xcode" package are you referring to?

**Comment by FantasticSkyBaby** [comment]
Installing your own plug-in via Xcode-OpenDev doesn't appear in the installed list in time, and it can be seen in Cydia as normal

**Comment by MaivKhanhPr0** [comment]
[]()

**Comment by wstyres** [comment]
Is this iOSOpenDev? Could you upload a copy of the file `/var/lib/dpkg/status` on your phone to https://ghostbin.com and send a link? Also mention what package you installed from iOSOpenDev.

**Comment by wstyres** [comment]
Just double checking, could you look at my comment above and send the information I requested? It would help us in solving the issue.

**Comment by FantasticSkyBaby** [comment]
Use MonkeyDev
Xcode-->MonkeyDev choose any Tweak Project-->Connect the phone-->config User-Defined-->run

After logging out, the plug-in will be installed on the phone. When zebra is opened, there is no newly installed plug-in in the local plug-in list

**Comment by wstyres** [comment]
Could you upload a copy of the file /var/lib/dpkg/status on your phone to https://ghostbin.com and send a link? Also mention what package you installed. Screenshots from Cydia showing this newly installed package would also be helpful.

**Comment by wstyres** [comment]
Just double checking, could you look at my comment above and send the information I requested? It would help us in solving the issue.

**Comment by FantasticSkyBaby** [comment]
Once again, I checked that after I manually installed the DEB plugin, Zebra turned on a default refresh and the plugin was displayed in the list after the refresh.

The problem should be the uncertainty of my local software source network, so it takes a long time to see the plug-in installed locally after all the software sources have been refreshed, which was mistaken for an error in display

**Comment by wstyres** [comment]
Once again, please provide a list of installed packages from /var/lib/dpkg/status and upload them for us to analyze. We cannot debug the issue without this list and the name of the package that you attempted to install.
