### ISSUE TITLE
Repos Not Updating

### ISSUE THREAD

**Issue by tdadvocate** [wstyres/Zebra#1456]
**Describe the bug**
Some repos not updating so packages being shown are cached older versions that can no longer be installed and will fail at the installation step because it isn’t the latest version or the package has been totally removed. 

**To Reproduce**
I’m honestly not sure how to reproduce this. I have my personal repo on my phone in Zebra and a package that I updated a while back to 1.4.2 is still showing the latest package as 1.4.1 which I have removed from the repo so the install will fail every time. This is even after manually refreshing the sources list. Cydia does not have this issue and installed the latest 1.4.2 version. 

**Expected behavior**
Sources should be forced to recache whenever the user manually refreshes the sources list to make sure the latest packages files for a repo are being used. 

**Screenshots**

![image](https://user-images.githubusercontent.com/15253422/86866366-d0e11880-c09e-11ea-86cc-e98a4b3c01d6.png)
![image](https://user-images.githubusercontent.com/15253422/86866372-d4749f80-c09e-11ea-9720-143fce942c63.png)
![image](https://user-images.githubusercontent.com/15253422/86866376-d8082680-c09e-11ea-84fd-b6f731f3536b.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version: 13.5.1
 - Zebra Version: 1.2~beta1b
 - Device Type: iPhone X
 - Jailbreak Type: checkra1n 0.10.2

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Could you try "Clear Sources Cache" option in Settings > Reset ?

**Comment by tdadvocate** [comment]
> Could you try "Clear Sources Cache" option in Settings > Reset ?

This appears to have worked and allowed me to see the latest packages again. Didn't know this was an option. Thank you!
