### ISSUE TITLE
In cydown, you cannot display whether the plug-in has been installed.

### ISSUE THREAD

**Issue by wybs484** [wstyres/Zebra#1462]
**Describe the bug**
.In cydown, you cannot display whether the plug-in has been installed.

**To Reproduce**
Steps to reproduce the behavior:If you open cydown, you can see that I have downloaded the plug-in package, but it does not show which plug-ins have been installed and which have not been installed

**Expected behavior**

We hope to clearly show which plug-in packages are installed and which are not

**Screenshots**
![DF5C979F-D9B5-4BA2-A6CC-5FE77F0E0938](https://user-images.githubusercontent.com/68453281/87843281-d41da500-c8e5-11ea-9caa-601c3227f139.png)
![6B2B73DE-446F-410C-9A6A-0B851A586437](https://user-images.githubusercontent.com/68453281/87843288-da138600-c8e5-11ea-918e-6427908a514d.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.5>13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.1.1.>
 - Device Type [e.g. iPhone or iPad]: <iphone11promax>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <unc0ver>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment]
CyDown is an independent project. Please report any bugs there as we won't and can't change anything on Zebra's end to fix CyDown.
