### ISSUE TITLE
Doesn't show/recognize new lines in markdown description

### ISSUE THREAD

**Issue by alolastmoment** [wstyres/Zebra#1469]
**Describe the bug**
I am using Silica to create my repo depictions. Thus, I am using markdown. Zebra does not show new lines in the markdown between the paragraphs. Instead, all text is right after the other as if there is no space/breaks in the markdown file.

**To Reproduce**
1- add repo https://alo.works
2- view any package description (for example, Lineal CC package)

**Expected behavior**
Zebra shows the new lines between paragraphs in the description.

**Screenshots**
Imgur album showing issue: https://imgur.com/a/FbclPav. I have also included a comparison shot with a different package manager to show how the description should be shown.

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta1b
 - Device Type [e.g. iPhone or iPad]: iPhone 11 Pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by absidue** [comment]
As Zebra doesn't support native depictions. You are seeing the web version of your depiction in Zebra. What you are seeing is a feature that web browsers have, that replaces multiple newlines with a single one (it's the same for other whitespace characters). You can see this happing in other web browsers as well if you open that [web depiction](https://alo.works/depiction/web/io.github.worksbybbs.linealcc.html).

The best way to solve this issue would be to edit the CSS of your repo and change the spacing between the text paragraphs. If you have no idea how to do that, there are enough resources on the internet to help you out, although you should only need to edit the values in the existing CSS.

Please close this issue, as this isn't an issue with Zebra.
