### ISSUE TITLE
No tweaks are working with Checkra1n jailbreak iOS 13.5.1

### ISSUE THREAD

**Issue by trippie469** [wstyres/Zebra#1470]
**Describe the bug**
A clear and concise description of what the bug is. Updated iOS to 13.5.1 with checkra1n and none of my tweaks are working

**To Reproduce**
Update to iOS 13.5.1
**Expected behavior**
Download Checkra1n and have my tweaks working
**Screenshots**
![8E927D86-C3ED-4DB3-A736-324276CAD5DB](https://user-images.githubusercontent.com/68718012/88352951-590f2100-cd21-11ea-9a3a-a5cd7cd9959b.jpeg)
![57FCA42B-95B9-4D4F-93AE-B655213C4446](https://user-images.githubusercontent.com/68718012/88352952-59a7b780-cd21-11ea-80ee-c98953c7d343.png)
![358B48E2-501D-4215-A250-94E4E932B55B](https://user-images.githubusercontent.com/68718012/88352954-5a404e00-cd21-11ea-837a-59955f3dae17.jpeg)
![217C4665-161E-43E1-9BA7-C78A37EB721D](https://user-images.githubusercontent.com/68718012/88352981-717f3b80-cd21-11ea-89d6-a40a1414e1bc.png)

Before and after

**Device Information (please complete the following information):*****Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <INSERT-HERE>13.5.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <INSERT-HERE>1.1.10
 - Device Type [e.g. iPhone or iPad]: <INSERT-HERE>iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <INSERT-HERE>checkra1n 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by trippie469** [comment]
![232B1892-C196-4138-9EB8-F9E34BCA0225](https://user-images.githubusercontent.com/68718012/88353298-8f00d500-cd22-11ea-89d5-fd5820a9ae30.png)
![Uploading FE7AD096-C647-4D31-B977-9BF55263DB80.png…]()

**Comment by trippie469** [comment]
![0834AC85-30C0-4DB6-87BE-514441C53AB3](https://user-images.githubusercontent.com/68718012/88353305-94f6b600-cd22-11ea-81e4-88c5370de95d.png)
![118220B2-C2BA-4770-A6A1-13DD1013C44E](https://user-images.githubusercontent.com/68718012/88353306-958f4c80-cd22-11ea-9b58-314715b6492d.png)

**Comment by absidue** [comment]
This isn't a Zebra issue. Please report issues with tweaks to the developers directly. Please close this issue.

**Comment by Introspelliam** [comment]
great!
