### ISSUE TITLE
Can anyone help with this. 

### ISSUE THREAD

**Issue by Wolfy35** [wstyres/Zebra#1471]
![04D7AAA5-0F4C-40DD-BD8D-9AD450E87933](https://user-images.githubusercontent.com/67271684/88459597-81685e00-ce8e-11ea-9d1c-2af2e0a9b68c.jpeg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [13.5]
 - Zebra Version [1.1.10]
 - Device Type [iphone Xs max
- Jailbreak [unvOver]

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
This is not an error. It is safe to ignore.
