### ISSUE TITLE
Tweak automatically install from list

### ISSUE THREAD

**Issue by Guanran928** [wstyres/Zebra#1474]
I wish zebra have a mode allow you when you give zebra a tweak list it’s will install tweaks automatically

**Comment by Guanran928** [comment]
I wish zebra have a mode allow you when you give zebra a tweak list it’s will install tweaks automatically

**Comment by wstyres** [comment]
We don't plan to implement this feature at the moment, it could still possibly be implemented in the future but for now other tweaks like Batchomatic work to implement this feature.
