### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by Tomi292** [wstyres/Zebra#1475]
**Describe the bug**
Dependency error when trying to install individual packages.

**To Reproduce**
Try to install Core Utilities 

**Expected behavior**
Successful installation without errors.

**Screenshots**
![BC5F812B-F262-4EB6-AE85-0B0C1F0159A6](https://user-images.githubusercontent.com/51470532/89024184-fcb19000-d324-11ea-8396-c5e6c304ff13.png)
![4410921C-3AA1-4FF0-8764-8BA769E06872](https://user-images.githubusercontent.com/51470532/89024199-00451700-d325-11ea-802a-2aab22992b06.png)
![714946F8-D2EA-4A13-BFE0-5298CF803713](https://user-images.githubusercontent.com/51470532/89024203-01764400-d325-11ea-93b3-4acc458c73a0.png)
![DF1FC9C4-3779-4621-A952-61F7CC6026A7](https://user-images.githubusercontent.com/51470532/89024204-01764400-d325-11ea-9030-95e119fc7492.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version <13.6>
 - Zebra Version <1.1.10>
 - Device Type <iPhone>
 - Jailbreak Type <Odysseyra1n>

**Crash Log or System Log**
I don’t have any logs. See Screenshots. 

**Additional context**

**Comment by wstyres** [comment]
Could to tell us which repo the packages come from?

**Comment by Tomi292** [comment]
https://apt.procurs.us/

**Comment by wstyres** [comment]
And are you trying to install both or is one a dependency of the other? Which one are you trying to install?

**Comment by Tomi292** [comment]
The “gettext” package could be updated without any problems.  The other package made trouble.

**Comment by Tomi292** [comment]
Zebra 1.1.12 solves the problem. Thanks.
