### ISSUE TITLE
Search by Repo/ Search within Repo

### ISSUE THREAD

**Issue by R0GUEEE** [wstyres/Zebra#1476]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
 
It’s pretty well known that some repositories are “dead”, without pointing any fingers. However, they do still make for relatively “handy to have” archives of past tweaks, and occasionally new ones as well. The problem though, is these massive entities tend to completely overshadow all the new and up to date repositories that hold relevant tweaks any time a search is performed. Of course a simple bypass to the problem is via the repository screen where you can delve into each individual repo and their subcategories, but, there becomes the problem of having to them manually search through each listing to find something relevant to your search.

**Describe the solution you'd like**

A simple filter by repo option in the search screen would alleviate most, if not all, of the listed concern. By default, all repos would be turned on for the search, and at that point could be further included/excluded from the search listings. A simple filter button at the end of the search pane, or included in the “name/description/author” field. Also to go alongside this for the latter part of the concern, would be a search bar in the repositories tab while browsing through individual repos and/or categories. 

**Describe alternatives you've considered**

I don’t know that there are any valid alternatives other than manually searching and filtering yourself. One “solution” could be to completely remove said boggy repository, but of course that leaves the issue of needing to do so every time you need to filter a search. 

**Additional context**

The “major” repositories are pretty evident in packix, dynastic, chariz, twickd, etc. Those would make sense to be the first place to look for any undiscovered “up and coming” tweaks and/or themes. Imagine searching for “modern” in the default search. You couldn’t because you wouldn’t. You would need to be explicit when specifying your search, such as “modern blue theme”, only to then still need to search through thousands being listed. It would be a much simpler and effortless task to simply filter your search down to only packix, or even in the packix themes category and not worry about searching yourself.

**Comment by wstyres** [comment]
We're going to be improving the package/repository search features a lot in 1.2 and these issues are tracked elsewhere (https://github.com/wstyres/Zebra/issues/923, https://github.com/wstyres/Zebra/issues/630, https://github.com/wstyres/Zebra/issues/192)
