### ISSUE TITLE
Disable Inserted Tables

### ISSUE THREAD

**Issue by MartinsZar** [wstyres/Zebra#1481]
**Is your feature request related to a problem? Please describe.**
A switch to disable inserted tables would be nice. I like the edge-to-edge tables of stock iOS and would like to see them again in Zebra.

**Describe the solution you'd like**
A switch in the settings of Zebra (possibly in the Display tab) that disables inserted tables.

**Describe alternatives you've considered**
Maybe detecting if the tweak shuffle has inserted tables enabled, so it would sync up with the settings app. This is very fancy and not really needed, but would still be cool.

**Comment by aabosh** [comment]
Hi there!

Thanks for the request.

Unfortunately, using the inset grouped table is a decision we made for 1.2+. Adding a setting to toggle it is not worth the technical work.

As we redesign more and more of the app, the use of the indented style will make more sense. Plus, it may grow on you!
