### ISSUE TITLE
mixed UserAgent for iPhone/iPod

### ISSUE THREAD

**Issue by blanxd** [wstyres/Zebra#1483]
**Describe the bug**
As the user agent contains the string "iPhone/iPod;" (in the end there), some repos seem to look for the string "iPod" and if they try to show the user's device type in their depictions, they report the user having an iPod if it's really an iPhone.

**To Reproduce**
Look at [[AppSync Unified]] depiction from https://cydia.akemi.ai/ repo, on an iPhone.

**Expected behavior**
Distinguish which device it is and report only that particular string in the user agent.

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5 (also 13.6.1, 13.4.1, 12.4)
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.12 (also 1.2~beta2a)
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver, Checkra1n, Odysseyra1n, Chimera

EDIT: added some more versions/iOSes/jailbreaks where it behaves the same.
EDIT2: added some more versions/iOSes/jailbreaks where it behaves the same.

**Comment by wstyres** [comment]
Switched the code to just return Apple's specification for "model" in 0260d4848b2d17abb0080f974e54de45c50daa8d. Documentation says that this should return "iPod touch" when in use on iPods but I can't test it personally. Let me know.

**Comment by blanxd** [comment]
Perfect! I don't have any iPods either to test this, but "_[they say](https://stackoverflow.com/questions/14411075/uidevice-currentdevice-model-possible-values)_" this should be exactly the correct thing for this situation. According to what the _they_ have found out, might even use (unless the "Simulator" part matters) something like:
```
(NSString *)[[[[UIDevice currentDevice] model] componentsSeparatedByString:@" "] firstObject]
```
