### ISSUE TITLE
Keeps freezing on downloding packages

### ISSUE THREAD

**Issue by RBx9** [wstyres/Zebra#1484]
![914756EA-8B01-4B07-A89E-8573E34872D8](https://user-images.githubusercontent.com/69745248/90327638-55785e00-df9e-11ea-868d-4e74215e7ab9.png)

Keeps freezing on downloding packages

**Comment by eve0415** [comment]
Remove `CyDown` please

**Comment by RBx9** [comment]
> Remove `CyDown` please

thanks it worked
