### ISSUE TITLE
Stuck in downloading process 

### ISSUE THREAD

**Issue by ahmedmedo07** [wstyres/Zebra#1485]
![D4026D6E-1FB0-43C9-A4A1-F8BC4A2FB28D](https://user-images.githubusercontent.com/69746452/90328841-fe738880-df9f-11ea-982e-da3a192f23a7.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.3.1>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.2-beta2a>
 - Device Type [e.g. iPhone or iPad]: <6splus>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: < checkra1n >

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
Stuck in downloading process of any types updates or install new tweaks or tools

**Comment by eve0415** [comment]
Remove `CyDown` please
