### ISSUE TITLE
[BUG] Package upgrade badge won't clear

### ISSUE THREAD

**Issue by SeMoOo** [wstyres/Zebra#149]
**Describe the bug**
the upgrade package badge won't clear after updating.

**To Reproduce**
- attempt to upgrade a package.

**Expected behavior**
notification badge won't clear.

**Screenshots**
none.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta13
 - Device Type [e.g. iPhone or iPad]: iPhone 11,6

**Crash Log or System Log**
None.

**Additional context**
To solve the issue, you have to choose "Drop Tables and Refresh" Then, refresh sources, close the app from the app switcher, refresh sources again.

**Comment by PoomSmart** [comment]
[This commit](https://github.com/wstyres/Zebra/commit/d9e6e60bd52f764fdce74cd1f4a5d68e2598cf9b) apparently fixes this exact bug, scheduled for the next beta.

**Comment by Amplespencer** [comment]
this should be closed as b14 has been released
