### ISSUE TITLE
Add source URL Scheme is broken

### ISSUE THREAD

**Issue by mwoolweaver** [wstyres/Zebra#1497]
**Describe the bug**

Add source URL scheme is broken

**To Reproduce**

1. visit https://miro92.com/repo/

2. tap "Add to Zebra" button

3. Zebra only opens the sources tab with no prompt to add source

**Expected behavior**

step 3 should be 

3. Zebra opens the sources tab and prompts to add source

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.6
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta2b (edit: This bug is ***NOT*** present in 1.1.12)
 - Device Type [e.g. iPhone or iPad]: iPhone10,2
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by mwoolweaver** [comment]
still present in 1.2~beta3a

**Comment by wstyres** [comment]
Has not been fixed yet, planning on a fix for beta 4

**Comment by wstyres** [comment]
Should be fixed as of 4dc060d4 for the next beta.

**Comment by mwoolweaver** [comment]
Confirmed fixed in beta4a
