### ISSUE TITLE
BigBoss

### ISSUE THREAD

**Issue by Lettucecake** [wstyres/Zebra#15]
I cannot add the BigBoss repo. I add this repo, or something similar:
http://apt.thebigboss.org/repofiles/cydia/
I keep getting error 404 or invalid URL.

**Comment by wstyres** [comment]
You cannot add BigBoss, Bingner, Modmyi, or any other "default" repos by yourself, they are available by going to the Zebra homepage and clicking "Community Sources" and then choosing which one you'd like to add.
