### ISSUE TITLE
Missing swipe action icon for copying sources

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#1506]
**Describe the bug**

When long pressing a repo the copy button no longer appears.

**To Reproduce**

Long press

**Expected behavior**

I expect the copy button to show like this:

![Uploading 42508FFC-1F8D-4EE0-B0CD-8112A2B2D259.png…]()

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2 beta 2b
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
Resolved in beta3
