### ISSUE TITLE
No close button after package install is completed

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#1509]
**Describe the bug**

I installed some packages and didn't want to respring afterwards. But there was no close button in the top right.

**To Reproduce**

Not sure

**Expected behavior**

I expected a close button

**Screenshots**

![9748AA22-07AC-49E3-AD2C-DDA93AA4D3E9](https://user-images.githubusercontent.com/51668635/91078163-86156300-e642-11ea-9b85-5a9cd3c7f8fd.jpeg)
![B0890050-3534-4F21-83EC-00A5C798022E](https://user-images.githubusercontent.com/51668635/91078178-8ada1700-e642-11ea-8c34-e2aa3352f464.jpeg)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2 beta 2b
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

**Comment by wstyres** [comment]
This is not a bug, you've upgraded Zebra and therefore Zebra must be closed in order to continue. Since you also installed/upgraded a tweak in the same step "Restart SpringBoard" is the option displayed.

**Comment by worldlydev** [comment]
> This is not a bug, you've upgraded Zebra and therefore Zebra must be closed in order to continue. Since you also installed/upgraded a tweak in the same step "Restart SpringBoard" is the option displayed.

Oops. Didn't even notice. Just pressed update all

**Comment by worldlydev** [comment]
Perhaps a close button could be added to the top right corner that closes Zebra if Zebra has been updated? So that a respring isn't the only option from within Zebra
