### ISSUE TITLE
Custom groups for sources

### ISSUE THREAD

**Issue by moorer2k** [wstyres/Zebra#1511]
Add the ability to create custom groups for sources you enter.

For example, if a person has a few repos for xenhtml widgets, maybe they’d like to remove them in the future when they have no use for xenhtml anymore. If a repo has a lot of other categories, its sometimes hard to remember what that source was for exactly. This would allow users to keep their sources better organized and they could simply remove the sources under this group, either one by one, or possibly by the group name thus removing all sources below.

**Comment by wstyres** [comment]
At the moment we don't see that much of a priority for this feature request, we're going to add new features in 1.2 for source management which might solve your issue.

If you'd like a temporary solution, I'd suggest looking into the tweak "Zenumbra" which will provide you with an easy way to determine which repos don't have any packages installed from them.
