### ISSUE TITLE
Transfer option in settings only shows one (the first prioritised) package manager

### ISSUE THREAD

**Issue by whiteblacksmiths** [wstyres/Zebra#1516]
**Describe the bug**
when tapping on “transfer sources“ option, only Cydia appeared but not Sileo.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
iPX iOS13.5, Odyssey Jailbreak

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2 beta 3b
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Odyssey

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Do you have the Sileo beta installed by chance?

**Comment by whiteblacksmiths** [comment]
yes! is that what‘s causing the issue? let me uninstall it. thanks!

**Comment by wstyres** [comment]
Well no, that isn't what is causing the issue. The Sileo beta might have a different app name than normal Sileo (which didn't occur to me) if you could tell me the name of the Sileo beta folder in /Applications I could add it to the list.

**Comment by whiteblacksmiths** [comment]
sure! it‘s Sileo-Beta.app. however, after uninstalling sileo beta and respringing (i still have the original sileo installed), zebra still failed to identify sileo as an option for transfer. not sure if that‘s an issue. thanks anyway!

**Comment by eve0415** [comment]
Do you have Cydia or Installer on your iPhone?

**Comment by whiteblacksmiths** [comment]
yes i do. is that what‘s causing the issue? the transfer option from cydia does appear but not for sileo

**Comment by eve0415** [comment]
Yep. I just checked, installed installer5 & sileo & sileo(beta)
Zebra only shows the first one and there is a priority.
Cydia > Installer5 > Sileo

If you have installed sileo only, then Zebra will show sileo

**Comment by eve0415** [comment]
So the title of the issue should be changed

**Comment by whiteblacksmiths** [comment]
> So the title of the issue should be changed

just changed, do you think this is more apt?

**Comment by eve0415** [comment]
nope. It’s just a Zebra’s bug

**Comment by wstyres** [comment]
Should be fixed as of 51039a2410b81a62fb6434957739da3eafbd18d4.
