### ISSUE TITLE
Pasting a link into the add a source pop up crashes the app.

### ISSUE THREAD

**Issue by Garydunlop00** [wstyres/Zebra#1519]
**Describe the bug**
When you tap the + button to add a source if you paste a url in the app crashes

**To Reproduce**
Step 1: Open Zebra
Step 2: Go to the Source tab
Step 3: Tap on the + button
Step 4: Tap the search bar to bring up the copy and paste menu and tap paste

**Expected behavior**
Step 4 should be - Tap the search bar to bring up the copy and paste menu and tap paste and then tap add.

**Screenshots**

**Device Information (please complete the following information):** iPhone X

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta3b
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: OdysseyRa1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment]
To help us reproduce the issue, could you please provide the URI you used and a crashlog if you have one?

**Comment by Garydunlop00** [comment]
The url I used was - http://cydia.kemis.info/ but it wasn't the url that crashed the app as soon as you hit the paste button the app crashed.

Crash log - https://pastebin.com/n6qqGKnf

**Comment by wstyres** [comment]
Not able to reproduce a crash with this URL, does the crash happen every time?

**Comment by Garydunlop00** [comment]
Okay strangely the bug has stopped but I haven't changed anything on my device.

Weird, Sorry for the hassle.
