### ISSUE TITLE
Most downloaded tweaks of the week.

### ISSUE THREAD

**Issue by Garydunlop00** [wstyres/Zebra#1520]
**Is your feature request related to a problem? Please describe.**
No problem just a feature request - Would it be possible to add a "Most downloaded tweaks of the week" section in zebra? 

**Describe the solution you'd like**
It could be placed as a section in the changes tab.

**Describe alternatives you've considered**

**Additional context**

**Comment by wstyres** [comment]
Currently we are unable to do this as it would require some tracking on what a user downloads and relaying that information back to a server which we don't have the mass infrastructure for. We can revisit it in the future but it is not currently on our roadmap.

**Comment by Garydunlop00** [comment]
Okay makes sense.
