### ISSUE TITLE
Tweaks’ screenshots are too big to be viewed

### ISSUE THREAD

**Issue by pompopopopom** [wstyres/Zebra#1521]
**Describe the bug**
On tweaks’ description pages screenshots are too big to be viewed comfortably.

**To Reproduce**
tap on a tweak to open its page.

**Expected behavior**
Screenshots should load and display reasonably sized on my screen. 

**Screenshots**
None

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.12
 - Device Type [e.g. iPhone or iPad]: iPhone 12,5 (11 Pro Max)
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
No crash, no log

**Additional context**

**Comment by wstyres** [comment]
Could you provide an example of a package this happens on? If it is a web depiction there isn't anything we can do about it it would fall more on the repository to fix this issue.

**Comment by pompopopopom** [comment]
Sure! 
Took time to check all installed repos. 

Only Chariz  Repo displays big screenshots whenever there’s any. 

So basically I have to ask them to try correcting this? 

Thank you for your fast feedback! Appreciate it. 
Best

**Comment by wstyres** [comment]
Yep I think this would be an issue on Chariz's end, I would suggest contacting them with some screenshots of the problem and I'm sure they'd be glad to help you out!

**Comment by pompopopopom** [comment]
Thanks a lot! I got on their discord channel. Have a nice one!
