### ISSUE TITLE
Add option to enable cydia:// for people that don't use Cydia or Sileo

### ISSUE THREAD

**Issue by ArturGamez** [wstyres/Zebra#1531]
Some of us don't use Cydia or Sileo because Zebra is a lot better than both of them. The issue is that some websites don't support the link for zbra:// yet, which makes it annoying for people that use Zebra to copy the link and paste it in the app. Maybe, if there would be a toggle in the Zebra settings to enable cydia:// for people that don't use Cydia or Sileo to make it easier and faster to add sources.

**Comment by absidue** [comment]
This was removed and won't be returning. Please see #1259.

**Comment by ArturGamez** [comment]
> This was removed and won't be returning. Please see #1259.

That's why I suggested to put it as a toggle in the settings. People that want to use it, would. People that don't, won't. For me, it's a little bit hectic to copy and paste sources every time I find a website that doesn't have a button for Zebra.

**Comment by absidue** [comment]
As mentioned in the other thread a tweak is a much better solution. EvilScheme on the Dynastic repo has a preset to redirect Cydia source URLs to Zebra.

**Comment by wstyres** [comment]
Tweaks like EvilScheme exist to be a middle man in this situation, as I explained in #1259 this feature isn't very user friendly and unless a better way is found to be able to do this or Cydia stops working entirely it will not be re-implemented.
