### ISSUE TITLE
Zebra marking Bingner repo as incompatible with unc0ver

### ISSUE THREAD

**Issue by rctfan929** [wstyres/Zebra#1536]
Zerbra is marking the Bingner/Elucubratus repo as incompatible with the unc0ver jailbreak.

1. Install unc0ver
2. Install Zebra 
3. Refresh sources

I expect this repo to not be marked as incompatible with unc0ver as it is a default repo for it.

[Screenshot 1](http://www.imagebam.com/image/371c521353727952) 
[Screenshot 2](http://www.imagebam.com/image/f8ddf61353727956) 

Device Information:
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta4a
 - Device Type [e.g. iPhone or iPad]: iPhone 6s
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 5.3.1

**Comment by kyondev** [comment]
Same on checkra1n for iPhone 6 on iOS 12.4.8

Also does not flag the Procursus repo

**Comment by wstyres** [comment]
Should have been fixed in d9e7365250e858c53909db071beb82a100afce8a.

**Comment by kyondev** [comment]
Quick follow up question:
Does this also prevent the user from removing the jailbreak specific repo and will it be added by default?

**Comment by wstyres** [comment]
Not currently, no
