### ISSUE TITLE
Pressing the warning message in the source tab opens the first source page

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#1539]
**Describe the bug**
When there were some errors fetching sources, the message shows up.
When tapping this message (padding) it will open the first source of source tab.

**To Reproduce**
Have some errors when fetching sources

**Expected behavior**
Instead of opening the source page, show us the full sources that has an errors.

**Device Information (please complete the following information):**
 - iOS Version: 13.5
 - Zebra Version: 1.2~beta4a
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
The feature has not yet been implemented so I'm going to close the bug report
