### ISSUE TITLE
Zebra sometimes ignores packge replacements and instead installs deprecated/unneeded tweaks

### ISSUE THREAD

**Issue by Amplespencer** [wstyres/Zebra#154]
**Describe the bug**
Zebra really wants to install LibColorPicker when LibColorPicker-Nepeta deprecates it and Snowboard is marked as a replacement for Anemone but Anemone will still get installed.
**To Reproduce**
Install libcolorpicker-nepeta

try installing bettersettings

it will try installing libcolorpicker and give a conflict error
**Expected behavior**
Allow user to manually fix conflicts (by swiping to remove like it let’s you when there isn’t conflicts) or fix the way zebra handles candidates
**Screenshots**
Screenshots wouldn’t give much more information then described
**Device Information (please complete the following information):**
 - iOS Version 12.1.1 
 - Zebra Version B13
 - Device Type iPhone xr

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
This similar kind of dependencies resolution bugs have been fixed and scheduled to beta 14. For letting users manually deal with conflicts, they are kind of permitted to swipe and delete some packages in order to resolve conflicts unless Zebra assumes you cannot do it or fails to handle yet other dependency cases.

**Comment by Amplespencer** [comment]
yeah it wasn’t letting me swipe, every day all my issues get cut down with
zebra, unlike sileo which still has that bug where the queue dissapears
with web depictions. Thank you PoomSmart, MidnightChips, and xtm3x for a
good replacement for cydia.
