### ISSUE TITLE
Proper Darkmode

### ISSUE THREAD

**Issue by MrGcGamer** [wstyres/Zebra#155]
I made a nice looking dark mode... could you implement it into the real version?
[IMG_1558.MP4.zip](https://github.com/wstyres/Zebra/files/3257554/IMG_1558.MP4.zip)

**Comment by midnightchip** [comment]
I have been working on a darkmode on the darkmode branch, if you'd like to we would love pull requests to make it better

**Comment by MrGcGamer** [comment]
I didn't really got what you wanted to tell me... so what did you say?

**Comment by mac-user669** [comment]
@MrGcGamer Hijacking this, what theme is that?

**Comment by MrGcGamer** [comment]
?? This a picture of my fork

**Comment by wstyres** [comment]
Duplicate of #66. @midnightchip is working on implementing this now on the darkmode branch
