### ISSUE TITLE
Clear Queue

### ISSUE THREAD

**Issue by ikeacat** [wstyres/Zebra#156]
I find packages that I don't think I need for anything, so I will check if anything depends on it. I have to exit and reopen the app to remove it from the queue.

I would love for a clear queue or button / text thing you can tap to open the red dots on the side to remove the tweak(s) so if you have a queue saved up, you dont have to start over.

**Comment by Amplespencer** [comment]
already a feature, simply swipe left to remove things from the queue. as long as there isn’t a critical conflict it will let you.

**Comment by wstyres** [comment]
I'm going to keep this open just because some of the conflict / depends systems need to be reworked so that you can actually remove them. Most packages can be swiped to delete though.

**Comment by PoomSmart** [comment]
@wstyres Is it also okay to give the users the option to *clear all* packages from Queue? That way, the users do not need to figure out the dependencies and remove in the order by themselves.

**Comment by wstyres** [comment]
In the current system if there are any dependency errors the queue will just clear everything by itself when you close the window. When we implement removing these issues then yes I'd say that a "Clear All" option would be appropriate.
