### ISSUE TITLE
Auto uninstall

### ISSUE THREAD

**Issue by EagleStrike0** [wstyres/Zebra#158]
**Describe the bug**
Whenever you install Zebra it automatically tries to uninstall and adds it to the queue.

**To Reproduce**
Step 1. Install Zebra 

**Expected behavior**
To not be in the the queue

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [ iOS 12.0]: 
 - Zebra Version [1.0\~beta13]: 
 - Device Type [iPhone]: 

**Crash Log or System Log**
Non existent

**Additional context**

**Comment by wstyres** [comment]
I can't reproduce this, could you provide a video of what you're experiencing?

**Comment by Amplespencer** [comment]
you have a tweak marked as conflicting with zebra. How? no clue. If you can’t provide any more info then it isn’t fixable.
