### ISSUE TITLE
Cannot Add Repos

### ISSUE THREAD

**Issue by Rybo713** [wstyres/Zebra#16]
**Describe the bug**
Cannot add repos 
ERROR: Unable to verify repo
“sources.list” couldn’t be copied because you don’t have access to “Documents”.

**To Reproduce**
Steps to reproduce the behavior

Adding any repo

**Expected behavior**
A clear and concise description of what you expected to happen

It should add the repo

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - AUPM Version [e.g. 1.0~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
iOS 12.0.1
1.0~beta1
iPhone 6S+

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

Tried transfering the sources from Cydia but nothing happens either

**Comment by wstyres** [comment]
Not sure if you meant to close this but it is a duplicate of #10, I've identified the problem and I'll try t get a fix out soon.
