### ISSUE TITLE
Zebra reads/writes sources in 2 directories

### ISSUE THREAD

**Issue by TheRealKeto** [wstyres/Zebra#164]
**Description**
Zebra reads/writes sources into the wrong directory, causing the user to re-add sources to Zebra, which are written into 2 directories once the issue is reproduced. You can notice this directory change by tapping "Open Documents directory" after reproducing the issue. 

**How to reproduce**
Step 1: Install Zebra, then open it
Step 2: Add a few repos, then close Zebra
Step 3: Open NewTerm2/MTerminal, and run `uicache -a -r`
Step 4: Open Zebra, hit "Open Documents directory"
Step 5: Profit

*If you already have Zebra installed:*
Step 1. Uninstall Zebra
Step 1b: Delete `/var/mobile/Containers/Data/Application/<Zebra>` (if present)
Step 1c: Delete `/var/mobile/Documents/xyz.willy.Zebra`
Step 2. Follow steps 1-5 above

**Expected behavior**
As far as I know, sources for Zebra are stored in a file named `sources.list` which is located in  `/var/mobile/Documents/xyz.willy.Zebra`. Zebra reads this directory, but once clearing the cache, a copy of this directory is made in `/var/mobile/Containers/Data/Application/<Zebra>`. 

**Device Information**
 iOS Version: 12.1
 Zebra Version: Latest public beta (1.0~beta13)
 Device Type: iPhone 8

**Comment by PoomSmart** [comment]
This is kind of a problem with app sandboxing. A possible mitigation can be checking if Zebra is sandboxed, if so, allow the user to run `uicache` properly again.
