### ISSUE TITLE
Language Internationalization

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#166]
I would love it if it were possible to have Zebra supported in my main language. I would be willing to do the translating if possible. I could translate to Norwegian Bokmål (my main language) but would also be willing to translate into Norwegian Nynorsk, Swedish, and Danish.

I made a quick mockup of what Zebra's homepage would look like in Norwegian Bokmål:
![Zerba Norwegian](https://user-images.githubusercontent.com/51668635/59210158-336e9900-8bad-11e9-9b61-0212b6b7e549.png)

**Comment by wstyres** [comment]
This is definitely planned but thank you for filing an Issue for it so that we can keep track of the progress.

**Comment by nielzyy** [comment]
I would help to add German :)

**Comment by dajibaxiao** [comment]
how to translate zebra? i'm jailbreak

**Comment by dajibaxiao** [comment]
chinese zebra add repo:https://crazyc.top

**Comment by pancakeufo** [comment]
I can translate Zebra to Italian as soon as language strings get released

**Comment by wstyres** [comment]
Being worked on in #392

**Comment by worldlydev** [comment]
> Being worked on in #392

Noticed last night and totally freaked out for a second. Shame I'm about to switch to the 11 pro. I'll still translate though in the hope of a future jailbreak. + I still have a jailbroken device but it won't be my main.

**Comment by Flipp3rrr** [comment]
I will translate everything to Dutch as soon as this is possible!

**Comment by wstyres** [comment]
Localization has been merged into master as of 53b512. Anyone who would like to help translate Zebra can do so by reading the guide on the README located here https://github.com/wstyres/Zebra#translations
