### ISSUE TITLE
Cancel button while refreshing sources

### ISSUE THREAD

**Issue by nn9dev** [wstyres/Zebra#167]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A cancel button in Zebra when refreshing sources to, y'know, /Cancel/ them refreshing.

**Describe alternatives you've considered**
None within Zebra, but I have considered just sticking with Cydia for the time being, although I do like Zebra a lot

**Additional context**
Where the plus would be while refreshing, instead a cancel button. This gets especially annoying sometimes because of data usage and such or I just don't want it refreshing the sources.

**Comment by nn9dev** [comment]
@PoomSmart I'm unsure if this was implemented or not, as I don't see it active in Beta 19. Was it not yet done then or was this closed because it won't be implemented?

**Comment by PoomSmart** [comment]
You are probably talking about a way to cancel sources refreshed triggered by “pull to refresh” then. This has not yet been implemented, rather only the one in Console.

**Comment by nn9dev** [comment]
Is there a chance that a cancel button will be added on the sources page?
