### ISSUE TITLE
Issues compiling with theos/linux

### ISSUE THREAD

**Issue by Amplespencer** [wstyres/Zebra#168]
ok, I have never used theos to compile a program. in the readme it states I need to use xcode to change something but I don't have xcode since I'm on Linux. I can make a MacOS vm to do it but I just wanna know if it is something stupid that I can change without xcode.

~/Downloads/Zebra$
```
make
Makefile:2: /null.mk: No such file or directory
make: *** No rule to make target '/null.mk'.  Stop.
```

**Comment by Amplespencer** [comment]
actually I just want some of the features fixed recently in commits like the package upgrade fix so if someone compiles a deb or me I would be fine with that too

**Comment by midnightchip** [comment]
The issue with compiling on Linux is that Zebra uses Storyboards for the layout of the UI and Theos is currently unable to compile storyboard files. If and when it becomes capable of compiling storyboards we will make a makefile for Theos as the current one just runs Xcode build/archive.

**Comment by Amplespencer** [comment]
ok, can you compile a deb for me? virtualbox is refusing to work rn

**Comment by wstyres** [comment]
Unfortunately since we're using Storyboards it is not possible to compile them without a Mac.
