### ISSUE TITLE
Sources gone after update

### ISSUE THREAD

**Issue by swaggyP36000** [wstyres/Zebra#17]
I just installed the latest update for ZEBRA, but all the sources I added aren’t there anymore. Is there a way I can get them back?

**Comment by wstyres** [comment]
If you click the "Open Documents Directory" button on the homepage of Zebra, where does it take you?

**Comment by swaggyP36000** [comment]
It takes me to a folder called xyz.willy.Zebra

Anyhow, I found a fix of sorts: I just used the “transfer sources from Cydia” feature to add all my sources immediately, since I add all my sources to Cydia by habit

**Comment by wstyres** [comment]
The latest beta fixed some issues that users were having not being able to write to their sources list so I moved it and gave it different permissions, glad you were able to figure it out.[](url)
