### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Garydunlop00** [wstyres/Zebra#176]
**Describe the bug**
App crash when switching to tweaks tab while having things in queue

**To Reproduce**
Switch to tweaks tab while having things in queue

**Expected behavior**
App crash and close out

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Latest Version 
 - Device Type [e.g. iPhone or iPad]: iPhone 6s

**Crash Log or System Log**
Date: 2019-06-15 21:38:17 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSRangeException
Reason: *** -[__NSArrayM objectAtIndex:]: index 3 beyond bounds for empty array
Culprit: Unknown
Device: iPhone 6s, iOS 12.0
Call stack:
0   CoreFoundation                      0x00000001992aff10 __exceptionPreprocess
1   libobjc.A.dylib                     0x000000019847da40 objc_exception_throw
2   CoreFoundation                      0x000000019922585c _CFArgv
3   CoreFoundation                      0x0000000199195ba8 -[__NSArrayM objectAtIndex:]
4   Zebra                               0x0000000100db36cc Zebra + 30412
5   UIKitCore                           0x00000001c6056f74 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:]
6   UIKitCore                           0x00000001c60574bc -[UITableView _createPreparedCellForGlobalRow:willDisplay:]
7   UIKitCore                           0x00000001c6022bb0 -[UITableView _updateVisibleCellsNow:isRecursive:]
8   UIKitCore                           0x00000001c6021164 -[UITableView _setNeedsVisibleCellsUpdate:withFrames:]
9   UIKitCore                           0x00000001c6041b38 -[UITableView _rectChangedWithNewSize:oldSize:]
10  UIKitCore                           0x00000001c6042220 -[UITableView setBounds:]
11  UIKitCore                           0x00000001c5f0cb88 -[UIScrollView setContentOffset:]
12  UIKitCore                           0x00000001c60433e4 -[UITableView setContentOffset:]
13  UIKitCore                           0x00000001c5f26b0c _UIScrollViewAdjustForOverlayInsetsChangeIfNecessary
14  UIKitCore                           0x00000001c5f26da0 -[UIScrollView(UIScrollViewInternal) setSafeAreaInsets:]
15  UIKitCore                           0x00000001c61eb0dc -[UIViewController _updateViewSafeAreaInsetsAndEagerlyUpdateContentScrollView:]
16  UIKitCore                           0x00000001c61eb834 -[UIViewController _setContentOverlayInsets:andLeftMargin:rightMargin:]
17  UIKitCore                           0x00000001c61ed2d4 __121-[UIViewController __updateContentOverlayInsetsWithOurRect:inBoundsOfAncestorViewController:viaImmediateChildOfAncestor:]_block_invoke
18  UIKitCore                           0x00000001c61ed0cc -[UIViewController __updateContentOverlayInsetsWithOurRect:inBoundsOfAncestorViewController:viaImmediateChildOfAncestor:]
19  UIKitCore                           0x00000001c61ec294 -[UIViewController _updateContentOverlayInsetsFromParentIfNecessary]
20  UIKitCore                           0x00000001c61ebaac -[UIViewController _updateContentOverlayInsetsForSelfAndChildren]
21  UIKitCore                           0x00000001c5df7178 -[UINavigationController _layoutViewController:]
22  UIKitCore                           0x00000001c5df1cf0 -[UINavigationController _layoutTopViewController]
23  UIKitCore                           0x00000001c5de7f24 __105-[UINavigationController _repositionPaletteWithNavigationBarHidden:duration:shouldUpdateNavigationItems:]_block_invoke
24  UIKitCore                           0x00000001c61d53a8 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:]
25  UIKitCore                           0x00000001c61d596c +[UIView(UIViewAnimationWithBlocks) animateWithDuration:animations:completion:]
26  UIKitCore                           0x00000001c5de7c10 -[UINavigationController _repositionPaletteWithNavigationBarHidden:duration:shouldUpdateNavigationItems:]
27  UIKitCore                           0x00000001c5de829c -[UINavigationController _setNavigationBarHidden:edgeIfNotNavigating:duration:]
28  UIKitCore                           0x00000001c6519bb0 __63-[_UISearchPresentationController dismissalTransitionWillBegin]_block_invoke.186
29  UIKitCore                           0x00000001c6223e64 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:]
30  UIKitCore                           0x00000001c622025c -[_UIViewControllerTransitionContext __runAlongsideAnimations]
31  UIKitCore                           0x00000001c61aa600 -[UIViewAnimationState _runAlongsideAnimations]
32  UIKitCore                           0x00000001c61a9194 -[UIViewAnimationState pop]
33  UIKitCore                           0x00000001c61a6810 +[UIViewAnimationState popAnimationState]
34  UIKitCore                           0x00000001c61d5430 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:]
35  UIKitCore                           0x00000001c61d58ec +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:]
36  UIKitCore                           0x00000001c6512a7c -[_UISearchControllerInPlaceSearchBarAnimator animateTransition:]
37  UIKitCore                           0x00000001c5e68040 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke
38  UIKitCore                           0x00000001c5b3f190 _runAfterCACommitDeferredBlocks
39  UIKitCore                           0x00000001c5b2d1d0 _cleanUpAfterCAFlushAndRunDeferredBlocks
40  UIKitCore                           0x00000001c5b5c508 _afterCACommitHandler
41  CoreFoundation                      0x000000019923db94 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
42  CoreFoundation                      0x0000000199238828 __CFRunLoopDoObservers
43  CoreFoundation                      0x0000000199238dc8 __CFRunLoopRun
44  CoreFoundation                      0x00000001992385b8 CFRunLoopRunSpecific
45  GraphicsServices                    0x000000019b4ac584 GSEventRunModal
46  UIKitCore                           0x00000001c5b33558 UIApplicationMain
47  Zebra                               0x0000000100dc44c4 Zebra + 99524
48  libdyld.dylib                       0x0000000198cf8b94 start

**Additional context**

**Comment by Amplespencer** [comment]
by latest version do you mean b13 or b14? If you update to b14 it may fix this as b13 had serious issues with package updates and dependencies

**Comment by midnightchip** [comment]
Can you check if this is still present in beta 15?

**Comment by PoomSmart** [comment]
Closed due to inactivity.
