### ISSUE TITLE
Move the current package info and some changes that could be made to reduce useless info

### ISSUE THREAD

**Issue by Amplespencer** [wstyres/Zebra#178]
The current package info should be under the icon/name in a way like

icon
**BetterSettings**
com.midnightchips.bettersettings (small)
0.1.3 • 0.1.3 <only show installed if there is an update available>
1.18MB • 1.92MB
Dynastic Repo
installed files > (button outside of a cell)

**Comment by Amplespencer** [comment]
sorry I don’t have a mockup image (not at my pc so it would look like shit)

**Comment by PoomSmart** [comment]
Beta 15 altered this part.
