### ISSUE TITLE
Sorting packages by date button doesn’t show up

### ISSUE THREAD

**Issue by atar13** [wstyres/Zebra#179]
**Description**
The button that sorts packages by date doesn’t appear. 

**To reproduce**
Any time I open the packages tab. 

**Expected behavior**
The button should appear.

**Screenshots**
Attached
![3E1C8884-07D0-44E2-9206-4A9C0D08BA85](https://user-images.githubusercontent.com/42757207/59560096-94c8aa80-8fa7-11e9-898b-30bd60cb099e.png)

**Device Information**
iPhone XR, iOS 12.1
Zebra version 1.0~beta14

**Comment by PoomSmart** [comment]
It's as if you have another tweak that overrides that button.

**Comment by midnightchip** [comment]
This is caused by obsidian I believe

**Comment by PoomSmart** [comment]
@midnightchip With that, this issue becomes invalid.
