### ISSUE TITLE
Updates section and app badge not changing after updating tweaks

### ISSUE THREAD

**Issue by Pjryes** [wstyres/Zebra#18]
**Describe the bug**
After updating a tweak, still showing the tweak needs to be update. Because there’s no respring, closing the app is necessary to take the badge for the tweaks that need to be updated. 

**To Reproduce**
Steps to reproduce the behavior: Open app, go to Package section, update all, after tweaks is updated hit Done tweaks still showing needs to be update. 

**Expected behavior**
After done updating tweak, badge to disappear and Package section not showing the same tweak needs to be update. 

**Device Information:
 - iOS Version: 12.1.1b3
 - AUPM Version: 1.0~b3
 - Device Type: iPhone

**Comment by wstyres** [comment]
I'll be rewriting the update system for the next beta, hopefully that will resolve the issue.

**Comment by wstyres** [comment]
This issue is fixed as of d166675 and will be in the next beta (1.0~beta4)
