### ISSUE TITLE
Changing icon doesn't work

### ISSUE THREAD

**Issue by CloneVince** [wstyres/Zebra#180]
**Describe the bug**
When I try to change the icon, the select form close itself.
If i choose the default icon i have the message : you change the icon for "Zebra"

**To Reproduce**
Choose one icon except the default

**Expected behavior**
Have the message "you change the icon for XXX" and then icon will be updated.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta14
 - Device Type [e.g. iPhone or iPad]: iPhone XS Max

**Comment by midnightchip** [comment]
This is caused by uicache not being run, so LSApplication is not aware of alternate icons. A fix may be to check if the device supports alternate icons and then run UICache if the icon is not available

**Comment by CloneVince** [comment]
Works as expected in beta16.
Thx
