### ISSUE TITLE
Changes tab doesn't update

### ISSUE THREAD

**Issue by CloneVince** [wstyres/Zebra#182]
**Describe the bug**
When I refresh packages, all new changes aren't shown in Changes tab.
All packages are still at the update of Zebra beta14

**To Reproduce**
Updates repos

**Expected behavior**
Display under crurent time updates / created packages

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta14
 - Device Type [e.g. iPhone or iPad]: iPhone XS Max

**Comment by midnightchip** [comment]
Fixed in beta 15
