### ISSUE TITLE
Zebra crashing after launch prior to sources completing refresh

### ISSUE THREAD

**Issue by cyntrifical** [wstyres/Zebra#185]
**Describe the bug**
Zebra crashes approximately 30sec to 1 min after launching
**To Reproduce**
Just start zebra on ios 11.4.1
**Expected behavior**
For zebra to run as normal 
**Screenshots**
Can’t get any 
**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 11.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta14 (introduction of dark mode and changes tab?)
 - Device Type [e.g. iPhone or iPad]: iPhone 6

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.
Wish I could but niether Crashreporter nor Cr4ashed produced a log following crash. 
**Additional context**

**Comment by PoomSmart** [comment]
I presume you have ZodTTD source added to Zebra, right?

**Comment by cyntrifical** [comment]
Yes, I do.   
  
  
  

  
  

  
  
>

**Comment by midnightchip** [comment]
Fixed in beta 15

**Comment by 0j0k3r** [comment]
Since yesterday I got the exact same Problem as described above. Tried already to update to the latest beta and/or deleting all of my repos, but sadly that doesnt help :(
