### ISSUE TITLE
Zebra doesn't show on home scren

### ISSUE THREAD

**Issue by KurdishBoy93** [wstyres/Zebra#19]
recently installed ZEBRA but it doesn't show it on home screen 

i'm on IOS 12.1.1 beta 3 

i respiring it but it doesn't show
![4A59654A-24AA-4FBC-A7D6-878450F4FFA4](https://user-images.githubusercontent.com/47488983/56527943-1e836b00-6557-11e9-8b3a-9f61e6047afe.png)

**Comment by wstyres** [comment]
Have you tried running `uicache` in terminal?

**Comment by wstyres** [comment]
Closing due to no response
