### ISSUE TITLE
Zebra randomly deleting repo list

### ISSUE THREAD

**Issue by p1neappledev** [wstyres/Zebra#191]
Installed a generally large amount of tweaks including dependencies.
When going through the process I got an error regarding nepeta lib color, and the regular lib color.
Towards the end it said “This process might take a while and Zebra might crash, it’s ok if it does”.
I resprung and now my repos besides the default are gone

**Comment by PoomSmart** [comment]
That looks like the `uicache` command that Zebra runs after its installation does not work properly. It causes Zebra to be sandboxed and thus its document directory, along with its source list path, are changed.

The workaround is to re-run `uicache` again. I recommend using PowerSelector tweak to do this.

**Comment by PoomSmart** [comment]
Superseded by #164
