### ISSUE TITLE
I have a problem with Zebra b15

### ISSUE THREAD

**Issue by minhtymeo** [wstyres/Zebra#193]
**Describe the bug**
I accidentally follow a tutorial on reddit and add this repo to my Zebra
http://apt.thebigboss.org/repofiles/cydia/dists/stable/main/binary-iphoneos-arm/
Now everytime i refresh my sources, it creates its own clone in my repo list. And everytime i try to delete, Zebra crash.

**Screenshots**
https://imgur.com/a/822fUOk

**Crash log**
https://pastebin.com/CaPzrp6u

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 15 
 - Device Type [e.g. iPhone or iPad]: iPhone X (iPhone 10,3)

**Comment by PoomSmart** [comment]
Have Filza installed, go to **Home** tab, tap on **Open Document Directory**, go inside **Documents** folder, open **sources.list** with text editor, and manually remove the duplicates.

**Comment by minhtymeo** [comment]
Thank you! Solved!
