### ISSUE TITLE
Repos gone

### ISSUE THREAD

**Issue by thekio1984** [wstyres/Zebra#196]
Running fine for around 4hours, without any reason, repo/sources have gone, no reboots/resprings or even installing of tweaks.....tried uicache & still no joy

**Comment by TheRealKeto** [comment]
This could be causes due to app sandboxing. Try tapping on "Open Documents directory" and see if Zebra is sandboxed (you'll see if its sandboxed if it doesn't send you to /var/mobile/Documents/xyz.willy.zebra).

One simple fix would be to reinstall Zebra through Cydia/Sileo.

**Comment by PoomSmart** [comment]
Superseded by #164
