### ISSUE TITLE
Is rootlessjb supported?

### ISSUE THREAD

**Issue by kerryj89** [wstyres/Zebra#20]
- iOS Version 12.1.1
- rootlessJB 3.2.8
- Zebra 1.0~beta3
- Installed Zebra via Filza
- Respring
- Ran command `uicache`

No Zebra app found on homescreen.
![file](https://user-images.githubusercontent.com/1977804/56550477-57b5de00-654b-11e9-9bac-ac49cd2f2837.jpg)
![file](https://user-images.githubusercontent.com/1977804/56550481-597fa180-654b-11e9-9c39-41a63f1d77bc.jpg)

**Comment by wstyres** [comment]
Currently it is not supported by rootless. I'm not sure if rootless even supports installing applications but I do not have a device to test it on.
