### ISSUE TITLE
No recent tab on iPhone se 12.1.1b3

### ISSUE THREAD

**Issue by Faolan** [wstyres/Zebra#205]
**Describe the bug**
No recent tab for installed packages. Shows up in safe mode 
**To Reproduce**
Works in safe mode
**Expected behavior**
To see the recent tap lol. It works on my 5s 10.3

**Screenshots**
![C4534885-47EB-41B6-A8D2-C44AB3B49EE2](https://user-images.githubusercontent.com/42007330/59965036-1738f900-94d7-11e9-968e-5aaf8165c7e5.png)
![25C74C6C-A98A-42D2-9295-D4591882048C](https://user-images.githubusercontent.com/42007330/59965037-17d18f80-94d7-11e9-9b83-f255a11e5c92.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.1b3
 - Zebra Version current released version 
 - Device Type iPhone se 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Provide the screenshots so we can understand better what you are reporting.

**Comment by PoomSmart** [comment]
It looks like you have a tweak that modifies Zebra behavior (share sheet button at top left). Best to contact the developer of that tweak and let them discuss with us directly, if not already.
