### ISSUE TITLE
Zebra is only simulated

### ISSUE THREAD

**Issue by jenhuff** [wstyres/Zebra#2060]
**Describe the bug*
No matt

**To Reproduce**er what o do the app k eps saying it is only simulated.

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by iAdam1n** [comment]
What device, iOS version and jailbreak? You need to fill that out so we have a chance of helping.

**Comment by jenhuff** [comment]
IPhone 7 iOS 15.7.9 uncover virtual


Sent from Yahoo Mail for iPhone


On Thursday, October 12, 2023, 5:12 AM, Adam I ***@***.***> wrote:




What device, iOS version and jailbreak? You need to fill that out so we have a chance of helping.

**Comment by iAdam1n** [comment]
That’s fake, that is why it’s saying simulated. Remove it and use palera1n.
