### ISSUE TITLE
Can't update Zebra

### ISSUE THREAD

**Issue by datadata95** [wstyres/Zebra#2067]
**Describe the bug**

Installed Zebra with Socket Jailbreak and it installs 1.1.28. I'm trying to update but there seems to be some issues with dependencies and firmware. Not sure what to do.
**To Reproduce**

Update Zebra inside Zebra won't let me update.
**Expected behavior**

Expecting the packages to not turn red marked and progress with installations.
**Screenshots**

![IMG_20240111_163951](https://github.com/zbrateam/Zebra/assets/69867381/051a3f4e-0a1c-4561-97d8-e85e0ac28dd7)
Says cannot install due to problem with firmware?
**Device Information:** 

 - iOS Version: <10.3.3>
 - Zebra Version: <1.1.28>
 - Device Type: <Ipad 4>
 - Jailbreak Type: < Socket >

**Crash Log or System Log**

**Additional context**

**Comment by iAdam1n** [comment]
Something is wrong with your jailbreak setup. You should remove the jailbreak then start again. This is not an issue with Zebra but your setup.
