### ISSUE TITLE
Removing a large amount of packages doesn't do anything

### ISSUE THREAD

**Issue by mdean808** [wstyres/Zebra#207]
**Describe the bug**
I queue up 8+ packages to be removed, tap on queue, confirm, and the console log appears, but it only says `Removing Packages`. I've waited about 1 minute for a change, and I end of quitting the app and nothing gets removed. It works fine with 4 queued to be removed, though.

**To Reproduce**
Queue up at least 5 (might work) packages and try to removed them all at once. 

**Expected behavior**
I expect Zebra to go through all of the steps to remove every package.

**Device Information (please complete the following information):**
 - iOS Version 12.1.2
 - Zebra Version 1.0~beta15
 - Device Type iPhone 6s

**Crash Log or System Log**
No crash

**Comment by Amplespencer** [comment]
can confirm; needs further research. seems to be related to http(s)/ssl because this happens when installing from http://cydia.kemmis.info sometimes. Maybe a chimera APT problem?

**Comment by PoomSmart** [comment]
A kind of dependency issue that apparently has been fixed lately.
