### ISSUE TITLE
This device is simulated

### ISSUE THREAD

**Issue by e-ave** [wstyres/Zebra#2076]
**Describe the bug**
Cannot install anything. Always says "This device is simulated, here are the packages that would be modified in this stage:"

**To Reproduce**
Jailbreak/install zebra and attempt to install something

**Expected behavior**
I expect the packages to install on my iPhone

**Screenshots**
![IMG_4656](https://github.com/zbrateam/Zebra/assets/13954045/00fceea0-0b5d-4b91-8bd5-66171e50210e)
![IMG_4655](https://github.com/zbrateam/Zebra/assets/13954045/baf031ad-fbb5-4cf6-99ee-61505b18e4dc)

**Device Information:** 

 - iOS Version: iOS 10.3.3 
 - Zebra Version: 1.1.28
 - Device Type: iPhone 6 plus
 - Jailbreak Type: doubleh3lix

**Additional context**
My cydia is broken. I cannot install anything via cydia because it will not open at all. That means I cannot install openSSH, I cannot install apple file conduit 2, I cannot install zebra from cydia, etc. 
 
First I tried installing it on a jailbroken phone with sideloadly. I chose 1.1.28 because newer versions refused to install via sideloadly on iOS 10. I figured that sideloadly could not give the app the proper permissions, so I created a fork of doubleh3lix and modified it to install Zebra.app during the jailbreak with cydia. All this succeeded in doing was making the zebra app uninstallable (no X), while still refusing to install any tweaks.

**Comment by iAdam1n** [comment]
If Cydia is not working then that suggests your jailbreak is broken and so Zebra isn't going to suddenly just work. This is intended behaviour. You need to start over and jailbreak fresh and find out why the jailbreak isn't working if it's still broken.

**Comment by e-ave** [comment]
> If Cydia is not working then that suggests your jailbreak is broken and so Zebra isn't going to suddenly just work. This is intended behaviour. You need to start over and jailbreak fresh and find out why the jailbreak isn't working if it's still broken.

Cydia does not work since jailbreaking in iOS 9. I cannot remove cydia without cydia eraser, which I cannot install without cydia. Updating iOS does not fix it. The jailbreak must work if it is able to install Zebra as a system application. Also tweaks from my iOS 9 still work. How are you supposed to install Zebra as a developer? A reddit post says theos is required and if using plain xcode you will get this simulation error because it thinks its the iOS simulator from xcode. I am simply downloading the .deb from the releases

**Comment by iAdam1n** [comment]
Did you not remove all the jailbreak stuff from iOS 9 when upgrading to 10? Maybe that is why? You need a properly working jailbreak environment for Zebra to work. Cydia does definitely work on iOS 9 and 10, so if it isn't for you then that means your jailbreak has issues somewhere. You'd be best to join r/jailbreak Discord or something to find out more because this isn't an issue with Zebra itself.

**Comment by e-ave** [comment]
> Did you not remove all the jailbreak stuff from iOS 9 when upgrading to 10? Maybe that is why? You need a properly working jailbreak environment for Zebra to work. Cydia does definitely work on iOS 9 and 10, so if it isn't for you then that means your jailbreak has issues somewhere. You'd be best to join r/jailbreak Discord or something to find out more because this isn't an issue with Zebra itself.

Okay. So you're saying it should just work if I extract the .deb from releases and copy Zebra.app to /Applications/ right?

**Comment by iAdam1n** [comment]
No, I mean if you install with dpkg-deb -i I'd guess it would? However if Cydia isn't working then that suggests your jailbreak has other issues, which means Zebra probably won't work either. You need to fix whatever is causing Cydia to not work.
