### ISSUE TITLE
[BUG] Unable to install more than a package simultaneously 

### ISSUE THREAD

**Issue by SeMoOo** [wstyres/Zebra#208]
**Describe the bug**
When trying to install more than one or two packages together, zebra fails to install all of them. 

**To Reproduce**
For example, installing instagram++ with all its dependencies or simply installing more than a package at once. 

**Expected behavior**
Install all queued packages

**Screenshots**
N/A

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: b15
 - Device Type [e.g. iPhone or iPad]: iPhone Xs Max

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by PoomSmart** [comment]
Possibly the age old issue with dependencies resolution which has been improved significantly in the latest betas.
