### ISSUE TITLE
Zebra don't install anything with stashing

### ISSUE THREAD

**Issue by platinumstufff** [wstyres/Zebra#2086]
**Describe the bug**
When i try to install anything zebra shows error.

**To Reproduce**

1.Install Stashing from coolstar repo
2.Try to install anything.

**Expected behavior**

Package installed
**Screenshots**

**Device Information:**
 - iOS Version:9.3.2
 - Zebra Version:1.1.36
 - Device Type:iPad Air
 - Jailbreak Type:kok3shi9 untethered

**Crash Log or System Log**
`Installing Packages...
CHAOS, CHAOS!
Zebra was unable to complete this command because it does not have the proper permissions. Please verify the permissions located at /var/stash/appsstash/Zebra.app and report this issue on GitHub. 
Importing local packages. 
Finished importing local packages. 
Finished!
`
**Additional context**

**Comment by iAdam1n** [comment]
Assuming this only happens once you've installed Stashing, you'd need to contact coolstar about that since they would need to make it not affect Zebra. This isn't something we can do.
