### ISSUE TITLE
Unable to verify repo: the file “sources.list” doesn’t exist

### ISSUE THREAD

**Issue by vladasbarisas** [wstyres/Zebra#21]
**Describe the bug**
Cannot add any repos to Zebra, I always get this error — Unable to verify repo: the file “sources.list” doesn’t exist

**To Reproduce**
1. Install Zebra using Cydia
2. Add any repo (example: https://repo.nepeta.me/)
3. Wait for 0.5 seconds until the errors occurs

**Expected behavior**
A repo is added to Zebra

**Device Information (please complete the following information):**
 - iOS Version: 12.1.1
 - AUPM Version: 1.0~beta4
 - Device Type: iPhone 

**Additional context**
Zebra installed using Cydia from your repo, the device is running unc0ver jailbreak, this is the first time that I’ve installed Zebra

**Comment by wstyres** [comment]
Try uninstalling, running uicache (or respringing), then installing again

**Comment by vladasbarisas** [comment]
I uninstalled Zebra, ran uicache, did a respring and installed Zebra again. Same issue

**Comment by wstyres** [comment]
and if you press "Open Documents Directory" on the zebra homepage could I see a screenshot of where it takes you?

**Comment by vladasbarisas** [comment]
It takes me to /var/mobile/Documents, which is empty:

![screenshot](https://i.imgur.com/ZMID6CS.jpg)

**Comment by vladasbarisas** [comment]
I also noticed that there's a red spinner near the Sources tab that doesn't seem to ever disappear, even though my source list is empty.

**Comment by vladasbarisas** [comment]
I tried searching my filesystem for sources.list and I've found it in `/var/mobile/Library/Caches/com.saurik.Cydia/`. There's also an empty sources.list located in `/private/var/mobile/Library/Caches/xyz.willy.Zebra`

**Comment by wstyres** [comment]
It looks like you don't have the right permissions to create directories in /var/mobile/Documents so Zebra cannot move files into the documents directory, try creating the directory xyz.willy.Zebra in the Documents directory

**Comment by vladasbarisas** [comment]
That seems to have worked! I created a directory `/var/mobile/Documents/xyz.willy.Zebra` and set its permission bit to 777, and repos work correctly now. My documents folder is owned by root:wheel with permission bit 755, and this is also the default. You might want to add a handler for this situation to avoid confusion by other users.

**Comment by vladasbarisas** [comment]
I just checked my iPad and its Documents folder is owned by root:wheel as well. I also did a rootfs restore on my phone not too long ago, so unless some tweak that I use changed the ownership of this folder, it's unfortunately set up to be this way by default.

**Comment by wstyres** [comment]
On 12.1.1 this is the output of `ls -l /var/mobile` showing that every directory in /var/mobile is owned by mobile
```
iPhone:/var/mobile root# ls -l           
total 0
drwxr-xr-x   4 mobile mobile  128 Feb 27 22:55 Containers/
drwxr-xr-x   3 mobile mobile   96 Mar 31 16:19 Documents/
drwx------   2 mobile mobile   64 Feb 27 23:01 Downloads/
drwx--x--x 100 mobile mobile 3200 Apr 17 22:11 Library/
drwxr-x---  12 mobile mobile  384 Mar  7 20:47 Media/
drwxr-xr-x   3 mobile mobile   96 Mar 31 15:55 MobileSoftwareUpdate/
```
I will try to confirm this on other devices when I get home but I think that you have improper permissions

**Comment by wstyres** [comment]
I confirmed this on an iPhone 6 running 12.1.2 (no rootfs restore at all)
```
Caliban:~ root# ls -l /var/mobile/
total 0
drwxr-xr-x   4 mobile mobile  128 Mar 26 23:24 Containers/
drwxr-xr-x   5 mobile mobile  160 Apr 21 22:29 Documents/
drwx------   2 mobile mobile   64 Mar 26 23:26 Downloads/
drwx--x--x 104 mobile mobile 3328 Apr 17 22:59 Library/
drwxr-x---  13 mobile mobile  416 Apr 17 23:00 Media/
drwxr-xr-x   3 mobile mobile   96 Apr  7 22:26 MobileSoftwareUpdate/
```
and an iPad running 10.3.3
```
Cibola:~ mobile$ ls -l                                                                           
total 88076                                                                                      
drwxr-xr-x  4 mobile mobile      136 Nov  9 20:48 Containers/                                    
drwxr-xr-x  4 mobile mobile      136 Nov  9 20:58 Documents/                                     
drwx------  2 mobile mobile       68 Nov  9 20:49 Downloads/                                     
drwxrwxrwx 76 mobile mobile     2618 Nov 17 11:57 Library/                                       
drwxr-x--- 15 mobile mobile      510 Mar 22 20:17 Media/                                         
drwxr-xr-x  2 mobile mobile      102 Jan 31 12:11 MobileSoftwareUpdate/
```

**Comment by vladasbarisas** [comment]
Well, seems like something on my device changed those permissions then, thank you for verifying this. I’ll look into what could’ve caused it. Here’s what my /var/mobile looks like by the way:
`drwxr-xr-x   4 mobile mobile  128 Feb  3 13:00 Containers/
drwxr-xr-x   5 root   mobile  160 Apr 24 19:32 Documents/
drwx------   3 mobile mobile   96 Apr 23 23:05 Downloads/
drwx--x--x 132 mobile mobile 4224 Apr 24 20:07 Library/
drwxr-x---  18 mobile mobile  576 Apr 24 14:48 Media/
drwxr-xr-x   3 mobile mobile   96 Apr 16 15:53 MobileSoftwareUpdate/`

**Comment by wstyres** [comment]
To verify that this was the problem, could you change the permissions of Documents back to mobile:mobile and delete the folder you created within it? Relaunching Zebra should then hopefully create a new folder.

**Comment by vladasbarisas** [comment]
Yeah, I changed Documents ownership to mobile:mobile, deleted Zebra’s folder and it successfully created a new one by itself after a relaunch.

**Comment by wstyres** [comment]
Good to hear, the Documents issue could have been related to your rootfs restore but I cannot confirm that myself.
