### ISSUE TITLE
Crash when looking at installed files

### ISSUE THREAD

**Issue by rctfan929** [wstyres/Zebra#218]
When I tap on installed files for a package Zebra crashes.

**To Reproduce**
1. Select a package
2. Tap on Installed files

I expect a list of what is installed to appear. Instead Zebra crashes.

 - iOS 12.1.2
 - Zebra Beta 16
 - iPhone 6s

Crash log:
https://pastebin.com/GzJeyFFZ

**Comment by midnightchip** [comment]
This will be fixed in the next build
