### ISSUE TITLE
Consistent sandbox error

### ISSUE THREAD

**Issue by joek1ng4312** [wstyres/Zebra#221]
#**Describe the bug**
Keep getting consistent sandbox error with lastest beta (1.0~16 I think) even after deleting the documents folder and running uicache

**To Reproduce**
Steps to reproduce the behaviour:
Simply keep using zebra after a couple of resprings

**Expected behavior**
A fix maybe?

**Screenshots**

**Device Information (please complete the following information):**
 iPhone X, iOS 12.1.2 zebra version 1.0~beta 16

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue

**Additional context**

**Comment by PoomSmart** [comment]
Workaround and comment: https://twitter.com/PoomSmart/status/1147333948680204288

**Comment by joek1ng4312** [comment]
Thanks!


On 6/07/2019, at 2:54 PM, Thatchapon Unprasert <notifications@github.com<mailto:notifications@github.com>> wrote:


Workaround and comment: https://twitter.com/PoomSmart/status/1147333948680204288
