### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 1375089732** [wstyres/Zebra#222]
![01D8D8CB-F7E4-4C1E-B0CC-D6048029ECB4](https://user-images.githubusercontent.com/52591760/60751968-7e839c80-9ff1-11e9-9b97-3ba44e27dffc.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by midnightchip** [comment]
This is fixed in the next beta
