### ISSUE TITLE
Tint selector doesn't work on credits page

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#223]
**Describe the bug**

The new tint selector is amazing and works exactly as I would expect it to except for on the credits page. It changes the text color on all pages to my knowledge other than that one. The links to the various profiles listed remain orange despite the fact that the tint was changed.

**To Reproduce**

Select tint from within app settings then go to the credits page.

**Expected behavior**

I expect the text color to be consistent with the text color in the rest of Zebra.

**Screenshots**

![IMG-0356](https://user-images.githubusercontent.com/51668635/60759249-4e082680-a022-11e9-94ed-bedeaa874066.JPG)
![IMG-0357](https://user-images.githubusercontent.com/51668635/60759250-4fd1ea00-a022-11e9-935d-6d72d6af7bfc.JPG)

**Device Information (please complete the following information):**
 - iOS Version [12.1.1 developer beta 3]: 
 - Zebra Version [1.0~beta16]: 
 - Device Type [iPhone Xs]: 

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by Amplespencer** [comment]
that’s not a tint but text changed by the dark mode selector, should be an easy fix.

**Comment by worldlydev** [comment]
The credits page hasn't exactly aged well. Perhaps it should be killed off in favor of an actual native page in zebra rather than linking to (https://xtm3x.github.io/zebra/credits.html)? The page doesn't support tint colors or the different dark mode types. What I mean to say is that I would like to feel like the rest of zebra does, native and functional. While you're at it get rid of the refresh button on the top right of the page. ![693DB3D0-3E21-4AF2-A879-8403FBE4B4C7](https://user-images.githubusercontent.com/51668635/67581296-109de500-f748-11e9-9d61-e975b53afd01.jpeg)

**Comment by wstyres** [comment]
The plan for 1.0 is to create a native credits plage in order to fix this issue.
