### ISSUE TITLE
Zebra hiperbug versão nova está bugada 

### ISSUE THREAD

**Issue by mitsuoliver** [wstyres/Zebra#224]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by worldlydev** [comment]
Your bug report literally is just "newest version of Zebra has bug". 😂

**Comment by mitsuoliver** [comment]
Enviado do meu iPhone

Em 7 de jul de 2019, à(s) 10:05, Thatchapon Unprasert <notifications@github.com> escreveu:
