### ISSUE TITLE
Bug na versão atual

### ISSUE THREAD

**Issue by mitsuoliver** [wstyres/Zebra#226]
![22C13A1D-E392-4220-AA37-C15495370F38](https://user-images.githubusercontent.com/51269789/60772393-15248c00-a0cc-11e9-8599-ac4e908b33c8.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by midnightchip** [comment]
A correção será incluída na próxima versão.

**Comment by mitsuoliver** [comment]
Top

Enviado do meu iPhone

Em 7 de jul de 2019, à(s) 15:46, MidnightChip <notifications@github.com> escreveu:

**Comment by mitsuoliver** [comment]
Novo bug versão 17 
Date: 2019-07-09 16:52:13 +0000 Process: Zebra Bundle id: xyz.willy.Zebra Exception type: NSRangeException Reason: *** -[__NSArrayM insertObject:atIndex:]: index 9223372036854775807 beyond bounds for empty array Culprit: Unknown Device: iPhone X, iOS 12.1.1 Call stack: 0 CoreFoundation 0x00000001b0648edc __exceptionPreprocess 1 libobjc.A.dylib 0x00000001af819a40 objc_exception_throw 2 CoreFoundation 0x00000001b05c0494 _CFArgv 3 CoreFoundation 0x00000001b052f8cc -[__NSArrayM insertObject:atIndex:] 4 Zebra 0x0000000102a07144 Zebra + 241988 5 Zebra 0x0000000102a06fa4 Zebra + 241572 6 Zebra 0x0000000102a053e0 Zebra + 234464 7 Zebra 0x0000000102a099ec Zebra + 252396 8 Zebra 0x0000000102a07654 Zebra + 243284 9 Zebra 0x00000001029e154c Zebra + 87372 10 UIKitCore 0x00000001dd760cc8 -[UIApplication sendAction:to:from:forEvent:] 11 UIKitCore 0x00000001dcf30530 __45-[_UIButtonBarTargetAction _invoke:forEvent:]_block_invoke 12 UIKitCore                           0x00000001dcf30460 -[_UIButtonBarTargetAction _invoke:forEvent:] 13 UIKitCore 0x00000001dd760cc8 -[UIApplication sendAction:to:from:forEvent:] 14 UIKitCore 0x00000001dd1ee700 -[UIControl sendAction:to:forEvent:] 15 UIKitCore 0x00000001dd1eea20 -[UIControl _sendActionsForEvents:withEvent:] 16 UIKitCore 0x00000001dd1eda20 -[UIControl touchesEnded:withEvent:] 17 UIKitCore 0x00000001dd79a420 -[UIWindow _sendTouchesForEvent:] 18 UIKitCore 0x00000001dd79b684 -[UIWindow sendEvent:] 19 UIKitCore 0x00000001dd77a980 -[UIApplication sendEvent:] 20 UIKitCore 0x00000001dd8491ec __dispatchPreprocessedEventFromEventQueue 21 UIKitCore 0x00000001dd84bbe4 __handleEventQueueInternal 22 UIKitCore 0x00000001dd8446d4 __handleHIDEventFetcherDrain 23 CoreFoundation 0x00000001b05d91f0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ 24 CoreFoundation 0x00000001b05d9170 __CFRunLoopDoSource0 25 CoreFoundation                      0x00000001b05d8a54 __CFRunLoopDoSources0 26 CoreFoundation 0x00000001b05d3920 __CFRunLoopRun 27 CoreFoundation 0x00000001b05d31f0 CFRunLoopRunSpecific 28 GraphicsServices 0x00000001b284c584 GSEventRunModal 29 UIKitCore 0x00000001dd75f5b4 UIApplicationMain 30  Zebra 0x00000001029e9654 Zebra + 120404 31 libdyld.dylib 0x00000001b0092bb4 start



Enviado do meu iPhone

Em 7 de jul de 2019, à(s) 22:21, Thatchapon Unprasert <notifications@github.com> escreveu:
