### ISSUE TITLE
buggggg

### ISSUE THREAD

**Issue by mitsuoliver** [wstyres/Zebra#227]
**Additional context**
Date: 2019-07-07 22:38:36 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSGenericException
Reason: *** Collection <__NSDictionaryM: 0x283401700> was mutated while being enumerated.
Culprit: Unknown
Device: iPhone X, iOS 12.1.1
Call stack:
0   CoreFoundation                      0x0000000220008edc __exceptionPreprocess
1   libobjc.A.dylib                     0x000000021f1d9a40 objc_exception_throw
2   CoreFoundation                      0x000000022000875c -[__NSSingleObjectEnumerator initWithObject:]
3   Zebra                               0x0000000102cca508 Zebra + 386312
4   Zebra                               0x0000000102cca6ac Zebra + 386732
5   CoreFoundation                      0x000000021ff7794c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
6   CoreFoundation                      0x000000021ff77918 ___CFXRegistrationPost_block_invoke
7   CoreFoundation                      0x000000021ff76e08 _CFXRegistrationPost
8   CoreFoundation                      0x000000021ff76ab4 ___CFXNotificationPost_block_invoke
9   CoreFoundation                      0x000000021feeec90 -[_CFXNotificationRegistrar find:object:observer:enumerator:]
10  CoreFoundation                      0x000000021ff76540 _CFXNotificationPost
11  Foundation                          0x0000000220987ca0 -[NSNotificationCenter postNotificationName:object:userInfo:]
12  Zebra                               0x0000000102cb6fac Zebra + 307116
13  Zebra                               0x0000000102c95be0 Zebra + 170976
14  CFNetwork                           0x00000002207a3f98 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.241
15  Foundation                          0x0000000220a988bc __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
16  Foundation                          0x00000002209a0ab8 -[NSBlockOperation main]
17  Foundation                          0x000000022099ff8c -[__NSOperationInternal _start:]
18  Foundation                          0x0000000220a9a790 __NSOQSchedule_f
19  libdispatch.dylib                   0x000000021fa416c8 _dispatch_call_block_and_release
20  libdispatch.dylib                   0x000000021fa42484 _dispatch_client_callout
21  libdispatch.dylib                   0x000000021fa18e04 _dispatch_continuation_pop$VARIANT$armv81
22  libdispatch.dylib                   0x000000021fa184e8 _dispatch_async_redirect_invoke
23  libdispatch.dylib                   0x000000021fa24aec _dispatch_root_queue_drain
24  libdispatch.dylib                   0x000000021fa2534c _dispatch_worker_thread2
25  libsystem_pthread.dylib             0x000000021fc2517c _pthread_wqthread
26  libsystem_pthread.dylib             0x000000021fc27cec start_wqthread

**Comment by wstyres** [comment]
We have no way of knowing what caused this crash without you giving us a description of what happened when it crashes. Steps to reproduce this crash would be useful as well as which version of Zebra you are using, iOS version, etc.

**Comment by PoomSmart** [comment]
This is assumed to be crashing when refreshing sources, which has been addressed.
