### ISSUE TITLE
Still crashing when tapping restart springboard

### ISSUE THREAD

**Issue by rctfan929** [wstyres/Zebra#228]
Zebra still crashes when I tap restart springboard after installing a tweak.

1. Install tweak
2. Tap Restart Springboard

I expect my device to respring but instead Zebra crashes. I have to manually respring to finish insallation. 

 - iOS 12.1.2
 - Zebra beta 17
 - iPhone 6s 

Crash log:
https://pastebin.com/iBHTK6py

**Additional context**
I am on uncover 3.2.1 (latest) but have downgraded jailbreak resources and UIKit Tools for stability reasons.

**Comment by TheRealKeto** [comment]
Since you don't have the latest UIKit Tools installed, `sbreload` isn't present, causing Zebra to not respring. 

I believe this has been fixed in recent commits by simply allowing Zebra to use the old respring method (aka `killall backboardd` or `killall -9 SpringBoard`), so this should come on later updates.

**Comment by rctfan929** [comment]
Supposedly it was fixed in beta16. I’m on beta17. 
![5DBF58D1-6CF4-47F7-B074-AFCCA0139CDE](https://user-images.githubusercontent.com/46878212/60801094-61131780-a144-11e9-8987-df88ca407265.png)

**Comment by pwn20wndstuff** [comment]
@TheRealKeto sbreload has been present in UIKit Tools since iOS 2—When Saurik originally made it...

**Comment by Samgisaninja** [comment]
either way, [zebra checks to see if sbreload exists and uses a regular respring as a fallback if it doesn't](https://github.com/wstyres/Zebra/blob/cfad20dd4227e1057eef6e9e6b2bda92a3bb6722/Zebra/ZBDevice.m#L61)

**Comment by rctfan929** [comment]
Do you think uninstalling and reinstalling will fix this for me?

**Comment by PoomSmart** [comment]
Closed in favour of #234
