### ISSUE TITLE
Zebra should have it’s own standalone repo at getzbra.com

### ISSUE THREAD

**Issue by A-Human-Person** [wstyres/Zebra#231]
xtm3x.github.io/repo only has 2 packages:Noblur and Zebra (beta).

I think zebra should use the getzbra.com domain for it’s repo instead of Wilson’s.

Wilson could even get rid of his repo and put Noblur on bigboss

**Comment by wstyres** [comment]
Zebra will transition to a repo on getzbra.com once it is out of beta. For the time being it will remain on my repo.
