### ISSUE TITLE
Can't respring

### ISSUE THREAD

**Issue by quanganh123** [wstyres/Zebra#232]
**Describe the bug**
I can't respring after install tweaks. After press respring button it just back to the recent tab and no respring

**To Reproduce**

**Expected behavior**
I want it to respring after I press the button when install tweak
**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 9.3.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: All version
 - Device Type : iPhone 4s
**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
It looks like `sbreload` under iOS 9 has to be run as root.
