### ISSUE TITLE
Issue where I can’t update and it deletes my sources when I try

### ISSUE THREAD

**Issue by biggietookmybmx** [wstyres/Zebra#233]
So I saw zebra has a new update in the changes tab, I went ahead and tried to but then got this:
![EB8FD2E2-B044-4F6D-8EAC-65DCE0EE5B90](https://user-images.githubusercontent.com/52762871/61007031-d0059180-a339-11e9-8d35-68287a41b404.png)
So when I respring after that I open zebra to find out it didn’t upgrade to beta 17 at all
![3A159A18-F152-46E5-9B5D-9F14CB846756](https://user-images.githubusercontent.com/52762871/61007147-0fcc7900-a33a-11e9-8d4b-87750f3c37b0.png)
All it did was delete all of my sources :/
![27B5D802-BC03-4A17-8844-32FC78B6D1EF](https://user-images.githubusercontent.com/52762871/61007169-21ae1c00-a33a-11e9-871d-db2d8c37f53c.png)

1. Be on zebra beta 16
2. Try to update to zebra beta 17 from the changes tab

**Expected behavior**
I expected it to update to the newest version and definitely not delete every source I had on there.

*Screenshots posted above*

**Device Information (please complete the following information):**
 - iOS Version 1.12.2
 - Zebra Version 1.0~beta16
 - Device Type iPhone XS Max

**Crash Log or System Log**
Doesn’t crash, just doesn’t update

**Comment by midnightchip** [comment]
Install using filza or an alternate package manager, this is do to an oversight when we migrated the database to a new location.

**Comment by biggietookmybmx** [comment]
This solved the issue thanks.
