### ISSUE TITLE
Buggg versão 17

### ISSUE THREAD

**Issue by mitsuoliver** [wstyres/Zebra#236]
Date: 2019-07-11 15:32:22 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSRangeException
Reason: *** -[__NSArrayM insertObject:atIndex:]: index 9223372036854775807 beyond bounds for empty array
Culprit: Unknown
Device: iPhone X, iOS 12.1.1
Call stack:
0   CoreFoundation                      0x00000001f2228edc __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001f13f9a40 objc_exception_throw
2   CoreFoundation                      0x00000001f21a0494 _CFArgv
3   CoreFoundation                      0x00000001f210f8cc -[__NSArrayM insertObject:atIndex:]
4   Zebra                               0x00000001048e7144 Zebra + 241988
5   Zebra                               0x00000001048e6fa4 Zebra + 241572
6   Zebra                               0x00000001048e5e24 Zebra + 237092
7   Zebra                               0x00000001048e9a68 Zebra + 252520
8   Zebra                               0x00000001048e72ec Zebra + 242412
9   Zebra                               0x00000001048e6fa4 Zebra + 241572
10  Zebra                               0x00000001048e53e0 Zebra + 234464
11  Zebra                               0x00000001048e99ec Zebra + 252396
12  Zebra                               0x00000001048e72d4 Zebra + 242388
13  Zebra                               0x00000001048d5184 Zebra + 168324
14  Zebra                               0x00000001048e398c Zebra + 227724
15  UIKitCore                           0x000000021f340cc8 -[UIApplication sendAction:to:from:forEvent:]
16  UIKitCore                           0x000000021eb10530 __45-[_UIButtonBarTargetAction _invoke:forEvent:]_block_invoke
17  UIKitCore                           0x000000021eb10460 -[_UIButtonBarTargetAction _invoke:forEvent:]
18  UIKitCore                           0x000000021f340cc8 -[UIApplication sendAction:to:from:forEvent:]
19  UIKitCore                           0x000000021edce700 -[UIControl sendAction:to:forEvent:]
20  UIKitCore                           0x000000021edcea20 -[UIControl _sendActionsForEvents:withEvent:]
21  UIKitCore                           0x000000021edcda20 -[UIControl touchesEnded:withEvent:]
22  UIKitCore                           0x000000021f37a420 -[UIWindow _sendTouchesForEvent:]
23  UIKitCore                           0x000000021f37b684 -[UIWindow sendEvent:]
24  UIKitCore                           0x000000021f35a980 -[UIApplication sendEvent:]
25  UIKitCore                           0x000000021f4291ec __dispatchPreprocessedEventFromEventQueue
26  UIKitCore                           0x000000021f42bbe4 __handleEventQueueInternal
27  UIKitCore                           0x000000021f4246d4 __handleHIDEventFetcherDrain
28  CoreFoundation                      0x00000001f21b91f0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
29  CoreFoundation                      0x00000001f21b9170 __CFRunLoopDoSource0
30  CoreFoundation                      0x00000001f21b8a54 __CFRunLoopDoSources0
31  CoreFoundation                      0x00000001f21b3920 __CFRunLoopRun
32  CoreFoundation                      0x00000001f21b31f0 CFRunLoopRunSpecific
33  GraphicsServices                    0x00000001f442c584 GSEventRunModal
34  UIKitCore                           0x000000021f33f5b4 UIApplicationMain
35  Zebra                               0x00000001048c9654 Zebra + 120404

**Comment by PoomSmart** [comment]
@midnightchip inquire more information from them?

**Comment by midnightchip** [comment]
Isso ainda está presente na versão beta 18

**Comment by PoomSmart** [comment]
Directly related: #258
