### ISSUE TITLE
Tweaks that have been purchased, don’t show up in search

### ISSUE THREAD

**Issue by p1neappledev** [wstyres/Zebra#238]
When I have my shop accounts added to Zebra, all of the packages I have purchased don’t show up in search results, and if I go through the store section and try to install from there, they just crash Zebra when hitting install

iPhone 8 (10,1) 12.2 (Stable) Latest Zebra version

**Comment by PoomSmart** [comment]
Which purchased packages?

**Comment by p1neappledev** [comment]
Sonus12 and Noctis

**Comment by PoomSmart** [comment]
As a workaround, you should log out and log in your Packix account.
