### ISSUE TITLE
Removal of dependencies isn’t correctly detected

### ISSUE THREAD

**Issue by MJavad** [wstyres/Zebra#239]
**Describe the bug**
After trying to remove Nghttp2 package from Electra repo, higher dependencies wasn’t detected. Git depends on cURL which depends on Nghttp2.
After confirming, log shows dependecy error, and the packages wasn’t removed. 
Afterwards the package is shown as removed in Zebra.
Tried dropping tables but still shown as not installed.
The bug was reproduced by installing Nghttp2 and removing again.

**Expected behavior**
Selecting remove on Nghttp2 should show other packages which must be removed together.
“Package not removed” errors should be detected correctly.

**Device Information (please complete the following information):**
 - iOS Version: 11.1.2
 - Zebra Version: beta17
 - Device Type: iPhone

**Additional context**
The error’s syntax is as follows:

dependency problems prevent removal of nghttp2: curl depends on nghttp2
error processing package nghttp2 (—remove): dependency problems - not removed

**Comment by MJavad** [comment]
I can’t re-open this issue, but this isn’t entirely fixed on beta18.
Dependency detection for Nghttp2 package is still not working. After trying to remove it, no other packages are marked for removal.
Then I tried some other packages and encountered this again. When removing cURL (Electra) package it correctly markes Git (Bingner) to be removed but package “Theos Dependencies” (BigBoss) depends on Git which isn’t marked and causes the same errors.

**Comment by MJavad** [comment]
@PoomSmart

**Comment by PoomSmart** [comment]
Can you provide the list of tweaks and the detailed steps to reproduce the issue?

**Comment by MJavad** [comment]
To reproduce add Electra repo and install Theos Dependencies (BigBoss), then attempt to remove either Nghttp2 or cURL (Electra repo) which are 3rd and 2nd level dependencies.

Now that I think about it, it may be because of my APT v1.7. I didn’t update because Cydia would get removed along.

 I could do further testing if you provide instructions (or try to upgrade apt).

Tweaks:
adv-cmds
applist
apt7
apt7-key
apt7-lib
base
bash
basic-cmds
berkeleydb
bootstrap-cmds
bzip2
co.vexation.nosubstitute
com.a3tweaks.flipswitch
com.aidoo.memsearch
com.chilaxan.ezswitch
com.creaturecoding.libcspreferences
com.creaturesurvive.libcscolorpicker
com.ex.libsubstitute
com.exile90.icleanerpro
com.ioscreatix.weathervane
com.ipadkid.flexit
com.julioverne.spotilife
com.kingpuffdaddi.control-center.ccvpn
com.lema.unicorn
com.lnx.aerify
com.matchstic.reprovision
com.mc.arp-spoof
com.mc.arpscan
com.mc.bc
com.mc.libpcap
com.mc.utillinux
com.muirey03.brickfix
com.opa334.ccsupport
com.pantsthief.flexing
com.rpetrich.rocketbootstrap
com.ryleyangus.libertylite.beta
com.shiftcmdk.ccaudiobalance
com.shmoopillc.flexible
com.spark.easyswitcherx
com.spark.libsparkapplist
com.spark.nolowpowerautolock
com.thecomputerwhisperer.detailedpowerusage
com.thireus.untrustedhostsblocker9
com.tigisoftware.filza64bit
com.vitataf.homegesture
com.vsz.redeb
coreutils
coreutils-bin
crash-reporter
curl
cydia
cydia-gui
cydia-lproj
darwintools
debianutils
diffutils
diskdev-cmds
dpkg
file-cmds
findutils
firmware-sbin
flex3beta
gawk
git
gnupg
grep
gzip
htop
inetutils
jp.ashikase.libcrashreport64
jp.ashikase.libpackageinfo64
jp.ashikase.libsymbolicate64
jp.ashikase.techsupport64
ldid
less
libactivator
libgcc
libressl
lldb
lsof
lzma
make
me.alfhaily.adblockforyoutube
me.alfhaily.cercube
me.alfhaily.cercube.lib
me.alfhaily.rocket
me.alfhaily.rocket.lib
me.jjolano.shadow
mobilesubstrate
nano
ncurses
net.limneos.classdump-dyld
network-cmds
nghttp2
openssh
openssl
org.coolstar.cctools
org.coolstar.iostoolchain
org.coolstar.ld64
org.coolstar.llvm-clang
org.coolstar.llvm-clang64
org.coolstar.tweakinject
org.thebigboss.cacerts
org.thebigboss.groff-base
org.thebigboss.libcolorpicker
org.thebigboss.libnet
org.thebigboss.libpipeline
org.thebigboss.man-db
org.thebigboss.repo.icons
org.theos.dependencies
org.xbmc.kodi-ios64
p7zip
patch
perl
preferenceloader
profile.d
python
radare2
re.frida.server
readline
rsync
ru.domo.cocoatop64
screen
sed
shell-cmds
socat
system-cmds
tar
top
uikittools
unrar
unzip
uuid
wget
ws.hbang.common
xyz.willy.zebra
xyz.xninja.systeminfo
zip

**Comment by Brixteren** [comment]
I experience a similar problem, though at a “1st level dependency”. Tried to remove “libnepeta”, which is depended on by the tweak “Nereid”. 

Zebra did not add Nereid to removal queue (I also restarted Zebra and tried again), but Cydia did. It happens for most packages with dependencies, however not all? See images. 

https://imgur.com/gallery/b5rKG2G
