### ISSUE TITLE
Installing somewhat frequently fails

### ISSUE THREAD

**Issue by campbellcole** [wstyres/Zebra#24]
When installing packages, about 1 in 5 fails with the error "--install needs at least one package archive file argument"

This error happened to me when installing the package "Clean Home Screen" from the BigBoss repo. I've noticed it has something to do with the name of the deb and the folder from which it was downloaded.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wstyres** [comment]
A screenshot of the install screen that displays the error would be useful so that I can see what filename it is downloaded to.

**Comment by wstyres** [comment]
I'm able to install Clean Home Screen (as well as other packages from Dynastic) as of 48e0c93, will be implemented in beta 6.
