### ISSUE TITLE
Zebra keeps asking if you'd like to add a cipoid link to sources

### ISSUE THREAD

**Issue by allendude51** [wstyres/Zebra#240]
Every time I go to the sources tab, the app always asks me if I'd like to add my copied like as a source.  Even after I say no, I re open the app and the pop-up keeps showing up every time. This has happened on 11.3.1 on 6s, X and iPad Air 1

**Comment by midnightchip** [comment]
This is scheduled, if the repo is already on your device you will no longer have a popup starting next beta
