### ISSUE TITLE
Queue button not always showing when packages in queue

### ISSUE THREAD

**Issue by Garydunlop00** [wstyres/Zebra#243]
**Describe the bug**
When queueing up tweaks with the slide feature when going back to the packages tab to find the queue button it doesn’t show and I have to go into settings and drop tables to get the button to show.

**To Reproduce**
It happens anytime I queue tweaks with the slide feature.

**Expected behavior**
Queue button to show when packages in queue.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: IOS 12.0
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:1.0 Beta18 
 - Device Type [e.g. iPhone or iPad]: iPhone 6s

**Crash Log or System Log**
There is no crash log as this bug doesn’t cause the app to crash.

**Additional context**

**Comment by PoomSmart** [comment]
"Slide feature" is unclear to me. Can you provide detailed steps to reproduce the issue?

**Comment by Brixteren** [comment]
I think the issue here is this feature: https://pasteboard.co/IoVfEo9.png

I can’t seem to reproduce the issue mentioned here, however when clearing the last package of a queue through the same feature, the “empty queue” problem happens
