### ISSUE TITLE
Very tiny bugs

### ISSUE THREAD

**Issue by yaserFA** [wstyres/Zebra#244]
**Describe the bug**

1- the search bar goes up to the statusbar 
2- when adding a source, the pop-up window doesn't show what I am writing
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version : 11.3.1
 - Zebra Version : 1.0 ~beta18
 - Device Type : Iphone 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by yaserFA** [comment]
The bugs only sometimes occur, not always

**Comment by wstyres** [comment]
It appears these bugs have been fixed as of the latest betas as I am not able to reproduce them.
