### ISSUE TITLE
"Installed Version" of all packages is 0.0

### ISSUE THREAD

**Issue by Samgisaninja** [wstyres/Zebra#245]
**Describe the bug**
"Installed version" uilabel always shows 0.0. IDK if it's not reading or parsing or what

**To Reproduce**
open any package depiction vc

**Expected behavior**
I wanted to see the actual version ¯\\\_(ツ)_/¯

**Screenshots**

**Device Information (please complete the following information):**
 - iOS 12.2
 - Zebra Version b18
 - iPhone X

https://cdn.discordapp.com/attachments/566255609251364867/600193603406397451/image0.png

**Comment by midnightchip** [comment]
Fixed :)
