### ISSUE TITLE
Actually im not reporting anything. Im just asking for a feature in zebra. Can you please add importing repo feature for zebra. So i can import my every repos from cydia. 

### ISSUE THREAD

**Issue by ahmedullah3778** [wstyres/Zebra#246]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by midnightchip** [comment]
Homepage -> Community Repos -> Transfer Sources
