### ISSUE TITLE
Import sources from Cydia/Sileo

### ISSUE THREAD

**Issue by Brixteren** [wstyres/Zebra#248]
**Is your feature request related to a problem? Please describe.**
The first time i used Zebra I was unsure where my sources were. Turned out I needed to export them manually and import them via the “multiple” option

**Describe the solution you'd like**
A setting/welcome alert to import sources from either Cydia or Sileo

**Describe alternatives you've considered**
Doing it manually or with a bash script seems like the only current solution. After looking at previous bug reports, I can see on issue #35 that it was reported the feature had been added in beta 9, however it seems like it has been removed again?

**Comment by midnightchip** [comment]
We do have a way to import repos, Home -> Community Repos -> Import from Cydia/Sileo

**Comment by Brixteren** [comment]
Ah my mistake, thanks for the hard work. Closing.

**Comment by neumaif02** [comment]
Maybe add an option that you can find more easily
