### ISSUE TITLE
Some tweaks are cannot install successfully

### ISSUE THREAD

**Issue by baobaoit** [wstyres/Zebra#256]
**Describe the bug**
Some tweaks are cannot install successfully, such as Callbar XS (requires firmware >= 12, although I already running iOS 12.2 on my iPhone), CopyLog (installed but doesn’t show the respring button, Filza (stuck at trigger Cydia).

**To Reproduce**
Install those tweaks above on Zebra.

**Expected behavior**
Install those tweaks above normally like Cydia, Sileo.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0\~beta18
 - Device Type [e.g. iPhone or iPad]: iPhone

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Could you list all packages installed on your device?

**Comment by baobaoit** [comment]
NoMoreFeedback
ReProvision
CopyLog
Callbar XS (install via Cydia)
Ultrasound
SnapBack
Filza (install via Cydia)
Neptune
CacheClearer
NewTerm 2
Liberty Lite (BETA)

**Comment by PoomSmart** [comment]
Could you also include package ID for each of the package? Example: xyz.willy.zebra

**Comment by baobaoit** [comment]
com.harrywantstodev.nomorefeedback (0.0.1)
com.matchstic.reprovision (0.4.2)
me.tomt000.copylog (1.2)
net.limneos.callbarxs (2.2-5)
me.midnightchips.snapback (2.0.0)
com.tigisoftware.filza (3.6.4)
com.duraidabdul.neptune (1.2)
com.julioverne.cacheearer11 (0.1a)
ws.hashbang.newterm2 (2.1)
com.ryleyangus.libertylite.beta (0.2.12)
