### ISSUE TITLE
Dependencies!

### ISSUE THREAD

**Issue by hwalker10** [wstyres/Zebra#257]
**Describe the bug**
Just a heads up @Midnightchips. When trying to install Newterm2, Zebra does not download the needed dependencies but cydia “searches” for them and downloads them.

**To Reproduce**
Start from a fresh jailbroken state, open zebra and attempt to download NewTerm2. An error pops up regarding dependencies.
However, when attempting to install NewTerm2 on Cydia, Cydia actually looks up and downloads the needed dependencies instead of coming up with an error.

**Expected behavior**
See above.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Latest
 - Device Type [e.g. iPhone or iPad]: iPhone 7 Plus

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Dependencies issue will be combined to #239
