### ISSUE TITLE
Typing one letter into the search bar and then tapping search freezes Zebra for ~10 seconds 

### ISSUE THREAD

**Issue by mattp12** [wstyres/Zebra#261]
Describe the bug:
Typing one letter (this issue doesn't appear to happen with the same severity with numbers or symbols) into the search bar and tapping search freezes the app. It unfreezes after around 10 seconds.

Go to the search tab and type in any single letter and tap search. You'll see the app hang for a bit and then display results.

Expected behavior:
The app to not hang on displaying the results.

Screenshots
N/A (Video below)

Device Information (please complete the following information):
 - iOS Version: 12.2 
 - Zebra Version: Beta 19 
 - Device Type: iPhone 8+ 

Crash Log or System Log:
N/A

Additional context:
[Video displaying the issue](https://www.youtube.com/watch?v=Y7Z5spzvi7s). The tweak ShowTouch is used to help demonstrate that the app is unresponsive. The video also shows how typing a number causes the app to hang slightly, but not nearly as long as a letter.

**Comment by PoomSmart** [comment]
It makes sense seeing this freeze because the query is too short - and why would someone perform a full search with a single letter? We think that not allowing full search for short queries will be the mitigation.

**Comment by mattp12** [comment]
> It makes sense seeing this freeze because the query is too short - and why would someone perform a full search with a single letter? We think that not allowing full search for short queries will be the mitigation.

Thinking about it now, searching by accident for a single letter sounds to me like the only time you would come across this. I mean, that's how I came across it. That mitigation proposal seems good.
