### ISSUE TITLE
The feature introduced in beta 19, "Featured packages now show only not-installed packages" doesn't appear to be working correctly

### ISSUE THREAD

**Issue by mattp12** [wstyres/Zebra#262]
Describe the bug:
The new feature introduced in beta 19, "Featured packages now show only not-installed packages" does not appear to be working.

Enter Zebra and on the home tab. Packages you already have installed may appear at the top (as they did in beta 18).

Expected behavior:
For packages you already have installed to not be shown there, as the feature says.

Screenshots: N/A, video below.

Device Information:
 - iOS Version: 12.2 
 - Zebra Version: Beta 19 
 - Device Type: iPhone 8+ 

Crash Log or System Log
N/A

Additional context:
[Video showing the issue](https://www.youtube.com/watch?v=Gvwl41SvjAk). The tweaks ShortLook and OneNotify are shown on the homepage but I already have them installed.

**Comment by PoomSmart** [comment]
Let us reopen so that others won't report the same issue again, plus the label "scheduled" means the fix will be in the next beta.
