### ISSUE TITLE
Changelog is not being updated

### ISSUE THREAD

**Issue by mmoroni** [wstyres/Zebra#264]
Please, update the changelog on every release.

I can only see the changes up to v15.

Thx.

**Comment by midnightchip** [comment]
Zebra home page -> Changelog. It is always updated.

**Comment by mmoroni** [comment]
if you go to packages, tap on Zebra and then go to changelog, it only shows up to v15.

**Comment by midnightchip** [comment]
This is because that was deprecated in favor of using GitHub releases, which include the changelog. If you’d like to view the changelog you can view it the way I listed above.
