### ISSUE TITLE
Zebra 1.0 beta19 crashes when trying to search for a tweak

### ISSUE THREAD

**Issue by lol7344** [wstyres/Zebra#267]
Device: iPhone 6 @ iOS 12.2 (jailbroken with unc0ver)
After updating Zebra to 1.0 beta19, it crashes when trying to search for a tweak, but I'm able to edit an older search from the history without it crashing.

1. Open Zebra
2. Tap the Search icon
3. Try inputting text into the search textbox

**Screenshots**
Uploaded a video to YouTube showing the problem: https://youtu.be/Lpl99Am4Bhk

**Comment by lol7344** [comment]
problem solved itself after clearing recent searches. Zebra was not generating any crashlog. will report if it happens again.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CornPicker** [comment]
I’m having the same issue and was able to get a crash log. 

Date: 2019-07-28 03:06:45 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSInternalInconsistencyException
Reason: UITableView (<UITableView: 0x1329bf400; frame = (0 0; 414 896); clipsToBounds = YES; autoresize = W+H; tintColor = UIExtendedSRGBColorSpace 1 0.584 0 1; gestureRecognizers = <NSArray: 0x280cd3840>; animations = { bounds.origin=<CABasicAnimation: 0x2803079a0>; bounds.size=<CABasicAnimation: 0x280307a60>; }; layer = <CALayer: 0x28031f4e0>; contentOffset: {0, -99}; contentSize: {414, 1299}; adjustedContentInset: {99, 0, 301, 0}>) failed to obtain a cell from its dataSource (<ZBSearchViewController: 0x131f52da0>)
Culprit: Unknown
Device: iPhone XR, iOS 12.0.1
Call stack:
0   CoreFoundation                      0x00000001a6f93f90 __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001a618c284 objc_exception_throw
2   CoreFoundation                      0x00000001a6ea43b0 +[_CFXNotificationTokenRegistration keyCallbacks]
3   Foundation                          0x00000001a79a330c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4   UIKitCore                           0x00000001d4a89420 -[UITableView _configureCellForDisplay:forIndexPath:]
5   UIKitCore                           0x00000001d4a9b9c0 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:]
6   UIKitCore                           0x00000001d4a9be78 -[UITableView _createPreparedCellForGlobalRow:willDisplay:]
7   UIKitCore                           0x00000001d4a665ec -[UITableView _updateVisibleCellsNow:isRecursive:]
8   UIKitCore                           0x00000001d4a64abc -[UITableView _setNeedsVisibleCellsUpdate:withFrames:]
9   UIKitCore                           0x00000001d4a85e88 -[UITableView _rectChangedWithNewSize:oldSize:]
10  UIKitCore                           0x00000001d4a8658c -[UITableView setBounds:]
11  UIKitCore                           0x00000001d4cab2d4 -[UIScrollView setContentOffset:]
12  UIKitCore                           0x00000001d4a8779c -[UITableView setContentOffset:]
13  UIKitCore                           0x00000001d4cc59d4 _UIScrollViewAdjustForOverlayInsetsChangeIfNecessary
14  UIKitCore                           0x00000001d4cc5c70 -[UIScrollView(UIScrollViewInternal) setSafeAreaInsets:]
15  UIKitCore                           0x00000001d427017c -[UIViewController _updateViewSafeAreaInsetsAndEagerlyUpdateContentScrollView:]
16  UIKitCore                           0x00000001d42708e0 -[UIViewController _setContentOverlayInsets:andLeftMargin:rightMargin:]
17  UIKitCore                           0x00000001d42723d4 __121-[UIViewController __updateContentOverlayInsetsWithOurRect:inBoundsOfAncestorViewController:viaImmediateChildOfAncestor:]_block_invoke
18  UIKitCore                           0x00000001d42721c8 -[UIViewController __updateContentOverlayInsetsWithOurRect:inBoundsOfAncestorViewController:viaImmediateChildOfAncestor:]
19  UIKitCore                           0x00000001d4271368 -[UIViewController _updateContentOverlayInsetsFromParentIfNecessary]
20  UIKitCore                           0x00000001d4270b68 -[UIViewController _updateContentOverlayInsetsForSelfAndChildren]
21  UIKitCore                           0x00000001d41e3704 -[UINavigationController _layoutViewController:]
22  UIKitCore                           0x00000001d41de0c0 -[UINavigationController _layoutTopViewController]
23  UIKitCore                           0x00000001d41d3dc8 __105-[UINavigationController _repositionPaletteWithNavigationBarHidden:duration:shouldUpdateNavigationItems:]_block_invoke
24  UIKitCore                           0x00000001d4d1ec90 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:]
25  UIKitCore                           0x00000001d4d1f290 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:animations:completion:]
26  UIKitCore                           0x00000001d41d3aa8 -[UINavigationController _repositionPaletteWithNavigationBarHidden:duration:shouldUpdateNavigationItems:]
27  UIKitCore                           0x00000001d41d4164 -[UINavigationController _setNavigationBarHidden:edgeIfNotNavigating:duration:]
28  UIKitCore                           0x00000001d48c8ae4 __66-[_UISearchPresentationController presentationTransitionWillBegin]_block_invoke.153
29  UIKitCore                           0x00000001d42aa6c8 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:]
30  UIKitCore                           0x00000001d42a6964 -[_UIViewControllerTransitionContext __runAlongsideAnimations]
31  UIKitCore                           0x00000001d4cf2c88 -[UIViewAnimationState _runAlongsideAnimations]
32  UIKitCore                           0x00000001d4cf17b4 -[UIViewAnimationState pop]
33  UIKitCore                           0x00000001d4ceed90 +[UIViewAnimationState popAnimationState]
34  UIKitCore                           0x00000001d4d1ed18 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:]
35  UIKitCore                           0x00000001d4d1f208 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:]
36  UIKitCore                           0x00000001d48c1840 -[_UISearchControllerInPlaceSearchBarAnimator animateTransition:]
37  UIKitCore                           0x00000001d41a1320 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke
38  UIKitCore                           0x00000001d428a410 __40+[UIViewController _scheduleTransition:]_block_invoke
39  UIKitCore                           0x00000001d4874610 _runAfterCACommitDeferredBlocks
40  UIKitCore                           0x00000001d4861c38 _cleanUpAfterCAFlushAndRunDeferredBlocks
41  UIKitCore                           0x00000001d4892978 _afterCACommitHandler
42  CoreFoundation                      0x00000001a6f1ffe0 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
43  CoreFoundation                      0x00000001a6f1aab8 __CFRunLoopDoObservers
44  CoreFoundation                      0x00000001a6f1b03c __CFRunLoopRun
45  CoreFoundation                      0x00000001a6f1a844 CFRunLoopRunSpecific
46  GraphicsServices                    0x00000001a91c9be8 GSEventRunModal
47  UIKitCore                           0x00000001d486831c UIApplicationMain
48  Zebra                               0x000000010090fb30 Zebra + 129840
49  libdyld.dylib                       0x00000001a69d0020 start
