### ISSUE TITLE
Escaping Unauthorized package message

### ISSUE THREAD

**Issue by rubrdcky** [wstyres/Zebra#28]
There is no way to escape this error message

![IMG_0592](https://user-images.githubusercontent.com/15958822/56863933-9fdd6200-698a-11e9-8a45-d8b0820fd945.PNG)

Attempting to install a paid package through Packix without being logged in will give you this error. You have to close Zebra to escape it.

**Expected behavior**
I would imagine after some delay a button like 'Return to Zebra' would pop up

**Device Information (please complete the following information):**
 - iOS Version 12.1.1
 - Zebra Beta 5
 - iPhone 8

**Comment by wstyres** [comment]
Usually a button does pop up but for these Packix packages it does not, I'll try to find out why.

**Comment by wstyres** [comment]
This has been fixed as of 81c87d6 and will be in the next beta

**Comment by rubrdcky** [comment]
Awesome!
