### ISSUE TITLE
Zebra sometimes crashes when trying to install/update packages

### ISSUE THREAD

**Issue by lol7344** [wstyres/Zebra#280]
**Describe the bug**
Zebra sometimes crashes when pressing the "Update All" button in the packages list (to update already installed packages) or when pressing "Confirm" to install a new package.

**To Reproduce**
1. Open Zebra
2. Try to update/install any package

**Expected behavior**
Zebra should begin the installation process.

**Device Information (please complete the following information):**
 - iOS Version: 12.2
 - Zebra Version: 1.0 beta19
 - Device Type: iPhone 6

**Crash Log or System Log**
https://pastebin.com/XWjvTbPw

**Comment by PoomSmart** [comment]
Inactivity
