### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kelvin1306** [wstyres/Zebra#281]
Zebra bugs

When I try to click on the information, it not work correctly. But I try the same on cydia it working* correctly.. (DEVELOPER) that says Twitter, Github, Contribute using PayPal and also where say (SOURCE INFO) Fouad’s Repo. in the repo of https://apt.fouadraheb.com/. Thanks 🙏 
![54609678-D666-454C-BC4A-BDA59C01B4C0](https://user-images.githubusercontent.com/52043094/61977795-6cc46200-afbd-11e9-9607-917e67095855.jpeg)
![1DB0D7AB-77E4-4E91-89AB-DDAF43B35501](https://user-images.githubusercontent.com/52043094/61977796-6cc46200-afbd-11e9-9498-16afc5254892.jpeg)

**Comment by kelvin1306** [comment]
I don’t know 🤷‍♂️ it only that repo or others.. I will keep contribute to make this apps the best package manager** ever in this community. Thanks

**Comment by midnightchip** [comment]
I got this one, Its probably not finished loading or something, Ill check it out on our end.

**Comment by kelvin1306** [comment]
Ok thanks, but I check already and I refresh all my repo but when I go to that repo of https://apt.fouadraheb.com/ is not working** thanks for aswer my bug. 👏🙏

**Comment by PoomSmart** [comment]
Most likely has nothing to do with Zebra.
