### ISSUE TITLE
Unable to resolve some dependencies 

### ISSUE THREAD

**Issue by wonkieinc** [wstyres/Zebra#283]
**Describe the bug**
Unable to install AudioRecorder XS from Limneos repo

**To Reproduce**
Install AudioRecorder XS from Limneos repo

**Expected behavior**
Package to install successfully 

**Screenshots**
![D544FE0B-7410-46CA-8269-ECEF62BB61CA](https://user-images.githubusercontent.com/7991537/62000731-a6ae7900-b121-11e9-814a-f4419ee65ebb.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta18
 - Device Type [e.g. iPhone or iPad]: iPhone 8

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Please use version 1.0~beta19 - in the future the issues reported from the outdated versions will be invalid.

**Comment by PoomSmart** [comment]
This is already fixed as of beta 19.
