### ISSUE TITLE
Cannot change to Dark Mode

### ISSUE THREAD

**Issue by Watermalia** [wstyres/Zebra#285]
**Describe the bug**
In the settings page, I can change the option for which dark mode is selected. However, the app itself does not change to dark mode.

**To Reproduce**
Change Dark Mode option, nothing happens.

**Expected behavior**
Upon selecting the dark mode option preferred, the app’s style will change to be dark.

**Screenshots**
https://imgur.com/a/vu11P4m

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta19
 - Device Type [e.g. iPhone or iPad]: 
 iPhone SE 
**Crash Log or System Log**

**Additional context**
No other tweaks have been added, I am using unc0ver latest version (3.4.2)

**Comment by midnightchip** [comment]
To toggle the darkmode one, you need to press the moon icon on the top right corner of the home screen
