### ISSUE TITLE
The UI shifted when refreshing sources in Changes Tab

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#286]
**Describe the bug**
The UI shifted up and overlap when refreshing sources in Changes tab. News is disabled.

**To Reproduce**
Drag and release in changes tab for refresh

**Expected behavior**
UI to not overlap

**Screenshots**
https://imgur.com/gallery/EHLdTzZ
-as can be seen, ‘Sunny Dayz’ package is overlapped with ‘Changes’ that is supposedly go back to top. News is disabled.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest, b19
 - Device Type [e.g. iPhone or iPad]: iPhone

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Can no longer reproduce this issue in beta 21
