### ISSUE TITLE
Featured packages are able to appear, even after being told not to. 

### ISSUE THREAD

**Issue by TheRealKeto** [wstyres/Zebra#291]
**Description**
On beta 18, Zebra introduced "Featured Packages". These packages are picked up and are entirely related to sources you have added, such as Chariz, or Dynastic Repo. With the introduction of this idea came a minor bug. The bug consists of these featured tweaks being shown after disabling the "Enable Feature Packages". 

**How to Reproduce (+ additional context)**
The bug is a bit hard to reproduce, and there isn't a constant method of reproducing this issue, so you may have to tinker with launching the app again and again, as well as some functions. 

I initially thought that this bug was caused due to "constant storage". Checking through the "Settings" tab of Zebra, I realized that the toggle was still being off, and even in Preference files, `xyz.willy.Zebra..plist` shows `wantsFeatured` marked as `NO`. 

The best way I managed to reproduce this issue was to: 
- Enable, then disable "Feature Packages" 
- Go to the "Home page, then relaunch the app.
- Pull down from the repo list
- Go back to "Home" and the banners for featured packages should appear. (if not, then scroll down.)

This lead me to conclude that this issue could perhaps be caused by Zebra recollecting sources (such as Chariz) that support featured packages and re-caching that data on `Featured.plist`?

**Device Information**
 iOS Version: 12.1 
 Zebra Version: 1.0~beta19 
 Device Type: iPhone 8

**Comment by wstyres** [comment]
Not able to reproduce this issue anymore on the latest beta. Does it still exist for you?

**Comment by TheRealKeto** [comment]
> Not able to reproduce this issue anymore on the latest beta. Does it still exist for you?

This issue does not occur on the latest beta. Thanks for fixing! :)
