### ISSUE TITLE
[Request] Add URL Scheme to add repos from Safari

### ISSUE THREAD

**Issue by mac-user669** [wstyres/Zebra#299]
**Describe the solution you'd like**
I would like a custom URL Scheme to be able to add repos from Safari. Similar to Sileo and Cydia, which look like this:
`sileo://source/https://mac-user669.github.io/repo`
'cydia://url/https://cydia.saurik.com/api/share#?source=https://mac-user669.github.io/repo'

**Additional context**
zebra://source/https://mac-user669.github.io/repo should add my repo

**Comment by wstyres** [comment]
Take a look at https://github.com/wstyres/Zebra/wiki/Supported-URL-Schemes. These schemes are already implemented in Zebra but if you have something else to add then I am open to adding it.

**Comment by mac-user669** [comment]
Ah, I missed that. That's awesome, thanks!
