### ISSUE TITLE
Updates being doubled upon source refresh

### ISSUE THREAD

**Issue by rubrdcky** [wstyres/Zebra#30]
**Describe the bug**
When there are updates available and sources are refreshed by pulling down in the sources view the amount of updates available doubles. I refreshed sources twice in this manor in the photos below to make sure I wasn't crazy. Initially started with 2 updates

**To Reproduce**

pull down in the sources view to refresh sources while there are updates available.

**Expected behavior**
Number of updates would stay the same, unless there was actually any update submitted in that amount of time.

**Screenshots**

![Zebra from sources](https://user-images.githubusercontent.com/15958822/56997115-ad564000-6b74-11e9-9e56-7a97a7111fc0.PNG)

![Actual Updates](https://user-images.githubusercontent.com/15958822/56997139-be9f4c80-6b74-11e9-92eb-7fe2fefd5319.PNG)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1
 - AUPM Version [e.g. 1.0~beta1 or beta1]: beta 5 
 - Device Type [e.g. iPhone or iPad]: iPhone 8

**Comment by wstyres** [comment]
This update is already fixed in beta 6
