### ISSUE TITLE
Clipboard added url error

### ISSUE THREAD

**Issue by ShunKun** [wstyres/Zebra#302]
**Describe the bug**
Add a URL from the clipboard, causing the program to quit or get stuck

**To Reproduce**
Copy the URL and open the Repos bar to make sure to add

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:     [[beta20]](https://github.com/wstyres/Zebra/commit/71daf77f5a8afe2a5c3e7c7b565adc7e39b90cd7)
 - Device Type [e.g. iPhone or iPad]: iPhone

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by jmd-aKBar** [comment]
From (#303)

Crash Log or System Log
CrashLog Saved at https://pastebin.com/4uY0FsYn

Additional context
After the crash, when you open the Zebra app and refresh sources, the newly added Repo is successfully added and the internal packages are shown properly after the refresh finishes.

(NEW INFO) 
The newly added Repo is only refreshed if you do it after the crash and without adding it again...
