### ISSUE TITLE
When trying to add Bingner's repo or ZodTTD, Zebra automatically adds ModMyI instead

### ISSUE THREAD

**Issue by captinc** [wstyres/Zebra#304]
**Describe the bug**
When trying to add Bingner's repo or ZodTTD, Zebra automatically adds ModMyI instead. This happens when I type in the repo URL and when I add from the community repos. 

**To Reproduce**
1. Tap Bingner's repo or ZodTTD in community repos. Can also be produced by typing in "http://cydia.zodttd.com/repo/cydia/" or "http://apt.thebigboss.org/repofiles/cydia/" to the add repo pop-up

**Expected behavior**
Should add ZodTTD/Bingner properly

**Screenshots**
N/A

**Device Information (please complete the following information):**
 - iOS Version: 12.1.1
 - Zebra Version: 1.0-beta19
 - Device Type: iPhone 6s

**Crash Log or System Log**
N/A

**Additional context**
Happens on unc0ver, unc0ver dark, and Chimera. Also happens when the 2 repos in question are included in the "Add Multiple" screen

**Comment by captinc** [comment]
Beta 20 does fix the issue I described above, but there a few other issues with beta 20: 

1. Adding Bingner's repo now causes a 404 error when I refresh sources. This can be fixed by making it "deb https://apt.bingner.com/ ./" in /var/mobile/Library/Application Support/xyz.willy.Zebra/sources.list (NOT "deb https://apt.bingner.com/ ios/1561.00 main")

2. When I add multiple repos and BigBoss/ZodTTD/ModMyI are included, Zebra only adds BigBoss and ModMyI (and nothing else). However if I do Add Multiple Repos with only BigBoss/ZodTTD/ModMyI, it works. Afterwards, I can do Add Multiple Repos with the rest of my sources and everything will work fine. It would be great if you could condense those 2 steps!

**Comment by PoomSmart** [comment]
@captinc Does beta 20-2 solve your current issues?

**Comment by captinc** [comment]
Bingner's repo is fixed, thanks! Issue #2 is not fixed yet though.

**Comment by Bloodn2** [comment]
Version 20-2 still this bug

**Comment by captinc** [comment]
@Bloodn2 beta20-2 still has which bug? Bingner's repo or BigBoss/ZodTTD/ModMyI?

**Comment by Bloodn2** [comment]
Whit the ZodTTD repo
