### ISSUE TITLE
Can not add sources

### ISSUE THREAD

**Issue by Ic0nic0de** [wstyres/Zebra#307]
**Describe the bug**
Can not add sources, bath or singular, zebra just refreshes big boss and modmyi

**To Reproduce**
Add any random source.. I’ve tried over 20 repos 

**Expected behavior**
Source added

**Screenshots**
N/A

**Device Information (please complete the following information):**
 - iOS Version [12.1]: 12.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0 beta 19
 - Device Type [e.g. iPhone or iPad]: iPhone 6s

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Possibly correlated with #304
