### ISSUE TITLE
Zebra clears queue when one incompatiblity happen

### ISSUE THREAD

**Issue by Dadoum** [wstyres/Zebra#311]
**Describe the bug**
After adding some tweak in the queue, if one tweak have an incompatibility (like a missing dependency), clicking on cancel clears all the queue instead of removing only the problematic tweak.

**Expected behavior**
When a tweak is creating an incompatibility in the queue, when user clicks on cancel, Zebra should only remove the problematic(s) tweak(s) and their deps.

**Device Information (please complete the following information):**
 - iOS Version : iOS 12.4 
 - Zebra Version : 1.0~beta19
 - Device Type : iPhone

**Comment by PoomSmart** [comment]
Addressed in beta 20
