### ISSUE TITLE
Installing tweaks through the “changes” tab not saving the place I had before

### ISSUE THREAD

**Issue by harel013** [wstyres/Zebra#312]
**Describe the bug**
When you scroll through the ”changes” tab for tweaks and then you install one of them and tap continue, and then return to the changes tab it’s take me out of place I’ve been before

**To Reproduce**
Just scroll through the changes tab enough time until it’s will start to scroll more things and then just get into one tweak install it and then go back, you will find your scrolling not in the same place that you found the tweak.

**Expected behavior**
Just want it to stay in the same place that I found the tweak so I can keep scrolling for more and not from almost the beginning 

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0- beta20-2
 - Device Type [e.g. iPhone or iPad]: 
iPhone 6s
**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**
Ty and have a nice day :) sorry for my English

**Comment by PoomSmart** [comment]
This is because the tweak list will be refreshed after package (un/re)installation anyway.
