### ISSUE TITLE
Lagging in search

### ISSUE THREAD

**Issue by Wh0ba** [wstyres/Zebra#313]
**Describe the bug**

Using the search controller when having a lot of packages is so laggy

**To Reproduce**

Get some big repos and try searching

**Expected behavior**

Smooth search 
**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest
 - Device Type [e.g. iPhone or iPad]: iPhone 5s

**Additional context**

Can you add a delay to the search so the search controller will wait a little bit until the user finishes typing to search the database 
This should dramatically increase performance and reduce lag 

Here is a stackoverflow thread about the same behavior 
https://stackoverflow.com/questions/24515294/ios-wait-until-user-finishes-typing-and-then-send-request

**Comment by Wh0ba** [comment]
deb http://akusio.github.io/ ./
deb http://worksbybbs.github.io/ ./
deb https://artikushg.yourepo.com/ ./
deb http://apt.thebigboss.org/repofiles/cydia/ stable main
deb https://ndoizo.ca/ ./
deb http://repo.chariz.io/ ./
deb https://creaturecoding.com/repo/ ./
deb https://DGh0st.github.io/ ./
deb http://repo.dynastic.co/ ./
deb https://fidele007.github.io/ ./
deb https://cydia.ichitaso.com/ ./
deb https://imjustsaying.yourepo.com/ ./
deb https://jpet26.yourepo.com/ ./
deb https://julioverne.github.io/ ./
deb https://cydia.akemi.ai/ ./
deb http://repo.incendo.ws/ ./
deb https://xenpublic.incendo.ws/ ./
deb https://repo.daus.ch/ ./
deb http://mcapollo.github.io/Public/ ./
deb http://apt.modmyi.com/ stable main
deb http://repo.nepeta.me/ ./
deb http://apt.noisyflake.com/ ./
deb https://opa334.github.io/beta/ ./
deb https://opa334.github.io/ ./
deb https://repo.packix.com/ ./
deb https://rpetrich.com/repo/ ./
deb https://shiftcmdk.github.io/repo/ ./
deb http://skitty.xyz/repo/ ./
deb http://wh0ba.github.io/repo/ ./
deb http://xtm3x.github.io/repo/ ./

**Comment by Wh0ba** [comment]
Gif 
https://gph.is/g/4DLeG2v

**Comment by A-Human-Person** [comment]
maybe add an option to disable live search? I have an ipod5 and had zebra on it and didn’t have that issue so it mustve been something from b17-b20

**Comment by wstyres** [comment]
An option to disable live search is provided in beta 21
