### ISSUE TITLE
Big boss not available

### ISSUE THREAD

**Issue by landen327** [wstyres/Zebra#318]
Tried on 2 separate iPhone 7s, import tweaks from Cydia will show big boss in the log, but bigboss doesn’t show up in repos or in the search tab, once I try to reinstall bigboss it says it is already installed

**Comment by wstyres** [comment]
Could you show a screenshot of the log that you're describing?

**Comment by wstyres** [comment]
This issue should be fixed as of 37e02e65fe3f0b4941a4cc5318741efc102556d8 and will be available in the next beta.

**Comment by landen327** [comment]
You’re awesome:) this is The only Fox I needed to make zebra my primary package manager

**Comment by wstyres** [comment]
Fixed in beta 21
