### ISSUE TITLE
install stuck on some tweaks

### ISSUE THREAD

**Issue by Mory5** [wstyres/Zebra#319]
The issue install and re-install stuck and also remove on some tweaks like filza or any large size tweak

ios 12.4
unc0ver 
iphone 7 

![DA1CF350-B25D-4B12-B5DC-05B6021345F9](https://user-images.githubusercontent.com/42302310/64057781-8dc23900-cba1-11e9-8d8d-5ae79d1d886e.png)

**Comment by PoomSmart** [comment]
Closed in favor of #316

**Comment by Mory5** [comment]
hope to be fixed soon bro
