### ISSUE TITLE
Zebra crashes on launch

### ISSUE THREAD

**Issue by ahmadfaridabbas** [wstyres/Zebra#32]
Date: 2019-04-30 21:54:11 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSInvalidArgumentException
Reason: -[ZBDatabaseManager postStatusUpdate:atLevel:]: unrecognized selector sent to instance 0x2810dc6c0
Culprit: Unknown
Device: iPhone 7, iOS 12.1.1
Call stack:
0   CoreFoundation                      0x00000001ed9a4edc __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001ecb75a40 objc_exception_throw
2   CoreFoundation                      0x00000001ed8bdc24 -[NSOrderedSet initWithSet:copyItems:]
3   CoreFoundation                      0x00000001ed9aa4d8 ___forwarding___
4   CoreFoundation                      0x00000001ed9ac48c _CF_forwarding_prep_0
5   Zebra                               0x000000010022b408 Zebra + 62472
6   CFNetwork                           0x00000001ee140f8c __82-[NSURLSession delegate_downloadTask:didFinishDownloadingToURL:completionHandler:]_block_invoke
7   Foundation                          0x00000001ee4348bc __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
8   Foundation                          0x00000001ee33cab8 -[NSBlockOperation main]
9   Foundation                          0x00000001ee33bf8c -[__NSOperationInternal _start:]
10  Foundation                          0x00000001ee436790 __NSOQSchedule_f
11  libdispatch.dylib                   0x00000001ed3dd6c8 _dispatch_call_block_and_release
12  libdispatch.dylib                   0x00000001ed3de484 _dispatch_client_callout
13  libdispatch.dylib                   0x00000001ed38182c _dispatch_continuation_pop$VARIANT$mp
14  libdispatch.dylib                   0x00000001ed380ef4 _dispatch_async_redirect_invoke
15  libdispatch.dylib                   0x00000001ed38da18 _dispatch_root_queue_drain
16  libdispatch.dylib                   0x00000001ed38e2c0 _dispatch_worker_thread2
17  libsystem_pthread.dylib             0x00000001ed5c117c _pthread_wqthread
18  libsystem_pthread.dylib             0x00000001ed5c3cec start_wqthread

**Comment by wstyres** [comment]
Could you download and install this deb? https://www.dropbox.com/s/fbvq5khmr8dbkif/xyz.willy.zebra_1.0~beta6-1%2Bdebug_iphoneos-arm.deb?dl=0 it should fix the issue based on what the crash log says, if it still crashes upload another crash log.

**Comment by ahmadfaridabbas** [comment]
It works now thanks.
