### ISSUE TITLE
3d-touch broken in changes tab

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#321]
**Describe the bug**
When 3d-touching on one of the Reddit links in the changes tab it brings up Zebra's package instead of the Reddit thread.

**To Reproduce**
3d-touch on any of the Reddit links in the changes tab. 

**Expected behavior**
I expected to be brought to Reddit such as I would be if I had just tapped the link instead of 3d-touching.

**Screenshots**

Screen recording is attached.

**Device Information (please complete the following information):**
 - iOS Version : iOS 12.1.1 beta 3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0 ~ beta 20-3
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
N/A

**Additional context**
N/A

Edit: It seems to bring up the package from the top of the changes tab aka the package that was last updated and not the Zebra package. So it is different just about everytime I open the app.

**Comment by worldlydev** [comment]
Screen recording:
https://imgur.com/a/OQYNTMB

**Comment by worldlydev** [comment]
Would also be nice if 3d-touch support would be brought to the featured packages and other menu items such as tweaks and whatnot. That would be a major win in my book. I just love to peek-and-pop 😊
![CA501376-38A5-4B03-AE54-64254FA139D4](https://user-images.githubusercontent.com/51668635/64062887-e5d25d00-cbec-11e9-94fa-69da48feebca.jpeg)
![F89BD9D9-D9AE-469D-B615-5DD79DD3E2DC](https://user-images.githubusercontent.com/51668635/64062888-e66af380-cbec-11e9-8961-b1fc76959e5b.jpeg)

**Comment by mattp12** [comment]
(I literally screen recorded this last night and planned on posting a bug report for this today lol)

**Comment by worldlydev** [comment]
> (I literally screen recorded this last night and planned on posting a bug report for this today lol)

Well I'm glad it wasn't only me who had this issue. 😁

**Comment by wstyres** [comment]
Fixed as of c05f15. The rest of these will likely change with the upcoming redesign

**Comment by wstyres** [comment]
Fixed in beta 21
