### ISSUE TITLE
Add to wishlist broken

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#323]
**Describe the bug**

Add to wishlist is broken. The menu is hidden behind other menu items.

**To Reproduce**

Go to any package and try to add it to wishlist.

**Expected behavior**

I expect the add to wishlist menu item to be present but it seems to be hidden behind the others.

**Screenshots**

Screenshot attached.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1 beta 3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0 ~ beta20-3
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.
N/A
**Additional context**
N/A
![92A73DE9-2BE7-40B7-BA74-D9CB6A4E3B26](https://user-images.githubusercontent.com/51668635/64106537-adf82080-cd78-11e9-8647-682793c3f063.jpeg)

**Comment by MemesDank456** [comment]
I have the same issue and it seems like that bar under the "more by this developer" bar is the add to wish list button. Also, when hitting Modify on an installed tweak, you can add the tweak to the wishlist, but that's pointless because you already have it

**Comment by Invisible40** [comment]
I’m getting the same issue. There used to be an Add to WishList button, but now it’s gone. I can still access my wishlist (with items I added before the bug started) on the home screen.

**Comment by Invisible40** [comment]
MemeDank456, I just noticed the same behavior you have (hit Modify, and the Add to Wish List burton is there). But you can’t Modify the tweak through that method because it has not been installed. I’m on iOS 12.4, latest version of Zebra beta 20-3.

**Comment by wstyres** [comment]
Add to wishlist has not been removed, a bug is just preventing it from showing up on the depiction page. This will be looked into and hopefully fixed for the next beta.

**Comment by wstyres** [comment]
Fixed in beta 21
