### ISSUE TITLE
I can’t add Sources in 12.2 is is show me 404 error page

### ISSUE THREAD

**Issue by hassan5045** [wstyres/Zebra#325]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Which source are you trying to add?

**Comment by hassan5045** [comment]
Im try to adds all cydia sources from community repos but not working

في أربعاء، 4 سبتمبر، 2019 في 6:01 ص، كتب Wilson Styres <
notifications@github.com>:

**Comment by hassan5045** [comment]
في أربعاء، 4 سبتمبر، 2019 في 6:01 ص، كتب Wilson Styres <
notifications@github.com>:

**Comment by wstyres** [comment]
Could you upload a screenshot and share a link to the photo?

**Comment by hassan5045** [comment]
في أربعاء، 4 سبتمبر، 2019 في 6:11 ص، كتب Wilson Styres <
notifications@github.com>:

**Comment by wstyres** [comment]
If you attached the image in the email it did not come through, try uploading the image to Imgur.com and providing a link.

**Comment by hassan5045** [comment]
Here we go
https://imgur.com/gallery/a8vDwTN


في أربعاء، 4 سبتمبر، 2019 في 6:23 ص، كتب Wilson Styres <
notifications@github.com>:

**Comment by wstyres** [comment]
Looks like you are using an older version of Zebra. What version are you running? Have you gotten Zebra from the official repo?

**Comment by hassan5045** [comment]
I use this version
https://imgur.com/gallery/5pfI0ON


في أربعاء، 4 سبتمبر، 2019 في 6:30 ص، كتب Wilson Styres <
notifications@github.com>:

**Comment by wstyres** [comment]
That is an old version. If you add the repo https://xtm3x.github.io/repo/ to Cydia and you should remove the version you have and install the new one from the new repo.

**Comment by hassan5045** [comment]
Oh. my bad I didn’t download from official repo


في أربعاء، 4 سبتمبر، 2019 في 6:33 ص، كتب y hassan <1231919hassan@gmail.com>:

**Comment by hassan5045** [comment]
Thanks bro its work now thank you 🥳

في أربعاء، 4 سبتمبر، 2019 في 6:36 ص، كتب Wilson Styres <
notifications@github.com>:
