### ISSUE TITLE
Cant install in packages

### ISSUE THREAD

**Issue by daffynw** [wstyres/Zebra#328]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Reinstalling "APT" from Cydia is a possible fix

**Comment by Albaraa2002** [comment]
> Reinstalling "APT" from Cydia is a possible fix

didn't work -_-        PLZ help

**Comment by PoomSmart** [comment]
@Albaraa2002 can you provide more details about what did you do and did not work out?

**Comment by PoomSmart** [comment]
Inactivity.

**Comment by teraswag** [comment]
This does not work for me either - I am running Dopamine on an 15.8 iPhone 6s and none of my packages will install anymore.

**Comment by iAdam1n** [comment]
> This does not work for me either - I am running Dopamine on an 15.8 iPhone 6s and none of my packages will install anymore.

We’re aware.
