### ISSUE TITLE
Installed with Zebra. But in Cydia the same tweak with the same version comes up as “Upgrade”. Faced in Neptune for iphone and Toneenabler.

### ISSUE THREAD

**Issue by Zunayedalam** [wstyres/Zebra#329]
![16732FFE-B24A-40AC-A118-4992112DC1BA](https://user-images.githubusercontent.com/53189544/64472747-f05c9b80-d184-11e9-969c-71ffe10059fe.png)
![5D395CD8-5451-4F47-BF89-01CB036C1298](https://user-images.githubusercontent.com/53189544/64472748-f0f53200-d184-11e9-81a4-429ba08115d5.png)

 - iOS Version 12.1.4
 - Zebra Version  1.0\~beta20-3
 - Device Type iPhone 7

**Comment by wstyres** [comment]
I'm not able to reproduce this issue, this could have been a one time issue where the repository was hosting two versions of the same package causing an update loop in Cydia.
