### ISSUE TITLE
Stuck at install screen

### ISSUE THREAD

**Issue by Zunayedalam** [wstyres/Zebra#330]
![8064BBEE-AB00-48A0-8B98-B07E50FA1009](https://user-images.githubusercontent.com/53189544/64472803-c5267c00-d185-11e9-9140-4fc1dc0b04c2.png)

**To Reproduce**
Install many tweaks at once after restoring iPhone

**Expected behavior**
It’s Supposed to show me an option of restarting springboard

**Device Information (please complete the following information):**
 - iOS Version: 12.1.4
 - Zebra Version: 1.0\~beta20-3 
 - Device Type: iPhone 7 

**Additional context**
I think it’s a compatibility issue with Cydia

**Comment by wstyres** [comment]
Fixed in beta 21
