### ISSUE TITLE
The “Processing” text overlaps

### ISSUE THREAD

**Issue by Zunayedalam** [wstyres/Zebra#331]
![5766C971-1B2C-4201-8480-46F1424E1FCF](https://user-images.githubusercontent.com/53189544/64472872-c60bdd80-d186-11e9-8707-3a9d1201e4e2.jpeg)

**Expected behavior**
There is supposed to be distance between the progress bar and the processes. It’s aesthetically imperfect. 

**Device Information (please complete the following information):**
 - iOS Version: 12.1.4 
 - Zebra Version: 1.0\~beta20-3
 - Device Type: iPhone 7

**Comment by wstyres** [comment]
Fixed as of 6dfbe4395e7128f779a434644055c9f20c319fbc

**Comment by wstyres** [comment]
Should be fixed in beta 22
