### ISSUE TITLE
Removing Packages doesn’t work

### ISSUE THREAD

**Issue by roboticess** [wstyres/Zebra#333]
**Describe the bug**
Removing packages doesn’t work.
Stuck on the console for minutes.

**To Reproduce**

**Expected behavior**

**Screenshots**
![364CAD20-B507-4133-9A3D-939B71BD30BD](https://user-images.githubusercontent.com/48863882/64474613-6528d900-d177-11e9-9154-fc5377467a65.jpeg)
![ED64E8DB-23F4-46FF-A77E-F6554850FE44](https://user-images.githubusercontent.com/48863882/64474614-6528d900-d177-11e9-8683-74dcdc34a43d.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0\~beta20-3
 - Device Type [e.g. iPhone or iPad]: iPhone7,2 - iPhone 6

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**
Downloads complete successfully but they don’t install because of this.

**Comment by PoomSmart** [comment]
Possible related to #328
