### ISSUE TITLE
Doesn’t provide “Done” option after importing sources from cydia

### ISSUE THREAD

**Issue by Zunayedalam** [wstyres/Zebra#336]
![B47FA24C-F9D3-4236-B258-1469CF100B8D](https://user-images.githubusercontent.com/53189544/64477966-6bdd3d80-d1c3-11e9-9762-01a8d1de4f2e.png)

**Device Information:**
 - iOS Version: 12.1.4 
 - Zebra Version: 1.0\~beta21 
 - Device Type: iPhone 7

**Comment by wstyres** [comment]
Should be fixed as of ea362a2f
