### ISSUE TITLE
HYI repo cannot be added when it can in Cydia

### ISSUE THREAD

**Issue by Zunayedalam** [wstyres/Zebra#338]
![024D2E24-88A0-4F3C-B32B-AB207956967E](https://user-images.githubusercontent.com/53189544/64477992-c5de0300-d1c3-11e9-94c6-124036329cef.png)
**Device Information:**
 - iOS Version: 12.1.4 
 - Zebra Version: 1.0\~beta21 
 - Device Type: iPhone 7

**Comment by wstyres** [comment]
It is possible that this is an issue on HYI's side and they are simply not supporting Zebra by not allowing its user agent to download the packages. I will look into it more but it could be the case where this is not a problem with Zebra and rather an oversight by the HYI team.

**Comment by rctfan929** [comment]
In Filza, open “hosts” file. See if HYI is listed. If it is delete it and save. You should now be able to add HYI.
