### ISSUE TITLE
Package names in queue are hard to read while in dark mode

### ISSUE THREAD

**Issue by ThunderFlame5926** [wstyres/Zebra#339]
When I queue packages and then go to the queue to check them while using the dark appearance, the package names show up in black, making them really hard to read.
In my opinion if the text was in white, it would be much better.
iOS 12.4(Stable)
iPhone 7
Zebra beta 21
Running the unc0ver jailbreak
![F9AAB76D-1B3D-4E5E-8D37-F06EF0584AE2](https://user-images.githubusercontent.com/39273158/64478359-1d727380-d1b0-11e9-9430-f4a47f5c29d5.png)

**Comment by worldlydev** [comment]
Lol that's weird. It works perfectly fine for me. But who am I to say. I'm experiencing other bugs in the latest beta. 🤷‍♂️🤷‍♂️
![E9449292-BAB5-4628-82EF-A642084897ED](https://user-images.githubusercontent.com/51668635/64478662-a63ae080-d1ab-11e9-8d0b-8e4332fdd521.png)

**Comment by ThunderFlame5926** [comment]
Well we may just have different devices

**Comment by PoomSmart** [comment]
Some tweaks are affecting Zebra?

**Comment by ThunderFlame5926** [comment]
I found out that Carbon dark mode was the reason this happened. Even without enabling the tweak for the specific app.
