### ISSUE TITLE
Swipe action icons/text not visible in sources page

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#341]
**Describe the bug**

The refresh icon/text isn't visible in dark mode on sources page.

**To Reproduce**

Swipe on a repo on sources page.

**Expected behavior**

I expect the icon/text to be readable.

**Screenshots**

Attached in comment.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1 beta 3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
Zebra 1.0~Beta21
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

N/A

**Additional context**

N/A

**Comment by worldlydev** [comment]
The swipe actions are visible in light mode as shown: 
![A0AB2ED6-5C17-4BC2-9B52-D7C5E1B05747](https://user-images.githubusercontent.com/51668635/64478731-e189df00-d1ac-11e9-8070-701572100e1e.jpeg)
In dark mode however the refresh icon/text isn't visible:
![2C606CF4-7140-4BE5-8E02-0853701F624A](https://user-images.githubusercontent.com/51668635/64478740-03836180-d1ad-11e9-9824-4452c88f04ad.jpeg)

**Comment by wstyres** [comment]
This was just an issue with selecting "white tint" and being in dark mode. This is fixed as of 81ac7f9c593aec87299558c4b4c622b586669b15.

**Comment by wstyres** [comment]
Fixed in beta 22
