### ISSUE TITLE
Clear queue not available while in queue

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#342]
**Describe the bug**

The clear queue button isn't available while in the queue.

**To Reproduce**

Queue some packages and go to the queue.

**Expected behavior**

I expect the button to be available.

**Screenshots**

Attached in comment

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0~beta21 
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

N/A

**Additional context**

N/A

**Comment by worldlydev** [comment]
Clear queue button available in packages tab:
![28BD9FB7-B6E5-494F-9CEA-EA4609C6D26E](https://user-images.githubusercontent.com/51668635/64479135-c752ff80-d1b2-11e9-9431-92f22f6584b5.jpeg)
Clear queue button unavailable while in queue:
![F228E70A-BB0D-4041-BA44-9A8659D56C85](https://user-images.githubusercontent.com/51668635/64479140-de91ed00-d1b2-11e9-885e-1dc294fd45f4.jpeg)

**Comment by worldlydev** [comment]
Just want to apologize to Willy and Poom for all the reports. Must make you think I'm crazy 🤣🤣 truth is I love Zebra and have been playing around with it after every update to see what I find. And I have to say it is incredibly stable and the new queue with it's translucent bar and bubbly animation is amazing. I appreciate what you do for the community.

P.S. more reports incoming 😂

**Comment by PoomSmart** [comment]
Their "Clear" are for two different purposes.

"Clear" in Packages page clears the entire queue.

"Clear" in Queue page clears the conflicts as you queue up conflicting packages.

**Comment by worldlydev** [comment]
> Their "Clear" are for two different purposes.
> 
> "Clear" in Packages page clears the entire queue.
> 
> "Clear" in Queue page clears the conflicts as you queue up conflicting packages.

Got it. Still think it's confusing tho.

**Comment by wstyres** [comment]
Closing as it isn't really a "bug" but more of an inconsistency. We are in the process of redesigning Zebra and will take this into account when we get to the Queue.
