### ISSUE TITLE
No dark mode in peek and pop menu

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#343]
**Describe the bug**

Dark mode doesn't seem to apply to the peek and pop menus when 3d touching. This goes for both the news and packages in changes tab, search tab,  and packages in packages tab.

**To Reproduce**

Peek and pop and swipe to get to action menu.

**Expected behavior**

I expect the menu items to be themed appropriately.

**Screenshots**

Attached in comment

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0 ~ beta 21 
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

N/A

**Additional context**

N/A

**Comment by worldlydev** [comment]
Menu in packages tab:
![13823A4E-45B3-4E39-8521-54A662716127](https://user-images.githubusercontent.com/51668635/64479374-9f659b00-d1b6-11e9-9305-d08bcce8bf7a.jpeg)
Menu in changes tab (news):
![B9A165DC-5E84-438C-8774-BB0437370578](https://user-images.githubusercontent.com/51668635/64479425-3e8a9280-d1b7-11e9-98f2-c86c492f2652.jpeg)

Menu in changes tab (packages):
![396BEA09-3F1F-4AC3-BE98-8041F63C8C79](https://user-images.githubusercontent.com/51668635/64479397-f5d2d980-d1b6-11e9-9298-5dcb7c08371f.jpeg)
Menu is search tab:
![97BF07B3-4963-4164-BAA3-63E356DB9CF9](https://user-images.githubusercontent.com/51668635/64479405-071be600-d1b7-11e9-906e-5d9fc95ff460.jpeg)

**Comment by wstyres** [comment]
Fixed in ccadae6bdf588ddfa08c33292b3689891b477263.
