### ISSUE TITLE
Repo bugs after update?

### ISSUE THREAD

**Issue by MustyAslan99** [wstyres/Zebra#346]
I keep getting this error and as everytime I refresh sources it keeps duplicating bigboss and it only happens to bigboss repo.. not sure why bigboss and why it happens..

https://user-images.githubusercontent.com/4683578/64481280-af46a480-d1e1-11e9-81f5-4bcd47448709.png

 - iOS Version: 12.4
 - Zebra Version: Latest Version
 - Device Type: iPhone 10.2

**Comment by wstyres** [comment]
Should be fixed as of 3b2e36ab08e8faea70c7c837abef29f0819a4a53.

**Comment by wstyres** [comment]
Fixed in beta 22
