### ISSUE TITLE
I can’t

### ISSUE THREAD

**Issue by chosvico** [wstyres/Zebra#348]
![AF816F65-2E33-428A-8F48-921A73E059F6](https://user-images.githubusercontent.com/53243793/64482233-ffeedb00-d1aa-11e9-88d6-797d0cd518fa.png)
**Describe a bug*
I can’t install pakages 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version 12.4
 - Zebra Version 1.0~beta21
 - Device Type iPhone 6s Plus 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
#328
