### ISSUE TITLE
[Request] ability to select multiple repos and delete them all at once

### ISSUE THREAD

**Issue by captinc** [wstyres/Zebra#349]
**Is your feature request related to a problem? Please describe.**
When I want to remove multiple repos, it's really slow to go swipe on every repo, tap delete, wait, and do it all over again. This gets quite ugly with 30-50+ repos

**Describe the solution you'd like**
It would be amazing if we could tap the "Edit" button, select multiple repos, tap "Done", and then be prompted to remove said repos

**Describe alternatives you've considered**
Not really sure how else to implement this. 

**Additional context**
Occasionally I temporarily remove all of my repos for testing purposes. Idk, I feel like this feature can't go wrong.

**Comment by worldlydev** [comment]
Would love this as well. Perhaps use the the apple music-like navigation bar used for the queue that brings up a selection mode similar to photos? And selection could use the same circles as photos? 
![DC244B4D-E13E-4A9F-BEBF-EF2F3F7476B7](https://user-images.githubusercontent.com/51668635/64486064-c52b8800-d228-11e9-9d27-767341112a6f.jpeg)

**Comment by wstyres** [comment]
We'll take a look and see what we can come up with when we're making the redesign for Sources

**Comment by wstyres** [comment]
Implemented in Zebra as of 149cdd3. This will be available in the upcoming redesign.
