### ISSUE TITLE
Import Sileo Sources

### ISSUE THREAD

**Issue by ZenIsBestWolf** [wstyres/Zebra#35]
**Is your feature request related to a problem? Please describe.**
It's a little tedious to reenter all my Sileo repos.
**Describe the solution you'd like**
A button to import Sileo repos like Cydia.
**Describe alternatives you've considered**
???
**Additional context**

**Comment by wstyres** [comment]
I'll look into adding this and keep you updated

**Comment by wstyres** [comment]
Implemented in Zebra 1.0~beta9
