### ISSUE TITLE
Doesn't add BigBoss/ZodTTD/ModMyI

### ISSUE THREAD

**Issue by captinc** [wstyres/Zebra#350]
**Describe the bug**
When trying to add BigBoss, ZodTTD, or ModMyI in any of the following ways, said repos do not actually get added

1. Add from Community Repos
2. Type in a single repo URL into the Add Repo dialog
3. Adding any/all of these 3 repos in "Add Multiple" when there are NO OTHER repos. 

**To Reproduce**
Try adding BigBoss/ZodTTD/ModMyI from Community Repos, by typing in a single URL to the Add Repo dialog, or add any/all of these 3 repos via Add Multiple. If doing Add Multiple, do not have any other third-party repos

**Expected behavior**
These repos should be added properly

**Screenshots**
N/A

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: 1.0-beta21
 - Device Type: iPhone 6s

**Crash Log or System Log**
N/A

**Additional context**
Remember: if you try to add these 3 repos via Add Multiple, do NOT type any other repos into the text box. For some reason, adding a third-party repo in addition to the 3 repos in question makes everything work properly.

**Comment by wstyres** [comment]
Should be fixed as of 76661299e7d95eea65a9d27f1b484105afcd2102

**Comment by wstyres** [comment]
Fixed in beta 22

**Comment by OCBiggiE** [comment]
I'm having the same issue right now and totally bummed
