### ISSUE TITLE
Can’t Install Paid Tweaks (Tried with Dynastic repo)

### ISSUE THREAD

**Issue by NickKrahn** [wstyres/Zebra#351]
**Describe the bug**
When trying to install a tweak from Dynastic repo (maybe other repos will have this issue too) “Downloading TweakName, Done TweakName, Nothing has been downloaded, Done!” is the message I get. I am signed into my Dynastic account and it says that I own the package, but it shows that message and doesn’t install.

**To Reproduce**
-Go to any owned tweak in Dynastic repo
-Sign into account
- Tap “Install”
-Error message shows

**Expected behavior**
I expected it to download and install normally like any other tweak.

**Screenshots**
![F86A39DF-CCBE-4743-BAFB-920E65D76276](https://user-images.githubusercontent.com/47406347/64482950-2703d780-d1c0-11e9-8f8f-4d618937cf6d.png)

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: 1.0~beta21  
 - Device Type: iPhone 7 Plus

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Fixed as of b675cc6d79dfdde70cfb61431985001d36012b0b

**Comment by wstyres** [comment]
Fixed in beta 22

**Comment by NickKrahn** [comment]
Awesome, thanks
