### ISSUE TITLE
New placeholder image for featured banners that don't appear

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#354]
**Is your feature request related to a problem? Please describe.**

No 

**Describe the solution you'd like**

A new featured banner that is more high res and perhaps even an entirely new photo as the current one is incredibly ugly.

![86335307-E356-4BC6-A2C4-BDFB9A3EF591](https://user-images.githubusercontent.com/51668635/64501252-e2139a00-d2c0-11e9-8305-2ff1676c662b.jpeg)

**Describe alternatives you've considered**

N/A

**Additional context**

I'm talking about the placeholder image that shows up when there is no featured banner for a featured package.

**Comment by wstyres** [comment]
Closing this issue as it has already been addressed with the redesign
