### ISSUE TITLE
APT Not Installed, Zebra beta22

### ISSUE THREAD

**Issue by CybrNight** [wstyres/Zebra#356]
**Describe the bug**
When installing Zebra beta22, an error shows up that APT is not installed, yet installing packages in Cydia works.

**To Reproduce**
 When using the latest APT install Zebra update from Cydia. Zebra will not install the update. After reopening Zebra, the error message will show up.
**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**
Tweak List: https://pastebin.com/jCBhrGy7

**Comment by wstyres** [comment]
Could you provide a list of packages that you have installed on your device?

**Comment by CybrNight** [comment]
Tweak list: https://pastebin.com/jCBhrGy7

**Comment by Albaraa2002** [comment]
How to reinstall "APT" I have packages "apt 7 "
and I reinstall it but nothing happens

**Comment by wstyres** [comment]
I've reimplemented basic `dpkg` support for devices without the ability to upgrade to the latest version of APT. This should resolve the problem.
