### ISSUE TITLE
Black, unreadable text with OLED mode in Zebra

### ISSUE THREAD

**Issue by Aditya245850** [wstyres/Zebra#357]
First a side note: Damn tho, I never expected Zebra to BE THIS GOOD. It's super-fast, user-friendly and DAMN STABLE MY GOD. SIMPLY AMAZING! Please continue to do the amazing work you guys do and thank you for your work!

THE ACTUAL BUG: Lol, ok so the bug is pretty simple. When you are on OLED mode on zebra on iPhone X(IDK about other devices), the text when you tap on a source is unreadable. Also when you are queuing up packages, the text is also unreadable.

![IMG_6549](https://user-images.githubusercontent.com/55038679/64573726-38b0c080-d321-11e9-8c0e-094edcb7c551.PNG)(I showed the delete button to show there is actually a tweak I'm trying to download)

![IMG_6548](https://user-images.githubusercontent.com/55038679/64573728-3ea6a180-d321-11e9-921e-5a1b61e3433b.PNG)

 - iOS Version [12.4]: 
 - Zebra Version [beta 22]: 
 - Device Type [iPhone X(10,3)]:

**Comment by PoomSmart** [comment]
Possibly tweak issues.
