### ISSUE TITLE
3D touch freeze issue

### ISSUE THREAD

**Issue by whiteblacksmiths** [wstyres/Zebra#358]
Zebra freezes when 3D touch is invoked, doesn't crash the app, but would have to kill Zebra from the appswitcher and reopen it.

To Reproduce: 3D touch on any package

Device Information:
 - iOS Version: 12.4
 - Zebra Version: beta 22-1
 - Device: iP6S

**Comment by wstyres** [comment]
Not able to reproduce this issue as of the latest beta.
