### ISSUE TITLE
Export list(s) of sources and/or tweaks (like Flame for Cydia)

### ISSUE THREAD

**Issue by TimeDiver0** [wstyres/Zebra#36]
**Is your feature request related to a problem? Please describe.**
Not applicable.

**Describe the solution you'd like**
Just like Flame does for Cydia, having an exported list of sources and tweaks can be a BIG time-saver, if something goes horribly wrong and mandates Restore RootFS.

**Describe alternatives you've considered**
Aside from keeping Cydia and Flame around permanently? Nothing comes to mind.

**Additional context**
Somewhat related; Flame had a time-out option for repos that took too long to respond; doesn't seem to work as of iOS 12. Would appreciate some research into this sort of option.

**Comment by wstyres** [comment]
There will be a way to import/export sources in the future in bulk

**Comment by wstyres** [comment]
Exporting sources/packages was implemented by @JAKESNAKE523 in PR #40. I'm going to work on a way to implement #29 so that we can import and export easily.

**Comment by wstyres** [comment]
Implemented in Zebra 1.0~beta9
