### ISSUE TITLE
upgrade button not showing

### ISSUE THREAD

**Issue by heath-toby** [wstyres/Zebra#361]
Hello, I am having a strange issue with Zebra where I do not see upgrades. I see them in Cydia if I have one available, but even though the repo is added the upgraderefuses to show. iOS version: 12.4. Zebra version: The latest available, I forget which one. Thanks in advance if you can fix this, it's a great packagemanager and would be my daily driver if it weren't for that bug.

**Comment by wstyres** [comment]
Could you give us a list of what repos you have and some screenshots of the Cydia upgrades? It would help us identify which packages have the issues.

**Comment by wstyres** [comment]
Closed due to inactivity.
