### ISSUE TITLE
During package installation 

### ISSUE THREAD

**Issue by Sufyanpahore** [wstyres/Zebra#362]
I like this package manager app
But a minor bug

          After installing a package when I press Restart springboard, it didn’t respring and goes back to home screen.Also have so other minor bugs.
Please ignore my bad English, Thanks! 
Have a good day.

**Comment by wstyres** [comment]
We will look into it. Which device, iOS version, and jailbreak are you on?

**Comment by wstyres** [comment]
We will look into it. Which device, iOS version, and jailbreak are you on?
