### ISSUE TITLE
Trouble loading sources

### ISSUE THREAD

**Issue by rctfan929** [wstyres/Zebra#370]
After having Zebra closed for an extended period of time I get the warning in the screenshot.

**To Reproduce**
1. Open Zebra
2. Close Zebra
3. Wait long enough that sources have to refresh when you open again
4. Open again

I expect sources to load without issues. 

[Screenshot](http://www.imagebam.com/image/2bd8b91319953824) 

**Device Information
 - iOS Version :  12.4
 - Zebra Version : beta22-1
 - Device Type : iPhone 6s

**Comment by wstyres** [comment]
Is this bug reproducible? How long do you have to wait? Does Zebra behave normally after you dismiss this error and refresh sources again?

**Comment by rctfan929** [comment]
This is not happening since updating to beta23-1.
