### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by neumaif02** [wstyres/Zebra#371]
**Describe the bug**
If I install Lotus, it will remove SnowBoard and replace it with iThemer.

**To Reproduce**
Install Lotus while SnowBoard is installed. It will replace it with iThemer

**Expected behavior**
It should install, but not install iThemer

**Screenshots**
Might add tomorrow

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest
 - Device Type [e.g. iPhone or iPad]: iPhone

**Comment by A-Humann** [comment]
this is probably a lotus issue/snowboard issue, I can make a dummy package for ithemer if you want, I just need to know the bundleid for it.

should be com.someonesname.ithemer or similar

**Comment by neumaif02** [comment]
It works in Cydia, tho.

HumanTM <notifications@github.com> schrieb am Sa., 28. Sep. 2019, 05:53:

**Comment by neumaif02** [comment]
net.dodtweaks.ithemer

**Comment by A-Humann** [comment]
thanks, will make that later for you

**Comment by wstyres** [comment]
From my testing it appears that the issue has been resolved as of 40f0eeb. If Snowboard is installed, iThemer will no longer replace it. I will do more testing and hopefully include the fix in the next beta of Zebra.

**Comment by wstyres** [comment]
This was not resolved as of the recent beta, the changes have yet to be merged.
