### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by busadoki** [wstyres/Zebra#372]
**Describe the bug**
I don’t have an issue, but I just want to add Arabic language to your beautiful package manager.

You can contact me at my Twitter account 
https://twitter.com/busadoki

**Comment by wstyres** [comment]
Thanks for you request, Zebra is not quite ready for translation features but we are working on it. You can use #166 to track our progress and we will be sure to let everyone know once we need people to translate. Thanks!

**Comment by busadoki** [comment]
Thanks 🙏
