### ISSUE TITLE
More section icons

### ISSUE THREAD

**Issue by Exp0rt** [wstyres/Zebra#376]
Sections not works all like Dictionaries shows white picture no image.

**Comment by wstyres** [comment]
Could you provide some more information about the issue you are experiencing?

**Comment by jailbre3k** [comment]
Dictionaries Sections in Zebra shows white icon but in Cydia works well (blue book icon)[https://imgur.com/gallery/t7fT4Qv](url)

**Comment by jailbre3k** [comment]
[Dictionaries](https://imgur.com/gallery/t7fT4Qv) Sections in Zebra shows white icon but in Cydia works well (blue book icon)

**Comment by wstyres** [comment]
It looks like these sections do not have an icon in Zebra. We will look into more missing icons and add them in a future update.

**Comment by relisiuol** [comment]
Missing sections (I think)

- Books
- Carrier Bundles
- Dictionaries
- Education
- Games
- Health and Fitness
- Java
- Keyboards
- Messaging
- Navigation
- Productivity
- Repositories
- Ringtones
- Scripting
- Site-Specific Apps
- Social
- Text Editors
- Wallpaper
- Widgets
- X Window

**Comment by wstyres** [comment]
The ability to add more section icons was added in 1.0.1. More section icons are being added soon though.

**Comment by aabosh** [comment]
Sorry for the long wait... Commit ece95f35 adds 21 new icons. Will be available in the next beta.
