### ISSUE TITLE
The internet connection appears to be offline

### ISSUE THREAD

**Issue by abigchopstick** [wstyres/Zebra#379]
Running iOS 12.4 on an iPhone XR, JB via Unc0ver and installed zebra using Cydia from zebra official source.

At first I installed beta22 and when the app first run it says "The internet connection appears to be offline", but I just download and installed Zebra from Cydia. Thought it might be Wifi so I switched to 4G and it still does the same thing.

Then I tried downgrade the app to lower version, beta21, beta18, nothing works, all the same error...so what could be wrong?

I suspect this could be related to the internet switch on settings app but Zebra is not on the list so I don't know how to turn it on or off, and it would be weird the default behavior is off.

**Comment by wstyres** [comment]
This could be due to a strange backgrounding issue when exiting Zebra while refreshing sources. I will see if I can do some more testing and attempt to resolve the issue but in the meantime, let me know if the issue resolves itself.

**Comment by abigchopstick** [comment]
I figure out wha the issue was.

I am using a China version of the iPhone, and due to Chinese regulations,
iOS default its behavior of all newly install APP to gain no access to
internet until it was permitted.

Normally all Apps installed via APPSTORE has to get permission from a
prompt or manually turn on in the settings app to gain access, but Zebra
isn't installed in a "normal" way so it doesn't have this prompt nor was
there anything in the settings app to turn on/off the access for Zebra.

It's an iPhone version related bug, so perhaps if you could consider this
in the future releases it would be nice.

**Comment by arslan2012** [comment]
@abigchopstick I'm facing the same issue how did you get around it?

**Comment by abigchopstick** [comment]
try resetting network settings.

**Comment by wstyres** [comment]
If anyone else experiences this issue I'd recommend taking a look at this issue on the unc0ver GitHub https://github.com/pwn20wndstuff/Undecimus/issues/136.
