### ISSUE TITLE
Some packages can't be installed

### ISSUE THREAD

**Issue by m00vie** [wstyres/Zebra#382]
When i tried to install Carbridge some rows of prices was yellow, there were said libswift4 doesn't works, so carbridge was installed but it didn't work. 
Next i tried to reinstall it in Cydia - all rows are white, but same effect - carbridge not working. 
Next i tried to reinstall libswift4 in Zebra - installation process was done, but carbridge still dead.
Next i try to reinstall carbridge - still yellow rows about libswift4, and still dead carbridge. 
Next i reinstall libswift4 in Cydia - and now it was successful, carbridge become alive.

So looks like Zebra couldn't reinstall libswift4. As i see - it's kinda bug maybe.

Thnx)

**Comment by wstyres** [comment]
It doesn't look like CarBridge requires or is related to libswift4 at all so this could have been completely unrelated.
