### ISSUE TITLE
[BUG] Zebra wont start

### ISSUE THREAD

**Issue by reloxx13** [wstyres/Zebra#383]
**Describe the bug**
Heya,
if i open up Zebra on my ipad, it will open but not "start". Its like its freezing when loading the featured packages. Its not showing the animated icon of loading sources and its completly unresponsive.
Sometimes after serveral (feels like hundrets) tries of opening/closing zebra and waiting some time the featured packages appear an its responsive again.
Tried with wifi and 3g data connection.

Tried to reinstall it with cydia, did not help.

I dont know how to explain it better or what could help you to determine the bug.
I also could not find something about it on reddit or in the issues here which could relate to this problem.

**To Reproduce**
Just open Zebra.

**Expected behavior**
Being responsive

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4 (unc0ver jb)
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta22-1
 - Device Type [e.g. iPhone or iPad]:  iPad4,8 (mini3)

**Crash Log or System Log**
Not available

**Additional context**
iPhone SE (father) has the same problem.
On my iPhone 5S its loading fine.

**Comment by wstyres** [comment]
Does this issue still happen on beta 24?

**Comment by reloxx13** [comment]
heya,

nope, its still freezing.

i got it with many luck disabled in settings, now i enabed it again, first random featured this worked.
then i switched to featured repos and now it freezes again.

trying to disable it again now...
tested on ipad mini (4,8, ios12.4, beta25-1)

**Comment by wstyres** [comment]
So this only happens with Featured Repos on?

**Comment by reloxx13** [comment]
yes, i got it disabled again and now its working fine without featured repos

**Comment by wstyres** [comment]
Could I see a list of repos so I can try to reproduce this myself?

**Comment by reloxx13** [comment]
long list, but same list on my old 5S is working fine with featured banners.

[sources.zip](https://github.com/wstyres/Zebra/files/3827464/sources.zip)

**Comment by wstyres** [comment]
Thank you, I'll look into the issue. Do you have any of them blacklisted?

**Comment by wstyres** [comment]
And just to confirm, the "Random" option in featured is on? Like so? 
![Simulator Screen Shot - iPhone 11 - 2019-11-09 at 14 49 16](https://user-images.githubusercontent.com/19736790/68534246-20005f00-0300-11ea-94b6-c24f6ddbe603.png)

**Comment by reloxx13** [comment]
random did work after re-enablung. repo featured did freeze

**Comment by reloxx13** [comment]
nope, nothing backlisted.

**Comment by wstyres** [comment]
I encountered Zebra freezing when toggling the "Featured Packages" back on after it had been set to random packages. I fixed the issue in 4d4d2310e1dbf4cc96057a442cdd4fb1eef9ee65. If the issue still occurs, see if it is fixed in the next beta.
