### ISSUE TITLE
Removing tweaks 

### ISSUE THREAD

**Issue by joiiesade** [wstyres/Zebra#384]
Removing tweaks. 
Can not remove tweaks in a bulk. Will he stuck on removing tweaks in which I have to use cydia to bulk delete them. 
I am using uncover Jailbreak iOS 12.4 iPhone X. 
![BEA99762-D929-406A-B30F-AC07FDAFD3B5](https://user-images.githubusercontent.com/56368768/66519670-5f435200-eaad-11e9-8e25-aca11b672405.png)

**Comment by wstyres** [comment]
I'm not able to confirm that this issue is fixed but when the next beta comes out give this a try again and see if it still occurs. A list of packages that you are trying to remove would also be helpful.
