### ISSUE TITLE
Cancel button after refreshing sources doesn't go away

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#389]
**Describe the bug**

After refreshing the sources the cancel refresh button won't go away. It can seems to affect the sources, changes, and packages tab. It doesn't always happen and when it does it can affect any of the three tabs. It is very random.

**To Reproduce**

Refresh sources

**Expected behavior**

I expect it to go back to the way it is before the refresh. Aka without a cancel button and with the icons that are supposed to be there.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0~Beta 23-1 
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

N/A

**Additional context**

Already digging the new cancel button. Hopefully this slight issue will be fixed 😊

**Comment by worldlydev** [comment]
https://imgur.com/gallery/MU7WYSy

The left side is the side with the issue while on the right shows it functioning properly.

More info: it seems to happen more often after one of the repo refreshes times out.

**Comment by PoomSmart** [comment]
I suspect that I fixed this issue.. let's see when the next update comes.
