### ISSUE TITLE
Not respecting repo http protocol when fetching icons

### ISSUE THREAD

**Issue by CreatureSurvive** [wstyres/Zebra#39]
**Describe the bug**
Repo icon fetching is done via http always rather than respecting the protocol for the repo e.g
- http://creaturecoding.com/repo/CydiaIcon.png
vs
- https://creaturecoding.com/repo/CydiaIcon.png

**To Reproduce**
N/A

**Expected behavior**
Use the http protocol defined by the repo url

**Screenshots**
N/A

**Device Information (please complete the following information):**
 - iOS Version [12.1.2]: 
 - AUPM Version [1.0~beta8]: 
 - Device Type [iPhoneX]: 

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by wstyres** [comment]
Should be fixed as of 10ed2a5
