### ISSUE TITLE
Nav bar sometimes cuts off tableview at the top

### ISSUE THREAD

**Issue by rweichler** [wstyres/Zebra#390]
**Repro steps**

I can't consistently repro. Happened to me three times. Seems like a race condition.

1. Fresh launch of the app
2. Possibly background the app, and bring it to the foreground?
3. Open a tab bar page for the first time.

**Expected behavior**
Tableview isn't cut off by the top nav bar.

**Actual behavior**
Tableview sometimes gets cut off by the top nav bar, and you can't scroll up.. I think the `frame.origin.y` gets set to 0 instead of the height of the nav bar, somehow:

<img width="200" src="https://user-images.githubusercontent.com/1661613/67151897-cddc9880-f281-11e9-86a0-6074b97231d1.png">

**Device Information (please complete the following information):**
- iOS 11.1.2, iPhone SE, Electra, Zebra 1.0~beta23-1

**Comment by wstyres** [comment]
Can reproduce on iOS 10, reopening issue.

**Comment by wstyres** [comment]
Can no longer reproduce on iOS 10 as of eb48e90afea51f5146b6e36c30a886943f43fd06.
