### ISSUE TITLE
Improved Package export

### ISSUE THREAD

**Issue by pepoboy** [wstyres/Zebra#403]
Hi! My english is not very good loooking ;) but I'll do my best.

Great great job! I was missing Cydia (it's usefull to change the version of a tweak), but now Zebra is all that I wanted.

It would be great if Zebra could save the list of tweaks WHIT the version of each one, and the list of repositories...
And maybe it's out of your objectives, but it would be great if Zebra could have something like "CyDown" included :) to download and save debs, etc ;)

Thank you very much for your job!!!

Peter.

Device Information:
iOS Version: 12.4
Zebra Version: 1.0~beta23
Device Type: iPhone 7

**Comment by worldlydev** [comment]
I would love this but feel pretty confident in saying that this probably won't be integrated into Zebra do to piracy concerns. Maybe reach out to https://mobile.twitter.com/ijulioverne and ask if he could make an alternative to his tweak that functions with Zebra.

**Comment by pepoboy** [comment]
Thank you very much for your job and your answer!! Good luck!! :D

**Comment by MTACS** [comment]
Do you mean add the version number next to each tweak, or save the deb of the version?

**Comment by worldlydev** [comment]
> Do you mean add the version number next to each tweak, or save the deb of the version?

Pretty sure he's asking for a method to save debs. He asks for a built in cydown alternative to save debs so.

**Comment by wstyres** [comment]
Downloading debs themselves will not be implemented as it can be used for piracy. We can look into a more detailed tweak export list that will import all repos/packages with correct versions so that transitioning between jailbreaks is easier.

**Comment by pepoboy** [comment]
@wstyres thank you very much x the answer, and for the constant update of Zebra! Bye!!

**Comment by PoomSmart** [comment]
Implemented at some point in the past.
