### ISSUE TITLE
[Localize] Zebra Norwegian Bokmål Support

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#409]
**What language are you adding?**

Norwegian Bokmål

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**

[nb.lproj.txt](https://github.com/wstyres/Zebra/files/3773280/nb.lproj.txt)

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**

WorldlyDev

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**

Twitter https://twitter.com/WorldlyDev

**Comment by wstyres** [comment]
Thanks! Support added in a9f1ae11aa38cd708d8bc0b7d5af55448ec07250 but I'm going to leave the issue open so that I remember to credit you when I complete #223.

**Comment by rweichler** [comment]
NICE 
<img width="200" src="https://user-images.githubusercontent.com/1661613/67596161-f4d11980-f71c-11e9-8b48-df3ae5d0bd6d.png">

**Comment by worldlydev** [comment]
> NICE
> <img alt="" width="200" src="https://user-images.githubusercontent.com/1661613/67596161-f4d11980-f71c-11e9-8b48-df3ae5d0bd6d.png">

Lol it looks broken. Will it look like that when released? Those weird (A)s are supposed to be (Å)s. And the small (..) and(y..) are supposed to be (Ø)s.

**Comment by wstyres** [comment]
It looks like there were some issues with encoding when you submitted the file as a .txt try uploading as a .strings file instead.

**Comment by worldlydev** [comment]
> 
> 
> It looks like there were some issues with encoding when you submitted the file as a .txt try uploading as a .strings file instead.


https://gofile.io/?c=9oyMMP

**Comment by wstyres** [comment]
Looks like that file has the same issue. Is it possible that your text editor is not properly saving the characters? There are other words that look odd and have a `¯` in them, not sure if this is intended or not.

**Comment by worldlydev** [comment]
> 
> 
> Looks like that file has the same issue. Is it possible that your text editor is not properly saving the characters? There are other words that look odd and have a `¯` in them, not sure if this is intended or not.

Check #410

**Comment by wstyres** [comment]
That seems to have fixed it 
![Simulator Screen Shot - iPhone 11 - 2019-10-25 at 15 36 33](https://user-images.githubusercontent.com/19736790/67599110-41c4e800-f73d-11e9-9441-302ae975b4d5.png)
