### ISSUE TITLE
Clicking all packages on sbingner’s repo causes a crash

### ISSUE THREAD

**Issue by PlanetAaron** [wstyres/Zebra#41]
**To Reproduce**
Add http://repo.bingner.com to zebra and browse it. Select all packages and it should crash.

**Expected behavior**
Being able to browse normally 

Device: iPhone XR
Firmware: 12.1.1b3
Jailbreak: Chimera 

Crash log: [https://pastebin.com/BfmKmW4j](https://pastebin.com/BfmKmW4j)

**Comment by wstyres** [comment]
Looks like the same issue as #38, I'll add that to the list of broken repos
