### ISSUE TITLE
[Localize] French Translation for Zebra

### ISSUE THREAD

**Issue by Far0pe7** [wstyres/Zebra#411]
**What language are you adding?**
French

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**
https://github.com/Far0pe7/FrenchZebraTranslation/blob/master/Localizable.strings

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**
No. Probably will.

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
Far0pe7

**Comment by wstyres** [comment]
Let me know if you ever join the Discord and I'll give you the role.
