### ISSUE TITLE
[Localize] German Translation

### ISSUE THREAD

**Issue by MartinsZar** [wstyres/Zebra#418]
**What language are you adding?**
German

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**
https://github.com/MartinsZar/Zebra-Translation-DE/blob/master/Localizable.strings

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**
MartinsZar#1533

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
MartinsZar (Twitter: https://twitter.com/ZarMartins)

**Comment by wstyres** [comment]
Thanks! German translation is already available [here](https://github.com/wstyres/Zebra/blob/master/Zebra/de.lproj/Localizable.strings). If you want to correct some of the strings, that is fine with me. I'll add you as a translator to the Discord though in case we need any future translations.

**Comment by MartinsZar** [comment]
Oh, didn't realize that. XD
The already included file looks good, so no corrections from my site.
But this isn't my only translation, I'll add one tomorrow ,so no problems with the Discord thing.
