### ISSUE TITLE
[Localize] Brazilian Translation

### ISSUE THREAD

**Issue by gladsonloureto** [wstyres/Zebra#419]
**What language are you adding?**
Português Brasil (pt-br)

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**

https://www.dropbox.com/s/kqzb5por2l4o2lm/localizable.strings?dl=0

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**

Sim. Gladson_Loureto

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**

Gladson_Loureto

**Comment by wstyres** [comment]
Looks like your .strings file is malformed after I downloaded it. Could you try to reupload and double check to make sure it is formatted correctly? 
<img width="912" alt="Screen Shot 2019-10-25 at 8 04 42 PM" src="https://user-images.githubusercontent.com/19736790/67610751-d130c200-f762-11e9-9407-881f7119ffe3.png">

Also, I wasn't able to find your username on the Discord. Are you sure that is it? Is there a website or a twitter that you'd like me to link for your credit?

**Comment by gladsonloureto** [comment]
Sorry...

https://www.dropbox.com/s/ohbe7rtgkkm53vl/Localizable-2.strings?dl=0

twitter.com/gladson_loureto

**Comment by wstyres** [comment]
Looks like your strings file is still malformed. I implemented another Brazilian translation from #424 but I will still add you to the credits for translating.

**Comment by gladsonloureto** [comment]
Sorry to bother you, I am learning to use Xcode and did the translation of
zebra to pt and my Xcode appears all normal, if not asking you too much and
disturb you could analyze the code? Don't even need to add to Zebra just to
give me that strength.

Thanks...

Em sáb, 26 de out de 2019 às 00:22, Wilson Styres <notifications@github.com>
escreveu:
