### ISSUE TITLE
Certain updates not showing up

### ISSUE THREAD

**Issue by rubrdcky** [wstyres/Zebra#42]
**Describe the bug**
It seems as though certain tweaks don't show up as updates in Zebra but they do in Cydia. See screenshots below. 'LetMeBlock' shows as an update in both apps but 'Gesto' does not. I thought maybe it was because I wasn't signed in to the Chariz repo through Zebra so I tried that but the website that the link directs to doesn't load. I did update sources several times to make sure that wasn't the issue.

On a somewhat related note Gesto shows up twice as a search result (seen in the third screenshot), no idea why.

**Screenshots**
![IMG_0680](https://user-images.githubusercontent.com/15958822/57292338-7fe72600-708f-11e9-982c-d99672cb0785.PNG)
![IMG_0679](https://user-images.githubusercontent.com/15958822/57292345-82e21680-708f-11e9-9dfc-1c695678eabc.PNG)
![IMG_0681](https://user-images.githubusercontent.com/15958822/57292361-8ecdd880-708f-11e9-94a3-3763acbe44f9.PNG)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1
 - AUPM Version [e.g. 1.0~beta1 or beta1]: Zebra Beta 8 
 - Device Type [e.g. iPhone or iPad]: iPhone 8

**Comment by JAKESNAKE523** [comment]
If you have a pirate repo added that might could explain the duplicate search results. I'm not accusing you of having one, and I don't care honestly, but if you do that could help narrow down the problem. Sorry if this seems accusatory, just trying to help. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rubrdcky** [comment]
It's a totally valid thing to bring up, I can assure you that I do not have any pirate repos added. Below is a copy of my sources.list from Zebra.

deb http://apt.saurik.com/beta/substrate11/ ./ 
deb http://artikushg.github.io/ ./ 
deb http://apt.thebigboss.org/repofiles/cydia/ stable main 
deb http://apt.bingner.com/ ios/1561.00 main 
deb https://c1d3r.com/repo/ ./ 
deb https://repo.chariz.io/ ./ 
deb https://creaturecoding.com/repo/ ./ 
deb https://creaturesurvive.github.io/ ./ 
deb http://getdelta.co/ ./ 
deb https://repo.dynastic.co/ ./ 
deb http://julioverne.github.io/ ./ 
deb http://limneos.net/repo/ ./ 
deb http://repo.incendo.ws/ ./ 
deb http://repo.midnightchips.me/ ./ 
deb http://apt.modmyi.com/ stable main 
deb http://yp261.github.io/repo/ ./ 
deb https://repo.nullpixel.uk/ ./ 
deb https://repo.packix.com/ ./ 
deb https://poomsmart.github.io/repo/ ./ 
deb http://qwertyuiop1379.github.io/ ./ 
deb https://rpetri.ch/repo/ ./ 
deb http://rubrdcky.github.io/ ./ 
deb https://ryleyangus.com/repo/ ./ 
deb http://skitty.xyz/repo/ ./ 
deb https://tweakportal.yourepo.com/ ./ 
deb https://xtm3x.github.io/repo/ ./ 
deb https://cydia.akemi.ai ./

**Comment by JAKESNAKE523** [comment]
Okay, thanks. I'll see about testing your repo list later on my device and see if the same thing happens.

**Comment by wstyres** [comment]
Issues with Gesto should be fixed as of 96277b2
