### ISSUE TITLE
[Localize] Spanish Translation for Zebra

### ISSUE THREAD

**Issue by totobighouse** [wstyres/Zebra#425]
**What language are you adding?**
Spanish

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**

https://www.dropbox.com/s/8vn2sqmllnm2zhs/Localizable.strings?dl=0 (note: I did a pull request but I don't know how to upload the whole project, so this link is the "Localizable. string")

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**

im not in the discord server, but my id is samoht#0903

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**

_Tomás Casagande_

**Comment by wstyres** [comment]
Spanish translation is already available in Zebra [here](https://github.com/wstyres/Zebra/blob/master/Zebra/es.lproj/Localizable.strings). If you'd like, you can take a look at the already translated Strings and check to make sure they are correct and press the "edit" button on that page to submit a new Pull Request.
