### ISSUE TITLE
[Localize] Hebrew Translation

### ISSUE THREAD

**Issue by Aransh** [wstyres/Zebra#431]
**Hebrew**

**https://www.dropbox.com/s/p2tej818dtwk7c7/Localizable.strings?dl=0**

**Are you a member of our discord? Yes, @Aransh**

**How would you like to be credited? (Aran Shavit @Aranshavit)**

**Comment by wstyres** [comment]
Looks like there are some formatting issues with your translation. Could you check the Base translation out [here](https://github.com/wstyres/Zebra/blob/master/Zebra/Base.lproj/Localizable.strings) and try to format your file like this? Thanks!

<img width="912" alt="Screen Shot 2019-10-26 at 11 51 17 AM" src="https://user-images.githubusercontent.com/19736790/67622285-ef400600-f7e6-11e9-90f0-23962d376ff9.png">

**Comment by Aransh** [comment]
I've used Filza to edit this, here's the raw text:

"%@ conflicts with %@"="%@ מתנגש עם %@";
"%@ depends on %@"="%@ תלוי ב-%@";
"%@ hasn't been modified"="%@ לא שונה";
"ABC"="אבג";
"Abort"="ביטול";
"Add"="הוסף";
"Add Multiple"="הוסף מרובים";
"Add Repo(s)"="הוסף מקור(ות)";
"Add to Wish List"="הוסף לרשימת המשאלות";
"Advanced"="מתקדם";
"All Packages"="כל החבילות";
"Are you sure you want to clear Queue?"="האם את\/ה בטוח\/ה שברצונך לנקות את התור?";
"Authenticate to initiate purchase."="אמת\/י כדי להתחיל רכישה.";
"Available Upgrades"="עדכונים זמינים";
"Black"="שחור";
"Blue"="כחול";
"Cancel"="ביטול";
"Change Icon"="שנה אייקון";
"Changelog"="מה חדש";
"Changes"="שינויים";
"Clear"="נקה";
"Clear Image Cache"="נקה מטמון תמונות";
"Clear Keychain"="נקה צרור";
"Clear Search"="נקה חיפוש";
"Clearing keychain completed"="ניקוי צרור הושלם";
"Click \"Return to Queue\" to return to the Queue and retry the download."="לחץ על \"חזור לתור\" כדי לחזור לתור ולנסות שוב את ההורדה.";
"Close"="סגור";
"Close Zebra"="סגור את זברה";
"Community"="קהילה";
"Community Repos"="מקורות קהילתיים";
"Complete"="הושלם";
"Console"="מסוף";
"Continue"="המשך\/י";
"Could not determine device information."="לא ניתן לקבוע פרטי מכשיר.";
"Could not find a download URL for"="לא ניתן למצוא כתובת הורדה עבור";
"Could not parse %@ from %@"="לא ניתן לנתח את %@ מ-%@";
"Could not resolve dependency for %@"="לא ניתן לפתור תלות עבור %@";
"Credits"="קרדיטים";
"Dark Mode"="מצב לילה";
"Date"="תאריך";
"Default"="ברירת מחדל";
"Delete"="מחק";
"Done"="סיום";
"Downgrade"="שנמך";
"Download Size"="גודל הורדה";
"Downloading"="מוריד";
"Downloading Packages..."="מוריד חבילות...";
"Downloads"="הורדות";
"Edit"="ערוך";
"Enable Featured Packages"="אפשר חבילות מומלצות";
"Enable News"="אפשר חדשות";
"Enter URL"="הזן\/י כתובת";
"Error"="תקלה";
"Error verifying repositories"="תקלה באימות מקורות";
"Error verifying repository"="תקלה באימות מקור";
"Error while opening sources.list"="תקלה בפתיחת sources.list";
"Feature Type"="סוג המלצה";
"Featured"="מומלץ";
"Finished importing local packages."="ייבוא חבילות מקומיות הושלם.";
"Finished!"="הושלם!";
"Follow me on Twitter"="עקוב\/י אחריי ב-Twitter";
"Graphics"="עיצוב";
"Home"="בית";
"Icon"="אייקון";
"Ignore Updates"="התעלם מעדכונים";
"Ignored Upgrades"="עדכונים שנדחו";
"Importing local packages."="מייבט חבילות מקומיות.";
"Incorrect documents permissions."="הרשאות מסמכים שגויות.";
"Info"="מידע";
"Information"="מידע";
"Install"="התקן";
"Installed Files"="קבצים מותקנים";
"Installed Version"="גירסה מותקנת";
"Installing"="מתקין";
"Installing Packages..."="מתקין חבילות...";
"Invalid URL"="כתובת לא תקינה";
"It may cause issues if you add it to Zebra resulting in possible restore."="אם תוסיף\/י אותו לזברה זה עלול לגרום לבעיות שיובילו לשחזור אפשרי.";
"Join our Discord"="הצטרך ל-Discord שלנו";
"Loaded"="נטען";
"Loading..."="טוען...";
"Local Repository"="מקור מקומי";
"Locally installed packages"="חבילות שהותקנו מקומית";
"Log Out"="התנתק\/י";
"Login"="התחבר\/י";
"Miscellaneous"="שונות";
"Modify"="נהל";
"More by this Developer"="עוד ממפתח זה";
"Move all sources from %@ to Zebra"="ייבא את כל המקורות מ-%@ לזברה";
"News"="חדשות";
"No"="לא";
"No Results Found"="לא נמצאו תוצאות";
"No repository urls detected."="לא אותרו כתובות מקורות.";
"OLED"="OLED";
"Ok"="אישור";
"One or more packages failed to download."="חבילה אחת או יותר נכשלו בהורדה.";
"Open Documents Directory"="פתח\/י תיקיית מסמכים";
"Orange"="כתום";
"Package"="חבילה";
"Package in Queue"="חבילה בתור";
"Packages"="חבילות";
"Packages in Queue"="חבילות בתור";
"Performing actions"="מבצע פעולות";
"Please Wait..."="נא להמתין...";
"Please relogin your account that is used to purchase this package (Possibly %@)"="אנא התחבר\/י מחדש לחשבונך ששומש לרכישת חבילה זו (עלול להיות %@)";
"Please remove this repo from your sources.list file."="אנא הסר\/י את מקור זה מקובץ הsources.list שלך.";
"Purchased"="נרכש";
"Purchased Packages"="חבילות שנרכשו";
"Purchases"="רכישות";
"Queue"="תור";
"Queue cleared"="תור נוקה";
"Random"="אקראי";
"Recent"="אחרונים";
"Refresh"="רענן";
"Reinstall"="התקן מחדש";
"Reinstalling"="מתקין מחדש";
"Reinstalling Packages..."="מתקין מחדש חבילות...";
"Remove"="הסר";
"Remove from Wish List"="הסר מרשימת המשאלות";
"Removed by"="הוסר ע\"י";
"Removing"="מסיר";
"Removing Packages..."="מסיר חבילות...";
"Repo Featured"="מומלץ מקור";
"Report a Bug"="דווח\/י על באג";
"Required by"="נדרש ע\"י";
"Resetting image cache completed"="איפוס מטמון תמונות הושלם";
"Restart SpringBoard"="הפעל מחדש את מסך הבית";
"Retry"="נסה\/י שוב";
"Return to Queue"="חזור לתור";
"Search"="חיפוש";
"Search while Typing"="חפש במהלך ההקלדה";
"Select Repos to be Featured"="בחר\/י מקורות שיהיו מומלצים";
"Select Version"="בחר\/י גירסה";
"Select a version to upgrade to"="בחר\/י גירסה לעדכן אליה";
"Settings"="הגדרות";
"Show Updates"="הצג עדכונים";
"Size"="גודל";
"Sources"="מקורות";
"Stores"="חנויות";
"Swipe Actions Display As"="פעולות החלקה מוצגות בתור";
"Tap to manage Queue"="לחץ\/י כדי לנהל את התור";
"Text"="טקסט";
"The repo %@ is incompatible with your jailbreak."="המקור %@ אינו תואם לפריצה שלך.";
"This may take awhile and Zebra may crash. It is okay if it does."="זה עלול לקחת קצת זמן וזברה עלולה לקרוס. זה בסדר אם זה יקרה.";
"This search query is too short for the full search, please use a longer query."="מושג חיפוש זה קצר מידיי עבור החיפוש המלא, אנא השתמש\/י במושג ארוך יותר.";
"Tint Color"="צבע גוון";
"Transfer Sources"="העבר מקורות";
"Transfer Sources from %@"="ייבא מקורות מ-%@";
"Unable to verify Repo"="לא ניתן לאמת מקור";
"Unknown"="לא ידוע";
"Unknown error."="תקלה לא ידועה.";
"Unlist"="הורד מהרשימה";
"Updating icon cache asynchronously..."="מעדכן מטמון אייקונים באופן אסינכרוני...";
"Upgrade"="עדכן";
"Upgrade All"="עדכן הכל";
"Upgrading"="מעדכן";
"Upgrading Packages..."="מעדכן חבילות...";
"Utilities"="כלים";
"Utility repo for %@"="מקור כלים עבור %@";
"Verifying Source(s)"="מאמת מקור(ות)";
"Version"="גירסה";
"Welcome to the Zebra Beta!"="ברוכים הבאים לבטא של זברה!";
"White"="לבן";
"Wish List"="רשימת משאלות";
"Would you like to add the URL from your clipboard?"="האם ברצונך להוסיף את הכתובת שהעתקת?";
"You have already added these repositories."="כבר הוספת את מקורות אלו.";
"iOS 13"="iOS 13";

**Comment by wstyres** [comment]
I've implemented your translation but I think you should still take a look [here](https://github.com/wstyres/Zebra/blob/90fc542a6dfa003aad65d67edfd2eaf18e56976d/Zebra/he.lproj/Localizable.strings) to make sure that there were no problems when you copied it from Filza.

**Comment by Aransh** [comment]
Hey, I've looked at my translation again looking for errors or strings with a better possible translation, much happier with the result now! 
Also looked at the link in your comment and everything looks great!

Anyway here is the updated translation:

"%@ conflicts with %@"="%@ מתנגש עם %@";
"%@ depends on %@"="%@ תלוי ב-%@";
"%@ hasn't been modified"="לא בוצעו שינויים ב-%@";
"ABC"="אבג";
"Abort"="ביטול";
"Add"="הוסף";
"Add Multiple"="הוסף מרובים";
"Add Repo(s)"="הוסף מקור(ות)";
"Add to Wish List"="הוסף לרשימת המשאלות";
"Advanced"="מתקדם";
"All Packages"="כל החבילות";
"Are you sure you want to clear Queue?"="האם את\/ה בטוח\/ה שברצונך לנקות את התור?";
"Authenticate to initiate purchase."="בצע\/י אימות כדי להתחיל רכישה.";
"Available Upgrades"="עדכונים זמינים";
"Black"="שחור";
"Blue"="כחול";
"Cancel"="ביטול";
"Change Icon"="שנה אייקון";
"Changelog"="מה חדש";
"Changes"="שינויים";
"Clear"="נקה";
"Clear Image Cache"="נקה מטמון תמונות";
"Clear Keychain"="נקה צרור";
"Clear Search"="נקה חיפוש";
"Clearing keychain completed"="ניקוי צרור הושלם";
"Click \"Return to Queue\" to return to the Queue and retry the download."="לחץ\/י על \"חזרה לתור\" כדי לחזור לתור ולנסות שוב את ההורדה.";
"Close"="סגור";
"Close Zebra"="סגור את זברה";
"Community"="קהילה";
"Community Repos"="מקורות קהילתיים";
"Complete"="הושלם";
"Console"="מסוף";
"Continue"="המשך";
"Could not determine device information."="לא ניתן לקבוע פרטי מכשיר.";
"Could not find a download URL for"="לא ניתן למצוא כתובת הורדה עבור";
"Could not parse %@ from %@"="לא ניתן לנתח את %@ מ-%@";
"Could not resolve dependency for %@"="לא ניתן לפתור תלות עבור %@";
"Credits"="זכויות";
"Dark Mode"="מצב לילה";
"Date"="תאריך";
"Default"="ברירת מחדל";
"Delete"="מחק";
"Done"="סיום";
"Downgrade"="שנמך";
"Download Size"="גודל הורדה";
"Downloading"="מוריד";
"Downloading Packages..."="מוריד חבילות...";
"Downloads"="הורדות";
"Edit"="עריכה";
"Enable Featured Packages"="אפשר חבילות מומלצות";
"Enable News"="אפשר חדשות";
"Enter URL"="הזן\/י כתובת";
"Error"="תקלה";
"Error verifying repositories"="תקלה באימות מקורות";
"Error verifying repository"="תקלה באימות מקור";
"Error while opening sources.list"="תקלה בפתיחת sources.list";
"Feature Type"="סוג המלצה";
"Featured"="מומלץ";
"Finished importing local packages."="ייבוא חבילות מקומיות הושלם.";
"Finished!"="הושלם!";
"Follow me on Twitter"="עקוב\/י אחריי ב-Twitter";
"Graphics"="עיצוב";
"Home"="בית";
"Icon"="אייקון";
"Ignore Updates"="התעלם מעדכונים";
"Ignored Upgrades"="עדכונים שנדחו";
"Importing local packages."="מייבא חבילות מקומיות.";
"Incorrect documents permissions."="הרשאות מסמכים שגויות.";
"Info"="מידע";
"Information"="מידע";
"Install"="התקן";
"Installed Files"="קבצים מותקנים";
"Installed Version"="גירסה מותקנת";
"Installing"="מתקין";
"Installing Packages..."="מתקין חבילות...";
"Invalid URL"="כתובת לא תקינה";
"It may cause issues if you add it to Zebra resulting in possible restore."="אם תוסיף\/י אותו לזברה זה עלול לגרום לבעיות שיובילו לשחזור אפשרי.";
"Join our Discord"="הצטרף\/י ל-Discord שלנו";
"Loaded"="נטען";
"Loading..."="טוען...";
"Local Repository"="מקור מקומי";
"Locally installed packages"="חבילות שהותקנו מקומית";
"Log Out"="התנתק";
"Login"="התחבר";
"Miscellaneous"="שונות";
"Modify"="נהל";
"More by this Developer"="עוד ממפתח זה";
"Move all sources from %@ to Zebra"="ייבא את כל המקורות מ-%@ לזברה";
"News"="חדשות";
"No"="לא";
"No Results Found"="לא נמצאו תוצאות";
"No repository urls detected."="לא אותרו כתובות מקור.";
"OLED"="OLED";
"Ok"="אישור";
"One or more packages failed to download."="חבילה אחת או יותר נכשלו בהורדה.";
"Open Documents Directory"="פתח תיקיית מסמכים";
"Orange"="כתום";
"Package"="חבילה";
"Package in Queue"="חבילה בתור";
"Packages"="חבילות";
"Packages in Queue"="חבילות בתור";
"Performing actions"="מבצע פעולות";
"Please Wait..."="נא להמתין...";
"Please relogin your account that is used to purchase this package (Possibly %@)"="אנא התחבר\/י מחדש לחשבונך ששומש לרכישת חבילה זו (עלול להיות %@)";
"Please remove this repo from your sources.list file."="אנא הסר\/י את מקור זה מקובץ ה-sources.list שלך.";
"Purchased"="נרכש";
"Purchased Packages"="חבילות שנרכשו";
"Purchases"="רכישות";
"Queue"="תור";
"Queue cleared"="תור נוקה";
"Random"="אקראי";
"Recent"="אחרונים";
"Refresh"="רענן";
"Reinstall"="התקן מחדש";
"Reinstalling"="מתקין מחדש";
"Reinstalling Packages..."="מתקין מחדש חבילות...";
"Remove"="הסר";
"Remove from Wish List"="הסר מרשימת המשאלות";
"Removed by"="הוסר ע\"י";
"Removing"="מסיר";
"Removing Packages..."="מסיר חבילות...";
"Repo Featured"="מומלץ מקור";
"Report a Bug"="דווח\/י על באג";
"Required by"="נדרש ע\"י";
"Resetting image cache completed"="איפוס מטמון תמונות הושלם";
"Restart SpringBoard"="הפעל מחדש את מסך הבית";
"Retry"="נסה שוב";
"Return to Queue"="חזרה לתור";
"Search"="חיפוש";
"Search while Typing"="חפש במהלך ההקלדה";
"Select Repos to be Featured"="בחר\/י מקורות שיהיו מומלצים";
"Select Version"="בחר גירסה";
"Select a version to upgrade to"="בחר\/י גירסה לעדכן אליה";
"Settings"="הגדרות";
"Show Updates"="הצג עדכונים";
"Size"="גודל";
"Sources"="מקורות";
"Stores"="חנויות";
"Swipe Actions Display As"="פעולות החלקה מוצגות בתור";
"Tap to manage Queue"="לחץ\/י כדי לנהל את התור";
"Text"="טקסט";
"The repo %@ is incompatible with your jailbreak."="המקור %@ אינו תואם לפריצה שלך.";
"This may take awhile and Zebra may crash. It is okay if it does."="זה עלול לקחת קצת זמן וזברה עלולה לקרוס. זה בסדר אם זה יקרה.";
"This search query is too short for the full search, please use a longer query."="מושג חיפוש זה קצר מידיי עבור החיפוש המלא, אנא השתמש\/י במושג ארוך יותר.";
"Tint Color"="צבע גוון";
"Transfer Sources"="ייבוא מקורות";
"Transfer Sources from %@"="ייבא מקורות מ-%@";
"Unable to verify Repo"="לא ניתן לאמת מקור";
"Unknown"="לא ידוע";
"Unknown error."="תקלה לא ידועה.";
"Unlist"="הסר מהרשימה";
"Updating icon cache asynchronously..."="מעדכן מטמון אייקונים באופן אסינכרוני...";
"Upgrade"="עדכן";
"Upgrade All"="עדכן הכל";
"Upgrading"="מעדכן";
"Upgrading Packages..."="מעדכן חבילות...";
"Utilities"="כלים";
"Utility repo for %@"="מקור כלים עבור %@";
"Verifying Source(s)"="מאמת מקור(ות)";
"Version"="גירסה";
"Welcome to the Zebra Beta!"="ברוכים הבאים לבטא של זברה!";
"White"="לבן";
"Wish List"="רשימת משאלות";
"Would you like to add the URL from your clipboard?"="האם ברצונך להוסיף את הכתובת שהעתקת?";
"You have already added these repositories."="כבר הוספת את מקורות אלו.";
"iOS 13"="iOS 13";
