### ISSUE TITLE
[Localize] Turkish Translation

### ISSUE THREAD

**Issue by haurogh** [wstyres/Zebra#434]
**What language are you adding?**
Turkish(Türkçe)

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**

[Localizable.strings.zip](https://github.com/wstyres/Zebra/files/3774714/Localizable.strings.zip)

https://drive.google.com/file/d/189jHdyR4HqJGV6VcyZbLw6O14k5TXCRv/view?usp=sharing

This is localizable.string . I did in text editor but I have XCODE too. 

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**

Yes. It's Haurogh.

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
No need to be credited. But my nick is Haurogh.
[Localizable.strings.zip](https://github.com/wstyres/Zebra/files/3774714/Localizable.strings.zip)

**Comment by wstyres** [comment]
Looks like someone has already implemented Turkish translation in #433. However, if you'd like to modify their translations for improvements you can edit them [here](https://github.com/wstyres/Zebra/blob/master/Zebra/tr.lproj/Localizable.strings) and I will still add your translator role to the Discord.
