### ISSUE TITLE
Cydia transferred repos returning 404 not shown in sources tab

### ISSUE THREAD

**Issue by alessaro92** [wstyres/Zebra#44]
I transferred from cydia the repos I used to have, but one of them has started returning http 404 error from time and I didn’t remove it from cydia. Now in the list of repos in the source tab I don’t have that one causing the 404 error, but when I refresh the sources, zebra show me the 404 error of that “hidden” repo.
In attachment you can see the list of sources and the error messkage.

Device Information
 - iOS Version 11.2.2
 - AUPM Version 1.0~beta8
 - Device Type iPhone SE 64

![IMG_8989](https://user-images.githubusercontent.com/43436642/57376386-24588d80-71a0-11e9-9be6-ffeb4456f89d.PNG)
![IMG_8990](https://user-images.githubusercontent.com/43436642/57376418-363a3080-71a0-11e9-9549-656eb5fd8457.PNG)
![IMG_8991](https://user-images.githubusercontent.com/43436642/57376426-39cdb780-71a0-11e9-9355-4809e981cb93.PNG)
![IMG_8992](https://user-images.githubusercontent.com/43436642/57376430-3c301180-71a0-11e9-8c83-309029572a26.PNG)
![IMG_8993](https://user-images.githubusercontent.com/43436642/57376435-3fc39880-71a0-11e9-9bb1-6f26f660d297.PNG)

**Comment by wstyres** [comment]
It doesn't look like that repo exists anymore, a quick google search I did says that the repo moved to https://sparkdev.me

**Comment by alessaro92** [comment]
I know that it doesn’t exist any more but since I imported the repo list from Cydia and this repo doesn’t show up in the zebra sources list but still it gives error on refresh, how can I delete it?

**Comment by wstyres** [comment]
Since they are 404, Zebra is never able to import them. You can manually remove them from Zebra's sources.list. If you press "Open Documents Directory" on Zebra's homepage you'll be able to find it there. I'll see what I can do about repos that are 404 when importing.

**Comment by alessaro92** [comment]
Thank you, I've just removed it from the zebra's sources.list file. What I was saying is that maybe someone could do that directly from zebra app. What if a repo source that we already have in zebra suddenly stop working? Does it vanish too from repo list?

**Comment by wstyres** [comment]
No, it would not disappear from the list. This would only occur when adding it manually to the sources file as Zebra would never have a chance to add it to the database.
