### ISSUE TITLE
[Localize] Czech Translation

### ISSUE THREAD

**Issue by kukulama** [wstyres/Zebra#440]
**What language are you adding?**
I'd like to add Czech, Čeština (Czech republic), if you will like it and add it, I'll post updates. I can also translate Zebra to Slovak, Slovenčina (Slovakia) if you want.

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**
https://github.com/kukulama/Zebra-CZ

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**
I'm not a member at this time. I'll maybe join later.

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
kukulama

**Comment by worldlydev** [comment]
> **What language are you adding?**
> I'd like to add Czech (Czech republic), if you will like it and add it, I'll post updates. I can also translate Zebra to Slovak (Slovakia) if you want.
> 
> **Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**
> https://github.com/kukulama/Zebra-CZ
> 
> **Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**
> I'm not a member at this time. I'll maybe join later.
> 
> **How would you like to be credited? (Name, Twitter Link, Website, etc.)**
> kukulama

I'm sure the people who speak Slovak would be happy if you translated it for them.

**Comment by wstyres** [comment]
I've implemented your Czech translation and if you want to do a Slovak translation as well that would be great!
