### ISSUE TITLE
Blue Dark Mode For Zebra

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#441]
**Is your feature request related to a problem? Please describe.**

Would be nice to have a blue dark mode option.

**Describe the solution you'd like**

A blue dark mode would be a nice option to have. Installer has a blue dark mode but it looks a little dull.  I personally think Twitter has the best example of a blue dark mode and think the colors used should be the same as Twitter uses. I made a mockup of Zebra with a dark mode using the same colors as Twitter uses. The darkest blue color is Hex: 181E2A and the lighter shade is Hex: 192734.

**Describe alternatives you've considered**

N/A

**Additional context**

![unnamed](https://user-images.githubusercontent.com/51668635/67621739-17ddf500-f813-11e9-9f84-1b9b24d23421.jpg)

**Comment by a2009981** [comment]
شكرا

**Comment by worldlydev** [comment]
Closed in favor of #988
