### ISSUE TITLE
Tweakcompatible for Zebra

### ISSUE THREAD

**Issue by qnblackcat** [wstyres/Zebra#446]
**Describe the bug**
Tweakcompatible for Zebra always show "unknown/No report". If i press (+) icon, Zebra will crash

**To Reproduce**
check compatible

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version: 12.2
 - Zebra Version: 1.0~beta23-1
 - Device Type: iPhone 6s

**Crash Log or System Log**
https://pastebin.com/N0uZJ54Z

**Additional context**
It happen after update to latest Zebra

**Comment by wstyres** [comment]
This is an issue that TweakCompatible most likely needs to be updated to work with the latest version of Zebra. I would suggest filing an issue on their GitHub repo or contacting the Developer.

**Comment by ann0see** [comment]
@midnightchips
