### ISSUE TITLE
Zebra crashes when scrolling through a repo

### ISSUE THREAD

**Issue by GucciGazm** [wstyres/Zebra#45]
Date: 2019-05-11 16:58:58 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSRangeException
Reason: *** -[__NSArrayM objectAtIndex:]: index 18 beyond bounds [0 .. 17]
Culprit: Unknown
Device: iPhone X, iOS 12.1.1
Call stack:
0   CoreFoundation                      0x000000019c4e4edc __exceptionPreprocess
1   libobjc.A.dylib                     0x000000019b6b5a40 objc_exception_throw
2   CoreFoundation                      0x000000019c45c494 _CFArgv
3   CoreFoundation                      0x000000019c3cc698 _CFDataInit
4   Zebra                               0x0000000100098980 Zebra + 51584
5   UIKitCore                           0x00000001c98dd0cc -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:]
6   UIKitCore                           0x00000001c98dd4bc -[UITableView _createPreparedCellForGlobalRow:willDisplay:]
7   UIKitCore                           0x00000001c98a8b94 -[UITableView _updateVisibleCellsNow:isRecursive:]
8   UIKitCore                           0x00000001c98c6a80 -[UITableView layoutSubviews]
9   UIKitCore                           0x00000001c9b5b96c -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
10  QuartzCore                          0x00000001a0ae1b74 -[CALayer layoutSublayers]
11  QuartzCore                          0x00000001a0ae6b2c CA::Layer::layout_if_needed(CA::Transaction*)
12  QuartzCore                          0x00000001a0a4544c CA::Context::commit_transaction(CA::Transaction*)
13  QuartzCore                          0x00000001a0a73d7c CA::Transaction::commit()
14  QuartzCore                          0x00000001a0a74be4 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
15  CoreFoundation                      0x000000019c4747cc __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
16  CoreFoundation                      0x000000019c46f460 __CFRunLoopDoObservers
17  CoreFoundation                      0x000000019c46fa00 __CFRunLoopRun
18  CoreFoundation                      0x000000019c46f1f0 CFRunLoopRunSpecific
19  GraphicsServices                    0x000000019e6e8584 GSEventRunModal
20  UIKitCore                           0x00000001c96b34c0 UIApplicationMain
21  Zebra                               0x0000000100099c7c Zebra + 56444
22  libdyld.dylib                       0x000000019bf2ebb4 start

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wstyres** [comment]
Which repo is this? I think this issue has already been fixed but I just want to be sure

**Comment by GucciGazm** [comment]
>Which repo is this? I think this issue has already been fixed but I just want to be sure

@wstyres issue is fixed with beta 9. Keep it up!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
