### ISSUE TITLE
[Localize] Slovak Translation

### ISSUE THREAD

**Issue by kukulama** [wstyres/Zebra#450]
**What language are you adding?**
Translation for Slovak (Slovenčina)

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**
https://github.com/kukulama/Zebra-SK

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**
Yes, my username is kukulama

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
kukulama

**Comment by Lupi-X** [comment]
Can I edit this? Not all the translations are that good..

**Comment by kukulama** [comment]
Yes yo can, send me your transtalion file to kukulama303@gmail.com and I will post it to my github https://github.com/kukulama/Zebra-SK and send it to dev.

**Comment by wstyres** [comment]
@Lupi-X you can actually directly edit the file [here](https://github.com/wstyres/Zebra/edit/master/Zebra/sk.lproj/Localizable.strings) and submit the PR yourself.
