### ISSUE TITLE
What’ going on 

### ISSUE THREAD

**Issue by JAliRepo** [wstyres/Zebra#454]
**Describe the bug**

I have translated zebra into Arabic, but I found the name of different guy on the ar.lproj  not mine 

**To Reproduce**

**Expected behavior**

**Screenshots**

https://anonfile.com/9eofp291n2/D479D2A9-D1D6-45A7-9498-B35701493260_png

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by GeopJr** [comment]
Thats the latest commit on  that file (https://github.com/wstyres/Zebra/pull/429)
Your's has already been pushed (https://github.com/wstyres/Zebra/commit/936cdafd59052e6cbe20c84a27aaa0d8ac9ff6fc)

**Comment by JAliRepo** [comment]
Thanks

**Comment by wstyres** [comment]
Yes @iA7myd updated your translation slightly. You can view the changes they made [here](https://github.com/wstyres/Zebra/pull/429/files).
