### ISSUE TITLE
Source Page bug

### ISSUE THREAD

**Issue by yllshahini** [wstyres/Zebra#458]
**Describe the bug**
First repo/package in Source page and Packages page is stuck under page title.

**To Reproduce**
Steps to reproduce the behavior: Consistent bug whenever Zebra is opened.

**Expected behavior**
Repo/package to not be cut off and have regular margins.

**Screenshots**
![IMG_1496](https://user-images.githubusercontent.com/39761205/67636065-da3da280-f8cc-11e9-8400-703fbe26d685.PNG)
![IMG_1497](https://user-images.githubusercontent.com/39761205/67636066-dad63900-f8cc-11e9-96b2-ff9505b54a75.PNG)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.0.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta23-1
 - Device Type [e.g. iPhone or iPad]: iPhone X

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Was fixed in #390. Hopefully it will not happen again in the next beta.
