### ISSUE TITLE
Error verifying repo.

### ISSUE THREAD

**Issue by Co2333** [wstyres/Zebra#46]
This is more a bug than a feature request, so I selected to report it in bug way.

The repo description aka Release search path should be at:

`    
public let release_search_path           = ["Release",  

                                                "dists/stable/main/Release",  

                                                "dists/tangelo/main/Release",  

                                                "dists/stable/main/binary-iphoneos-arm/Release",  

                                                "dists/hnd/main/Release"] . `

The repo packages aka package.bz .gz balabala should be at:

`   
 public let release_database_search_path  = ["Packages",  

                                                "Packages.bz2",  

                                                "Packages.gz",  

                                                "dists/stable/main/binary-iphoneos-arm/Packages.bz2",  

                                                "dists/stable/main/binary-iphoneos-arm/Packages.gz",  

                                                "dists/hnd/main/binary-iphoneos-arm/Packages.bz2",  

                                                "dists/tangelo/main/binary-iphoneos-arm/Packages.bz2",  

                                                "dists/tangelo/main/binary-iphoneos-arm/Packages.gz",  

                                                "dists/unstable/main/binary-iphoneos-arm/Packages.bz2",  

                                                "dists/unstable/main/binary-iphoneos-arm/Packages.gz",  

                                                "dists/unstable/main/binary-iphoneos-arm/Packages",  

                                                "dists/stable/main/binary-iphoneos-arm/Packages",  

                                                "dists/tangelo/main/binary-iphoneos-arm/Packages"] . `

I'm attaching a private file (just currently) which is written in swift in Saily 0.2 for you to make ref from.

[BackendCodes.zip](https://github.com/wstyres/Zebra/files/3169311/BackendCodes.zip)

If you want more, check icy out.

**Comment by Co2333** [comment]
As for chimera.sh, it is using just the plain txt with .bz and .gz backend. so take good care of this child

**Comment by wstyres** [comment]
Not sure what the bug is here, could you elaborate?

**Comment by Co2333** [comment]
Because Zebra only check one file while verifying the repo while a repo may not have it but working fine. It is better to do it checking all the files. If one of them exists, break the loop and push to success.

**Comment by wstyres** [comment]
Zebra checks both Packages.bz2 and Packages.gz to verify the repos. All the other "dists" urls are from repos that have different distributions (usually default repos, Cydia/BigBoss/ModMyi/Bingner) so they don't need to be checked every time a repo is added

**Comment by Co2333** [comment]
....... fine.
