### ISSUE TITLE
[Localize]

### ISSUE THREAD

**Issue by kukulama** [wstyres/Zebra#467]
**What language are you adding?**
Czech

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**
https://github.com/kukulama/Zebra-CZ -- I have removed typing mistakes and improved translations

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**
kukulama

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
kukulama

**Comment by wstyres** [comment]
Thanks! Since the strings are already implemented, you can edit the strings by going [here](https://github.com/wstyres/Zebra/edit/master/Zebra/cs.lproj/Localizable.strings) and submitting a new Pull Request.
