### ISSUE TITLE
Custom package icons over HTTPS

### ISSUE THREAD

**Issue by Shugabuga** [wstyres/Zebra#47]
**Is your feature request related to a problem? Please describe.**
Currently, Zebra does not allow for custom package icons, which, if an unknown category is in use, Zebra will display no icon. If icons were supported over HTTPS, the repo maintainers can define their own icon, just as it is in Sileo.

**Describe the solution you'd like**
Allow for package icons to be loaded over HTTPS based on the `Icon` key in the package's `control` file.

**Additional context**
This may be considered a duplicate of #7, as it brings Sileo-like functionality to Zebra, but I consider it a separate issue (icons are not related to native depictions).

**Comment by relisiuol** [comment]
That should be enough, I think.
https://github.com/wstyres/Zebra/pull/106

**Comment by wstyres** [comment]
Implemented in #112 and was merged into master
