### ISSUE TITLE
[BUG] Can't see cursor when adding repo

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#471]
**Describe the bug**

When adding a repo in Zebra the cursor is white making it impossible to see. Makes it very difficult to use the keyboard gesture and is just a pain in general for text editing.

**To Reproduce**

Add a repo in Zebra then try to move the cursor to edit the text.

**Expected behavior**

I expect the cursor to be black.

**Screenshots**

![6BDCF482-EAE3-40CA-8F81-68AD6A18C9D9](https://user-images.githubusercontent.com/51668635/67776815-29b4d780-fa61-11e9-84b4-39af10bfe625.jpeg)
![AD4146B7-A6A4-4814-8719-C6E509A5F0C8](https://user-images.githubusercontent.com/51668635/67776816-29b4d780-fa61-11e9-8afc-718d15daa7bb.jpeg)
![67490F68-4325-4F61-B684-81E7929578B2](https://user-images.githubusercontent.com/51668635/67776819-2a4d6e00-fa61-11e9-8191-cf2e46a96b6b.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0 ~ beta 23-1
 - Device Type [e.g. iPhone or iPad]: 
iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by worldlydev** [comment]
Update: The cursor is affected by the tint color. This is only an issue for those who have selected dark mode with white tint. Would be nice is the cursor was black for those with white tint enabled.

**Comment by wstyres** [comment]
Fixed in def436b7e19016698e285adfeeff923de8159b6d by setting the text field's background color to white when in dark mode. 
![Simulator Screen Shot - iPhone 11 - 2019-11-01 at 15 10 28](https://user-images.githubusercontent.com/19736790/68049631-c5408500-fcb9-11e9-8678-abf1e7269b4d.png)

**Comment by worldlydev** [comment]
Saw that you fixed it in def436b. Thank you so much 😊
