### ISSUE TITLE
[Localization] Add serbian translation

### ISSUE THREAD

**Issue by fvaha** [wstyres/Zebra#483]
**What language are you adding?**
Serbian

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**
https://github.com/fvaha/Zebra/blob/master/Localizable.strings

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**
You can find me on twitter

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
twitter @vahanet

**Comment by wstyres** [comment]
In the future, translations will be maintained by Crowdin located [here](https://translate.getzbra.com/) so keep an eye out for new strings!
