### ISSUE TITLE
[BUG] Installation Issue

### ISSUE THREAD

**Issue by ZenIsBestWolf** [wstyres/Zebra#487]
**Describe the bug**
Zebra crashes when installing a tweak called [[FLEXing]] (com.pantsthief.flexing) on BigBoss. I suspect it's an issue with the tweak's postinst and postuninst scripts.
**To Reproduce**
1. Search "FLEXing" on Zebra with the BigBoss repository installed.
2. Attempt to install it/uninstall it.
**Expected behavior**
The tweak installs and Zebra is fine.
**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4 (Stable)
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0\~beta23-1
 - Device Type [e.g. iPhone or iPad]: iPhone 8+

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.
[Crash On Installation](https://gist.githubusercontent.com/ZenIsBestWolf/f332d371b48c21ed6b569b11881b88a4/raw) [Crash On Removal](https://gist.githubusercontent.com/ZenIsBestWolf/43a6710965485200ee5792947297b6ca/raw)
**Additional context**
This was using unc0ver, with u0 Dark bootstrap so I can uninstall Cydia and Sileo, allowing Zebra to be my primary package manager if that matters at all.

**Comment by ZenIsBestWolf** [comment]
This also happens with Crux, from the CreatureSurvive github repo.

**Comment by wstyres** [comment]
Do these tweak crash Zebra every time or only part of the time?

**Comment by PoomSmart** [comment]
This is weird. The crash log itself points to layout constraints issue.

**Comment by ZenIsBestWolf** [comment]
> Do these tweak crash Zebra every time or only part of the time?

So sorry for just seeing this, it's every time.

**Comment by wstyres** [comment]
Is this still reproducible in the latest beta (beta 24, 25, or 26)?

**Comment by wstyres** [comment]
Not able to reproduce with installing FLEXing on the latest beta, will keep trying with the other two that you reported.

**Comment by ZenIsBestWolf** [comment]
No longer can reproduce on the latest beta.
