### ISSUE TITLE
Filter for the packages

### ISSUE THREAD

**Issue by EPiCxRIOTZZ** [wstyres/Zebra#49]
A filter so instead of it being named A-Z in packages, you can have recent packages showed as an option (if that makes sense)

**Comment by EPiCxRIOTZZ** [comment]
hi, sorry if you are confused in what i mean

i was meant to say was, where in sileo you can switch between date and name in the packages sort by section 

![IMG_1249](https://user-images.githubusercontent.com/24723906/57574257-972a6880-742d-11e9-9634-7340e5518033.PNG)

**Comment by wstyres** [comment]
Merged in #131
