### ISSUE TITLE
[BUG] UI unresponsiveness

### ISSUE THREAD

**Issue by pwn20wndstuff** [wstyres/Zebra#499]
To reproduce:

Open Zebra
Tap Sources
Tap Edit
Pull down to refresh
Tap cancel
Tap done
Tap edit
Pull down to refresh
Tap done
The cancel button won’t be responsive anymore

**Comment by PoomSmart** [comment]
Mitigated in https://github.com/wstyres/Zebra/commit/7c543d2572a15bcd8a2661b126d4854cdebac4a7
