### ISSUE TITLE
Add community repos

### ISSUE THREAD

**Issue by relisiuol** [wstyres/Zebra#507]
Hello,

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there is a monopoly somewhere.

**Describe the solution you'd like**
Add other community repos:
- YouRepo (https://www.yourepo.com)
- TwickD (https://repo.twickd.com)
- ...

**Describe alternatives you've considered**
Use this list instead, repos are ordered by most page views.
https://www.ios-repo-updates.com/api/popular-repos/

Best regards,
Louis

**Comment by wstyres** [comment]
I agree that the Community Repos section needs to be modified to be more open. For now, we are going to leave it as it is but we will revisit it after 1.0 is released to allow for more repos to be added.

**Comment by wstyres** [comment]
Going to move this back to the redesign, we have a new sources picker designed that will include several community repos so that many more will be able to be discovered.

**Comment by PoomSmart** [comment]
Implemented.

**Comment by relisiuol** [comment]
Can you please edit "https://yourepo.com" to "https://www.yourepo.com" ? It's better to avoid an useless redirection, I think.

**Comment by PoomSmart** [comment]
@wstyres
