### ISSUE TITLE
Ability to Ignore updates

### ISSUE THREAD

**Issue by notmicrodev** [wstyres/Zebra#51]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wstyres** [comment]
I can add this for a future update

**Comment by notmicrodev** [comment]
awesome thank you so much! :)

**Comment by wstyres** [comment]
Implemented in c4c4a9e. Will be in the next beta.

**Comment by notmicrodev** [comment]
GG
