### ISSUE TITLE
[Localize]

### ISSUE THREAD

**Issue by kukulama** [wstyres/Zebra#510]
**What language are you adding?**
Czech, Slovak

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**
I tried to find and translate string "Drop Tables" which can be found in Zebra's settings but it I haven't found it in Base.lproj could you repair it please?

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
kukulama

**Comment by wstyres** [comment]
I've uploaded the strings to Crowdin.
