### ISSUE TITLE
Update settings page to better support localizations

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#511]
**Is your feature request related to a problem? Please describe.**

Lot's of localizations are too long and get cut off in the settings page. This isn't ideal and results in translators translating incorrectly to get shorter strings or leaving the translations as is.

Example of long strings in Zebra:
![468A081B-FA1C-4317-B712-8ACDD0F102C1](https://user-images.githubusercontent.com/51668635/68069632-122c6600-fd63-11e9-9f53-dd40c9b10734.jpg)

**Describe the solution you'd like**

I would like the the settings page to be slightly redesigned. The settings page is already using UITableView but I think it should be slighty adjusted so that it more closely mimics the actual settings app in iOS. Instead of using the UISegmentedControl as Zebra is now I think that each table should open up into a menu as settings does now. This leaves much more room allowing for better localization support but also makes the settings page easier to navigate and less cluttered.

Example from settings:
![1C782E05-8DEE-41BF-A0AE-F47266677446](https://user-images.githubusercontent.com/51668635/68069622-ead59900-fd62-11e9-8118-2a29243397bb.JPG)

**Describe alternatives you've considered**

As I said in the beginning of this post the only options are leaving translations as is or incorrectly translating them to make the strings shorter.

**Additional context**

I made a quick mockup of how a redesigned settings page could look:
![0DD7D7B6-07B0-4E75-BB74-D18B5549BCC4](https://user-images.githubusercontent.com/51668635/68069663-97b01600-fd63-11e9-9609-5a7fd8c1fa91.jpeg)

In my opinion this is the ideal version of an updated settings page in Zebra. Let me explain why:

I repaced the UISegmentedControls with tables that open up into menus. I moved the icon in the "change icon" tab to the right to make the settings page look more balanced as there is now text on the left and icons on the right. Last thing I did was add a short description in the menu, explaining what this setting actually changes.

**Comment by worldlydev** [comment]
I really hope this is considered for a future update. Maybe even 1.0 🤷‍♂️😉

**Comment by relisiuol** [comment]
Okay, lemme implement that.

**Comment by ann0see** [comment]
I saw the same problem here:
https://imgur.com/a/TRtNnFV (Image is SFW)

**Comment by worldlydev** [comment]
> I saw the same problem here:
> https://imgur.com/a/TRtNnFV (Image is SFW)

Can confirm that I have that issue as well. Just didn't get around to reporting it. It says kansel in the top right but should say kanseller.

![78F8959D-9880-4D8E-9096-498D904BEF65](https://user-images.githubusercontent.com/51668635/68074954-c0570080-fda1-11e9-83c5-6393be91d326.png)

**Comment by ann0see** [comment]
And in the Packaging area the Header looks strange. https://imgur.com/a/U0K3RDI

**Comment by wstyres** [comment]
Implemented in #513
