### ISSUE TITLE
[BUG] No dark mode in peek and pop menu

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#512]
Report #343 
Should be fixed in ccadae6

I recently tested a debug version from @wstyres in the Discord and the new peek and pop menus seemed to be present. However they are not present in the latest release. None of the menus are themed in Zebra 1.0~beta 24-1.

I don't know if this is true for everybody or if it is only affecting me.

Device info:
iPhone Xs
iOS 12.1.1 b3

**Comment by wstyres** [comment]
Should be fixed again as of 6a5bcfb3e475e66a475582dbb4df079b20b03731

**Comment by gkeep** [comment]
Broken again? beta33-1
![2532F52F-C79A-425C-8987-B569E793FEE2](https://user-images.githubusercontent.com/20600053/70893413-169f9c00-1ffc-11ea-8787-627ecd301cf2.png)

**Comment by eve0415** [comment]
I think it refer to #616

**Comment by gkeep** [comment]
It appears so. Good to know that this is a known bug.

**Comment by worldlydev** [comment]
> I think it refer to #616

Correct. This bug reappeared when the fix for #616 was implemented. It's a known issue.
