### ISSUE TITLE
[BUG] Lag in search tab compared to beta 23

### ISSUE THREAD

**Issue by qnblackcat** [wstyres/Zebra#514]
**Describe the bug**
Zebra is very lag when im searching tweak

**To Reproduce**
Searching tweaks

**Expected behavior

**Screenshots

**Device Information (please complete the following information):**
 - iOS Version: iOS 12.2 
 - Zebra Version: ~beta 24-1
 - Device Type: iPhone 6s

**Crash Log or System Log

**Additional context**
Downgrade to beta~23 and everything is fine. No more lag when searching

**Comment by worldlydev** [comment]
Don't think this is a bug. Probably just the issue with live search for older devices. Open Zebra > go to the settings page > turn off search while typing

**Comment by PoomSmart** [comment]
https://twitter.com/PoomSmart/status/1190640370314436610

Potentially related.
