### ISSUE TITLE
[BUG] Only Cancel button after repo has been synced

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#516]
**Describe the bug**

Once all the repos are updated I get a screen showing nothing just a Cancel button at the bottom

**To Reproduce**

1. Open Zebra
2. Wait a few seconds to finish update all of the repos

**Expected behavior**

When there is no error, like internet offline, it should't have been pop up.

**Screenshots**

https://media.discordapp.net/attachments/572784833714192395/640309948600942632/image0.png?width=263&height=468

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta24-1,24-2
 - Device Type [e.g. iPhone or iPad]: iPhone

**Comment by worldlydev** [comment]
Experiencing the same thing. 
https://imgur.com/gallery/WOojWXB

**Comment by wstyres** [comment]
Should be fixed as of 206d9247

**Comment by eve0415** [comment]
Thanks. It was fixed with the latest beta 25
