### ISSUE TITLE
[BUG] Queue bar not appearing for swipe actions

### ISSUE THREAD

**Issue by joshuah345** [wstyres/Zebra#517]
**Describe the bug**
The floating queue does not appear when swiping to modify any package.

**To Reproduce**
1. Swipe left on any package and choose any option (except downgrade and upgrade)

**Expected behavior**
The queue should appear above the tab bar (just like it did in beta23)

**Screenshots**
https://imgur.com/gallery/XezwQgl

**Device Information:**
 - iOS Version: 12.4 
 - Zebra Version 1.0~beta24-2
 - Device Type: iPhone 

**Additional context**
The floating queue will appear when triggered from the packages tab then swiping down or pressing continue.

**Comment by worldlydev** [comment]
Just press the queue label in the top left. Hopefully this gets fixed tho

**Comment by wstyres** [comment]
Should be fixed as of b9d9ab6.
