### ISSUE TITLE
[BUG] Modification badges do not appear

### ISSUE THREAD

**Issue by joshuah345** [wstyres/Zebra#518]
**Describe the bug**
Badges do not appear on packages that are currently in the queue.
(Upgrade, Remove, Install,) etc

**To Reproduce**
1. Add any package to the queue
1b. if the package is in a list, Skip step 2
2. Exit the depiction and search for the package

**Expected behavior**
An indicator for what will happen to the package should be next to the name

**Screenshots**
https://imgur.com/gallery/XezwQgl

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: 1.0~beta24-2
 - Device Type: iPhone X

**Comment by wstyres** [comment]
Should be fixed as of b9d9ab6.
