### ISSUE TITLE
More localization UI bugs

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#519]
**Describe the bug**

Just for context my device language is set to Norwegian Bokmål.

While installing a tweak the cancel button says kansel but should say kanseller. It is cut off.

In the packages tab the update all button pushes the UISegmentedControls to the left. Perhaps move the button down or replace it with an icon (like in the 3d touch menu for the appstore or testflight)?

And in the queue the file size of the tweak is cut off.

![510A2B0B-EFE2-4905-AAFB-FBBBBBAA3800](https://user-images.githubusercontent.com/51668635/68091541-6168b880-fe81-11e9-8e08-e1c4623e2858.jpeg)
![B7996784-E75A-4C97-8BC2-3D9619F3D68C](https://user-images.githubusercontent.com/51668635/68091542-6168b880-fe81-11e9-8f65-1c0a3e27c966.jpeg)
![0566AC07-F692-486F-8AD5-89FA77C490AE](https://user-images.githubusercontent.com/51668635/68091543-6168b880-fe81-11e9-99ae-1500e9eea83d.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
Zebra 1.0~Beta 24-2
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Comment by worldlydev** [comment]
Credit to @ann0see for this one. The queue text and empty also mess up the UISegmentedControl in the packages tab. 
![2EACA10E-D6D8-4BD7-B0F4-96DBA02C2528](https://user-images.githubusercontent.com/51668635/68091755-10a68f00-fe84-11e9-81ad-48d79aead033.jpeg)

**Comment by worldlydev** [comment]
@Willy the more I think about the more difficult it seems to fix lots of these. The queue one and the installing page one seem like quick fixes but the others aren't as straight forward. 

Maybe change the the "setting for swipe actions display as" to just "actions display as". An option for icons for actions would be awesome. 

Gonna open a new issue.

**Comment by MaciejBorek** [comment]
![image0](https://user-images.githubusercontent.com/39622526/68092435-5b77d500-fe8b-11e9-83e8-85c32db6923c.png)
color selection is off the screen, settings in general are broken

**Comment by gkeep** [comment]
@MaciejBorek This is fixed now. See #513

**Comment by wstyres** [comment]
Current plans for this are:
- Move the segmented control down into the tableview and have a "filter" button so that it takes up a lot less space. 
- The "Queue" and "Clear" buttons have been removed as of b25 so hopefully that allows for more space

**Comment by wstyres** [comment]
@worldlydev Does the issue in the console still appear?

**Comment by worldlydev** [comment]
> @worldlydev Does the issue in the console still appear?

If you are referring to the cancel button being cut off then no. That has been fixed.

**Comment by worldlydev** [comment]
> Current plans for this are:
> 
> * Move the segmented control down into the tableview and have a "filter" button so that it takes up a lot less space (this likely won't happen until after 1.0 though)
> * The "Queue" and "Clear" buttons have been removed as of b25 so hopefully that allows for more space

Filter button like in the messages app?
![6E0C40E7-72C2-48CB-B93B-064BE028601F](https://user-images.githubusercontent.com/51668635/71194181-c8083100-228b-11ea-89aa-5facb6ee75f5.jpeg)
I think that would work pretty well.

**Comment by aabosh** [comment]
The queue truncate bug has also been fixed as of b329ee7d. Please retest when the next beta is out.

**Comment by worldlydev** [comment]
Can confirm that it is fixed.
