### ISSUE TITLE
Getting error for upgrading APT 0.6 transitional  and core utilities 

### ISSUE THREAD

**Issue by zaheeralam82** [wstyres/Zebra#52]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - AUPM Version [e.g. 1.0~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Make sure that you have the proper repos installed. If you are using Chimera, do not use the Elcubaratus repo and instead use the Chimera repo and vise versa.

**Comment by zaheeralam82** [comment]
So can u advice which repo isn’t proper cuz I just had all those repos on Sileo with no issue

**Comment by wstyres** [comment]
A list of repos that you have added would be helpful to solve this issue

**Comment by wstyres** [comment]
Closing this issue as it is most likely due to having improper repos in Zebra
