### ISSUE TITLE
Icons for all actions

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#520]
**Is your feature request related to a problem? Please describe.**

#519

**Describe the solution you'd like**

I want the"swipe actions show as" setting to just be "actions show as". Should squash lots of UI bugs related to localizations that may be awkward to fix. Plus I really like the idea of icons for everything. It seems like it could make for a really clean UI.

**Additional context**

**Comment by worldlydev** [comment]
Some quick mockups. Not my proudest work but you get the point. I suggest the update all icon from the appstore or testflight's 3d touch menu for update all. The apple music queue icon makes since for the queue since it is obviously apple music inspired already. And just a simple x for clearing the queue.

![35204797-9875-4B33-8391-0D9257488317](https://user-images.githubusercontent.com/51668635/68092238-5f0a5c80-fe89-11e9-9623-ab7fa84cd106.jpeg)
![B67BC418-DE99-4903-AE9F-74C8FF36A554](https://user-images.githubusercontent.com/51668635/68092239-5fa2f300-fe89-11e9-85b5-49a2d93b04b9.jpeg)

**Comment by worldlydev** [comment]
Update: some of the Sf Symbols look great. Would love it if some of them were used. Maybe "list open" for queue?

**Comment by wstyres** [comment]
Looks like there may be a way to export the symbols for use on less than iOS 13. I'll look into this because it would be a pretty easy solution.

**Comment by worldlydev** [comment]
> Looks like there may be a way to export the symbols for use on less than iOS 13. I'll look into this because it would be a pretty easy solution.

Yeah I saw something about exporting as svg.

**Comment by worldlydev** [comment]
You closed the issue. Does that mean this won’t be implemented and isn’t being considered for the future?

**Comment by wstyres** [comment]
Most text cannot be conveyed properly with a simple icon. We're going to try moving things out of the nav bar like in the solution mentioned here https://github.com/wstyres/Zebra/issues/519#issuecomment-550654723
