### ISSUE TITLE
[BUG] App crashes when searching for '3'

### ISSUE THREAD

**Issue by MTACS** [wstyres/Zebra#524]
**Describe the bug**
When the option 'Search while typing' is enabled, typing just '3' in search crashes app

**To Reproduce**
Open Search page and enter 3 into the search box

![image](https://user-images.githubusercontent.com/13209789/68171720-ea93f400-ff42-11e9-9360-747541f5663a.png)

iPhone X, iOS 12.4
Zebra 1.0~beta24-2

**Comment by wstyres** [comment]
Not able to reproduce this. Could you send a list of repos that I can test with?

**Comment by MTACS** [comment]
https://psty.io/p?q=873bb

**Comment by wstyres** [comment]
![Simulator Screen Shot - iPhone X - 2019-11-04 at 21 15 59](https://user-images.githubusercontent.com/19736790/68173232-5cbb0780-ff48-11e9-9f01-66c54e2dd6f4.png)

Not able to reproduce on the Simulator. I'll try again on an actual device tomorrow and see if I get the crash then.
