### ISSUE TITLE
[BUG] UI Bug - Swipe to remove in search

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#525]
**Describe the bug**

When you search for a package in Zebra and no results are found Zebra shows text that reads "no results are found". You can swipe to delete it even though it isn't a package.

It should only be an option to remove it from the search log. Not while in search.

**To Reproduce**

Search for anything that gives no results. Then swipe to delete on the shown text.

**Expected behavior**

I expect nothing to happen/swipe actions shouldn't show up.

**Screenshots**

Screen recording:
https://imgur.com/gallery/IIfa25j
Screenshot:
![ADF95973-62D2-4D99-915A-D27403695C0C](https://user-images.githubusercontent.com/51668635/68247380-04086f00-001b-11ea-8d25-abb7ca60a30e.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0~beta 24-2
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Comment by wstyres** [comment]
Fixed as of 3dca329

**Comment by worldlydev** [comment]
Seems to be fixed.
