### ISSUE TITLE
Zebra crashes after changing filter on packages tab

### ISSUE THREAD

**Issue by RaZeR9** [wstyres/Zebra#526]
**Bug**
Zebra crashes after changing filter by size on packages tab.

**To Reproduce**
1. Open Zebra
2. Change to packages tab
3. Change filter by size

**Expected behavior**
Show all packages installed by size.

**Screenshots**
https://imgur.com/a/hXd34wM

**Device Information:**
 - iOS Version: 12.4
 - Zebra Version:  1.0~beta24-2
 - Device Type: iPhone 6 Plus

**Crash Log or System Log**
Don’t have, sorry.

**Additional context**
Downgrading to a older version and updating doesn’t clear the filter.

**Comment by TheTrumpetDude1** [comment]
I also have this issue.

**Comment by wstyres** [comment]
This issue should be resolved in beta 27. Please try updating and see if the size filter works now.

**Comment by RaZeR9** [comment]
Issue solved! Thanks!
