### ISSUE TITLE
[BUG] Queue won't go away after package installation

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#527]
**Describe the bug**

After installing a tweak that doesn't require a respring the console automatically closes. However the queue doesn't go away. It is stuck and says queue cleared.

**To Reproduce**

Install a package that doesn't require a respring. I personally reinstalled emoji library.

**Expected behavior**

I expect the queue to close itself as it is no longer needed.

**Screenshots**

Screenshot:
![43E10C46-D47F-4DCB-A224-B1B668613F62](https://user-images.githubusercontent.com/51668635/68343448-19e66480-00ed-11ea-8994-1dbf70df783d.jpeg)
Screen recording:
https://imgur.com/gallery/bbfGFXq

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0~Beta 25
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Comment by eve0415** [comment]
One more thing, after you've installed something and the queue tab won't go away, you cannot install nor do anything because you cannot open queue page.

**Comment by wstyres** [comment]
Should be fixed as of 286ab9692a7780e1a458b9451595584377c54c05

**Comment by wstyres** [comment]
Should be fixed in beta 26. I'm going to leave this issue open for you to test it @worldlydev @eve0415 in case there are more issues. If you can both verify it doesn't happen anymore then feel free to close the issue.

**Comment by eve0415** [comment]
Yes, I think its fixed, Thanks

**Comment by worldlydev** [comment]
Can confirm that it has been fixed for me at least.
