### ISSUE TITLE
[Bug] Disabling dark mode on the report a bug page messes up the ui

### ISSUE THREAD

**Issue by absidue** [wstyres/Zebra#528]
**Describe the bug**

When disabling dark mode after tapping the "Report a Bug" cell in Zebra's settings break colours of the home view, all button/links in the navbar and the status bar.

**To Reproduce**

1. Enable dark mode
2. Open the setttings view
3. Tap the "Report a Bug" cell
4. Disable dark mode in the navigation bar
5. Go back to the settings view
6. Leave the settings view
7. Enjoy the lovely colours of the ui ;)

**Expected behavior**

Disabling dark mode should properly update the colours of all relevent elements.

**Screenshots**

Ignore my bad blanking skills please :(

![EC6F541C-DADB-4771-A127-12E8186FEBCE](https://user-images.githubusercontent.com/48293849/68411627-14d7f280-018b-11ea-9cda-5224a23178d0.jpeg)
![F7AE82AB-793A-4DDF-93FB-8E875795E9F7](https://user-images.githubusercontent.com/48293849/68411628-14d7f280-018b-11ea-97f9-38ec8960ed9a.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta25-1
 - Device Type [e.g. iPhone or iPad]: iPhone

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

Not applicable

**Additional context**

Affects all variants of the dark mode
Affects all tabs

**Comment by wstyres** [comment]
ZBWebViewController, which manages the bugs view, will be removed eventually with the coming redesign. Because of this, I'm just going to remove the "dark mode" button from the web view and close the issue.
