### ISSUE TITLE
[BUG] Depiction scrolls behind top info while loading

### ISSUE THREAD

**Issue by Aransh** [wstyres/Zebra#529]
**Describe the bug**
Depctions in Zebra scroll behind the top info section and then gets stuck

**To Reproduce**
1. open package page.
2. Wait until the web depiction loads a little (shows the ad or something) but not all the way (indicated by the loading bar on top).
3. Start scrolling on the web depiction.
4. When it fully loads, experience the weird behavior, sometimes unable to acroll back up. It behaves differently every time (probably relative to the time when you start scrolling).

**Expected behavior**
1. Open package page
2. Scroll down with the top info section scrolling too

**Screenshots**
Screen recording of an example:
`https://streamable.com/s/m56r2/tprgbd`

**Device Information**
 - iOS Version [iOS 12.4]: 
 - Zebra Version [1.0\~beta25-1]: 
 - Device Type [iPhone X🅂 Max]:

**Comment by wstyres** [comment]
Unfortunately we will have to address this issue in the redesign and not for 1.0 as we're going to be re-working the depiction page.

**Comment by wstyres** [comment]
This was fixed in beta27
