### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by greatvaluesoda** [wstyres/Zebra#53]
Date: 2019-05-11 21:01:01 +0000
Process: Zebra
Bundle id: xyz.willy.Zebra
Exception type: NSInvalidArgumentException
Reason: *** -[__NSDictionaryM setObject:forKey:]: key cannot be nil
Culprit: Unknown
Device: iPhone 7 Plus, iOS 11.3.1
Call stack:
0   CoreFoundation                      0x000000018165ada4 __exceptionPreprocess
1   libobjc.A.dylib                     0x00000001808145ec objc_exception_throw
2   CoreFoundation                      0x00000001815f3750 _CFArgv
3   CoreFoundation                      0x0000000181528c48 -[__NSDictionaryM setObject:forKey:]
4   Zebra                               0x000000010438f680 Zebra + 79488
5   Zebra                               0x00000001043a0510 Zebra + 148752
6   Zebra                               0x000000010438e4e0 Zebra + 74976
7   CFNetwork                           0x0000000181daf760 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.207
8   Foundation                          0x0000000182082e88 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
9   Foundation                          0x0000000181fc48d0 -[NSBlockOperation main]
10  Foundation                          0x0000000181fc3cac -[__NSOperationInternal _start:]
11  libdispatch.dylib                   0x0000000180f4cae4 _dispatch_client_callout
12  libdispatch.dylib                   0x0000000180f541f4 _dispatch_block_invoke_direct$VARIANT$mp
13  libdispatch.dylib                   0x0000000180f4cae4 _dispatch_client_callout
14  libdispatch.dylib                   0x0000000180f541f4 _dispatch_block_invoke_direct$VARIANT$mp
15  libdispatch.dylib                   0x0000000180f540e0 dispatch_block_perform$VARIANT$mp
16  Foundation                          0x0000000182084750 __NSOQSchedule_f
17  libdispatch.dylib                   0x0000000180f4cae4 _dispatch_client_callout
18  libdispatch.dylib                   0x0000000180f54f18 _dispatch_continuation_pop$VARIANT$mp
19  libdispatch.dylib                   0x0000000180f53850 _dispatch_async_redirect_invoke$VARIANT$mp
20  libdispatch.dylib                   0x0000000180f59d30 _dispatch_root_queue_drain
21  libdispatch.dylib                   0x0000000180f59a80 _dispatch_worker_thread3
22  libsystem_pthread.dylib             0x000000018127ffac _pthread_wqthread
23  libsystem_pthread.dylib             0x000000018127fb08 start_wqthread

**Comment by wstyres** [comment]
What repos are you using?

**Comment by wstyres** [comment]
#84 looks like the same issue as this and the user has reported that as fixed with a deb I gave him so I'm closing this issue.
