### ISSUE TITLE
[Localize] Untranslated strings

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#531]
There are still a few untranslated strings.

![555B708E-9C8C-4966-8BAB-FE61881E7CEB](https://user-images.githubusercontent.com/51668635/68431968-bffca200-01b3-11ea-8601-ab1b7e806fee.jpeg)
![A093759A-67BF-4A2C-8F68-9790B1D622B9](https://user-images.githubusercontent.com/51668635/68431969-bffca200-01b3-11ea-8425-4476c0a40d54.jpeg)
![D787B702-1785-4F3A-9069-9E8F10FA6B24](https://user-images.githubusercontent.com/51668635/68431970-bffca200-01b3-11ea-8b0e-3a100284abf6.jpeg)
![1A9695B1-EB63-41F9-AD4A-6F1007D7DD1E](https://user-images.githubusercontent.com/51668635/68431971-bffca200-01b3-11ea-9a14-15e073f8daea.jpeg)

Would it be possible for the report a bug page to get a native page in the same way the credits page did? #528

**Comment by worldlydev** [comment]
Also not sure if this is easy to implement but it would be awesome with localization support Reddit tags.
![C33463B7-0862-431B-8208-F5671BF8657E](https://user-images.githubusercontent.com/51668635/68432411-af006080-01b4-11ea-99cc-7bc6eaf81007.jpeg)

**Comment by worldlydev** [comment]
![7DFE7E00-C242-43D2-B064-C8077463AD2E](https://user-images.githubusercontent.com/51668635/68433271-677ad400-01b6-11ea-9bc3-307842471cb4.jpeg)

**Comment by worldlydev** [comment]
![7DFE7E00-C242-43D2-B064-C8077463AD2E](https://user-images.githubusercontent.com/51668635/68433271-677ad400-01b6-11ea-9bc3-307842471cb4.jpeg)

**Comment by wstyres** [comment]
"Changelog" and "Stores" have been fixed for the next beta. The "Package Information" and bug reporting page will not be localized as they will be removed or made native in an upcoming version. Reddit tags will be localized in the redesign and icon titles will have to be thought about because there isn't a good way to localize those.

**Comment by worldlydev** [comment]
@wstyres 
![4F72467E-69DF-4B8B-8F58-7175E581569F](https://user-images.githubusercontent.com/51668635/68539835-c775a400-0389-11ea-900e-b2e049def74c.jpeg)

Just realized I found another untranslated string.
