### ISSUE TITLE
[BUG] Queue Status label not removed after queue is cleared

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#532]
**Describe the bug**

As the title says, label like “reinstall”, “delete, won’t be cleared in the package list after que is cleared. 

**To Reproduce**

1. do anything you want with the package. Install, Delete, Upgrade
2. open que list
3. clear all ques

**Expected behavior**

The label should be removed when que is cleared.

**Screenshots**

https://media.discordapp.net/attachments/572784833714192395/642179471658713088/video0.mov

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta25-1
 - Device Type [e.g. iPhone or iPad]: iPhone

**Comment by eve0415** [comment]
It still happens on the latest
https://www.dropbox.com/s/qgyt5vya3buymwk/RPReplay_Final1573561647.mp4?dl=0

**Comment by PoomSmart** [comment]
Fixed as of e59b6a90c59adb74d2b298c19c7c9cfd7e66eedb

**Comment by eve0415** [comment]
This issue came out from rc1.
Clearing all queue is ok but no when removing one by one.
https://cdn.discordapp.com/attachments/572784833714192395/656678289871601743/video0.mov

**Comment by eve0415** [comment]
https://cdn.discordapp.com/attachments/572784833714192395/656698847032246283/video0.mp4
Note: Removing from queue individually.
