### ISSUE TITLE
[BUG] dependencies installing marked as remove

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#533]
**Describe the bug**

Dependencies trying to install is marked as remove in the que tab.

**To Reproduce**

1. Try to install any tweaks that require dependencies.
2. Open que tab

**Expected behavior**

It should say “Install” or marked as “Install”

**Screenshots**

![136FEA21-A2A1-41F6-B380-7BD3464DE0E9](https://user-images.githubusercontent.com/40632436/68443558-91b0ae00-0217-11ea-81d5-136d929cbb63.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta25-1
 - Device Type [e.g. iPhone or iPad]: iPhone

**Comment by wstyres** [comment]
Could you elaborate more on how this situation occurred? Do you have both iThemer and SnowBoard installed and you're updating SnowBoard?

**Comment by eve0415** [comment]
I just did a test and found out that dependencies is doing wrong in zebra.
I never installed iThemer but zebra was trying to remove. I don't know why.
And, if you can watch this video, I don't have anemone, ithemer but the dependencies of the package conflict with some packages that need to be removed and zebra try to do that. (sorry, bad english)
https://www.dropbox.com/s/5jzrckghglqn06u/RPReplay_Final1573278163.mp4?dl=0

**Comment by eve0415** [comment]
So the title should be different because its not about "dependencies installing marked as remove" issue

**Comment by rctfan929** [comment]
I have the same issue. When trying to update snowboard in Zebra it wants to remove a theme and also iThemer (never installed). Can update fine in Cydia.

**Comment by wstyres** [comment]
Ok, this makes more sense. Looks like when trying to queue packages for removal that conflict with the package you're installing, it checks ALL the packages on the device, not just the ones installed.

**Comment by wstyres** [comment]
Fixed in cc7145111ef41f1e810e05720ff3cf240acd5c7a
