### ISSUE TITLE
[BUG] LocalRepository Package’s description page has UI issue

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#534]
**Describe the bug**

As the title says, LocalRepository Package’s (installed from Filza) description Page has a UI issue.
I think Zebra cannot calculate the size of the Package because it was installed via Filza.

**To Reproduce**

1. Install package that is not on any repo via Filza.
2.Open Zebra and go to description page of what you installed.

**Expected behavior**

I dunno. It must be readable.

**Screenshots**

![CA9E847B-2592-4D2A-9D39-6277ACC6B3C5](https://user-images.githubusercontent.com/40632436/68447838-ba8b7000-0224-11ea-897f-2b877ad5dc56.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta25-1
 - Device Type [e.g. iPhone or iPad]: iPhone

**Comment by worldlydev** [comment]
Can confirm
![B3FF1609-DD97-448C-9D51-91EE1ECFFD7C](https://user-images.githubusercontent.com/51668635/68470815-1baf4580-021d-11ea-9acf-897a576b4b44.jpeg)

**Comment by eve0415** [comment]
It’s fixed, now show us “-“
