### ISSUE TITLE
[BUG] Cannot exit featured repo selection in Settings

### ISSUE THREAD

**Issue by gkeep** [wstyres/Zebra#535]
**Describe the bug**
User cannot exit featured repo selection in Settings.

**To Reproduce**

1. Open Settings
2. Select 'Feature Type': Random
3. Open 'Select Repos to be Featured'
4. Select/Unselect repos
5. Try to exit.

**Expected behavior**
Button 'Done' should appear to exit selection mode.

**Screenshots**
[Video demonstration](https://i.imgur.com/ucj18md.mp4)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta25-1
 - Device Type [e.g. iPhone or iPad]: iPhone 5s

**Crash Log or System Log**
Not applicable.

**Comment by PoomSmart** [comment]
The new navigation design will fix this

**Comment by PoomSmart** [comment]
Fixed as of 0726d0d778e2f2c7d33194b71fca85b58f57995e
