### ISSUE TITLE
Cannot see packages on beta 24 and 25

### ISSUE THREAD

**Issue by kikouyou** [wstyres/Zebra#537]
**Describe thebug**

The bug was initiated on 24 by pressing the new size button in the package view. This locks the package view on size and does not display packages. 25 does not fix this. I had to revert to 23.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Duplicate of #526
