### ISSUE TITLE
Package version strings do not have proper RTL alignment

### ISSUE THREAD

**Issue by Aransh** [wstyres/Zebra#539]
Several strings are incorrectly aligned for RTL languages, for example Size/Version Cells in package info.
Example of How Zebra's page looks like:
![Image](https://i.imgur.com/9gO4LtN.jpg)
Mockup of how it should look like:
![Image](https://i.imgur.com/wMHsmBh.jpg)

**Comment by wstyres** [comment]
Queue strings were modified in b13ed1018ebcef7affaa2668360ba5119049dc2b to support RTL formats for queue strings

**Comment by Aransh** [comment]
Queue strings? That's not what this issue is about 😅

**Comment by wstyres** [comment]
Was referring to your Discord message, the strings in the depictions are not fixed yet.

**Comment by wstyres** [comment]
Just for an update on this, these issues will probably have to be addressed when we redesign the depiction page. To make it easier, we're likely just going to remove those troublesome strings with parenthesis in them and separate them into different cells.

**Comment by wstyres** [comment]
Moving this back to 1.2 since we have a new design in place for the depiction page.

**Comment by relisiuol** [comment]
This issue seems solved. @Aransh, can you confirm?

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-05-08 at 10 27 08](https://user-images.githubusercontent.com/49282232/81387140-7ff08a80-9116-11ea-802f-4d469303f70b.png)

**Comment by Aransh** [comment]
@relisiuol Definitely much better, 
In your screenshot "size" is perfect, and version looks correct too (Although installed version has ":", instead of a dot, is this normal?)
But as I expected, there's an issue with versions containing "~".
Here's a screenshot of how it currently appears:
![image](https://user-images.githubusercontent.com/11724502/81387914-2a20e000-9120-11ea-88fd-ca3045ac0960.png)

And here's a visualization of how it should look:
![image](https://user-images.githubusercontent.com/11724502/81388692-52f5a500-9121-11ea-9eab-5022338cb487.png)

**Comment by wstyres** [comment]
We've moved to a different layout for showing installed version/size so this issue should no longer occur.
