### ISSUE TITLE
[BUG] UIKit Tools Conflict

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#542]
**Describe the bug**

While trying to update Sileo to version 1.5.2 in Zebra it said "Sileo has issues which can't be solved: "UIKit Tools" conflicts with Sileo." When updating Sileo in Sileo it didn't have any issues.

**To Reproduce**

Update Sileo to version 1.5.2 from 1.5.1.

**Expected behavior**

I expect it to update without issue.

**Screenshots**

![108997E9-86E9-44ED-A849-75EAA4375820](https://user-images.githubusercontent.com/51668635/68537747-ba48bd00-0369-11ea-82c3-8701f5be7d7c.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0~beta 25-1
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
Odd, is this on unc0ver or Chimera?

**Comment by worldlydev** [comment]
> Odd, is this on unc0ver or Chimera? Also, what version were you upgrading from?

Chimera. Upgraded from 1.5.1 to 1.5.2.

**Comment by wstyres** [comment]
Looks like Zebra isn't checking the specific version for conflicts. UIKitTools has a conflict with `org.coolstar.sileo (<= 0.8b9)` and Zebra is simply ignoring the version requirement for that conflict. I will look into it a little more.

**Comment by wstyres** [comment]
Should be fixed as of 582e312c9e265bdf12184606bcb333df17a351fa
