### ISSUE TITLE
Search in packages tab

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#543]
**Is your feature request related to a problem? Please describe.**

No. Just think it would be easier to navigate your packages, especially if you have a lot, if you could search.

**Describe the solution you'd like**

Similar to Sileo's implementation. Sweeping down reveals a search bar.

As such (Screen recording): https://imgur.com/gallery/49ETPsV

![46A6BEAD-C710-45E7-A486-B8549ECDF27F](https://user-images.githubusercontent.com/51668635/68539754-76b17b80-0388-11ea-979e-653dd864031d.png)

Mockup in Zebra. This was just a quick edit so please implement it better than this but you get the idea.
![9E53138F-764B-4A40-9347-FBE9E705138E](https://user-images.githubusercontent.com/51668635/68835719-f6a55180-06b8-11ea-98b9-95e85c13558e.png)

**Comment by worldlydev** [comment]
Edit: would love search in individual repos as well:

![CE852D1B-7E71-4D31-98F6-7B9E7EA4AD9F](https://user-images.githubusercontent.com/51668635/68835770-16d51080-06b9-11ea-9647-2dacf2b2d565.png)

**Comment by worldlydev** [comment]
Perhaps it should be implemented like messages app.

![EF2B2ECA-FE4D-43C2-B3B2-BB895326E8DE](https://user-images.githubusercontent.com/51668635/68844874-c5358180-06ca-11ea-9013-be800ad134e2.jpeg)

Title up top. Search under. Then move the segmented control down into it's own feel below the search bar.

**Comment by worldlydev** [comment]
Oooh. Really like Sileo's implementation as well. With a login page for the stores up top in the category view. With search in the packages view. As such:

![620F6813-227D-476F-A56E-6FAC7BAE987A](https://user-images.githubusercontent.com/51668635/69830472-45102f80-1225-11ea-9f2f-cd6f630b61ce.png)
![7064BBAA-C651-4111-B7A0-C9255AB03E01](https://user-images.githubusercontent.com/51668635/69830473-45102f80-1225-11ea-824f-5d24cc632c1e.png)

**Comment by wstyres** [comment]
Closing in favor of #630
