### ISSUE TITLE
[BUG] Certain packages can’t be updated in Zebra

### ISSUE THREAD

**Issue by rctfan929** [wstyres/Zebra#544]
**Describe the bug**
I can’t update Snowboard through Zebra. I will update through Cydia. All other packages seem to upgrade normally. 

1. Select Snowboad
2. Select Modify
3. Choose Upgrade
4. Confirm upgrade in queue
5. Restart Springboard
6. Open Zebra or Snowboard to see old version still installed.

**Expected behavior**
I expect that the upgrade should happen successfully.

**Device Information (please complete the following information):**
 - iOS Version : 12.4
 - Zebra Version : beta26
 - Device Type : iPhone 6s

**Comment by wstyres** [comment]
Do you have a screenshot of the Console that you could provide? It would be helpful to view that log.

**Comment by rctfan929** [comment]
![8EEA1B43-91AD-4958-A541-DEA8EA310646](https://user-images.githubusercontent.com/46878212/68550481-1e529c00-03d1-11ea-8177-423fc9974067.png)

**Comment by eve0415** [comment]
@rctfan929 Can you try “dpkg --configure -a’ on your device using newterm or something like that? And then try again on zebra.

**Comment by wstyres** [comment]
Yes it seems that the package was not configured properly when installed the first time. Does uninstalling SnowBoard then installing it again fix the issue?

**Comment by rctfan929** [comment]
@wstyres That fixed the upgrade issue. But now when I try to downgrade Snowboard in Zebra it wants to uninstall any snowboard extension installed and snowboard application. It should just queue the downgrade.

**Comment by wstyres** [comment]
The downgrade issue with removal should be fixed as of 34844fc558505de962b06ca8a54c1b8bc6381b49
