### ISSUE TITLE
[BUG] Cercube for YouTube conflict

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#548]
**Describe the bug**

Can't update to the version 5.1.0 of Cercube to 5.1.1 on https://apt.alfhaily.me/

**To Reproduce**

^^

**Expected behavior**

I expect it to update without issue.

**Screenshots**

![4BB60D71-69A9-48BF-9D9F-3827AA6E7FEB](https://user-images.githubusercontent.com/51668635/68562532-695cc580-044a-11ea-94cf-077f7c2fca88.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0~beta 26-3
 - Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Did the package ID of cercube change by chance? The 5.1.1 version conflicts with `me.freemanrepo.cercube`.

**Comment by worldlydev** [comment]
> Did the package ID of cercube change by chance? The 5.1.1 version conflicts with `me.freemanrepo.cercube`. This might be a lapse in logic on Zebra's end but our algorithm currently prefers installed packages over packages that you want to install in terms of Conflicts. Perhaps that should be changed.

Not sure if the package ID changed. All I know is that I can update it in Sileo without issue.

**Comment by wstyres** [comment]
Can't really debug this without a proper control file for the older version and it is not still hosted on his repo.

**Comment by wstyres** [comment]
Was able to get an old version. Will investigate.

**Comment by wstyres** [comment]
Found the problem, `me.alfhaily.cercube` conflicts with `me.alfhaily.cercube.lib` which when searching the database comes up as an issue.

**Comment by wstyres** [comment]
This should be fixed as of 0f842b8461dbd827c4d5124330b70eacdc52f4e8. It shouldn't cause issues with other conflicts but we will have to test it for the next beta.
