### ISSUE TITLE
[Localize] Albanian Translations

### ISSUE THREAD

**Issue by rkycyku** [wstyres/Zebra#549]
**What language are you adding?**
Albanian

**Please paste a link to the translated .strings file you have created. If you have not created a .strings file already, please see [the README](https://github.com/wstyres/Zebra#translations) for more info**
https://controlc.com/7b09888c

**Are you a member of our discord? If so, what is your username so we can give you a special role to be notified of future translation updates**
No

**How would you like to be credited? (Name, Twitter Link, Website, etc.)**
Rilind Kycyku,@rilindkycyku16 - Twitter

**Comment by Nexuist** [comment]
Faleminderit nga shqiperia!

**Comment by wstyres** [comment]
Thanks for your contribution! I've put your strings in Zebra and uploaded them to Crowdin as well. To translate the rest of the strings head on over to https://translate.getzbra.com/translate/zebra/28/en-sq to view them all.
