### ISSUE TITLE
Zebra crashes when trying to reinstall any package

### ISSUE THREAD

**Issue by vilP1l** [wstyres/Zebra#55]
**Describe the bug**
Zebra crashes when trying to reinstall any package.

**To Reproduce**
- Go to any package you've installed
- Click reinstall  

**Expected behavior**
The package should reinstall normally.

**Device Information (please complete the following information):**
 - iOS 12.1.1
 - beta9
 - iPhone

**Crash Log or System Log**
Couldn't really get one

**Comment by ahanank** [comment]
Same

**Comment by Insaneous** [comment]
Same. iOS 11.3.1, unc0ver. Here is the crash report from Cr4shed: https://pastebin.com/qBftFa06

**Comment by PoomSmart** [comment]
It seems that all the `ZBPackage` instances OP tried to reinstall have incomplete information, i.e., `filename` field is missing. Moreover, their associated `ZBRepo` are all local ones (`repoID` is 0), as if Zebra failed to correctly assign the repo to the package.

**Comment by wstyres** [comment]
Yeah this is exactly what happens. Packages in repo 0 (locally installed) do not have a filename field. This is just an oversight on my end as I forgot to match these local packages with their repository equivalents when trying to reinstall.

**Comment by wstyres** [comment]
This should be fixed as of fc59523 and it will be in the next beta but I'll leave this issue open for awhile to make sure the problem doesn't happen anymore

**Comment by wstyres** [comment]
Closing this as it should be fixed
