### ISSUE TITLE
[BUG] UI bug in the sources tab

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#550]
**Describe the bug**
There is a UI bug for me. I can’t see the bottom source in the source tab. It's Zebra's repo

**To Reproduce**
Open source page and scroll down.

**Expected behavior**
Should have scroll down more to see able.

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/643589792147177483/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta23(i think) to the latest
 - Device Type [e.g. iPhone or iPad]: iPhone 7

**Comment by greenywd** [comment]
I'm on 13.2.2, iPhone X and it's also occurring for me.

**Comment by wstyres** [comment]
Can't reproduce this on a simulator with a decent amount of repos. Does it happen every time?

**Comment by eve0415** [comment]
I don’t know why but it doesn’t happen any more on beta28 so I’m going to close this issue.

**Comment by greenywd** [comment]
Confirmed fixed here too.
