### ISSUE TITLE
Two tabs being highlighted 

### ISSUE THREAD

**Issue by Aditya245850** [wstyres/Zebra#551]
Whenever you close out of zebra from the app switcher and then relaunch it, it has two tabs highlighted randomly. Unless you tap the tabs it doesn’t go away.

Screenshot:
![1A119158-3461-4C03-9900-8E59B122B5AE](https://user-images.githubusercontent.com/55038679/68632434-5e824f00-04a3-11ea-86a6-9ff77e14be84.png)

 - iOS Version: 13.2.2
 - Zebra Version: 26-4
 - Device Type: iPhone X(10,3)

**Comment by BitGrub** [comment]
Seconded. iPhone 7, ios 13.2.2

**Comment by PoomSmart** [comment]
Fixed as of beab5c496fc69a3b5b865eea9e70ff4b295d5b75
