### ISSUE TITLE
Menu for exporting sources, packages list and wishlist

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#553]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I would love the implementation shown in the screenshot below.

**Describe alternatives you've considered**

Okapi for zebra offers this but okapi is broken and it would be nice if this was integrated directly into Zebra. Would just be a nice little ease of use adjustment.

**Additional context**

![622C3314-B797-4753-B3B4-5F4761B3BDE6](https://user-images.githubusercontent.com/51668635/68662568-5ecf2880-053d-11ea-9149-d0922277cecf.jpeg)

**Comment by worldlydev** [comment]
Update: maybe make it possible to export the wishlist as well? Would make it easy to move everything over to a new device.

**Comment by Juvencus** [comment]
An option for "Both as well, like Flame does for Cydia.
Also, currently the native packages export of Zebra lists them as i.e. "com.chpwn.iconsupport".
Is it possible to export them in a more friendly way with a clean package name?

**Comment by wstyres** [comment]
Something could be done where Zebra would export *everything* like packages and sources and it could be imported back into Zebra and add all sources and all packages. It would be a bit complex but I think that is what is being requested here?

**Comment by worldlydev** [comment]
> Something could be done where Zebra would export _everything_ like packages and sources and it could be imported back into Zebra and add all sources and all packages. It would be a bit complex but I think that is what is being requested here?

I was more hoping for a menu such as the one showed above that lets you export wishlist, packages, or repos.

It would be cool with a sync feature perhaps that saves all settings (like installer) and the other stuff mentioned but that isn't what I'm requesting. Would be great but I already have batchomatic. The many would just be nice for exporting some stuff.

**Comment by wstyres** [comment]
Wishlist export was added in 3e04c44c. What improvements should be made to the Package/Source export screens? The Sources export is designed to be importable back into Zebra so I don't think that will change too much but improvements to the packages export can be made.

**Comment by cxen** [comment]
> 
> 
> Wishlist export was added in [3e04c44](https://github.com/wstyres/Zebra/commit/3e04c44c8c02bcf2565bd785dd0e6cd3b0e951f4). What improvements should be made to the Package/Source export screens? The Sources export is designed to be importable back into Zebra so I don't think that will change too much but improvements to the packages export can be made.

The Sources export is fine, although I think it glitches if the repo has a dash in the link like the Nepeta-Mirror.

Packages export should have the human-readable name of tweaks, instead of the internal package name e.g "IconSupport" instead of "com.chpwn.iconsupport".

**Comment by worldlydev** [comment]
> Wishlist export was added in [3e04c44](https://github.com/wstyres/Zebra/commit/3e04c44c8c02bcf2565bd785dd0e6cd3b0e951f4). What improvements should be made to the Package/Source export screens? The Sources export is designed to be importable back into Zebra so I don't think that will change too much but improvements to the packages export can be made.

Like @cxen 's idea. At least partially.

Maybe something like this:

- xtweak by xauthor (xBundleID) via xsource

Such as:

- SmallSiri by Muirey03 (com.muirey03.smallsiri) via Packix

This makes it easy to read the author and tweak, gives the bundleID, and specifies the source as there are tweaks with the same name or that are hosted in multiple places.

**Comment by wstyres** [comment]
I think for now we can just make it more detailed with the package name and source. It doesn't make much sense from a UX standpoint to have sources and wishlist be exported from the packages tab. We might revisit this in the future when more complex forms of export are available but for the time being I think the more detail will do.

**Comment by wstyres** [comment]
Implemented the more detailed descriptions in a1e7ccae07cd665cd4573baa62d9762e857da73d. We will revise the export menu when doing more complex exports/imports in the future.
