### ISSUE TITLE
[BUG] Zebra says that the Bingner/Elecubratus Repo is not compatible with the checkra1n jailbreak

### ISSUE THREAD

**Issue by Bananastudios** [wstyres/Zebra#556]
**Describe the bug**
Whenever I refresh my sources a warning pops up in Zebra that the Bingner/Elecubratus repo is not compatible with my checkra1n jailbreak and that I should remove it from my sources list.

**To Reproduce**
Refresh your sources in Zebra

**Screenshots**

![0703A179-3DA7-40CF-B626-A4F8F878333E](https://user-images.githubusercontent.com/14057880/68672329-a52e8280-0551-11ea-8700-e7034211c24a.png)

**Device Information (please complete the following information):**
 - iOS Version [13.2.2]: 
 - Zebra Version [e.g. 1.0~beta23-1]: 
 - Device Type [iPhone X]:

**Comment by PoomSmart** [comment]
Please update to the latest beta.

**Comment by wstyres** [comment]
Be sure you have the beta repo added https://getzbra.com/beta/

**Comment by Bananastudios** [comment]
Thank you for your assistance!
