### ISSUE TITLE
[BUG] Package page scroll issue

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#557]
**Describe the bug**

When scrolling on certain packages' pages the page scrolls but the package information stays up top.

**To Reproduce**

In the screen recording below I try to navigate the package page on a package from https://julioverne.github.io/.

**Expected behavior**

I expect the scrolling to function as it does in other repos.

**Screenshots**

Screen recording:
https://imgur.com/gallery/XhwUArK

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
Zebra 1.0~beta26-4
- Device Type [e.g. iPhone or iPad]: iPhone Xs

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
Can you reproduce this reliably? Are you scrolling on the web view itself or on the table?

**Comment by worldlydev** [comment]
> Can you reproduce this reliably? Are you scrolling on the web view itself or on the table? You also say "Other Repos" does this only happen on one repo?

I've only seen this happen on this repo. I scroll on the web view itself as I usually do but normally the table scrolls up along with the web view.
