### ISSUE TITLE
[BUG] Zebra tries to install Substitute with every tweak

### ISSUE THREAD

**Issue by BitGrub** [wstyres/Zebra#561]
**Describe the bug**
On a fresh jailbreak (no tweaks installed) any attempts at installing a tweak will also attempt a force-install of substitute. I had to install my first tweak via Cydia (which correctly chose to install substrate instead) to get around this.

**To Reproduce**
1. Restore RootFS
2. Jailbreak with Checkra1n
3. Try installing any* tweak

*any tweak that needs to be injected

**Device Information (please complete the following information):**
 - iOS Version [13.2.2]: 
 - Zebra Version [26-4]: 
 - Device Type [iPhone 7]:

**Comment by wstyres** [comment]
I'm not able to reproduce this, are you sure you have the correct repos added? You should have the checkra1n utility repo and elcubaratus added. The checkra1n utility repo is the one with Substrate.
