### ISSUE TITLE
Alert that zebra crashes while refreshing repos

### ISSUE THREAD

**Issue by seanie86** [wstyres/Zebra#564]
**Describe the bug**
It seems every time I try to refresh sources now I will get an alert from cr4shed that zebra has crashed and then it will freeze up.

**To Reproduce**
Steps to reproduce the behavior: you should be able to try to refresh the sources and if cr4shed is installed you’ll get an alert saying zebra crashed and then it will freeze up 

**Expected behavior**
I expected to be able to refresh sources like normal. 

**Screenshots**
![8C0D4E05-C4D3-4138-8DDB-089BDBCE2FA6](https://user-images.githubusercontent.com/41923151/68766766-5c6bdd80-05d4-11ea-96d0-59a0c1a2edb7.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 26
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: using unc0ver 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue. im not sure how to add the crash log from cr4shed but I can add that or email it.

**Additional context**
Zebra is awesome! Keep up the great work.

**Comment by wstyres** [comment]
Are you able to reproduce this issue? A screen recording would be helpful if so. Also, could you please try updating to beta 27 to see if that resolves the problem?

**Comment by seanie86** [comment]
Thanks I updated to beta 27 and it works fine now.
