### ISSUE TITLE
Add 3D Touch on Homepage

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#566]
**Describe the bug**

Not really a bug but I swear that this used to be possible. Perhaps I'm just a moron but who knows. It isn't possible to 3d touch on the featured packages on the homepage.

**To Reproduce**

3d touch on the featured packages on the homepage.

**Expected behavior**

I would like it to open up the same menu that is opened up when 3d touching a package in the changes tab or packages tab.

**Screenshots**

![D5CFCF68-CD1C-490A-B895-62B15D6EB1C3](https://user-images.githubusercontent.com/51668635/68771099-a205c600-0627-11ea-997d-d9ec4b7fa78d.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:
Zebra 1.0 ~beta26-4
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
Closing in favor of #764
