### ISSUE TITLE
[BUG] Respring button comes up instead of Close Zebra

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#567]
**Describe the bug**
After installing or re-installing Zebra package, it should have been "Close Zebra". It was on the last beta, if I am correct. But it says Respring where it will not work. When you press Respring, the device might freeze a little and than crash.
When installing other packages and needed to respring, it will work.

**To Reproduce**
Re-install Zebra

**Expected behavior**
I think it should say "Close Zebra" instead of showing "Respring"

**Screenshots**
https://www.dropbox.com/s/8fktfmg14tw6re2/RPReplay_Final1573690296.mp4?dl=0

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta27 & beta27-1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by ann0see** [comment]
Same error here.

**Comment by eve0415** [comment]
It's still not fixed in beta29

**Comment by wstyres** [comment]
Sorry, didn't mean to close the issue, it had a scheduled tag by accident.

**Comment by PoomSmart** [comment]
Finally fixed as of 44b1c8246be6b3069c108116a69ac506eee3ab91

**Comment by PoomSmart** [comment]
Fixed in versions newer than beta 29
