### ISSUE TITLE
Cannot remove packages

### ISSUE THREAD

**Issue by MustyAslan99** [wstyres/Zebra#568]
**Describe the bug**
Discovered this bug when I tried to remove tweak and did the uninstalling thing then respringed then I checked again it was still installed and tried again so nothing changed

**To Reproduce**
Uninstall package..

**Expected behavior**
Package to be uninstalled.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest version
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Checkra1n

**Comment by wstyres** [comment]
By "Latest Version" do you mean beta23 which is available on https://getzbra.com/repo/ or beta27 which is available on https://getzbra.com/beta/

**Comment by MustyAslan99** [comment]
Sorry I mean the beta version 27-1

**Comment by wstyres** [comment]
Ok, can you send a screenshot of what the console says when trying to uninstall a package?

**Comment by MustyAslan99** [comment]
Well unfortunately sadly I do not get error or something somehow it just shows the console without error and it seems really uninstalling package but after respring on Cydia or Zebra the package is still in installed list. 🤔

https://m.imgur.com/gallery/zbeynP0 This when uninstalling
https://m.imgur.com/gallery/v2jMk1X This is after uninstall process. So it's not uninstalled somehow.. and just to confirm I tried it many times on various packages.

**Comment by wstyres** [comment]
I'm not able to see your pictures on imgur, the links are broken.

**Comment by worldlydev** [comment]
> I'm not able to see your pictures on imgur, the links are broken.

Take the imgur links and replace gallery with a.

As such /gallery/ > /a/

**Comment by wstyres** [comment]
@worldlydev nice tip, thanks!

Seems like something is wrong with your console somehow. It is getting repo update text when there shouldn't be. Don't think that would be affecting the package removal though. I'll see if I can reproduce this on a device when I get the chance.

**Comment by MustyAslan99** [comment]
Eh the repo update doesn't happen I guess it happens when I try to uninstall the package while the update process is ongoing when I open Zebra. I hope you get what I mean

**Comment by wstyres** [comment]
Something makes me think this might be a problem with removing packages marked as “essential” but I will have to do more research on that when I get a chance.

**Comment by MustyAslan99** [comment]
i wish there could be some logs for it but it doesn't have or report one for this reason.. well i had to restore for other issues and let's see if i will face it again. :/

**Comment by MustyAslan99** [comment]
> You say this happens for every package?

Well yeah when i had the issue it doesn't wanna uninstall anything or update i guess since i didn't get package updates meanwhile...

**Comment by wstyres** [comment]
Ok, let us know if this issue still occurs when you rejailbreak.

**Comment by MustyAslan99** [comment]
Well so far i have being playing around uninstall and install and as usual this package manager is my main and favorite but don't see any problems but i guess i had dpkg and cydo problems before restore and still i don't understand how those happened and just before restore zebra wasn't affected.. 🤔🤔

**Comment by MustyAslan99** [comment]
Yup it's same issue as he has.. and till now I didn't experience that problem yet but I guess it could be some packages that occur dpkg files?

**Comment by wstyres** [comment]
Going to close this issue in favor of #581. It seems `sedfix` is marked as an essential package and can't be removed. It is only certain packages that have this issue. This issue should be fixed for the next beta.
