### ISSUE TITLE
Multiple packages with the same download link (php) will not be installed

### ISSUE THREAD

**Issue by LuaDeathGame** [wstyres/Zebra#569]
**Describe the bug**
Look, this bug is still happening, when I try to install a Packix tweak or nepeta for example, it gives me this error, to take this repo as an example. I install the tweaks, and it tells me that it is already done, I do respring and it does not install them, As you can see, it only installs 2 packages instead of 3, and I have to do it from cydia to be able to achieve it.

**To Reproduce**
In my case: go to pulandres repo, install CallBar Xs Cracked
It will install 2 dependencies and one tweak
Do the process and restart springboard
Enter zebra, go see installation, and in my case just install me, the 2 dependencies, without the tweak.

**Expected behavior**
I expected the setting and dependencies to be installed, but it doesn't work, and I really like zebra and I want it to work, because I don't want to use Sileo, Installer or Cydia.

**Screenshots**

![1](https://user-images.githubusercontent.com/57741079/68827060-62aa9a00-0666-11ea-9681-c91b976ea2f1.jpg)
![74589268_442282609813116_4628491529671933952_n](https://user-images.githubusercontent.com/57741079/68827059-62aa9a00-0666-11ea-8d24-54a999b163f2.jpg)
![3](https://user-images.githubusercontent.com/57741079/68827058-62aa9a00-0666-11ea-8e29-8a0cbbe8cb12.jpg)

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: beta27
 - Device Type: Iphone 8
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
There is no crash log, because app doesnt crash.

**Additional context**

**Comment by wstyres** [comment]
Does this happen with tweaks from any other repo? I'm unable to even download tweaks from this repo as it gives me an error message.

**Comment by LuaDeathGame** [comment]
In my case yes... but i contact the creator and he said me, that the same happens with some tweak of the repo if packix. 
¿Do you think si a problem of zebra, or the repo?
This is another example, i tried another tweak today, and doesnt install nothing. 
![E0619E90-54A0-4EDA-8B0F-060D84CF672B](https://user-images.githubusercontent.com/57741079/68864847-6581ab00-06b7-11ea-86c2-57554d638c18.png)

**Comment by wstyres** [comment]
That Tweak appears to be from the same repo. I can check on a real device when I have the change but I can't verify this bug on the simulator because the packages aren't actually downloading. If you could find a package from another repo (Packix) that also has this problem, this would be helpful. Otherwise, I think this may be a problem with the repo, not Zebra. 
![Simulator Screen Shot - iPhone 11 - 2019-11-14 at 09 25 00](https://user-images.githubusercontent.com/19736790/68865423-cd88bf00-06c0-11ea-99bf-7a459227beeb.png)

**Comment by LuaDeathGame** [comment]
Hummm. Okaay, ¿did you know a way, to eliminate all the data of zebra and start as new and see if i can install doing that?

**Comment by LuaDeathGame** [comment]
The repo had a restriction for simulator, but the creator removed it, if you like you can already try.

**Comment by wstyres** [comment]
Ok, that make more sense. I will try again and see if I can find the issue.

**Comment by wstyres** [comment]
I've found the issue, there are two packages being downloaded here. Both have a url of download.php. Zebra incorrectly labels them both as 'sedfix' instead of installing them separately like it is supposed to. I will try and fix this for the next beta and keep you updated.

**Comment by LuaDeathGame** [comment]
Woow bro, you really found it, I hope you can correct it. Thanks for your attention bro.
I really think Zebra is better, than cydia, sileo and installer

**Comment by wstyres** [comment]
This bug should be fixed as of 400824085d5b1d0dc8cb6d49f6084942c2e85445. It will be included in the next beta.

**Comment by Pulandres** [comment]
thanks to fix this bug! :)

**Comment by LuaDeathGame** [comment]
Thanks men!
