### ISSUE TITLE
Remove seconds from packages' installed time

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#570]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

In the changes tab the time shows seconds and it's actually useful. In the packages time the date shows seconds even though it is useless and serves no purpose. I would like the seconds to be removed from the packages tab but I want them to stay in the changes tab if possible.

**Describe alternatives you've considered**

N/A

**Additional context**

Remove what is highlighted in red:
![E463BF07-6F90-4C31-AEED-A5E961341421](https://user-images.githubusercontent.com/51668635/68836949-ce6b2200-06bb-11ea-8433-5932f033083c.jpeg)

**Comment by worldlydev** [comment]
But keep this:

![236988AC-859D-4A71-A1E9-866C74D3A827](https://user-images.githubusercontent.com/51668635/68837048-08d4bf00-06bc-11ea-94bd-aa7daeefc204.jpeg)

**Comment by wstyres** [comment]
Implemented in c5f12ecb07c970d907994d007d1fc4cf57d4ab9e.

**Comment by worldlydev** [comment]
Working in beta 28
