### ISSUE TITLE
[BUG] UI Bug - Loading icon is black in dark mode

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#571]
**Describe the bug**

When Zebra automatically refreshes the sources after opening the app the loading icon is black even though I have dark mode turned on. This makes it difficult to see the loading icon.

**To Reproduce**

Open the app. If it automatically refreshes the sources go to the packages tab and the refresh icon will be black. I can sometimes reproduce this by refreshing from the sources page and going back to the packages page.

**Expected behavior**

I expect the loading icon to be white (or maybe the chosen tint color?).

**Screenshots**

Screen recording:
https://imgur.com/gallery/Zf1Ezgc

Screenshot:
![79F78113-2F57-4F7F-B860-1CEAE8C4426C](https://user-images.githubusercontent.com/51668635/68847126-6f62d880-06ce-11ea-9055-16ea312be674.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta 27-1
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

I have chosen the iOS 13 dark mode and white tint.

**Comment by eve0415** [comment]
oh that’s why i couldn’t see loading icons. I thought its just disappered

**Comment by wstyres** [comment]
Should be fixed as of 9e1ecf69fc0fb07e4da873b1194ea4e66b850f46.

**Comment by worldlydev** [comment]
Can confirm that the fix is working in the latest beta
