### ISSUE TITLE
[BUG] UI Bug - Loading icon freezes when switching tabs

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#572]
**Describe the bug**

The loading icon freezes when switching tabs. Let's say you pull to refresh from the sources tab go to the packages tab and then go back to the sources tab. The loading icon will then freeze. This happens no matter which tab you pull to refresh in. Pull to refresh in tab x > go to tab y > go back to tab x and the refresh icon will be frozen.

**To Reproduce**

^^

**Expected behavior**

I expect the refresh/loading icon to keep spinning.

**Screenshots**

Screen recording:
https://imgur.com/a/DA0GD3k

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta27-1
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
Should be fixed as of ec89957ed37864b804906e3ceba539da6ef45c12.

**Comment by worldlydev** [comment]
Can confirm that the fix is working in the latest beta
