### ISSUE TITLE
[BUG] UI Bug - Loading icon not showing after selecting a package

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#573]
**Describe the bug**

The loading icon is not showing after selecting a package.

**To Reproduce**

Open Zebra and go into the packages tab. Select any package. I attached 2 screen recordings showing that you can select either a package with an update or an installed package. Exit the package page. Pull to refresh. The loading icon will not be there.

**Expected behavior**

I expect the loading icon to be visible.

**Screenshots**

2 screen recordings:
https://imgur.com/a/nySKWii

Screenshot:
![8EC3D9DF-25FE-449F-A940-FC4F63715ED9](https://user-images.githubusercontent.com/51668635/68855538-b35dd980-06de-11ea-89bb-b65c55dabed0.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 27-1 
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by worldlydev** [comment]
Update 1: This bug is also existent on the sources page and it's reproduced in a very similar fashion. Open Zebra and go to the sources page then enter any of the repos. Then exit the repo and pull to refresh. The same bug will occur where the loading icon is not showing.

![DC7EE6C6-E1A5-4654-8325-70A2DB5CE596](https://user-images.githubusercontent.com/51668635/68892743-ee363080-0723-11ea-8a60-83439dc13e25.png)

**Comment by worldlydev** [comment]
Update 2: This bug seems to contain multiple bugs in one. After following the steps outlined in the previous comment go to the packages tab and select any package. When you exit that package the title for the package tab is missing.

Screenshot:
![4DB4D967-AB3E-40DB-AB4D-ED046F30CE3E](https://user-images.githubusercontent.com/51668635/68893041-964bf980-0724-11ea-81db-1e397a539b96.jpeg)

Screen recording demonstrating the bugs in both updates to this issue:
https://imgur.com/a/15pjLDX

**Comment by PoomSmart** [comment]
Fixed as of 78572efc055231d1ca12dacf70ff359d4a99c726
