### ISSUE TITLE
[BUG] UI Bug - Tint doesn't apply to sources tab

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#574]
**Describe the bug**

Changing the tint doesn't apply to the sources tab while still in app. For the change to take place you have to completely close Zebra in the app switcher.

**To Reproduce**

In my case I had white tint selected and switched to orange. I went through all the tabs and noticed that the change was applied everywhere except for in the sources tab.

**Expected behavior**

I expect the tint to change in the sources tab as it does in the other tabs.

**Screenshots**

Screen recording:
https://imgur.com/a/rd8605T

Screenshots:
![3E093489-50F4-4E67-94C0-422D79CA9136](https://user-images.githubusercontent.com/51668635/68856287-6da21080-06e0-11ea-9252-498fda866288.jpeg)
![0C48CBC7-44C6-403E-BDB0-5C0249017667](https://user-images.githubusercontent.com/51668635/68856288-6da21080-06e0-11ea-9ec7-f3009e49e799.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
Beta 27-1
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
Should be fixed as of 0797d2770a74ff2aa1e619fb9eef6fb32a174846.

**Comment by worldlydev** [comment]
Can confirm that the fix is working in the latest beta
