### ISSUE TITLE
Some repos show no packages

### ISSUE THREAD

**Issue by Vastomo** [wstyres/Zebra#58]
Some repos apparently have no packages inside them, whereas in cydia they do. For example the repo https://apt.geometricsoftware.se/

**Device Information**
 - iOS Version [11.3]: 
 - Zebra Version [e.g. 1.0~beta1 or beta1]: 
 - Device Type [iPhone 6s+]: 

**Additional context**
Cydia has updates for two of the packages in the repo listed above, but I don’t think this should cause an issue.

Also, I imported sources from Cydia

![7D7347AD-5149-4FFD-81E6-D319BEFA3AE2](https://user-images.githubusercontent.com/40142377/57582418-e8a72600-7507-11e9-8ad9-ce59cf703204.png)
![4381DC64-D67D-4145-8BF6-AEC91D0BC2F3](https://user-images.githubusercontent.com/40142377/57582419-e93fbc80-7507-11e9-9551-a3f75f23363f.png)

**Comment by wstyres** [comment]
I'll check this repo out and see what is up

**Comment by Vastomo** [comment]
Cheers!

**Comment by wstyres** [comment]
The server throwing off a 500 (Internal Server Error) response code for /Packages.bz2 right now so I'm unsure if this is actually a Zebra problem or a problem with the server. I'll wait and check again later.

**Comment by Vastomo** [comment]
Cheers. When I'm using cydia this repo is fine but in Zebra it get's this error

**Comment by wstyres** [comment]
Still not able to get any information from the repo. Might be on the repos end and not Zebras as the repo may check only for Sileo. This may be a problem to contact the repo maintainer about but I could be wrong as the server is still spitting out 500s

**Comment by Vastomo** [comment]
Alright cheers, thanks for trying

**Comment by wstyres** [comment]
Closing this as it is most likely an issue with the repo and not with Zebra
