### ISSUE TITLE
[BUG] Zebra detect the wrong jailbreak

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#580]
**Describe the bug**
As in the title, Zebra detects the wrong jailbreak type sometimes. Like I use unc0ver but detects Chimera.
Not everytime.

**To Reproduce**
Open Zebra and refresh repos. If there is an error says it is incompatible, the Zebra might have detected wrong jailbreak type.
Check community repo to know which jailbreak type is detected.

**Expected behavior**
It should detect the correct jailbreak type.
This didn’t happen in the last beta.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta27 & beta 27-1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Additional context**

If anyone has the same problem, just re-open Zebra and it would work fine.
Check discord.

**Comment by worldlydev** [comment]
Experiencing the same issue. Just the other way around. I am using Chimera but sometimes it detects Unc0ver instead.

**Comment by wstyres** [comment]
Put in a possible fix in 52765b7a7456b0e15b2ef168b02ec854e9b097f1. We'll see how it goes when I release the next beta.

**Comment by wstyres** [comment]
Going to leave the issue open. Beta 28 is out but if there are no jailbreak detection issues I'll close the issue.

**Comment by worldlydev** [comment]
So far it seems to be functioning for me at least. Will keep using to see if I run into this issue again but so far, all is good.

**Comment by eve0415** [comment]
I just need a little more time because it doesn’t happen always. I just try to open many times in a day and try to see if it still occurs or no.

**Comment by wstyres** [comment]
Alright let me know

**Comment by eve0415** [comment]
Ok, I think its fixed. Thank @wstyres . You ca close this issue.
