### ISSUE TITLE
[BUG] Can't remove Essential packages

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#581]
**Describe the bug**

Title says it all. Zebra can't uninstall Saily Store while Sileo can do so just fine.

Repo:
http://ouop.github.io/

**To Reproduce**

^

**Expected behavior**

I expect the tweak to be uninstalled.

**Screenshots**

![EB9D37B3-4F7B-44A1-B2A0-568A76925FF2](https://user-images.githubusercontent.com/51668635/68982970-42ffa700-0809-11ea-857a-95637fd18b08.png)
Screen recording:
https://imgur.com/a/vWeRd40

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
1.0~Beta 27-1 
- Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by worldlydev** [comment]
Update: I first noticed this issue months ago when I was localizing Saily. I forgot to report it then and it seems it is still not possible.

**Comment by wstyres** [comment]
This looks to be related to #568 with removing essential packages. I will try to reproduce when I get a chance.

**Comment by wstyres** [comment]
Currently working on the UI for this. Packages with `Essential: Yes` or `Priority: Required` will now have some extra information before you remove them as removing them is a potentially harmful action. 

![Simulator Screen Shot - iPhone 11 - 2019-11-17 at 16 28 50](https://user-images.githubusercontent.com/19736790/69014347-5caf0480-0957-11ea-963d-2fb777f02c62.png)
![Simulator Screen Shot - iPhone 11 - 2019-11-17 at 16 28 53](https://user-images.githubusercontent.com/19736790/69014348-5e78c800-0957-11ea-9e77-299643edd93d.png)

It _should_ work as of 2c2b3f3ad23bec4c4e3fb1f6331fabce07522f7c but I'm unable to verify it right now. When I can check on it I will report back. If there are any UI changes you'd like to suggest I'm open to them.

**Comment by wstyres** [comment]
In the case of #568, I did find that `sedfix` was an Essential package which was possibly why it was not getting removed. This should be truly fixed for the next beta but I'm unable to confirm until I test.

**Comment by worldlydev** [comment]
I actually do have a suggestion for the UI. Maybe make "ok" red instead of "remove from queue" as removing the package from the queue is the safe option.

**Comment by wstyres** [comment]
Slightly modified as per @worldlydev's suggestion.

![Simulator Screen Shot - iPhone 11 - 2019-11-18 at 10 51 05](https://user-images.githubusercontent.com/19736790/69067598-553c3980-09f1-11ea-9c5b-4ea2559f341a.png)

**Comment by wstyres** [comment]
I'm able to uninstall Saily and sedfix after the fix in 2c2b3f3, it will be available in the next beta.

**Comment by MustyAslan99** [comment]
Hey by the way you mentioned "sedfix" so what package is that?

**Comment by wstyres** [comment]
It is an add-on called "CracksCompatibility" from some piracy repo. For some reason it is marked as essential.

**Comment by MustyAslan99** [comment]
Oh yeah I remember getting that when I "Upgrade all" in Cydia or Zebra it auto adds it but it's not in changes and it can easy be removed... But it's really annoying so I had to remove the repo..

**Comment by wstyres** [comment]
Not saying that it contains malware, just pointing out that it is marked as essential and thus cannot be removed.

**Comment by MustyAslan99** [comment]
Also just found that for my issue and on this issue was caused by him maybe? And there's a solution if it's fine but idk? https://twitter.com/pulandres_/status/1193585970895114242?s=21

**Comment by MustyAslan99** [comment]
> Not saying that it contains malware

Well I didn't say you said it.. I mean like that could cause this problems? Just trying to figure it out and help out

**Comment by worldlydev** [comment]
Can confirm that the fix is functioning in beta 28-1
