### ISSUE TITLE
[BUG] False dependency resolution for package "zip"

### ISSUE THREAD

**Issue by captinc** [wstyres/Zebra#582]
**Describe the bug**
When I try to remove zip, Zebra thinks that a ton of other packages depend on zip and therefore Zebra tries to remove them too. In actuality, those other packages do NOT depend on zip

**To Reproduce**
Add "zip" to the queue for removal

**Expected behavior**
Should only remove the packages that truly depend on zip

**Screenshots**
N/A

**Device Information (please complete the following information):**
 - iOS 13.2.2
 - Zebra 1.0~beta27-1
 - iPad Pro 10.5"
 - checkra1n

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by wstyres** [comment]
Packages are remove that depend on zip and then packages are also removed that depend on those packages. For example, if dpkg depends on zip, dpkg is removed as well. But since Zebra and Cydia also depend on dpkg, they are removed as well.

**Comment by captinc** [comment]
@wstyres dpkg does not depend on zip. Output of “apt-cache depends dpkg” below: 

bash-5.0$ apt-cache depends dpkg
dpkg
  PreDepends: tar
  Depends: bash
  Depends: bzip2
  Depends: coreutils-bin
  Depends: diffutils
  Depends: file
  Depends: findutils
  Depends: gzip
  Depends: ldid
  Depends: lzma
  Depends: ncurses
  Depends: tar
  Depends: xz

**Comment by wstyres** [comment]
I was using it as an example. All of the packages that you just listed will be removed as well as any packages that depend on them.

**Comment by captinc** [comment]
Hmmm, I don’t quite understand what you’re saying. Maybe this will clarify things. I have a fresh installation of checkra1n and the only tweaks I have are Filza and Zebra (and their dependencies). 

When using Zebra, trying to remove only zip also removes Filza and every system tweak. When using Cydia, it only removes zip and Filza. Zebra 1.0~beta23-1 did not have this problem

I know that Filza depends on zip, so no problem there. But I’m not sure why Zebra wants to remove all of the system tweaks. I checked the relationships of zip on other tweaks. Filza depends on zip, and zip depends on dpkg. So, I should be able to remove zip and Filza without removing dpkg. Here’s the output of “apt-cache rdepends zip”

bash-5.0$ apt-cache rdepends zip
zip
Reverse Depends:
  com.tigisoftware.filza

**Comment by wstyres** [comment]
Is dpkg removed by Zebra when removing zip? That is probably what is removing all of the other packages if so.

**Comment by captinc** [comment]
Yep

**Comment by wstyres** [comment]
Ok it looks like when Zebra is trying to resolve the conflicts, it is mislabeling "bzip2" and "gzip" as "zip". Which causes dpkg to be removed because it depends on bzip2 and gzip. I'll see if I can fix that issue in the next few days and keep this post up to date.

**Comment by captinc** [comment]
Awesome, thanks for your time!

**Comment by wstyres** [comment]
Should be fixed as of 1111683e324ce707276a54074276cab3a6a9fc8b. Here is how it resolves now:
![Simulator Screen Shot - iPhone 11 - 2019-11-19 at 13 59 29](https://user-images.githubusercontent.com/19736790/69177088-e801d480-0ad4-11ea-8b2e-ebdef9d68679.png)

If you know of any more packages that have this issue (or any other improper dependency resolution) post them here so that I can test them.

**Comment by captinc** [comment]
Awesome! That’s all that I know of for now. You can close the issue

**Comment by wstyres** [comment]
Going to leave it open for now until the next beta is released.
