### ISSUE TITLE
Automatically remove tweak from wishlist after installation

### ISSUE THREAD

**Issue by BirkhoffLee** [wstyres/Zebra#583]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As the title says

**Describe alternatives you've considered**

**Additional context**

**Comment by worldlydev** [comment]
I'd prefer it to stay as is. If this is implemented please make it an option.

I don't want my wishlist automatically cleared in the same way that I don't want my search history automatically cleared.

**Comment by wstyres** [comment]
An option could be implemented but I would think that once someone successfully installs a package they would want to remove the package from their wishlist.

**Comment by JakeValenzuela** [comment]
I agree that most people would want it automatically removed after installation. (i.e. Nintendo's eShop doesn't remove items after purchase and seems like the majority would rather it be automatic/shouldn't be a chore to go back in and remove everything)

**Comment by worldlydev** [comment]
> An option could be implemented but I would think that once someone successfully installs a package they would want to remove the package from their wishlist.

My feelings on this have slightly changed. Still don't want it automatically cleared but sense that seems to be the general consensus for what's best I think it should be implemented.

Would love for the wishlist to be exportable though so I can save it along with my sources and packages list. That would make up for it imo.

**Comment by wstyres** [comment]
Implemented in 4b128429a278088f7ba8081d32f3a3ffced4c4e9 will be in the next beta.
