### ISSUE TITLE
Icon remove bug

### ISSUE THREAD

**Issue by Filtar2000** [wstyres/Zebra#584]
**Describe the bug**
When you remove zebra app from Cydia the icon remains 
**To Reproduce**
Delete zebra from Cydia
**Expected behavior**
I expect the app disappears
**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 13.1.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta
 - Device Type [e.g. iPhone or iPad]: iPhone 7 Plus
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
This is likely an issue with Cydia, not Zebra. As when any application is installed or removed, `uicache` must be run either by the package manager or the user in order for the icons to be updated.
