### ISSUE TITLE
Zebra not loading when trying to add repo

### ISSUE THREAD

**Issue by Aditya245850** [wstyres/Zebra#585]
Bascially, when you go to a repo and then press open in Zebra, it redirects to zebra.... but it doesnt load. Its really weird

go to https://poomsmart.github.io/repo and press add in cydia(it will open in zebra). It will open zebra, but zebra will just show a blank screen

 - iOS Version 13.2.2
 - Zebra Version :27-1
 - Device Type: iPhone X(10,3)
 - Jailbreak Type: Checkra1n 9.5.0

**Comment by wstyres** [comment]
Fixed as of d3b88cfc1dcb00d2efb7a94865b8ff05aca63119
