### ISSUE TITLE
Tap to manage/packages queued text unreadable

### ISSUE THREAD

**Issue by qasim311** [wstyres/Zebra#590]
![EE2DFC61-3F54-47F2-8598-3D22D8B4047B](https://user-images.githubusercontent.com/57723688/69012169-bf88a780-0927-11ea-961c-fda4a4d3faa0.png) 

**To Reproduce**
Worked fine up until today, but now doesn’t work

**Expected behavior**
It should be orange

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 13.2.2]: 
 - Zebra Version [latest version]
 - Device Type [e.g. iPhone X]: 
 - Jailbreak Type [ checkra1n

**Comment by wstyres** [comment]
Should be fixed as of 1b9eaac45bd67d1028986d46745826c3f0bae0cf.
