### ISSUE TITLE
Dark mode tweak search

### ISSUE THREAD

**Issue by Astra-no-touch** [wstyres/Zebra#594]
Dark mode search text color is black and it blends in, makes it unable to see what you’re typing.

Open Zebra
Toggle to dark mode
Search tweaks

**Expected behavior**
I would like to be able to see the text.

**Screenshots**
![FF43333E-474E-4369-9537-32F9E5167501](https://user-images.githubusercontent.com/57969139/69195970-c44d8700-0af2-11ea-9e5e-0fc0cc00b0f6.jpeg)

**Device Information (please complete the following information):**
 - iOS Version 13.1.2
 - Zebra Version: Zebra 1.0~beta23-1
 - Device Type iPhone 6s [iPhone8,1]
 - Jailbreak Type: checkra1n

**Crash Log or System Log**
None, everything works😇.
Except for a few little GUI bugs.

**Comment by wstyres** [comment]
I see you're on iOS 13, is the system dark mode on by chance?

**Comment by Astra-no-touch** [comment]
Yes I toggled it off and revisited the app to make sure it wasn’t that.

**Comment by wstyres** [comment]
I also see you're not on the most up to date beta. Could you update to beta27-1 from https://getzbra.com/beta for me?

**Comment by wstyres** [comment]
Should be fixed as of a9fe1a06311eaaefa84fad892eb28e460f956336.
