### ISSUE TITLE
Built-in Push notifications à la CyPush

### ISSUE THREAD

**Issue by PencilNotPen** [wstyres/Zebra#595]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

It would be a great enhancement to Zebra as a more modern package manager to have built-in icon badges and push notifications which update periodically in the background. The functionality which CyPush2 adds to Cydia is essentially what I’m thinking of.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by wstyres** [comment]
This has been implemented, will be available in a beta shortly.
