### ISSUE TITLE
Crash if search button is touched

### ISSUE THREAD

**Issue by ann0see** [wstyres/Zebra#596]
**Describe the bug**
If I tap on the search tab button Zebra crashes. 
**To Reproduce**
Tao the search button on the bottom right
**Expected behavior**
Search tab should open
**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 28
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]:  unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by ann0see** [comment]
Crashlog on Request.

**Comment by wstyres** [comment]
This was fixed in fdb7fbe07b2bb1e13c61d10f31b829131e2a6cb2 and has already been pushed out in beta28-1. Please update your Zebra to see if that fixes the issue.

**Comment by ann0see** [comment]
Ok. Thanks. Will update.

**Comment by ann0see** [comment]
Ok. I have now updated Zebra. Now it works. Thanks for the fast update!
