### ISSUE TITLE
[BUG] Untranslated strings

### ISSUE THREAD

**Issue by ann0see** [wstyres/Zebra#598]
**Describe the bug**

The back buttons for Text_editors and Data_storage are not translated in German. 

**To Reproduce**
Open Bingner/Elucubratus repo, tap on Text Editors and e.g. the ed package. Now the back button says Text_Editors. 
**Expected behavior**
The back button should display the translated string. 
**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Should be fixed as of ad8e08ca636495fb6ab9447f1c550b6b649c8e1a
