### ISSUE TITLE
sbreload is part of the original UIKit Tools

### ISSUE THREAD

**Issue by pwn20wndstuff** [wstyres/Zebra#60]
sbreload has been part of UIKit Tools for almost a decade. There’s no point in checking for a specific jailbreak to run it. All jailbreaks should have it by default.

**Comment by wstyres** [comment]
Only reason I added the check was because I was unable to run it on my device that is using unc0ver and I was told that the command had not worked for a long time so to be safe I added the check for sbreload/killall to be sure that the device restarted.

**Comment by wstyres** [comment]
Just tried to verify this, updated to the latest unc0ver build and rejailbroke. Still getting the error with sbreload.
![IMG_0033](https://user-images.githubusercontent.com/19736790/57583611-148ec100-74a0-11e9-91cb-63394bd33924.PNG)

**Comment by pwn20wndstuff** [comment]
Okay so that's not the expected behavior. I will check this out.

**Comment by wstyres** [comment]
Thanks, let me know if you find a fix and I'll be happy to remove the check

**Comment by Amplespencer** [comment]
this has been updated, please check for the version of coreutilities then decide to killall backboardd kr sbreload

**Comment by pwn20wndstuff** [comment]
UIKit Tools was updated on Elucubratus and it now works. Please update Zebra to use this as well.

**Comment by wstyres** [comment]
Awesome, I'll see if I can do some testing and get it fixed for the next beta,

**Comment by wstyres** [comment]
Zebra will now run `sbreload` on every device. If this command fails, it will fall back to stopping backboardd. I'm not able to verify this on a device with older UIKit Tools at the moment but if an issue arises then another issue can be created.
