### ISSUE TITLE
[BUG] UI Bug - Wrong actions in queue

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#600]
**Describe the bug**

When queuing packages the actions get switched around. For example, the package that is being uninstalled says reinstalling. While the package being reinstalled says it's being removed.

**To Reproduce**

^^ or watch my screen recording 🔻

**Expected behavior**

I expect the queue actions to display correctly.

**Screenshots**

Screenshot: 
![70DBBAF9-A4A9-490D-A7C8-001A9C0E1813](https://user-images.githubusercontent.com/51668635/69275137-1ae2c000-0bdc-11ea-8c9f-7fecad076141.jpeg)

Screen recording:
https://imgur.com/a/X1ca4jX

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta28-1 
- Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by wstyres** [comment]
Are the packages correctly installed/removed? Is it just a UI bug?

**Comment by worldlydev** [comment]
> Are the packages correctly installed/removed? Is it just a UI bug?

Yep. Simply a UI bug.
![F8FEDCF9-CC50-4297-B5F3-FEB9BA06C1FD](https://user-images.githubusercontent.com/51668635/69277590-cdb51d00-0be0-11ea-81cd-8b35eb72878d.png)

**Comment by PoomSmart** [comment]
Fixed as of 901d1f8bd489437c459f4fd882a1097533560bf3
