### ISSUE TITLE
[BUG] UI Bug - Inconsistent Home tab title size

### ISSUE THREAD

**Issue by gkeep** [wstyres/Zebra#602]
**Describe the bug**
After opening Settings on 'Home' tab and closing them the 'Home' title will be small, as if I was scrolling down.

**To Reproduce**
1. Open Zebra on 'Home' tab
2. Notice that everything works (swipe down and up and notice that 'Home' tab title at the top changes from big to small)
3. Open Settings
3. Close Settings
4. Swipe down and up on 'Home' tab and notice that the tab title does not change size anymore.

**Expected behavior**
Tab title should change it's size like before opening Settings.

**Screenshots**
[Video representation](https://i.imgur.com/px9h6Sz.mp4)

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: 1.0-beta28-1
 - Device Type [e.g. iPhone or iPad]: iPhone 5s
 - Jailbreak Type: checkra1n

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by PoomSmart** [comment]
Fixed as of c42d516e26ede7436eabd588cfde605fbbe7faa8
