### ISSUE TITLE
When adding sources in batch, one failing URL cancels the entire import

### ISSUE THREAD

**Issue by Astra-no-touch** [wstyres/Zebra#604]
**Is your feature request related to a problem? Please describe.**
When adding multiple sources, if one of the URLs in the list is wrong Zebra will not add the list. It's almost like it cancels the entire operation to fix just one mistyped URL. 

**Describe the solution you'd like**
When adding multiple URLs if one is wrong it prompts that you fix it and continues to add all of the other URL instead of canceling.

**Describe alternatives you've considered**
You could make this using a sort of code editing [Error on line #] sort of style.
If one of the URLs does not work, take the user back to the editor and highlight the misspelled or broken URLs.

**Additional context**
If you haven't copied your source list to paste into the multiple source prompt; when one is misspelled and the operation is canceled, you find yourself retyping all of the URLs again.

**Comment by PoomSmart** [comment]
Workaround as of 9502616968a2b7ebceed1c84a7b3cf97d753b315

**Comment by PoomSmart** [comment]
Fix released
