### ISSUE TITLE
Sources "Done Editing" button remains after switching to another tab

### ISSUE THREAD

**Issue by Astra-no-touch** [wstyres/Zebra#605]
**Describe the bug**
When tapping edit button on Sources list, then swapping tabs and returning to the sources tab; a simple UI bug occurs

[https://vimeo.com/374568739](https://vimeo.com/374568739)

**Device Information (please complete the following information):**
 - iOS Version : 12.2.3
 - Zebra Version : Zebra 1.0~beta28-1
 - Device Type: iPhone 6s
 - Jailbreak Type: checkra1n

**Comment by PoomSmart** [comment]
Fixed as of 785ca885e36f6178e558b8ced35049a229e78a7a
