### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by sashareimer** [wstyres/Zebra#606]
**Describe the bug**
1. The source list and package list moves upwards and the UI covers the first item on the list. 
2. Also getting an error that says bingner repo is not compatible with my jailbreak and asks me to delete it.
3. The text is black in search bar when dark mode is on
4. The news hasn’t been updated for long.
5. Cant find a way to download beta 28

**To Reproduce**
Reopening the app helps for a while with the first issue, the rest stays

**Screenshots**
![F2500A97-C1D3-4E84-9DC7-97EE22D5DCD0](https://user-images.githubusercontent.com/46461110/69312706-161d1b00-0c73-11ea-82ad-2b838328c8af.png)
![A2DE24D0-CA06-4C04-905D-C61922C4DEFC](https://user-images.githubusercontent.com/46461110/69312707-161d1b00-0c73-11ea-9741-32d9f4e071b7.png)
![69B7911C-9446-4F8B-8AFB-7488D01B563F](https://user-images.githubusercontent.com/46461110/69313126-0b16ba80-0c74-11ea-9204-f237f5c52dcc.png)
![EAF14570-AF62-4B33-BC61-7C59E32A9A56](https://user-images.githubusercontent.com/46461110/69313128-0b16ba80-0c74-11ea-8a3f-dcf53ffd3c5c.png)

**Device Information (please complete the following information):**
 - iOS Version: 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1 beta 23
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n 0.9.5

**Comment by wstyres** [comment]
Please update to the latest beta, beta 28 is available from our beta repo located at https://getzbra.com/beta/

**Comment by wstyres** [comment]
Closing as these bugs should be fixed as of beta 28
