### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by sashareimer** [wstyres/Zebra#607]
**Describe the bug**
The tweaks descriptions have white background even in dark mode

**To Reproduce**
Were not found

**Expected behavior**
Should be colored as the app interface 

**Screenshots**
![A9F9BFBE-693E-48F7-9B72-05681AF56F42](https://user-images.githubusercontent.com/46461110/69313349-a740c180-0c74-11ea-9a0c-c845984bd945.png)

**Device Information (please complete the following information):**
 - iOS Version: 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 1
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
This is a repo issue, not an issue with Zebra. The repo controls how its depictions appear to the user.
