### ISSUE TITLE
[BUG] 3D Touch and Scrolling

### ISSUE THREAD

**Issue by gerbil-snot** [wstyres/Zebra#608]
**Describe the bug**
Freezing occurs when 3D touching a package in the Packages tab and scrolling at the same time. 

**To Reproduce**
Slightly 3D Touch a package, not enough to bring up the description, but enough to blur the other packages. Use the quick scroll letters on the right side to scroll while 3D Touching. The app will freeze after releasing, and you have to force close the app. 

**Expected behavior**
This occurred to me several times by me just using the letter scroll bar while I was searching for a package, I believe it froze 4 times before I gave up and just scrolled normally. 

**Screenshots**
Quick GIF here: https://i.imgur.com/LXxMxHI

**Device Information:**
 - iOS Version: 12.4
 - Zebra Version: beta28-1
 - Device Type: iPhone Xs Max 
 - Jailbreak Type: unc0ver v3.7~b3

**Comment by wstyres** [comment]
I wouldn't label 3D-Touching and scrolling at the same time as "intended behavior" but I'll see if I can just disable the quick scroller while 3D-Touch is present

**Comment by wstyres** [comment]
Not able to reproduce this anymore, does it occur on beta 29-4? If so, could you provide a video?

**Comment by worldlydev** [comment]
> Not able to reproduce this anymore, does it occur on beta 29-4? If so, could you provide a video?

Tested on beta 30-1. The issue seems to be resolved.

https://imgur.com/a/pt1IADs
