### ISSUE TITLE
Feature for packages tab.

### ISSUE THREAD

**Issue by braenden** [wstyres/Zebra#61]
Would be awesome if there were sections in the packages tab, which sorted packages by tweaks, themes, widgets etc. Zebra is gold btw.

Wanted this for ages in Cydia but everyone knows that's not gonna happen.

**Comment by PoomSmart** [comment]
Right now, it can be sorted by alphabets, or installed time.

**Comment by Amplespencer** [comment]
I actually really want this, could be done by checking a packages set tab (the debs have a section dedicated to show either Tweaks themes or something else.)

this could be done by going through every package and checking it’s section. have Tweaks tab set to packages in Tweaks* Tweak *Tweaks *Tweak etc

**Comment by PoomSmart** [comment]
Closed in favor #192
