### ISSUE TITLE
[BUG] Dependency Issue with a SnowBoard Extension

### ISSUE THREAD

**Issue by dcallen7** [wstyres/Zebra#612]
**Describe the bug**
I had SnowBoard installed, and wanted to install one of its Extensions - SnowBoard Preset Extension. When I press install, it queues 2 packages: the extension AND SnowBoard (the same version/repo as the one installed), which I already have.

This did not occur in Cydia when I tested it, so it’s not an issue with Spark’s control files/repo.

**To Reproduce**
1) Install SnowBoard ONLY and respring.

2) Search for SnowBoard Preset Extension, and press Install.

3) You will see that 2 packages have been queued, one of which is your already-installed SnowBoard dependency.

**Expected behavior**
Zebra should only have attempted to install the SnowBoard Preset Extension, without queuing SnowBoard as well, since that was already installed.

**Screenshots**
Can’t show the problem with a screenshot.

**Device Information (please complete the following information):**
 - iOS Version: 13.2.3
 - Zebra Version: Beta28-1 
 - Device Type: iPhone X
 - Jailbreak Type: checkra1n

**Crash Log or System Log**
Not applicable

**Additional Context**
This is such an incredibly minor issue, but I still thought it would be another data point in the effort to smooth out dependency resolution.

**Comment by eve0415** [comment]
I can reproduce this bug on beta29

**Comment by eve0415** [comment]
This bug only affect "Snowboard Preset Extension". Not other extensions.

**Comment by wstyres** [comment]
Should be fixed as of 87a8b47bc1802a572fa347d7621ec6621c398489

**Comment by wstyres** [comment]
Fix was included as of beta 29-1. Let me know if the issue still persists.

**Comment by eve0415** [comment]
Confirm that its fixed using beta 29-2. I don't know about beta 29-1.
