### ISSUE TITLE
[BUG] Web view inside Depiction page does not expand to fit its content

### ISSUE THREAD

**Issue by Am1nCmd** [wstyres/Zebra#613]
Some of package description / information is not showing. I have comparing zebra to cydia just to make sure that is not a problem from repo itself

Screenshot
![3E505701-3D16-4224-B07A-537BEDBF1578](https://user-images.githubusercontent.com/15339573/69472978-95c9f780-0de3-11ea-8a16-934d8ccd2200.png)
![0853DC6F-F6EE-4230-8C59-5B66790B7D0F](https://user-images.githubusercontent.com/15339573/69472979-96628e00-0de3-11ea-8679-27333704e4c0.png)

**Device Information 
 - iOS Version : 13.2.2
 - Zebra Version : 1.0~beta29
 - Device Type : iPhone
 - Jailbreak Type : checkra1n

**Comment by PoomSmart** [comment]
Mitigated in 7a77d1c3897e8d8cd45217dcf8fe63d8351aceeb

**Comment by Am1nCmd** [comment]
true
