### ISSUE TITLE
Queues Substitute everytime I install a tweak

### ISSUE THREAD

**Issue by crappy-coder21** [wstyres/Zebra#614]
**Describe the bug**
Everytime I install a new tweak with zebra it automatically queues substitute(v 0.1.0) even thought it is the latest version 

**To Reproduce**
Steps to reproduce the behavior: Upgrade substitute to v 0.1.0 and then install any tweak

**Expected behavior**
For it to only update substitute when a new version is available

**Screenshots**
I don’t know how to link screenshots sorry

**Device Information (please complete the following information):**
 - iOS Version 12.4 
 - Zebra Version 1.0~b29 / latest version
 - Device Type iPhone XR
 - Jailbreak Type unc0ver 3.7~b2

**Crash Log or System Log**
Not applicable I don’t think

**Additional context**
Only started after updating to the latest version of substitute

**Comment by Greigh** [comment]
It does the same for me. Let me know if there's anything I can do/send that will help you fix this issue. I attached some screenshots. 

iPhone XS Max. iOS 12.4. Zebra 1.0 b26 unc0ver 3.7 b3

![IMG_0127](https://user-images.githubusercontent.com/57759540/69473782-6933c280-0d86-11ea-8fbc-567906b67055.PNG)
![IMG_0128](https://user-images.githubusercontent.com/57759540/69473783-6933c280-0d86-11ea-86ac-cec8a61a7d74.PNG)

**Comment by wstyres** [comment]
Should be fixed as of a8737812545dd37f4e601f4f0ab473255c30cce0.

**Comment by wstyres** [comment]
Was implemented as a part of beta 29-2, let me know if the issue still persists.
