### ISSUE TITLE
[BUG] Dependency Issue with Notchification on c1d3r's repo

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#615]
**Describe the bug**
Dependency issue with libcolorpicker from the same repo when trying to install Notchification on https://c1d3r.com/beta/. Could be a possible repo issue??? But it doesn't know to find the dependency library package. 

![IMG_0122](https://user-images.githubusercontent.com/57759540/69473875-6f766e80-0d87-11ea-97b2-9815cbcd4ae9.PNG)

**To Reproduce**
Try to upgrade (maybe even install???) Notchification. It will not let you install as shown above. 

**Expected behavior**
Install Notchification and all of its dependencies without having to find them yourself.

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: 1.0~beta29
 - Device Type: iPhone XS Max
 - Jailbreak Type: unc0ver 3.7.0 b3

**Crash Log or System Log**
DNA

**Additional context**
Like I've said above I am not sure if this is a repository issue or not. When trying to install with Cydia it does tell me that libcolorpicker and libcolorpicker - Nepeta conflict and gives me the option to uninstall the Nepeta version and install the one from c1d3r's repo. 

Let me know if there is anything I can share or I can do to help in any way to fix this.

**Comment by Greigh** [comment]
Just to clarify com.thebigboss.libcolorpicker is on c1d3r's repo.

**Comment by wstyres** [comment]
Do you already have libcolorpicker installed? If so I don't think this is a dependency issue but rather an installation/download issue. I will investigate.

**Comment by wstyres** [comment]
Looks like it was a download issue. Should be fixed as of f31243eb1b95d8379533426eea281b4b7840b7e5.
