### ISSUE TITLE
[BUG] Can't downgrade packages from 3d-touch menu

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#616]
**Describe the bug**

Title says it all.

**To Reproduce**

Downgrading from the 3d touch menu does nothing. While downgrading from the packages page works fine.

**Expected behavior**

I expect the list of available versions to show up.

**Screenshots**

Screen recording:
https://imgur.com/a/AU1uxPQ

Screenshots:
(From packages page)
![34EC6678-ECEE-42B6-BDF5-6862C5DFEE05](https://user-images.githubusercontent.com/51668635/69476513-1f28fc00-0ddb-11ea-8791-37cebd35f58e.png)
(From 3d-touch menu)
![A8559BEF-1D9C-46DA-9214-3E7D45E3631C](https://user-images.githubusercontent.com/51668635/69476514-1fc19280-0ddb-11ea-83c6-101e884ab1d8.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
Beta 29-2
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by eve0415** [comment]
I can confirm that. It doesn't do anything after pressing Downgrade in 3D touch menu.

**Comment by wstyres** [comment]
Should be fixed as of fa656d1024177e4aeb4aa19072125cbf07d0eeff.

**Comment by wstyres** [comment]
Fix was included as a part of 29-3. Unfortunately the 3D Touch buttons aren't being themed again so that is a known bug. See if you can use the Downgrade menu from 3D Touch now though.

**Comment by worldlydev** [comment]
> Fix was included as a part of 29-3. Unfortunately the 3D Touch buttons aren't being themed again so that is a known bug. See if you can use the Downgrade menu from 3D Touch now though.

Yep. Bug seems to be fixed but the buttons are no longer themed.
