### ISSUE TITLE
[UI BUG] Loading icon disappear in Package Tab

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#617]
**Describe the bug
As the title says.

**To Reproduce**
start sync sources
open package tab
scroll up to show loading icon space.

**Expected behavior**

Show us loading icon

**Screenshots**
![40DE7BF9-0426-4ACE-AFBA-EAD4590A65D7](https://user-images.githubusercontent.com/40632436/69479720-06a0fc00-0e44-11ea-9ea8-5234d8a09553.png)
![241D9B5B-D13E-43BC-B7DE-995F24C1B453](https://user-images.githubusercontent.com/40632436/69479721-06a0fc00-0e44-11ea-94ed-5b32487f62dd.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 29-2
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Aditional context**
I have a lot of UI bugs so I will open issues one by one.

**Comment by PoomSmart** [comment]
Merged to #620
