### ISSUE TITLE
[BUG] Respring button does not do anything at the certain situations

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#621]
**Describe the bug**
As the title says.
Respring button does not work when trying to update / downgrade / re-installing Zebra AND other tweaks what needed to respring afterward.
After pressing Respring, it stay still and clash or close Zebra. I don't know which.

**To Reproduce**
update / downgrade / re-installing Zebra AND other tweaks that need to respring when installing / downgrading / re-installing.

**Expected behavior**

Restart Springboard.

**Screenshots**

N/A

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:beta 29-3 
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

I think #567 fixes has occurred this

**Comment by PoomSmart** [comment]
Possibly resolved as of d1846e62114462f5acd59469c87eb8c7c49ed655

**Comment by wstyres** [comment]
The fix was included as a part of the 29-4 update. Please check if the issue still occurs.

**Comment by eve0415** [comment]
Not working on 29-4.
https://cdn.discordapp.com/attachments/572784833714192395/648748209614749698/video0.mp4

**Comment by wstyres** [comment]
I've found this doesn't affect Zebra when Upgrading/Downgrading and can only reproduce when re-installing. Can you confirm?

**Comment by eve0415** [comment]
Ok, I just try twice.
downgrading Zebra to beta 29-3 and reinstalling other package that need to respring: “Close Zebra”
upgrading Zebra to beta 29-4 and reinstalling other package that need to respring: “Respring” which won’t work

**Comment by wstyres** [comment]
So it seems that the issue was fixed as of 29-4?

**Comment by wstyres** [comment]
I added in some extra steps to ensure a respring / prevent crashing as of d590c3dc874b11990c638145f2a0a768a082a8d3. Hopefully doing the same reinstall steps will be fixed in the next beta.

**Comment by eve0415** [comment]
no, after reinstalling Zebra and other tweaks will not make Zebra respring.
Respring button will pop up but it does not do anything

**Comment by eve0415** [comment]
not fixed of beta 30
won’t respring

**Comment by wstyres** [comment]
Are you doing the same steps (reinstalling zebra and reinstalling another tweak) to reproduce?

**Comment by eve0415** [comment]
yes

**Comment by wstyres** [comment]
Further checks in 90b240530ca02209b109323a77a081af2e3cfffb. Fix will be in beta30-1

**Comment by wstyres** [comment]
I'm not able to reproduce by re-installing a tweak and re-installing Zebra in the same stage anymore. See if you can reproduce on beta 30-1

**Comment by worldlydev** [comment]
Reinstalled NoBlur and Zebra in beta 30-1 and the respring button functioned properly.

**Comment by eve0415** [comment]
Yes, it’s fixed in beta 30-1. Thank you!!!
