### ISSUE TITLE
[BUG] Web Depictions are cut off

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#622]
**Describe the bug**

As the title says. Sometimes it load perfectly, sometimes not,

**To Reproduce**

Open many kind of tweaks' web view depiction page.

**Expected behavior**

Show us web view depiction page

**Screenshots**
![5D062789-50FF-4BDF-A0F3-435114DC96DB](https://user-images.githubusercontent.com/40632436/69487315-0c75fc00-0e9b-11ea-9631-5870b8db5c5e.png)
![69B1F50A-9E4E-4F7F-8F2A-07E33C76AEC0](https://user-images.githubusercontent.com/40632436/69487316-0d0e9280-0e9b-11ea-8e67-e4c3ce51cf5b.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:beta 29-3 
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]:unc0ver 

**Additional context**

#613 this fix might have occurred this

**Comment by absidue** [comment]
iPhone X, 12.4, Zebra 1.0~beta29-3

Example of a working depiction: Navale, Packix
Example of a broken depiction: Nice Siri, Packix

**Comment by wstyres** [comment]
I'm able to load the Zebra depiction just fine. Is there a specific tab that this occurs on? @absidue Both of the packages you reported work fine for me as well.

**Comment by eve0415** [comment]
How about avlock from Packix.
About Zebra, it sometimes load but sometimes not.
Some tweaks from Packix does not work but some does.
I don’t know whats the difference

**Comment by wstyres** [comment]
avlock works fine as well. I suspect this is more of a random occurrence than a specific package problem

**Comment by absidue** [comment]
@wstyres
For me it looks like this if I overscroll
![F9076FD4-A6BB-4D3F-AF56-1F5C60391540](https://user-images.githubusercontent.com/48293849/69487488-1e37af00-0e5b-11ea-9345-fa7802959915.jpeg)

**Comment by eve0415** [comment]
@absidue me too for AVlock.
It does not scroll down to show us the rest of the page

**Comment by eve0415** [comment]
And NiceSiri happen this to me too

**Comment by wstyres** [comment]
So is this an issue of the depiction not loading or not being able to scroll to see all of the depiction?

**Comment by eve0415** [comment]
I don’t know which. It sometime not load completely, I mean its black and end at the “Installed File” tab. Sometime it load but cannot scroll down. Sometime it load and can scroll down perfectly.

**Comment by absidue** [comment]
Not being able to scroll

Inspecting and tapping preview on the WKCompositingView with FLEXing reveals a bit more of the depiction

**Comment by eve0415** [comment]
![AFDCFF8B-5DCF-4069-A099-FF4BF9BBF1BC](https://user-images.githubusercontent.com/40632436/69487582-ebfc7080-0e9f-11ea-8789-c869e7f7b144.png)
Like this, scroll bar on the right is already at the bottom where it should have more.

**Comment by absidue** [comment]
The WKContentView extends beyond the visible area but the WKScrollView cuts it off

Moving the WKContentView in the WKScrollView with FLEXing allows you to view more of the depiction

**Comment by PoomSmart** [comment]
Mitigated in 276be54b3b8cdc967de9c3ae1fdf70ebfc1e349d

**Comment by wstyres** [comment]
The fix was included as a part of the 29-4 update. Please check if the bug still occurs.

**Comment by eve0415** [comment]
Not fixed on 29-4.
![EA881868-8F37-4D21-8FAD-AD21CAAEFB67](https://user-images.githubusercontent.com/40632436/69600573-72f24a00-1054-11ea-88c7-70167d224a16.png)

**Comment by aRvedk** [comment]
I also experienced this issue a couple of times. Just checked some of my installed/updated tweaks. 

So far the depictions are not fully loaded and I can’t scroll all the way down for the following tweaks:

Cydia installer
Little11
FloatingDockPlus13
Safari Plus

Screenshots attached and scrolled all the way down

Zebra beta 29-4

![CB4D5E90-6F57-4194-ACE7-02D4A1533FD0](https://user-images.githubusercontent.com/58183058/69607759-29076500-1050-11ea-8936-ede0c71d406c.png)
![026E8841-FCC4-4F59-8393-3AAA94A09C2E](https://user-images.githubusercontent.com/58183058/69607761-299ffb80-1050-11ea-9208-b7dd42923eae.png)
![A4073DB0-EEB2-4760-BEE5-BFB163A16BF0](https://user-images.githubusercontent.com/58183058/69607763-299ffb80-1050-11ea-9e0f-a160325909d0.png)
![3FD2FE40-D954-4432-9805-743D01B01553](https://user-images.githubusercontent.com/58183058/69607764-2a389200-1050-11ea-995c-3bb614489bf7.png)

**Comment by worldlydev** [comment]
@wstyres related to the fix for #557? Perhaps try reverting the changes made for it to see if it fixes this issue in the beta? Don't know any code lol but it may be: https://github.com/wstyres/Zebra/commit/37db07cc58267fef10a5edfc49778cf3d199ee4f

I have a possible solution I could file as an enhancement. Tbh not being able to scroll is way more annoying than the other scrolling issue that was fixed.

**Comment by wstyres** [comment]
Not quite sure, the problem is it seems to be a random occurrence, I am not able to reproduce it myself.

**Comment by worldlydev** [comment]
> Not quite sure, the problem is it seems to be a random occurrence, I am not able to reproduce it myself.

I can reproduce it consistently and it always affects the Santee packages.

Give it a try? If it doesn't work just revert back.

**Comment by wstyres** [comment]
I'll see if I can refactor the depiction view (which I've been meaning to do for awhile) and find any bugs with it.

**Comment by eve0415** [comment]
When you try to scroll down quickly when you open the package depiction page and when the web depictions is loading, you can scroll down to the bottom of the page.
But if you wait for it to load, you cannot scroll down. If I can I will post the video on discord later today

**Comment by wstyres** [comment]
Ah ok, so the page is not finished loading when you try to scroll down and that results in it not showing the entire page?

**Comment by Greigh** [comment]
Yes. I can confirm @eve0415 is correct. If you wait for it to load (with the loading bar at the top) you'll be able to see the whole depiction. But it stops loading as soon as you try to scroll down.

**Comment by Greigh** [comment]
Except for some repo sources, it still doesn't let me. For example, CPDD Supporter Repo (https://suporter.cpdigitaldarkroom.com/repo/). It cuts off most of the depiction. WebKit error possibly?

**Comment by wstyres** [comment]
Are you able to downgrade to a lower beta to confirm this?

**Comment by Greigh** [comment]
Just downgraded to 28-1 and I have no issues with Depictions.

**Comment by wstyres** [comment]
So yes, it looks like 7a77d1c that fixed #617 may be causing this bug. I'll investigate more on how to fix this while still maintaining #617's fix.

**Comment by wstyres** [comment]
Was fixed in 8329f55fd3553695b86f46fca19f3c0296c253c5. #617 should not be affected. Fix will be included in beta 30.

**Comment by worldlydev** [comment]
> Was fixed in [8329f55](https://github.com/wstyres/Zebra/commit/8329f55fd3553695b86f46fca19f3c0296c253c5). #617 should not be affected. Fix will be included in beta 30.

Lol guess I was wrong. Good job 😎

**Comment by eve0415** [comment]
fixed in beta 30

**Comment by aRvedk** [comment]
It’s definitely fixed for a lot of my packages but now I just found BigShotJb (iOS 11) which is cut off again. But for a lot of packages it’s working now already. 👍
