### ISSUE TITLE
[BUG]Zebra not showing the right dependencies to remove

### ISSUE THREAD

**Issue by aRvedk** [wstyres/Zebra#624]
**Describe the bug**
I was playing around with Zebra installing new packages removing old ones and so on while I stumbled across that:
When I try to remove libpackageinfo (Spark) Zebra doesn’t show the dependencies which  it has to remove as well. Interestingly zebra is still removing all of the dependents but it’s not showing them in the GUI. 

Attached a screenshot from zebra queue and cydia 
![7105EE89-F2B9-448F-8F5D-29F9C70465F5](https://user-images.githubusercontent.com/58183058/69558346-3a119100-0fd2-11ea-8f20-52142e5761db.png)

![96FD44E5-F130-4C6C-85AD-4CB3EF1E8701](https://user-images.githubusercontent.com/58183058/69558345-3a119100-0fd2-11ea-9ed3-9883737e0d2a.png)

**Device Information (please complete the following information):**
 - iOS Version : 13.2.2
 - Zebra Version : Beta-29-3
 - Device Type : iPhone 7
 - Jailbreak Type : checkra1n 0.9.5

**Crash Log or System Log**
On Twitter I got asked to post my dpkg status too. 
https://pastebin.com/3SucvPgU

If you need more info I’m happy to help ..

**Comment by aRvedk** [comment]
Maybe it’s something related to spark’s libs .. tried a couple of libs or other packages to remove to see if zebra would show me the dependencies to remove too, all worked until I tried to remove libSparkAppList. Same as libpackageinfo .. maybe that helps to solve the issue

**Comment by wstyres** [comment]
Looks like spark's libpackageinfo provides `jp.ashikase.libpackageinfo` and Zebra was not detecting that removal. I'll see what I can do.

**Comment by wstyres** [comment]
Should be fixed as of 67e8c290c36fefa519f5e2ddee0cd26f018d87e2.

![Simulator Screen Shot - iPhone 11 - 2019-11-25 at 20 16 24](https://user-images.githubusercontent.com/19736790/69591341-79cf7d00-0fc0-11ea-83ec-e266d6553e89.png)

**Comment by wstyres** [comment]
Fix was included as a part of the 29-4 update. Please check to see if the bug still occurs.

**Comment by aRvedk** [comment]
Works as supposed! Thanks a lot 🦓🙏
