### ISSUE TITLE
[BUG] Tab Bar icons are all selected by default

### ISSUE THREAD

**Issue by MTACS** [wstyres/Zebra#626]
**Describe the bug**

When opening Zebra 1.0~beta29-4, all tab bar icons are in selected form, and only return to normal behavior when toggling dark mode

**To Reproduce**
Open Zebra 1.0~beta29-4

**Expected behavior**
Selected tab bar to be colored, the rest have unselected color

**Screenshots**
![IMG_545326D14B41-1](https://user-images.githubusercontent.com/13209789/69654014-15550200-1042-11ea-83cf-18915b2141b0.jpeg)

**Device Information (please complete the following information):**
- iPhone X, iOS 13.2.2 (Checkra1n), Zebra 1.0~beta29-4
- iPhone 7, iOS 13.1.3 (Checkra1n), Zebra 1.0~beta29-4

**Comment by wstyres** [comment]
Does this issue affect 29-3 as well?

**Comment by MTACS** [comment]
Just 29-4

**Comment by wstyres** [comment]
Should be fixed as of af2cc4df02fe1f75f8a2bb2c76f8f6d724b6b95f.
