### ISSUE TITLE
[BUG] zip is not installable

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#627]
**Describe the bug**
Dependency error with Filza 64bit from TiGi’s repo. 

**To Reproduce**
Install Filza 64bit and gives a zip dependency error. 

**Expected behavior**
Installs all dependencies and package. 

![1BCC3CA0-40F5-41D5-9AC0-CB41B8B4F49B](https://user-images.githubusercontent.com/57759540/69688876-4dd1fb80-1095-11ea-8973-d01b00ec0310.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0 29-4
 - Device Type [e.g. iPhone or iPad]: iPhone XS Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
Let me know if there’s anything I can provide to help more.

**Comment by Greigh** [comment]
https://tigisoftware.com/cydia/

**Comment by wstyres** [comment]
Hmm, I'm able to install the packages just fine on my device. Are you sure you're on the latest beta and have you tried installing it again?

**Comment by Greigh** [comment]
Really strange. I wasn’t able to reproduce it a fourth time. Sorry about that.
