### ISSUE TITLE
[BUG] UI Bug - Use same controller class for change icon as other settings

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#628]
**Screenshots**

![41067F37-8334-46A1-910D-294FA3899E32](https://user-images.githubusercontent.com/51668635/69750406-f68f6200-114c-11ea-90ba-6514a50e41be.png)
![D181C622-DFEC-4574-854E-5BCF3D16CB7B](https://user-images.githubusercontent.com/51668635/69750405-f68f6200-114c-11ea-8577-2ef851759f07.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
Beta 29-4
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, Checkra1n]: Chimera

**Comment by wstyres** [comment]
Implemented in f586447d5638ba889b65ec9a3fd2e2ce73cfa324.

**Comment by worldlydev** [comment]
Can confirm that this is fixed in beta 30.
