### ISSUE TITLE
Restart Springboard dint work

### ISSUE THREAD

**Issue by Wo0of** [wstyres/Zebra#629]
**Describe the bug**
Downloaded the new update for Zebra, was given the option to restart springboard. clicked it but nothing happened then zebra crash. So had to manually respring. 

**To Reproduce**
Downloaded Update for Zebra then clicked restart springboard. 

**Expected behavior**
Expected restart springboard to work.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version 12.4.3 
 - Zebra Version 1.0 b29
 - Device Type iPhone 6 
 - Jailbreak Type Checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
No biggie tho

**Comment by eve0415** [comment]
Refer to #621

**Comment by wstyres** [comment]
Duplicate of #621
