### ISSUE TITLE
Can’t import any sources 

### ISSUE THREAD

**Issue by backwardatom** [wstyres/Zebra#63]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - AUPM Version [e.g. 1.0~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Could you elaborate on what you mean?

**Comment by backwardatom** [comment]
Can’t add any repo at all for some reason I don’t know why

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wstyres** [comment]
Should be fixed in beta 10, try it out.
