### ISSUE TITLE
The ABC section UI bug

### ISSUE THREAD

**Issue by baobaoit** [wstyres/Zebra#631]
**Describe the bug**
Where the UI displays the ABC section, then scroll it up/down, the character is stick there, but the backgroud is gone.

**To Reproduce**
1. At the Source/Package tab, we scroll it up/down

**Expected behavior**
The character and the background will stick there, instead of the character only.

**Screenshots**
![7D6AAC64-7F77-4C23-B96C-39C9C7FD4F6A](https://user-images.githubusercontent.com/31947091/69843554-a58d8400-129a-11ea-86c2-989995378e3f.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta29
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by wstyres** [comment]
Fixed in f37ffcb299ffca9fdaf88073b2cf6120e03d0ff3.

**Comment by eve0415** [comment]
I want this on Package tab not only source tab

**Comment by eve0415** [comment]
I can’t see on package tab only
![EED4F5C5-04F1-47B9-AC28-CF1B314B67DB](https://user-images.githubusercontent.com/40632436/69844291-e55e6680-12ae-11ea-94e2-36d701f495cf.png)

**Comment by wstyres** [comment]
I don't think this applies to the Package tab, only the sources tab.

**Comment by eve0415** [comment]
I don’t think we need this in the store page
![CA0A3988-DE6B-46C0-A197-83123383FD43](https://user-images.githubusercontent.com/40632436/69844479-cca28080-12af-11ea-8351-33a6155d0541.jpeg)

**Comment by wstyres** [comment]
Fixed in Stores as of 5c846c070020d157447b1c5ac63fe31fc77cdc6a

**Comment by eve0415** [comment]
Thanx

**Comment by baobaoit** [comment]
Thank you! I’m closing the issue now.
