### ISSUE TITLE
[BUG] Not showing package on some sub category in the source tab

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#632]
**Describe the bug**

As the title says.
The section with “()”, “-“, space (maybe).
But some of them will show us.

**To Reproduce**

Open any source’s sub category.

**Expected behavior**

show us package in the sub category section

**Screenshots**

![B0495C0E-E179-418D-A73F-832A206464E9](https://user-images.githubusercontent.com/40632436/69844997-10968500-12b2-11ea-8fe8-adfc3037d414.png)
![CFF9F6C3-0331-4A08-8AB5-5D1CFCABC2FD](https://user-images.githubusercontent.com/40632436/69844998-10968500-12b2-11ea-8ce9-f962d48cbdbc.png)
![2F2A06E6-8A28-4312-A9A1-642C1BDE0B82](https://user-images.githubusercontent.com/40632436/69844999-112f1b80-12b2-11ea-9a89-8b26bb981db2.png)
![0419DE03-5180-4B0B-A95A-93B77E2D88C5](https://user-images.githubusercontent.com/40632436/69845000-112f1b80-12b2-11ea-932a-2b55afd5c732.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4 / 13.2.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 29-4
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver / checkra1n

**Comment by wstyres** [comment]
Should be fixed as of 357f7c38725fc096c0b79ff6df7556b4e00ea606. Test the sections you've found when beta 30 is released.

**Comment by eve0415** [comment]
seemed to be fix as of beta 30
