### ISSUE TITLE
[UI BUG] when swiping back, the black something come out

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#633]
**Describe the bug**

Please look screenshots

**To Reproduce**

open package depiction page 
swipe back

**Expected behavior**

**Screenshots**

![8DF7BF30-E7BD-44B6-A405-429488CF34D2](https://user-images.githubusercontent.com/40632436/69845247-51db6480-12b3-11ea-9f48-7f0c0f7fcb9c.jpeg)
![7D0FA8FC-002A-49BF-B712-B200F927CC65](https://user-images.githubusercontent.com/40632436/69845248-51db6480-12b3-11ea-8f37-b8ec589a9fc1.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 29-4
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by wstyres** [comment]
Are you sure this is not the navigation bar extending down to allow for large titles?

**Comment by eve0415** [comment]
https://cdn.discordapp.com/attachments/572784833714192395/649999999433965590/video0.mp4

**Comment by wstyres** [comment]
That looks like the navigation bar extending to fill its space for large titles. It is more of an iOS bug than a Zebra bug.

**Comment by eve0415** [comment]
So, it mean that you cannot do anything?

**Comment by worldlydev** [comment]
> That looks like the navigation bar extending to fill its space for large titles. It is more of an iOS bug than a Zebra bug.

Now this is quite interesting. This only seems to happen with the oled dark mode. With the other dark modes enabled it seems that zebra scrolls down when entering a package on the package tab. But with OLED mode it doesn't do this. Resulting in the nav bar expanding on top of the icon while exiting the package depiction page.

**Comment by eve0415** [comment]
Yes, @worldlydev is right. 
I try without OLED mode and it didn't have that.

**Comment by wstyres** [comment]
The OLED navigation bars are different from any other theme because they have to be opaque and tinted black in order to achieve the OLED "true black" iOS has a bug in older versions, might be fixed in 13, that has this glitch happen unfortunately so I can't do much.

**Comment by worldlydev** [comment]
> The OLED navigation bars are different from any other theme because they have to be opaque and tinted black in order to achieve the OLED "true black" iOS has a bug in older versions, might be fixed in 13, that has this glitch happen unfortunately so I can't do much.

Lol that sucks. Nice to know.
