### ISSUE TITLE
[UI BUG] The spinner when using Light mode 

### ISSUE THREAD

**Issue by baobaoit** [wstyres/Zebra#634]
**Describe the bug**
When we use the light mode, the spinner tinted with the white color, so it is hard to seeing it.

**To Reproduce**
1. Switch to the light mode 
2. Go to the Source tab
3. Pull it down to refresh 

**Expected behavior**
The spinner tint is black, so we can see it easily.

**Screenshots**
![4E1F2612-AD2B-4A8D-89C6-BB7F2DD2475F](https://user-images.githubusercontent.com/31947091/69881954-3303bf00-1301-11ea-899b-a8c86abac69c.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta30 
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by PoomSmart** [comment]
Should be fixed as of 4dc645afaef2412bcd090f42d967de93214e2a9f

**Comment by baobaoit** [comment]
Fixed on the beta30-1
