### ISSUE TITLE
Rounded corners in console (consistency)

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#636]
**Describe the solution you'd like**

iOS' UI uses a lot of rounded corners and so do most apps on the platform, including Zebra. Really makes the "performing actions" and "downloading" buttons stick our like a sore thumb with straight 90° corners. I wish they were rounded. I know for a fact that they were in earlier betas.

![EBEEE77D-69C1-448E-8626-6171F4B9A525](https://user-images.githubusercontent.com/51668635/69883803-0e462200-12d6-11ea-97ac-de5075110832.jpeg)

**Comment by PoomSmart** [comment]
Fixed as of 575106d43a76ab549e551a19eb65ec41ef101c0f

**Comment by worldlydev** [comment]
> Fixed as of [575106d](https://github.com/wstyres/Zebra/commit/575106d43a76ab549e551a19eb65ec41ef101c0f)

Can confirm that this is implemented in beta 30-1.
