### ISSUE TITLE
New names for the alternative icons (consistency)

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#637]
**Describe the solution you'd like**

I wish all the alternative icons had the same naming scheme. Such as:
Zebra (Light), Zebra (Dark), Zebra Pattern (Light), Zebra Pattern (Dark), Zebra Pattern with Z (Light), and Zebra Pattern with Z (Dark).

![6949804E-CA19-438A-87D0-2F15310374BB](https://user-images.githubusercontent.com/51668635/69884014-db505e00-12d6-11ea-9a39-fe9fda4588fb.jpeg)

**Comment by worldlydev** [comment]
+ localization support for their names.

**Comment by worldlydev** [comment]
![887B75B4-8641-415B-9AF7-9E4D456133CC](https://user-images.githubusercontent.com/51668635/70381287-f448b700-1947-11ea-8183-74232eebcc58.jpeg)

The new names are exactly what I wanted. Awesome. Just need localization support

**Comment by wstyres** [comment]
New names have been added for 1.1 but we're not going to localize them since they are unique titles for each icon (similar to how "Zebra" may translate to another language but we don't want the app's name to be translated).
