### ISSUE TITLE
[BUG] Cancel button not localized in some instances

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#638]
**Describe the bug**

The cancel button isn't always localized when errors occur.

**To Reproduce**

In the screen recording below I turned off WiFi from the control center to simulate repo connection errors. Can occur for different errors as well.

**Expected behavior**

I expect it to say cancel in the set device language.

**Screenshots**

Screen recording:
https://imgur.com/a/iOjeHva

Screenshots:
![D0D915AC-16F4-458F-ABEF-0A28D6564C04](https://user-images.githubusercontent.com/51668635/69885526-df33ae80-12dd-11ea-8ad2-be5c638b6370.jpeg)
![6866760F-166F-49B0-AD95-8510D26DEDDD](https://user-images.githubusercontent.com/51668635/69885543-e8248000-12dd-11ea-8830-1047ef7db7fb.jpeg)
(Second one is from an error in an older beta. That error no longer occurs but I forgot to report this issue. Shows that different errors cause this issue as well.)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 30 
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Comment by eve0415** [comment]
Can confirm and reproduce.

**Comment by PoomSmart** [comment]
Fixed as of a54c72926fb8b4bed536592288f22876e3a6ebe2

**Comment by worldlydev** [comment]
> Fixed as of [a54c729](https://github.com/wstyres/Zebra/commit/a54c72926fb8b4bed536592288f22876e3a6ebe2)

Can confirm that this is fixed in beta 30-1
