### ISSUE TITLE
Deep link to package

### ISSUE THREAD

**Issue by ann0see** [wstyres/Zebra#643]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be great if we could open the install page of a tweak with a deep link. E.g. if someone links zbra://package&id=com.dev.tweak&repo=https://my.repo.com
On his site, the page for the tweak com.dev.tweak opens in Zebra. If the repo wasn’t added before, Zebra should ask, if the user wants to add the repo in order to add the tweak or search for the tweak in other repos. 
**Describe alternatives you've considered**

**Additional context**

**Comment by wstyres** [comment]
This can already be done with the scheme `zbra://packages/<package id>?source=<source url>` Zebra will prompt the user to add a repo if it wasn't added before and will show the package only if the package exists from that repo URL.

**Comment by ann0see** [comment]
That’s nice. Probably I didn’t find the correct documents.

**Comment by ann0see** [comment]
That’s nice. Probably I didn’t find the correct documents.
