### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by cmot17** [wstyres/Zebra#644]
![image0](https://user-images.githubusercontent.com/25753364/69922034-55631d00-1466-11ea-92a4-3bbb4d8d896d.png)
![image1](https://user-images.githubusercontent.com/25753364/69922037-598f3a80-1466-11ea-97d3-8d41001ab9a3.png)

As you can see, when dark mode is on the text "HidePageDots13 (0.0.1)" at the top of the menu is nearly impossible to see.

**Comment by wstyres** [comment]
This should be fixed on devices running on 12 and below. Still seeing if I can get a fix for iOS 13.

**Comment by wstyres** [comment]
Should be fixed on iOS 13 devices on eec5e589a66e1a38d9ced29da437cd0914df043e.
