### ISSUE TITLE
Old Cydia Substrate Listed as Installed

### ISSUE THREAD

**Issue by rctfan929** [wstyres/Zebra#645]
Version 0.9.7033 of Cydia Subtrate is listed as installed in Zebra and not in Cydia even though it has been uninstalled.

**To Reproduce**
1. Install version 0.9.7100~b4
2. Open Zebra and Cydia
3. Compare

**Expected behavior**
I expect only the new version to be listed.

**Screenshots**
Zebra
http://www.imagebam.com/image/b9ca9f1326749083
http://www.imagebam.com/image/dd0a6d1326749085
Cydia
http://www.imagebam.com/image/5abdc61326749087
http://www.imagebam.com/image/1efa271326749089

Device Info:
 - iOS 12.4
 - Zebra 1.0~beta30-1
 - iPhone 6s 
 - unc0ver 3.70-b3

**Comment by wstyres** [comment]
Could you post the contents of /var/lib/dpkg/status onto ghostbin.co and paste a link here?

**Comment by rctfan929** [comment]
https://ghostbin.co/paste/cxfex

**Comment by rctfan929** [comment]
@wstyres Sam Bingner released “u0 Substrate Transitional” which seems to have fixed this.

**Comment by wstyres** [comment]
Alright, I'll close the issue.
