### ISSUE TITLE
Keyboard is laggy

### ISSUE THREAD

**Issue by Wo0of** [wstyres/Zebra#646]
**Describe the bug**
Everytime I type there is a ~1 sec or more delay.

**To Reproduce**
Just type anything, slow or fastbkgndndbfn

**Expected behavior**
No delay, speed should be at least close to “instant”. 

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 30-1
 - Device Type [e.g. iPhone or iPad]: iPhone6
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Checkra1n 0.9.5

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
Sometimes when first time starting up typing at the search bar, keyboard would freeze for ~3 sec. Yes, I let my sources refresh first before doing anything.

**Comment by worldlydev** [comment]
Turn off search while typing?

**Comment by Wo0of** [comment]
> Turn off search while typing?

When I turned it off it was pretty smooth and fast, then I decided to turn it on again. Now much its much much better than the last time, there is still some little lag but its very negligible. It fixed the lag, thank you!

The good ol "turn it on & off" trick, lol.
