### ISSUE TITLE
[BUG] not getting updates for Launch Daemon Controller

### ISSUE THREAD

**Issue by allendude51** [wstyres/Zebra#647]
I have the bingner repo added on both Cydia and zebra but on Cydia it shows an update for Launch Daemon Controller Which is from that repo but on zebra it doesn't show up. I'm able to get updates from other packages from that repo except for that one.

**Comment by wstyres** [comment]
What version of Launch Daemon Controller do you currently have installed? What version does Cydia want to upgrade to?

**Comment by allendude51** [comment]
The latest update is 23-1. I can't tell you the previous version because I already installed the update using Cydia. The package shows up in zebra, it just didn't fetch the update for some reason.

**Comment by allendude51** [comment]
Ok so I just installed zebra on another device which doesn't have the latest version of launch daemon controller. The update is showing up on zebra now.

**Comment by wstyres** [comment]
Alright, I’ll close the issue.
