### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#648]
**Describe the bug**
Random crashes when opening a package depiction after searching. 

**To Reproduce**
Search for a package and try to open one. For example, I searched for Cercube and clicked on it and it crashes. 

**Expected behavior**
Opens package depiction giving the normal options to install, etc.

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: beta 30-2
 - Device Type: XS Max
 - Jailbreak Type: u0 3.7.0~b4

**Crash Log or System Log**
https://ghostbin.co/paste/vxtme

**Comment by eve0415** [comment]
For me it always crashes when opening any of depiction

**Comment by Greigh** [comment]
Yes I can confirm any depiction.

--
Greigh Canary

**Comment by Greigh** [comment]
https://ghostbin.co/paste/eem5h Crash log with installed deb.
