### ISSUE TITLE
Newly added repo doesn’t show in list

### ISSUE THREAD

**Issue by JKakaofanatiker** [wstyres/Zebra#653]
**Describe the bug**
I added a repo and it isn’t in the List

**To Reproduce**
Add a repo
**Expected behavior**
The repo should be in the list

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
what repo did you try to add?

**Comment by wstyres** [comment]
Please add steps to reproduce as well as device information. A list of repos that don't show up would also be helpful. We're not able to fix a bug based on so little information so the more information you can provide (even screen recordings) the better.

**Comment by JKakaofanatiker** [comment]
After some hours the repo is there. I just need to wait with every repo.
