### ISSUE TITLE
Update for a tweak not showing

### ISSUE THREAD

**Issue by Wo0of** [wstyres/Zebra#658]
**Describe the bug**
Theres an update for App Sync Unified but its not showing, meanwhile in Cydia it appears. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 30-4
 - Device Type [e.g. iPhone or iPad]: iphone 6
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Checkra1n 0.9.6

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
I must go to the bathroom now, thx.

**Comment by wstyres** [comment]
Can you provide a dpkg status log (located at /var/lib/dpkg/status) and the repo that you installed AppSync Unified from?

**Comment by Wo0of** [comment]
> Can you provide a dpkg status log (located at /var/lib/dpkg/status) and the repo that you installed AppSync Unified from?

Log: https://drive.google.com/open?id=1sNZk1wm0MJMwbYvUfUO3XB97UMoX4fv2
Repo installed from: https://cydia.angelxwind.net

Is that how you reply by quoting?

**Comment by wstyres** [comment]
Thanks, I'll look into it.

**Comment by wstyres** [comment]
Should be fixed as of 1d1e9897efb7d53c5b3b2b271e0e4b3811355b68.

**Comment by Wo0of** [comment]
thx
