### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by Vastomo** [wstyres/Zebra#66]
I think a darkmode option would be great. I've made an icon to see what it looks like
![Full Image](https://user-images.githubusercontent.com/40142377/57585516-94fb0380-752c-11e9-964e-497f0bf5871e.png)

**Comment by navanchauhan** [comment]
I have been working on it on a private fork, should I do a PR or make my fork public?

<img width="458" alt="Screenshot 2019-05-13 at 12 10 44 AM" src="https://user-images.githubusercontent.com/29234112/57586442-9f5cd380-7513-11e9-80af-c9279f24c2f7.png">

**Comment by Vastomo** [comment]
Personally, if it's working fine I would make it public once you get rid of all the bright colours

**Comment by CodeyMoore** [comment]
I'm currently working on a dark mode which I've almost completed.
![IMG_5540](https://user-images.githubusercontent.com/21144094/57592289-1aa2a180-7575-11e9-97f2-13bd028f0c36.PNG)
![IMG_5541](https://user-images.githubusercontent.com/21144094/57592290-1b3b3800-7575-11e9-823e-318d2894027b.PNG)
![IMG_5544](https://user-images.githubusercontent.com/21144094/57592291-1b3b3800-7575-11e9-9aed-ff1d74ecbb2f.PNG)
![IMG_5545](https://user-images.githubusercontent.com/21144094/57592293-1bd3ce80-7575-11e9-9cb7-890217616cd1.PNG)
![IMG_5546](https://user-images.githubusercontent.com/21144094/57592294-1bd3ce80-7575-11e9-8533-d85f7adc6f9b.PNG)

**Comment by navanchauhan** [comment]
`https://github.com/navanchauhan/Zebra-Dark`

I am planning on keeping the source code almost-mirrored until native dark mode support is added to Zebra

**Comment by midnightchip** [comment]
A dark mode has been made and will be part of the next beta.
