### ISSUE TITLE
[BUG] Zebra crashes after changing Featured Packages settings

### ISSUE THREAD

**Issue by gkeep** [wstyres/Zebra#662]
**Describe the bug**
Zebra crashes after playing around with Featured Packages settings

**To Reproduce**
1. Open Settings
2. Enable Random in Feature Type
3. Quickly go back and disable Featured Packages

Now every time you open Zebra it will crash.

**Device Information:**
 - iOS Version: 12.4
 - Zebra Version: beta31
 - Device Type: iPhone 5s
 - Jailbreak Type: checkra1n

**Crash Log or System Log**
[Crash log](https://gist.github.com/gkeep/1560848a32056bbee7c98a9d16d4e272).

**Comment by wstyres** [comment]
Could I get a list of repos?

**Comment by gkeep** [comment]
If I understand correctly, it is located at `/var/mobile/Library/Application Support/xyz.willy.Zebra/sources.list`? If so, [here](https://gist.github.com/gkeep/1560848a32056bbee7c98a9d16d4e272#file-sources-list) it is.

**Comment by wstyres** [comment]
And did you have any repos blacklisted?

**Comment by gkeep** [comment]
I think so, yes. But isn’t blacklisting removed in the latest beta?

**Comment by wstyres** [comment]
No, blacklisting isn't removed. If you could export your Zebra preferences and upload those as well hopefully I'll be able to see which repo is causing the crash.

**Comment by gkeep** [comment]
The [.deb](https://www.dropbox.com/s/c6c8vyq4rurx66s/xyz.willy.zebra_1.0~beta31-1%2Bdebug_iphoneos-arm.deb?dl=0) you provided in Discord (which includes 682a498059466f0bb6ab0b9206eb806d66977e77) fixed the issue.
