### ISSUE TITLE
Automatic Respring Setting

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#666]
**Is your feature request related to a problem? Please describe.**

some user want auto respring function

**Describe the solution you'd like**

make auto respring button in the setting

![F93ECFD9-F3F1-4912-A49F-DA2E9B0C5A19](https://user-images.githubusercontent.com/40632436/70384984-feac9480-19cb-11ea-9b34-7b9f7d3945b0.jpeg)

**Comment by wstyres** [comment]
Sure, this can be added in the future

**Comment by absidue** [comment]
@eve0415 For the moment you can use ZebraAutoComplete from my repo https://apt.absidue.me
