### ISSUE TITLE
cannot reach this two repos while cydia can

### ISSUE THREAD

**Issue by CySxL** [wstyres/Zebra#668]
![414AA4BB-B5D0-421F-ACCC-5A1947636558](https://user-images.githubusercontent.com/15531137/70389477-bb1d4f00-19fa-11ea-96fa-1ee4fb6a16ff.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by relisiuol** [comment]
Nope, try to add it again in Cydia, you can't.
drewbydrew.github.io: No Packages(.(bz2|gz)? file
apt.niceios.com: No Release file

**Comment by CySxL** [comment]
Not really, u can see I got two repos loaded their packages in Cydia.  #(
![25A79DC6-1F43-4DA6-B417-486D59937B62](https://user-images.githubusercontent.com/15531137/70390002-b7d99180-1a01-11ea-90b6-546f60595d63.png)
combine this screenshot with Snapper2)

**Comment by CySxL** [comment]
Sorry for first using Github, my device is iPhone6s, iOS12.4, latest unc0ver.

**Comment by relisiuol** [comment]
I think, that's due because Cydia can't find a new Packages file and so doesn't clean previous packages fetched. Try to delete these repos and add it again, you can't. Also, you may
 have warnings/errors when refreshing your repos.

![Uploading IMG_0007.png…]()

**Comment by wstyres** [comment]
drewbydrew.github.io should be able to be added even if it is missing a release file. However, I can confirm that the second repo (apt.niceios.com) does not have a package file and cannot be added in Cydia either.

**Comment by relisiuol** [comment]
Fix #671

**Comment by CySxL** [comment]
Sorry for asking. how and where can I update it?

**Comment by wstyres** [comment]
It will be in the next beta.
