### ISSUE TITLE
Zebra not getting proper r/w permissions.

### ISSUE THREAD

**Issue by SOZIKILLYOUZ** [wstyres/Zebra#67]
**Describe the bug**
Zebra doesn’t have proper r/w access to the documents folder. setting it to r/w for everyone works but isn’t ideal 

**To Reproduce**
install Zebra. 

**Expected behavior**
Sources to refresh and Zebra to create its folder in the documents folder. 

**Screenshots**
N/A. 

**Device Information (please complete the following information):**
 - iOS Version: 12.1.2
 - AUPM Version: 1.0~beta9 
 - Device Type: iPhone X

**Crash Log or System Log**
Dunno how to do this :( 

**Additional context**
N/A.

**Comment by wstyres** [comment]
Can you run the command `ls -l /var/mobile/` on Terminal/SSH/NewTerm?

**Comment by SOZIKILLYOUZ** [comment]
i did, Documents is the outlier, highlighted in green.

**Comment by wstyres** [comment]
Could you take a screenshot? And you have not modified this correct? Have you run a rootfs restore before?

**Comment by SOZIKILLYOUZ** [comment]
i’ve used snapback to go from unc0ver to chimera. but i’m using unc0ver as of now. 

Don’t know how to paste a screenshot on mobile so i’ll paste it in. hope you don’t mind !

drwxr-xr-x   4 mobile mobile  128 Feb 22 21:10 Containers/                                             
drwxrwxrwx  10 root   mobile  320 May 12 13:46 Documents/                                              
drwx------   3 mobile mobile   96 Mar  3 13:42 Downloads/                                              
drwx--x--x 115 mobile mobile 3680 May 11 11:21 Library/                                                
drwxr-x---  16 mobile mobile  512 May  2 08:25 Media/                                                  
drwxr-xr-x   3 mobile mobile   96 May  1 15:14 MobileSoftwareUpdate/                                   
drwxr-xr-x   2 root   mobile   64 Apr 19 12:56 tmp/

**Comment by wstyres** [comment]
Thank you, could you install this deb https://www.dropbox.com/s/fydkl46nsknjx0o/xyz.willy.zebra_1.0~beta9-6%2Bdebug_iphoneos-arm.deb?dl=0 and try Zebra again?

**Comment by wstyres** [comment]
Thanks, could you install this deb and tell me if it is fixed? https://www.dropbox.com/s/dhw31qf0h6249fn/xyz.willy.zebra_1.0~beta9-7%2Bdebug_iphoneos-arm.deb?dl=0

**Comment by SOZIKILLYOUZ** [comment]
i assume i set the r/w back to its default for the Documents folder, right?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wstyres** [comment]
Yep, mobile:mobile

**Comment by wstyres** [comment]
If you install the deb it should do it for you

**Comment by SOZIKILLYOUZ** [comment]
i set the defaults back for the documents folder, installed the deb, resprung, opened the app. the spinning icon next to sources isn’t there like it was before. i tapped import sources from cydia and its did it all correctly. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wstyres** [comment]
Ok awesome, that means it should be fixed, I'll push out a beta very soon.
