### ISSUE TITLE
[Localize] Hungarian Language request for Crowdin

### ISSUE THREAD

**Issue by wickdj** [wstyres/Zebra#670]
Hungarian

https://twitter.com/wickdj

**Comment by wstyres** [comment]
Would you like to translate to Hungarian?

**Comment by wickdj** [comment]
Hello. Yes.

**Comment by wstyres** [comment]
Ok, let me add the language files and I'll post a link here when I'm finished.

**Comment by wickdj** [comment]
Ok. Waiting for it. Thank You!

**Comment by wstyres** [comment]
Here is the link: https://translate.getzbra.com/translate/zebra/28/en-hu

You'll have to create an account with Crowdin to translate the strings but you can do that by linking your GitHub. Once you translate them they'll be included in the next beta of Zebra! Thanks!
