### ISSUE TITLE
Ability to disable repo timed out request

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#673]
**Is your feature request related to a problem? Please describe.**
Usually when a repo goes down, a timed out console message will display (`The request timed out. for http:...`), this is sometimes cumbersome and not necessary, as repo do goes down for maintenance and such.

**Describe the solution you'd like**
Ability to disable this in settings, or perhaps better, just highlight red (colorize) the timed out repo on the sources tab.

**Describe alternatives you've considered**
Alternative way is to swipe to disable specific repo (from refreshing) on sources tab, without removing it.

**Comment by wstyres** [comment]
"Disabling" the repo timed out request would result in Zebra waiting on the repo to respond for an indefinite amount of time. Could you clarify more on what you mean by this? Would you just like for the message not to appear? I think the message is pretty important as it lets a user know that a source was not refreshed due to an error on their side. Repositories rarely go down and if they do it is a problem that users should know about so they know why it was not refreshed.

**Comment by yur1xpp** [comment]
Oh no, I didn't mean disabling the repo timed out request, but to disable displaying the message, sorry if I was not clear. You're right about the message is important for user to know, but sometimes I used zebra for quick installation or removal of tweak without waiting for the sources refresh to finish, and once it's finish refreshing sources, it will overlap with the installation console.

Another case scenario is that usually the not so popular repo (other than packix, bigboss etc) where the devs managing the repo alone, it sometimes will goes down frequently, and I do host my own local repo which is not always online too.

I try to modify Zebra's ZBRefreshViewController using Flex but didn't success 😁

**Comment by wstyres** [comment]
I think there is too small of a need for this to be implemented in Zebra itself. 

The code for presenting the console after a refresh w/ errors is located [here](https://github.com/wstyres/Zebra/blob/37899460eb1292c25a4b5fb9e9fbafe57cd90cb0/Zebra/Tabs/ZBTabBarController.m#L171). If you'd like to make a Flex patch I would suggest hooking the errorMessages property and going from there.
