### ISSUE TITLE
[BUG] Missing title in settings

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#676]
**Describe the bug**

Missing title in settings for "swipe actions display as". The other settings have titles.

**Screenshots**

Missing title:
![208D044D-2AAC-497A-BE24-B43641DD89E4](https://user-images.githubusercontent.com/51668635/70453801-ab107880-1aa9-11ea-84a0-02eb0fb05f29.jpeg)
What it is supposed to look like:
![4077426F-4D2B-46C5-A7B9-33E30C933E90](https://user-images.githubusercontent.com/51668635/70453823-b368b380-1aa9-11ea-88b0-40985ac9dc3f.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1 b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta 31 
 - Device Type [e.g. iPhone or iPad]: iPhone Xs
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Chimera

**Comment by wstyres** [comment]
Fixed as of be16443a1d112f664be91d9d5ed6664f1a1736ad though I'm still looking for a new title for this setting.

**Comment by worldlydev** [comment]
> Fixed as of [be16443](https://github.com/wstyres/Zebra/commit/be16443a1d112f664be91d9d5ed6664f1a1736ad) though I'm still looking for a new title for this setting.

Might I suggest “swipe actions”? Swipe actions is infinitely simpler and I honestly don’t think you could find a better name. The title should do as long as there is a description that explains how the settings work.
