### ISSUE TITLE
Descriptions for all settings

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#677]
**Describe the solution you'd like**

Descriptions for all settings.

Like this:
![5F5A1ACC-616A-40B8-9376-5D8D1E648321](https://user-images.githubusercontent.com/51668635/70454147-3db11780-1aaa-11ea-9bd2-2fc0981cd2f4.jpeg)
These are missing descriptions:
![370D8438-179F-4A9B-90D9-B577D6FB1E7C](https://user-images.githubusercontent.com/51668635/70454166-486bac80-1aaa-11ea-8b71-2edc83ab08ed.jpeg)
![96D56587-7AF5-49BD-A90E-C3B228DBA9FF](https://user-images.githubusercontent.com/51668635/70454230-60dbc700-1aaa-11ea-9e5c-73b31de0d658.jpeg)

**Comment by wstyres** [comment]
The "Swipe Actions" description already appears outside of its cell but it doesn't make sense to me as is. Likely what I would do instead of text would be an actual image showing the user what will appear with a specific option.
