### ISSUE TITLE
Add localization support to dpkg tags

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#679]
![67D8A8F9-3B7D-4B74-8C38-B3CBB6ACAF1F](https://user-images.githubusercontent.com/51668635/70455320-620df380-1aac-11ea-9f07-04039e10078f.jpeg)

**Comment by wstyres** [comment]
I'll work on this once we have a better design for the external package manager in the future.

**Comment by wstyres** [comment]
We're going to remove this view and replace it with an actual rendered depiction for installing external packages so there is no need to localize the dpkg tags themselves.
