### ISSUE TITLE
Option to change language in settings

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#680]
**Describe the solution you'd like**

Option in settings to follow system language or pick from the supported languages.

![D271151B-9F53-400A-BEF3-D6D17F0200B4](https://user-images.githubusercontent.com/51668635/70455454-a4cfcb80-1aac-11ea-802c-95ace96c995d.jpeg)

**Comment by wstyres** [comment]
This is something we will look into and include in a future version

**Comment by wstyres** [comment]
This would also serve as a better place to put the "Help translate Zebra" button link than the homepage

**Comment by PoomSmart** [comment]
Note that iOS 13 already provides this feature.

**Comment by worldlydev** [comment]
> Note that iOS 13 already provides this feature.

Coolio. Does Zebra have a page in settings like👇or is that just for apps?

![7E3EB037-BB8E-409D-A444-AFDABFEFABAB](https://user-images.githubusercontent.com/51668635/70861424-f3a6b680-1f2d-11ea-8c6c-a1ef872a2b20.png)


And would it be possible to implement one? For notifications, language selection, etc.

**Comment by eve0415** [comment]
I’m still using ios12 and I want that to be implement so that I don’t have to change all language on my iPhone just to take video of Zebra

**Comment by wstyres** [comment]
Implemented as of ebe6a030ead03e47b322cc7423c0b42fb5b8042b.

**Comment by worldlydev** [comment]
You definitely deserve a round of applause 👏👏
