### ISSUE TITLE
Unexpected UI behavior when refreshing sources

### ISSUE THREAD

**Issue by mattp12** [wstyres/Zebra#682]
Describe the bug:
When refreshing sources, the current page either gets cut off slightly, or is pushed down, depending on if you're using light or dark mode.

To Reproduce:
1. Turn either light or dark mode on
2. Swipe down to refresh sources

Expected behavior:
For the current page to behave normally.

Screenshots:
N/A, see videos below.

Device Information (please complete the following information):
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0 beta 32
 - Device Type [e.g. iPhone or iPad]: iPhone 8+
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

Crash Log or System Log:
N/A

Additional context:
Video showing dark mode behavior: https://youtu.be/diaaZ6_5y68 
(The spinner being glitchy when refreshing on the packages tab is already addressed in another issue, https://github.com/wstyres/Zebra/issues/681)

Video showing light mode behavior: https://youtu.be/cyoq_2I5jBE

**Comment by wstyres** [comment]
Resolved in 1.1
