### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CySxL** [wstyres/Zebra#683]
**Describe the bug**
Do those repos which cannot be fetched still be stored in somewhere? Because I imported my all repos from Cydia and could’t find those repos in screenshot to delete or manage them.
**To Reproduce**

**Expected behavior**
Still show those cannot be fetched repos in repos section in order to manage them.

**Screenshots**
![F2E9CDF5-DF3A-4A4A-982B-DD231464E36C](https://user-images.githubusercontent.com/15531137/70491901-97aeed00-1b3d-11ea-8a15-7b10ef76f441.png)

**Device Information (please complete the following information):**
 - iOS Version [iOS12.4] 
 - Zebra Version [1.0~beta32-1] 
 - Device Type [ iPhone6s]
 - Jailbreak Type [unc0ver, 3.7.0~b4]

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
The sources list is located at `/var/mobile/Library/Application Support/xyz.willy.zebra/sources.list` you can remove the bad URLs from there. In the future we will try adding more verification for repos imported from Cydia so that this does not happen.

**Comment by CySxL** [comment]
Appreciate it .
