### ISSUE TITLE
[Localize] Repo Blacklist title not localized

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#685]
![D11D020C-84A1-4057-828B-16A44E2A8678](https://user-images.githubusercontent.com/40632436/70504387-081f3380-1b69-11ea-82ad-5999b55d474e.png)

Just in case, I just post it here.
Title isn’t localized

**Comment by relisiuol** [comment]
You can contribute here: https://translate.getzbra.com/

**Comment by eve0415** [comment]
Yes I know that, I translated all of the strings to Japanese.
I mean there isn’t in crowdin, @wstyres might had forget it so I just posted here

**Comment by eve0415** [comment]
There is “Featured Package” or “Repo Featured” but no “Featured Repos”

**Comment by worldlydev** [comment]
@eve0415 means that the title is not localizable. There isn't an available string to translate.

**Comment by wstyres** [comment]
I added the string in 6e33c45012a1c198562f73317f034b89eb311785 but it will likely change in a future version. Should be available on CrowdIn soon.
