### ISSUE TITLE
[BUG] issue with dependencies when removing some package

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#686]
**Describe the bug**
Zebra didn’t show me other package that will be removed

**To Reproduce**
trying to delete this:
![BA49C087-9D91-4725-AE7B-015903A1FBF5](https://user-images.githubusercontent.com/40632436/70504624-7237d880-1b69-11ea-8036-a6a461cbfc28.png)

**Expected behavior**
show me the package that will be remove, otherwise i just remove it

**Screenshots**
![6E2D29DB-CCD8-4919-A557-F7EFAC7953BE](https://user-images.githubusercontent.com/40632436/70504783-d2c71580-1b69-11ea-8090-fe0f724c4e9c.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 32-1
 - Device Type [e.g. iPhone or iPad]: iphone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 

![46FF4453-596F-4330-BE8D-7C0E20608C4A](https://user-images.githubusercontent.com/40632436/70504875-00ac5a00-1b6a-11ea-97b8-74031278a0db.png)
![Uploading 0977E4FB-DA7A-409A-AE27-197BDC502DCD.png…]()

**Comment by wstyres** [comment]
Could you provide a dpkg status log? Located at /var/lib/dpkg/status/

**Comment by eve0415** [comment]
just sent to dm

**Comment by wstyres** [comment]
Should be fixed as of ff0f38b796c1927f4a1e1956272463a9e290d8b8.
![Simulator Screen Shot - iPhone 11 - 2019-12-11 at 19 34 05](https://user-images.githubusercontent.com/19736790/70672476-5e65a280-1c4d-11ea-9449-48884043342a.png)

**Comment by eve0415** [comment]
Thank you

**Comment by wstyres** [comment]
Please test in beta 33 to see if the issue is resolved.

**Comment by eve0415** [comment]
has been fixed in beta33
