### ISSUE TITLE
Auto Lock while downloading

### ISSUE THREAD

**Issue by Squidkingdom** [wstyres/Zebra#690]
**Is your feature request related to a problem? Please describe.**

Yes, when I download large packages, my phone falls asleep and the connection fails.

**Describe the solution you'd like**

Two ways to solve this.
1. Disable auto lock while downloading a package

**Describe alternatives you've considered**

 Adding support for downloading packages in the background.

**Additional context**

**Comment by aabosh** [comment]
Done in commit 2979a447.
