### ISSUE TITLE
Dark Mode Issues

### ISSUE THREAD

**Issue by SteppedSubset58** [wstyres/Zebra#696]
**Describe the bug**
Zebra has a few issues with Dark Mode (only tested with the “iOS 13” setting). See screenshots for examples. 

**To Reproduce**
Switch Zebra to Dark Mode (I tested this with the “iOS 13” setting though the bugs may also be present with other Dark Mode settings). Add a package to the Queue. Switch to the Packages tab and tap Clear. Notice the black text on the dark background (and if you hold your finger on the Cancel button you’ll see it glow white). 

**Expected behavior**
For the text to be white on the dark background and for the Cancel button’s accent color to be a lighter gray as opposed to white

**Screenshots**
![B5305252-172B-4599-B545-E8AED4DF9E1F](https://user-images.githubusercontent.com/51096169/70869114-7d1daf00-1f55-11ea-8450-008ffb7a534b.png)
![CFA3CFE4-9DD9-481D-8058-E4C4AB9A4A44](https://user-images.githubusercontent.com/51096169/70869113-7d1daf00-1f55-11ea-9fd8-1cb80c766595.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~beta23-1
 - Device Type [e.g. iPhone or iPad]: iPhone 8 Plus
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n version 0.9.7 (beta)

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by wstyres** [comment]
The latest beta is beta 33-1 and is available from https://getzbra.com/beta/ please update and check if the issue is resolved.
