### ISSUE TITLE
Bingner repo is duplicated

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#697]
**Describe the bug**
There’s two Bingner’s repo added to the sources.

**To Reproduce**
Delete either one, and restart Zebra. It’ll comes back as duplicates.

**Expected behavior**
Only one unique repo.

**Screenshots**
https://imgur.com/a/fgSpQJh

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Could you post the contents of your sources.list file? It could be that the repo was duplicated in the original file. The file is located at /var/mobile/Library/Application Support/xyz.willy.zebra/

**Comment by yur1xpp** [comment]
![7A346CB1-2A1D-4690-9995-B065AE353BF2](https://user-images.githubusercontent.com/34767893/70998782-075f4200-2113-11ea-8a6b-5523247d153b.jpeg)

Yeah, seems like it’s duplicated. But I don’t how it got there.

**Comment by wstyres** [comment]
"Drop Tables" is a debug option that simply allows you to delete all of the information stored in Zebra's database and re-download it in case there are any unforeseen glitches.

**Comment by wstyres** [comment]
I will keep this issue open to keep an eye on it in the future.
