### ISSUE TITLE
Can’t install or update alongside “APT 0.6 Transitional “ from the Cydia/Telesphoreo repo

### ISSUE THREAD

**Issue by RedTailedLizerd** [wstyres/Zebra#698]
**Describe the bug**
I had 3 things to upgrade, including aforementioned one. When I went and updated them, I weirdly saw the very same updates tab with no changes to any of the packages. I install them one-by-one until only one was not passing this and leaving the list of packages with updates. This one still does it. I tested again installing Bolders and its dependency with APT 0.6 and the whole app crashed and when I reopened Zebra, Bolders and it’s dependency were install and our problem package was still waiting to be upgraded. 

**To Reproduce**
Upgrade APT 0.6 Transitional, ProfileDirectory and zip from the Cydia/Telesphoreo repo simultaneously. 

**Expected behavior**
Nothing more in the Available Upgrade(s) section, all those packages in my recent installs. 

**Screenshots**
A simulated/recreated series of events 
![C96FAF2C-BACB-40DE-A5EA-7F6548FCB695](https://user-images.githubusercontent.com/20884437/70968358-01138c00-2067-11ea-8e05-eb4406a5a12d.png)
![2AE064B6-6653-4C22-BD9E-E41BA96C2A0D](https://user-images.githubusercontent.com/20884437/70968359-01138c00-2067-11ea-9d7b-e0efda4728e1.png)
![333DD4B5-9B8E-454A-B28E-4C10EB735877](https://user-images.githubusercontent.com/20884437/70968360-01138c00-2067-11ea-87ed-724cc2b80f54.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0\~beta23-1
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
N/A

**Additional context**
The problem before was on pack delay others, but now one pack can’t be installed which is more an issue of that specific dev i think

**Comment by eve0415** [comment]
You should use the latest version from the beta repo of Zebra
https://getzbra.com/beta/

**Comment by RedTailedLizerd** [comment]
I am now on 33-1 and the problem remains. 

I’m not too worried about it for my own use, I’m just reporting it to maybe help development

**Comment by eve0415** [comment]
weird, I couldn’t find APT 0.6 Transitional
![14DBC672-7514-429B-8313-92E259C54325](https://user-images.githubusercontent.com/40632436/71001042-c7eb2280-211f-11ea-848d-737caf0ab008.png)
![A02D23E4-8C41-4048-A9F3-B9AD71CD3D18](https://user-images.githubusercontent.com/40632436/71001043-c883b900-211f-11ea-9fb9-50faa39e4cae.png)

**Comment by RedTailedLizerd** [comment]
That is weird. I got updates for 0.7 and installed them but then they never showed in the recent section either and I never saw them again. Also, Zebra has said that http://apt.saurik.com/ is incompatible with Zebra and must be removed from the sources file

**Comment by RedTailedLizerd** [comment]
![05B1C5E8-B06E-4C6D-8B64-BCFCDD7D54BC](https://user-images.githubusercontent.com/20884437/71005167-2d53fa80-20b1-11ea-8a0e-77da121355cc.png)
![ACE9048A-C949-40EC-B221-BEDFC0C3A867](https://user-images.githubusercontent.com/20884437/71005168-2d53fa80-20b1-11ea-81ff-2dd81a7a806f.png)

It says I have 0.6 installed but still wants me to upgrade

**Comment by eve0415** [comment]
Yes because you are using the old one. Read this. This will explain your issue.
https://github.com/wstyres/Zebra/issues/694#issuecomment-565770093

**Comment by RedTailedLizerd** [comment]
Oh so maybe this explains all the issues I’ve presented in this thread. 

However, I had https://apt.bingner.com/ before and Zebra told me to remove it so I did and replaced it with the saurik one.

**Comment by eve0415** [comment]
I think it’s because you were using the old version of Zebra. Go to community source so that you can find repos there.

**Comment by RedTailedLizerd** [comment]
Ah you’re probably right. I added bingner and removed saurik. Should I remove everything from the saurik repo or something? 

Or maybe it’s all good now

Sorry for this bug report for an old version of Zebra

**Comment by eve0415** [comment]
No, I don’t think you don’t have to delete all package from saurik repo. It is still used in bingner repo as well (the updated package for new iOS) ex) apt, cydia installer

**Comment by RedTailedLizerd** [comment]
Okay, thank you
