### ISSUE TITLE
[BUG] Doesn’t queue dependencies on second time

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#699]
**Describe the bug**
As the title says.

**To Reproduce**
Try queuing any package that depends on other packages. 
Delete queues
Again, try queuing any packages that need other packages

**Expected behavior**
Queue dependencies anytime.

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/656625520003383316/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta up to rc1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Additional context**
One more issue on this video. The pop up won’t come up for “Substitute & TweakInject Dummy” when pressing information mark.

**Comment by wstyres** [comment]
The main issue is fixed as of dcf2ed0719ce656af9c1af0e83ecffcb79d2306a. Still working on the other issue reported.

**Comment by wstyres** [comment]
Issue for "Substitute & TweakInject Dummy" not showing up fixed as of 640518a17e59af7c3aab4074ddfaaf7da73819aa.

**Comment by eve0415** [comment]
This issue appeared again in RC3.
