### ISSUE TITLE
Sileo Depictions

### ISSUE THREAD

**Issue by heyitzspencer** [wstyres/Zebra#7]
I think adding Sileo's native depictions instead of using the web depictions would bring this project to the next level!

You can find documentation at [https://developer.getsileo.app/native-depictions](https://developer.getsileo.app/native-depictions)

**Comment by wstyres** [comment]
3f521fd adds support for ZBPackage -getField: which if called on @"SileoDepiction" will return the URL for Sileo's depiction. Since Zebra does not yet have support for these new depictions, a tweak can be made to add them if anyone chooses to.

**Comment by pancakeufo** [comment]
> I think adding Sileo's native depictions instead of using the web depictions would bring this project to the next level!
> 
> You can find documentation at https://developer.getsileo.app/native-depictions

@heyitzspencer Looks like pixelomer will create ModernDepictions for Zebra https://twitter.com/pixelomer/status/1127251383089020929 and https://twitter.com/pixelomer/status/1127303411693752333

**Comment by heyitzspencer** [comment]
@pancakeufo thank you, i'll close this issue now!
