### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by kickinvapors** [wstyres/Zebra#70]
**Describe the bug**
Toneenabler shows an update but it’s actualy a downgrade. 
**To Reproduce**
Install toneenabler for unlimapps repo with cydia add repo to zebra. 

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version 11.1.2 iPhone 6s+ 
![FE21493C-5AFD-424E-BC79-5CC140283392](https://user-images.githubusercontent.com/50551387/57591722-cbbb2480-7500-11e9-872b-a911d846f932.png)
![AB1D434D-F812-4EBC-A95E-9BC50E5EC513](https://user-images.githubusercontent.com/50551387/57591723-cbbb2480-7500-11e9-90fa-25d4bfb769e4.png)

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by kickinvapors** [comment]
Idk if I need to add more for help or not?

**Comment by wstyres** [comment]
Fixed as of b284439
