### ISSUE TITLE
Zebra still says “beta” on welcome screen

### ISSUE THREAD

**Issue by Burrit0z** [wstyres/Zebra#702]
**Describe the bug**
The welcome page says “Welcome to the Zebra beta” on zebra 1.0-c1
**To Reproduce**
Open zebra
**Expected behavior**
The welcome page will say “beta”

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]:
12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
1.0-c1
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.
N/a
**Additional context**

**Comment by wstyres** [comment]
Fair enough, I changed the string to "Welcome to Zebra!" in a662fc70320e1e6352ad901ba9fbe2fa53c1b39b.

**Comment by Burrit0z** [comment]
> Fair enough, I changed the string to "Welcome to Zebra!" in [a662fc7](https://github.com/wstyres/Zebra/commit/a662fc70320e1e6352ad901ba9fbe2fa53c1b39b).

Thanks! Fixed my OCD!
