### ISSUE TITLE
Don’t make multiple queue for the same package

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#705]
**Is your feature request related to a problem? Please describe.**
I can queue to downgrade different version on the same package.

**Describe the solution you'd like**
I don’t think we don’t need to downgrade many times
![4CA75BEE-8790-4F9F-AB32-60B1895C79A6](https://user-images.githubusercontent.com/40632436/71051313-429d5780-218b-11ea-8ae2-d8cfacf87913.png)

**Describe alternatives you've considered**
Make only one queue for the package

**Comment by eve0415** [comment]
Updating and Downgrading the same package is not necessary I think. 
![51526587-7F8B-4C2F-BDC8-CFCA3D51BBD9](https://user-images.githubusercontent.com/40632436/71051512-ebe44d80-218b-11ea-978f-240eed9d64aa.png)

**Comment by wstyres** [comment]
I would label this more of a bug than an intended feature.

**Comment by eve0415** [comment]
> I would label this more of a bug than an intended feature.

ok, thanks

**Comment by wstyres** [comment]
Fixed as of 5f65aa8a04c9afa0aa1fbcee25bf882d9425f8f2.
