### ISSUE TITLE
[BUG] Label for downgrade

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#706]
**Describe the bug**
No label for downgrading package in queue 

**To Reproduce**
Downgrade queue 

**Expected behavior**
Label 

**Screenshots**
https://cdn.discordapp.com/attachments/566255609251364867/656685226445111306/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta up to rc1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by wstyres** [comment]
Fixed as of 71844fdc81b10cd248ff797d9516b6afe220186a.
