### ISSUE TITLE
[UI Bug] Packages from Packix don't load images in Home page

### ISSUE THREAD

**Issue by gkeep** [wstyres/Zebra#707]
**Describe the bug**
Packages from Packix don't load images on Home page. Someone reported this on Discord some time ago. I am experiencing it too, for some time now. 

**To Reproduce**
Enable 'Repo Featured' or select Packix in Featured Packages (Feature Type -> Random -> ../ -> Select Repos to be Featured)

**Expected behavior**
Images from Packix should load.

**Screenshots**
Only Packix Enabled
![IMG_0751](https://user-images.githubusercontent.com/20600053/71053912-27b5ed80-2161-11ea-923c-c17c6f875535.PNG)

Chariz, Dynastic and a few others (no Packix)
![IMG_0749](https://user-images.githubusercontent.com/20600053/71053917-2b497480-2161-11ea-8ec4-e158649bcea1.PNG)

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: rc1
 - Device Type: iPhone 5s
 - Jailbreak Type: checkra1n

**Comment by eve0415** [comment]
I can reproduce that too

**Comment by wstyres** [comment]
I'm not able to reproduce this. Randomly selected packages from Packix load just fine for me. I tried this on an 11, Xs, and a 5s on 13.3, 12.4, and 12.4 respectively. 

![Simulator Screen Shot - iPhone Xs - 2019-12-18 at 11 25 43](https://user-images.githubusercontent.com/19736790/71104103-45974880-2189-11ea-8648-e52b4d53460b.png)
![Simulator Screen Shot - iPhone 5s - 2019-12-18 at 11 25 20](https://user-images.githubusercontent.com/19736790/71104107-46c87580-2189-11ea-82a5-5c67046307a1.png)

I do find it a bit odd that the packages that don't load are always from Packix though. I would have to see Zebra's database files (located at `/var/mobile/Library/Application Support/xyz.willy.zebra/zebra.db`) to know why these aren't being read for sure.

**Comment by gkeep** [comment]
[Here](https://cvws.icloud-content.com/B/AZtNiHF37b64vqaHUukGUcsB5CyBAY7WWHLyDnTVR0XnMRhF1c-IsfLO/zebra.db?o=AkqyfLwhISuJyZvFWX1C5KOmnisJtPVY5on5EQWFs_ei&v=1&x=3&a=CAogq2O-EOCdx3xbHyaN_KsfofAFxGAtwBZ7yby3SaNcy3sSHRCPwOfO8S0Yr7eez_EtIgEAUgQB5CyBWgSIsfLO&e=1576687606&k=1h7l_wzRdo9S6PfwbDlY8w&fl=&r=d0b62d93-8016-4752-8929-71f0cac01753-1&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=65&s=FooB9Cw2F8fkIJwMfcw3l1zYCk0) is my zebra.db.

**Comment by wstyres** [comment]
Are you able to see any icons in Packix's repo listing? For example, the listing for nControl:
![Simulator Screen Shot - iPhone Xs - 2019-12-18 at 11 42 38](https://user-images.githubusercontent.com/19736790/71105399-81331200-218b-11ea-926a-b12e1ad548af.png)

And are you able to see the image when you visit this URL? https://repo.packix.com/api/Packages/5d7564ab3fb7400011e7ee03/icon/download

**Comment by gkeep** [comment]
Yes and yes.

**Comment by wstyres** [comment]
What about https://repo.packix.com/api/Packages/5d7564ab3fb7400011e7ee03/icon/download?size=medium&hash=2

**Comment by gkeep** [comment]
Yep.

**Comment by wstyres** [comment]
Very odd, I'll see if I can't load better placeholder images because the URL should be loading... The download is just failing somehow.

**Comment by wstyres** [comment]
I made the placeholder image respective of the section image as of bc1fae1f0c2ca2f18f598c7a9f61a45be00262a2 but I'm going to leave the issue open because it seems there is a larger issue here.

**Comment by gkeep** [comment]
Looks like new placeholder images don't work on Packix, too.
![IMG_0762](https://user-images.githubusercontent.com/20600053/71228042-21a34680-22f2-11ea-822f-d30c66fc6d60.jpeg)


Meanwhile, non-Packix:
![IMG_0758](https://user-images.githubusercontent.com/20600053/71227939-c83b1780-22f1-11ea-8a39-6f233c904c49.jpeg)

**Comment by wstyres** [comment]
That is even more bizarre...

**Comment by wstyres** [comment]
Here is a debug build of Zebra that will (hopefully) show a popup when the image download fails. Try it out: https://www.dropbox.com/s/c6c8vyq4rurx66s/xyz.willy.zebra_1.0~beta31-1%2Bdebug_iphoneos-arm.deb?dl=0

**Comment by gkeep** [comment]
No popup. Old placeholder images for Packix packages.

**Comment by wstyres** [comment]
What do you mean by old placeholder images? There shouldn't be any placeholder images

**Comment by gkeep** [comment]
![IMG_0763](https://user-images.githubusercontent.com/20600053/71230007-e5271900-22f8-11ea-81dd-2bc8145760f0.PNG)

**Comment by gkeep** [comment]
Maybe you sent the wrong deb? The one you linked is debug of beta31.

**Comment by wstyres** [comment]
🤦‍♂️ Here is the actual link https://www.dropbox.com/s/c6c8vyq4rurx66s/xyz.willy.zebra_1.0~beta31-1%2Bdebug_iphoneos-arm.deb?dl=0 an

**Comment by eve0415** [comment]
![B8ABD9A2-EE03-4865-A496-C3112466A6B8](https://user-images.githubusercontent.com/40632436/71230459-099ce880-232d-11ea-9a07-33c4295d3c1a.png)

**Comment by wstyres** [comment]
@eve0415 Could you set your system language to English and post again? The description of the error is the important part.

**Comment by gkeep** [comment]
I just selected only Packix packages and now it works... wtf
![IMG_0765](https://user-images.githubusercontent.com/20600053/71230562-359f7600-22fb-11ea-9a77-d9ef59621716.jpeg)

Here's my popup, but with Chariz, for some reason
![IMG_0764](https://user-images.githubusercontent.com/20600053/71230537-199bd480-22fb-11ea-94f0-56aaae036341.PNG)

**Comment by eve0415** [comment]
![B65B06DE-7F18-4BEC-A15A-7AE968267F20](https://user-images.githubusercontent.com/40632436/71230588-947de300-232d-11ea-9c0e-b8b89d42906c.png)
![A2847B58-A2DB-4E54-8493-33103414A05D](https://user-images.githubusercontent.com/40632436/71230589-947de300-232d-11ea-9780-a38488eafc8d.png)

**Comment by wstyres** [comment]
Here is another debug version, it should now give an HTTP error code too https://www.dropbox.com/s/9vp9ai31aolz1rr/xyz.willy.zebra_1.0~rc2-1-2%2Bdebug_iphoneos-arm.deb?dl=0

**Comment by gkeep** [comment]
My Packix doesn't load images if I select Repo Featured in Feature Type, but no popups. 

If I select Packix only (Feature Type = Random) Packix loads images.

Popup returns 404.

**Comment by eve0415** [comment]
![FDBEE5FF-4EF8-4066-9190-0FA0453052C8](https://user-images.githubusercontent.com/40632436/71230930-ed9a4680-232e-11ea-9e40-a39935cd7a2d.png)
![BD8FEAD4-D134-4419-A6DD-1D4FF7123861](https://user-images.githubusercontent.com/40632436/71230931-ee32dd00-232e-11ea-9c9e-307ed733c0f6.png)
![D9443556-EDEA-45D8-BB98-6468500BB0D0](https://user-images.githubusercontent.com/40632436/71230932-ee32dd00-232e-11ea-9c5e-3ee050e36c84.png)

**Comment by wstyres** [comment]
I don't think Packix provides a featured.json so there shouldn't be any Packix packages when selecting "Repo Featured". The chariz images not loading are now a different problem? Try out this deb https://www.dropbox.com/s/t9lglzfmpcblrjo/xyz.willy.zebra_1.0~rc2-1-3%2Bdebug_iphoneos-arm.deb?dl=0

**Comment by eve0415** [comment]
Only Packix
![108227E7-4A12-4FC1-ACFF-A141246ECD2A](https://user-images.githubusercontent.com/40632436/71231102-c09a6380-232f-11ea-9bc4-0d6e618ed917.png)
![A62C2499-9D01-482E-8A4C-5194DD70EE8B](https://user-images.githubusercontent.com/40632436/71231103-c09a6380-232f-11ea-9460-707bd1d50735.png)

**Comment by gkeep** [comment]
![IMG_0768](https://user-images.githubusercontent.com/20600053/71231137-9e87ed80-22fd-11ea-89f1-fc70e5413488.PNG)
![IMG_0767](https://user-images.githubusercontent.com/20600053/71231140-9fb91a80-22fd-11ea-95b2-83beb1c3a3c3.PNG)

**Comment by wstyres** [comment]
@gkeep Can you delete https://repo.chariz.io and add https://repo.chariz.com instead? I think your cached featured plist is old because those packages no longer exist on Chariz. They exist on Packix instead.

**Comment by gkeep** [comment]
...I didn't have https://repo.chariz.io added 
![IMG_0769](https://user-images.githubusercontent.com/20600053/71231282-4998a700-22fe-11ea-801c-b5ae043e6b4d.jpeg)

**Comment by gkeep** [comment]
Maybe it redirects to .io for images?

**Comment by eve0415** [comment]
when the setting is to repo featured, the error says chariz.io , if random, chariz.com

**Comment by eve0415** [comment]
Like this
![9E3B99D1-F563-4872-81A9-E1FC0E073EF1](https://user-images.githubusercontent.com/40632436/71231389-0d326e80-2331-11ea-9d7f-f350f1af55e0.png)
![A8B432E4-E107-427D-A8BE-EF68CD15E37E](https://user-images.githubusercontent.com/40632436/71231390-0d326e80-2331-11ea-91fd-536879ea83b4.png)

**Comment by wstyres** [comment]
@gkeep Either way, could you open Zebra's documents directory and delete the Caches folder? The color flow and ncontrol packages don't exist on Chariz anymore, they exist on Packix.

**Comment by gkeep** [comment]
Sure

**Comment by wstyres** [comment]
@eve0415 Same for you, dimid is no longer a package on chariz, it is on Packix.

**Comment by gkeep** [comment]
That has fixed most popups. One new from Chariz, though
![IMG_0771](https://user-images.githubusercontent.com/20600053/71231631-df810180-22ff-11ea-977b-a89252f4d368.PNG)

**Comment by eve0415** [comment]
After deleting cache
![850DB74A-2F1D-432D-86D1-19A87B1556E3](https://user-images.githubusercontent.com/40632436/71231793-aca43100-2332-11ea-9683-31b7223714bc.png)

**Comment by wstyres** [comment]
Some of the icons in the background look like they're loaded from Packix though in that screenshot @eve0415

**Comment by wstyres** [comment]
As for sunflower @gkeep, it simply doesn't have an icon. The server is returning a 403 instead of a 404 but I'm not sure exactly why.

**Comment by eve0415** [comment]
This package seem to be returning 404 but deleting cache made errors more less and loads more icons
![C9EFE3A6-835A-419F-837F-37C3FF0D34C1](https://user-images.githubusercontent.com/40632436/71232008-93e84b00-2333-11ea-857a-1ea7e6396f78.png)
![22E72850-0C85-44A7-A3EA-2474DE1926AB](https://user-images.githubusercontent.com/40632436/71232009-9480e180-2333-11ea-9104-7a80a63dfc49.png)

**Comment by gkeep** [comment]
Packix returns this error only if Random from Packix is enabled (same as @eve0415's) 
![IMG_0774](https://user-images.githubusercontent.com/20600053/71231978-29b6b280-2301-11ea-8342-7219546955e5.PNG)


If Repo Featured is enabled everything works! So it's probably a Packix issue.
![IMG_0773](https://user-images.githubusercontent.com/20600053/71232087-90d46700-2301-11ea-8fce-89e73b67a583.PNG)

**Comment by wstyres** [comment]
Yeah this is looking more and more like an odd Packix server-side issue. I get some weird responses from their API sometimes. Chariz's URLs on the other hand have valid error messages so I think it is just a Packix only issue.
