### ISSUE TITLE
Scroll position lost in packages list

### ISSUE THREAD

**Issue by EminFPS** [wstyres/Zebra#708]
**Describe the bug**
When opening a specific repo and browsing tweaks by date, the list resets and scrolls all the way back up when exiting the tweak page. 

**To Reproduce**
1. Open Zebra and click on sources. 
2. Open a repo.
3. Pick a sub-category and sort its tweaks by date. 
4. Click on a specific tweak.
5. Go back to the previous page. The list will reset and you must scroll all the way to wherever you were. 

**Expected behavior**
The list must stay where it was when you go back to it, instead of jumping all the way back to the top when you return from a tweak page. 

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~rc1 
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Checkra1n 

**Crash Log or System Log**
N/A. No crashes occur. 

**Additional context**

**Comment by wstyres** [comment]
Does this only happen when sorting tweaks by date?

**Comment by EminFPS** [comment]
It happens when sorting both by date and by alphabetical order.

**Comment by wstyres** [comment]
Does this only happen after scrolling all the way to the bottom to load new tweaks?

**Comment by EminFPS** [comment]
Yes it doesn’t jump back if I only scrolled a little bit, without loading new tweaks. I think the issue is related to Zebra loading tweaks as you scroll. When you open a tweak that is far down enough and go back, the list isn’t loaded enough. Because of that, it jumps back to the last loaded spot. For example: I scroll down and open a tweak in the list that is 40% loaded. When I go back, Zebra doesn’t load past 5-10%. So it can’t go back to the same spot because it wasn’t loaded.

**Comment by wstyres** [comment]
This should be resolved since we no longer use batch loading, if it still occurs, open a new issue.
