### ISSUE TITLE
Check conflict before installing

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#711]
**Is your feature request related to a problem? Please describe.**
Some packages conflict when proceeding form the queue.

**Describe the solution you'd like**
I would like Zebra to check conflict before installing or inside queue.

Like this screenshot, I can queue iThemer, Snowboard, anemone at the same time but those packages will conflict each other. It will not install because APT or DPKG will tell us that it conflicts
![6F722158-A7EE-4308-BEF4-45D280134D0D](https://user-images.githubusercontent.com/40632436/71175352-b2563400-22aa-11ea-8bc0-bc3c0976f293.png)

**Comment by worldlydev** [comment]
You mean like a popup saying that the packages conflict before you add them to the queue?

**Comment by eve0415** [comment]
yeah, something like that would be nice to notice people

**Comment by wstyres** [comment]
This is more of a bug with the queuing system that it isn't showing the conflict

**Comment by wstyres** [comment]
Should be fixed as of 73a77de9cb229b96b729ea4180033f918675df0d.

**Comment by eve0415** [comment]
this was fixed in rc3 and was in rc4 but appears again from 1.0.0
