### ISSUE TITLE
Separators become white on home page upon switching from dark to light mode and switching tabs

### ISSUE THREAD

**Issue by mattp12** [wstyres/Zebra#714]
Describe the bug:
When switching between dark and light modes and different tabs, the separators on the home page turn white.

To Reproduce:
1. Be in dark mode on the main page and turn to light mode
2. Switch to any other tab
3. Switch back to the home page and turn dark mode on again. The separators become white. Switching to a different tab and then back again to home resolves this.

Expected behavior:
For the separator color to not change.

Screenshots
N/A, see video below.

Device Information (please complete the following information):
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0 rc2
 - Device Type [e.g. iPhone or iPad]: iPhone 8+
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

Crash Log or System Log:
N/A

Additional context:
Video: https://youtu.be/wyZhQt0_p8g

**Comment by PoomSmart** [comment]
Hopefully fixed in c56e6676c124266cf6e4de420e15cb9a60c35351
