### ISSUE TITLE
ATweakDisabler is not installable

### ISSUE THREAD

**Issue by xi7i6** [wstyres/Zebra#715]
**Describe the bug**
The dependency of SnapBreak tweak can not be installd

**To Reproduce**
Try to install SnapBreak from its repo : https://repo.snapbreak.app/
**Expected behavior**
Install with its dependency 

**Screenshots**
![2B8699AF-BF35-4AED-AA0D-FBC2B423904C](https://user-images.githubusercontent.com/55637002/71216764-7764f800-22cc-11ea-84ea-94b0ea885950.png)

**Device Information (please complete the following information):**
 - iOS Version [12.4]: 
 - Zebra Version [1.0 rc 2]: 
 - Device Type [iPhone]: 
 - Jailbreak Type [uncover, checkr1an]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
![2C24B875-4519-4C69-BD5F-BA3AB3930A26](https://user-images.githubusercontent.com/40632436/71217257-82398000-2300-11ea-9847-dce5a13a044e.png)
Mine works fine

**Comment by xi7i6** [comment]
It shows the dependency but can not install both of the packages.

**Comment by wstyres** [comment]
Because I don't have the package purchased it will take some more time to fix the issue. I hope to have it done before 1.0 but the fix may be pushed back until a future version.

**Comment by xi7i6** [comment]
> Because I don't have the package purchased it will take some more time to fix the issue. I hope to have it done before 1.0 but the fix may be pushed back until a future version.

You only have to register not to purchase the package.

**Comment by wstyres** [comment]
Should be fixed as of e53f3433abe68a49ed8245a9c5a35926be3f2b5c and will be included in 1.0.1. I haven't personally verified this fix for this particular package but there shouldn't be an issue with it.
