### ISSUE TITLE
Being in dark mode and switching to light and then back to dark mode makes white cells appear when refreshing on the sources tab

### ISSUE THREAD

**Issue by mattp12** [wstyres/Zebra#716]
Describe the bug:
Switching from dark mode to light and back to dark and refreshing packages from the sources tab makes some white cells appear for a short time.

To Reproduce:
1. Be in dark mode, and switch to light
2. Switch back to dark
3. Go to the sources tab and swipe down the refresh. Right when the sources finish refreshing, some white cells appear for a moment.

Expected behavior:
For these cells to not appear.

Screenshots:
N/A, see video below.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0 rc2
 - Device Type [e.g. iPhone or iPad]: iPhone 8+
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

Crash Log or System Log:
N/A

Additional context
Video: https://youtu.be/o49_T6RGW6I
This bug seems similar to https://github.com/wstyres/Zebra/issues/714 because of it also having to do with dark and light mode switching.

**Comment by wstyres** [comment]
Resolved in 1.1
