### ISSUE TITLE
[BUG] the version in the queue should be the one that is installed

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#718]
**Describe the bug**
As the title says. When I queued to remove the package that Zebra suggest to update, the queue show us the latest version, not the version I have installed.

**To Reproduce**
Queue the package that is not latest but showing the latest.

**Expected behavior**
Show us the right version

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/657364473325027346/video0.mov

**Device Information (please complete the following information):**
 - iOS Version : 12.4
 - Zebra Version : rc2
 - Device Type : iPhone
 - Jailbreak Type : unc0ver

**Additional context**
Also I want this to be labeled as well.
![CDDF8410-94E5-4523-AC7D-7071EFF06941](https://user-images.githubusercontent.com/40632436/71218407-b6af3b00-2304-11ea-8a2f-52af8c141d73.jpeg)

**Comment by eve0415** [comment]
Additional Context refer to #722

**Comment by wstyres** [comment]
I think this should be fixed as of e72f84bbfeb7961fe1e7cda23d7e21b1227e8a34? If I'm understanding this correctly the version that is added to the queue when you swipe to remove a package that is in the upgrade section is the upgraded package when it should be the package that is installed. If that is the case then this issue is fixed and will be included in 1.0.1.

**Comment by eve0415** [comment]
yes, that is what i was trying to say. thank you.
One more thing and this is not the same issue but related. Trying to re-install the package in the upgrade section, I don’t think there should be re-install option which is actually upgrading the package.
And for downgrading too, when the latest is ver. 2.0 and you have 1.0 installed, trying to downgrade to 1.5 means upgrading. If you can fix this complex thing it would be much more accurate and less confusion.

**Comment by wstyres** [comment]
I understand what you mean. Could you file a different issue for this?

**Comment by eve0415** [comment]
ok sure
