### ISSUE TITLE
[UI BUG] swiping left sometime give UI bug

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#719]
**Describe the bug**
As the title says. It’s hard for me to explain so please watch the video on discord.

**To Reproduce**
Swipe left and put in queue.
Again, swipe left.

**Expected behavior**
Show properly?

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/657370700075499530/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: rc2
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
Does this happen in every tab?

**Comment by eve0415** [comment]
I just checked and yes it does

**Comment by wstyres** [comment]
This is likely an iOS issue on 12.4. I'll see what I can do but it is more than likely that the bug will remain unless the iOS is updated.

**Comment by Sa1Beer777** [comment]
> **Describe the bug**
> As the title says. It’s hard for me to explain so please watch the video on discord.
> 
> **To Reproduce**
> Swipe left and put in queue.
> Again, swipe left.
> 
> **Expected behavior**
> Show properly?
> 
> **Screenshots**
> https://cdn.discordapp.com/attachments/572784833714192395/657370700075499530/video0.mp4
> 
> **Device Information (please complete the following information):**
> 
> * iOS Version: 12.4
> * Zebra Version: rc2
> * Device Type: iPhone
> * Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
This is looking more like an iOS 12 issue with UIKit itself. There is nothing I can do other than suggest not to swipe so much 😉
