### ISSUE TITLE
Replace package version in Queue when modifying a new package

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#720]
**Describe the bug**
After putting package for downgrading or upgrading to one of the version to the queue, I cannot change afterwards before I remove thenm from queue 

**To Reproduce**
Downgrade/ Upgrade to any version
Then, again try to downgrade/ upgrade to any different version

**Expected behavior**
Overwrite queue

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/657373589703491594/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: rc2
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by wstyres** [comment]
Fixed as of e89f3863fe1386ef09b3bb3c780e61b690fce733.
