### ISSUE TITLE
[UI BUG] Queue status label not updated

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#722]
**Describe the bug**
The queue label is not updated when removing package from queue individually.

**To Reproduce**
Queue two or more package
open queue and remove one package

**Expected behavior**
Queue to be update every-time

**Screenshots**
https://github.com/wstyres/Zebra/issues/532#issuecomment-566852264

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: rc1&2
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Additional context**
Going to other tab or moving to somewhere else and back will make queue label update

**Comment by PoomSmart** [comment]
Fixed as of 383d013f76ae10fe7f23fc7955d42f62eec29d5f

**Comment by wstyres** [comment]
Check to see if the issue is resolved in RC3

**Comment by eve0415** [comment]
Fixed in RC3.
