### ISSUE TITLE
[UI BUG] Changing Zebra icon to Original (Dark) doesn't work on iPad Pro 11

### ISSUE THREAD

**Issue by m0kum** [wstyres/Zebra#724]
**Describe the bug**
When trying to change the app icon to Original (Dark) on iPad Pro 11, it won't do so.

**To Reproduce**
Go to Settings > Alternate Icons > Original (Dark) on iPad Pro 11

**Expected behavior**
The app icon changes to Original (Dark)

**Screenshots**
Video: https://gofile.io/?c=SjROwN

**Device Information (please complete the following information):**
 - iOS Version: 12.1 
 - Zebra Version: 1.0 rc2-1 
 - Device Type: iPad Pro 11 
 - Jailbreak Type: Chimera

**Comment by wstyres** [comment]
Could you try running `uicache -a` in terminal? It appears that Zebra doesn't have the proper permission to change its icon for some reason.

**Comment by m0kum** [comment]
Tried it but doesn’t do the trick... The issue also appears to only be with this specific one as the other ones work.

**Comment by wstyres** [comment]
Odd, are you able to find the dark icon in /Applications/Zebra.app?

**Comment by wstyres** [comment]
Seems like the icons aren't named properly, I'll see if I can find a fix.

**Comment by wstyres** [comment]
Fixed as of 974af1070fa739782bf5db3cff58570f71d24fe2.

**Comment by m0kum** [comment]
Awesome, thanks 🙏🏼
