### ISSUE TITLE
Can’t use Zebra after update

### ISSUE THREAD

**Issue by vincedes3** [wstyres/Zebra#725]
**Describe the bug**
After the latest update, I am unable to open tweak page :(

**To Reproduce**
![71EAE0AC-049D-45E8-9545-61B607F0C317](https://user-images.githubusercontent.com/26314689/71245838-de5acf00-2315-11ea-8a3a-cebe70b5f313.png)

Linked the recording screen & the crash log

**Expected behavior**
Fix the bug 
**Screenshots**
If applicable, add screenshots to help explain your problem. -> linked 

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1RC2
 - Device Type [e.g. iPhone or iPad]: iPhone X🅂
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by vincedes3** [comment]
Can’t add screen recording 😪

**Comment by eve0415** [comment]
Try deleting tweak compatible for zebra

**Comment by wstyres** [comment]
This is a problem with Tweak Compatible for Zebra, I'd suggest reporting this to the developer of that Tweak so that they can resolve the issue for their tweak. For the meantime, I'd suggest removing the tweak until the issue is resolved.

**Comment by vincedes3** [comment]
Worked, thanks!

**Comment by Samgisaninja** [comment]
@vincedes3 can you open an issue over on Samgisaninja/tweakcompatible-zebra please? Also which package were you looking at when it crashed?

**Comment by Samgisaninja** [comment]
Also if you could upload /Library/dpkg/status that would be helpful. Thanks.
