### ISSUE TITLE
Request to hide/unhide uuid device

### ISSUE THREAD

**Issue by x4apple** [wstyres/Zebra#727]
**Is your feature request related to a problem? Please describe.**

I here to request for zebra 

I wonder if there possible to uuid options hide/unhide because when I recording screen it show asap on iPad :/ I don’t like show my uuid...

**Comment by worldlydev** [comment]
Already know this is planned but I just saw something and thought it was interesting. My banking app automatically censors sensitive info when screen recording. Not sure how it works but just thought I'd share as I haven't seen it elsewhere.

![0BBA8CE3-0B5D-4EDD-988C-6756C1DADE49](https://user-images.githubusercontent.com/51668635/77677833-8d9be780-6f90-11ea-9b7c-cea014f46f5f.png)

**Comment by wstyres** [comment]
I do like that idea a lot actually, unfortunately it looks like blocking screenshots and screen recordings is quite the difficult task. I've looked around and the only thing I could find is something like [ScreenShieldKit](https://screenshieldkit.com) but unfortunately it looks like that's a paid thing. I'll keep looking but it might be out of reach at the moment.

**Comment by absidue** [comment]
This looks promising: https://medium.com/@abhimuralidharan/detecting-screen-capturing-in-ios-11-cca15881c785

**Comment by wstyres** [comment]
That does look very promising, screenshots are another story though. Everything I can see has the screenshot notification sent AFTER the screenshot is taken so that any changes to the view wouldn't be in the screenshot.

**Comment by wstyres** [comment]
Toggle implemented in 5d9ddc36d17a4f24daf8e36b52948a56da20fb4a.
