### ISSUE TITLE
Cannot find tweaks with search bar. Have to go directly from the repo

### ISSUE THREAD

**Issue by Wo0of** [wstyres/Zebra#731]
**Describe the bug**
I search SnowBoard but it only shows a few of the related tweaks of snowboard. However when I go into the repo I can see all the SnowBoard related tweaks.

**To Reproduce**

**Expected behavior**
By searching SnowBoard I should see all tweaks with a name of SnowBoard 

**Screenshots**
https://imgur.com/a/kRMBSE6

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: ios 12.4.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0 rc2
 - Device Type [e.g. iPhone or iPad]: iPhone6
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n 0.9.7

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
Send me F pls, im sick. I think I just coughed up blood

**Comment by wstyres** [comment]
F

**Comment by wstyres** [comment]
Do the full list of tweaks show when you press "Search" on the keyboard? Zebra doesn't show the full listing to make searching quicker so once you press "Search" all of the results should show up.
![Simulator Screen Shot - iPhone 11 Pro - 2019-12-22 at 13 05 10](https://user-images.githubusercontent.com/19736790/71325499-b73e0200-24bb-11ea-9770-ee15f2453db5.png)

**Comment by aabosh** [comment]
F

**Comment by Wo0of** [comment]
Yep, all started showing up when I clicked Search. Thank you.

![IMG_0011](https://user-images.githubusercontent.com/43326488/71348017-8f779880-25a6-11ea-9c5d-c61396c00360.JPG)
