### ISSUE TITLE
Sync Zebra's Dark Mode with stock iOS Dark Mode on iOS 13.

### ISSUE THREAD

**Issue by kukulama** [wstyres/Zebra#737]
It would be nice when you enable system dark mode, Zebra enables it's Dark Mode automatically.

**Comment by wstyres** [comment]
This is planned for a future release.

**Comment by wstyres** [comment]
Mostly implemented as of c2f75992e76f1396dcea052c1f5d029c35997212. The settings for it still need some work but it looks alright.
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-09 at 22 40 43](https://user-images.githubusercontent.com/19736790/72126999-23ce5300-333c-11ea-938c-ac3c20f493fb.png)
