### ISSUE TITLE
Navigation Bar occludes content on iOS 10

### ISSUE THREAD

**Issue by BurapaLi** [wstyres/Zebra#738]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
![IMG_9869](https://user-images.githubusercontent.com/16442090/71390064-c1860a80-2639-11ea-84c3-07db872beb8f.PNG)

**Comment by BurapaLi** [comment]
on ZBRepoSectionsListTableViewController.m in line 75 modify
if (@available(iOS 10.0, *)) {
        self.automaticallyAdjustsScrollViewInsets = NO;
    }
    CGFloat top = self.navigationController.navigationBar.bounds.size.height;
    self.tableView.contentInset = UIEdgeInsetsMake(top + 20, 0, 64, 0);

**Comment by BurapaLi** [comment]
But this should be more accurate to say
if (@available(iOS 11.0, *)) {
        self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        CGFloat top = self.navigationController.navigationBar.bounds.size.height;
        self.tableView.contentInset = UIEdgeInsetsMake(top + 20, 0, 64, 0);
    } else {
        self.automaticallyAdjustsScrollViewInsets = NO;
        self.edgesForExtendedLayout = UIRectEdgeNone;
    }

**Comment by fi2006sal** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Device Information (please complete the following information):**
> 
> * iOS Version [e.g. 12.1.2 or 10.3.3]:
> * Zebra Version [e.g. 1.0~beta1 or beta1]:
> * Device Type [e.g. iPhone or iPad]:
> * Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]:
> 
> **Crash Log or System Log**
> Please provide a Crash Log to help us solve the issue.
> 
> **Additional context**
> Add any other context about the problem here.
> ![IMG_9869](https://user-images.githubusercontent.com/16442090/71390064-c1860a80-2639-11ea-84c3-07db872beb8f.PNG)


@BurapaLi

**Comment by PoomSmart** [comment]
Implemented in 2423ff9ee39a5765cc7ddf50b76d563b1a510d38

**Comment by wstyres** [comment]
Looks like this fix adds extra padding on iOS 13, I will look into it a little more before pushing out 1.0.3.

**Comment by wstyres** [comment]
Should be fixed as of 893067cd254a943543588cc45de825150b4c5fdc
![Simulator Screen Shot - iPhone 6 - 2020-01-04 at 20 49 22](https://user-images.githubusercontent.com/19736790/71773921-b2556580-2f33-11ea-95fa-616c3de853f9.png)
