### ISSUE TITLE
Debug Server from Bingner won’t update 

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#742]
**Describe the bug**
Debug server update won’t install. 

**To Reproduce**
Try to install the update from Bingner repo. 

https://cdn.discordapp.com/attachments/572784833714192395/659479116894044176/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: RC 3
 - Device Type: XS Max
 - Jailbreak Type: u0

It installs fine with Cydia and Installer.

**Comment by lucky13820** [comment]
Yeah, it’s missing a dependency, libllvm10. Updating from Cydia works fine.

**Comment by wstyres** [comment]
Fixed as of f95295f3c1e492eccf6f3d4e495baa0c86e51a76.
