### ISSUE TITLE
UIcache Legacy Warning with Sileo extension

### ISSUE THREAD

**Issue by iMonZ** [wstyres/Zebra#745]
**Describe the bug**
I installed The Sileo extension with the updates and when I trie to install an app that needs uichache I will get this warning

**Screenshots**

![IMG_0049](https://user-images.githubusercontent.com/11319871/71474617-a0115400-27dc-11ea-8f3c-8bb427bd19c5.png)
![IMG_0050](https://user-images.githubusercontent.com/11319871/71474619-a30c4480-27dc-11ea-94d5-8e9fb070c79b.png)

**Device Information (please complete the following information):**
 - iOS Version [13.3.1]: 
 - Zebra Version [1.0rc3]: 
 - Device Type [iPhone]: 
 - Jailbreak Type [checkra1n with Sileo extension]: 

The point is: it's working perfect for me except this warning.

**Comment by wstyres** [comment]
That is an alert from Chimera's / Sileo's version of UIKit Tools and `uicache` that is triggering that alert. I can't do anything about this popup as it is from Coolstar's loader. Sorry about the inconvenience :(.
