### ISSUE TITLE
[UI BUG] label are not updating when queuing “update” only

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#746]
**Describe the bug**
It’s kind of same problem as #722 but only when queuing to update package only. Queuing for removing, downgrading seems fine.

**To Reproduce**
swipe left and press update

**Expected behavior**
Label “Upgrade”

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/659754215673167882/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: latest
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
Was there a similar issue with downgrading?

**Comment by wstyres** [comment]
Yeah it appears I fixed the issue for downgrading in 71844fd but forgot to implement the fix for upgrading, oops.

**Comment by wstyres** [comment]
Fixed in abae566d1fb647757e0892abfb4e1bb23b4d6c16.
