### ISSUE TITLE
Zebra didn’t delete the app icon

### ISSUE THREAD

**Issue by baobaoit** [wstyres/Zebra#747]
**Describe the bug**
After uninstalled an app, Zebra didn’t delete the app icon on the Spring Board

**To Reproduce**
1. Install MTerm
2. Uninstall MTerm

**Expected behavior**
The app icon of MTeram be delete

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 11.3.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~rc3
 - Device Type [e.g. iPhone or iPad]: iPad
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Could you post a picture of the console when doing this? Zebra should run uicache automatically so maybe this is only a bug for MTerm?

**Comment by eve0415** [comment]
Maybe a one time bug?
I did this but couldn’t reproduce.

**Comment by baobaoit** [comment]
I can’t reproduce too. So maybe one time bug. Thank you.
