### ISSUE TITLE
Issue when downloading/installing multiple packages

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#748]
**Describe the bug**
Gives request timed out or other messages when trying to download and install multiple packages at once. 

**To Reproduce**
1. Install multiple packages at once. Not sure the amount that it does this at though. 

**Screenshots**

![](https://cdn.discordapp.com/attachments/572784833714192395/660130050955280404/image0.png)

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: rc 3
 - Device Type: XS Max
 - Jailbreak type: u0 

**Crash Log or System Log**
No crashes.

**Comment by Greigh** [comment]
To add on: No issues with Cydia and installing all these at once.

**Comment by wstyres** [comment]
It looks like libswift4 is the package that failed. Could this have been a server error or does it happen every time?

**Comment by Greigh** [comment]
It is with others. Not just TSS Saver and Libswift4. You just have to add 10+ packages. @eve0415 said they experienced the same thing.

**Comment by Greigh** [comment]
![82F01763-1830-41F4-9A31-44DFFEAFA9FD](https://user-images.githubusercontent.com/57759540/71528376-80962c00-28ad-11ea-93f5-70cc14c5a358.png)

**Comment by Greigh** [comment]
Another example.

**Comment by wstyres** [comment]
Does this still occur in 1.1?
