### ISSUE TITLE
Tweak update not showing up in zebra

### ISSUE THREAD

**Issue by allendude51** [wstyres/Zebra#749]
The tweak Cephei from the Charizard repo won't show any updates in zebra, even after dropping tables. The update shows up on Cydia just fine. iP6s 13.3
![9B61C7AD-6FB1-47CD-B728-ED46F4CFE790](https://user-images.githubusercontent.com/51012842/71547665-7422d980-2968-11ea-9bd2-785651ab7f11.png)

![D0AE4C6D-5B31-485E-B16D-536CDBDDB2A5](https://user-images.githubusercontent.com/51012842/71547672-7dac4180-2968-11ea-9393-77f670ddf22a.png)

**Comment by wstyres** [comment]
What version of Zebra are you running?

**Comment by allendude51** [comment]
1.0 rc3

**Comment by wstyres** [comment]
Thanks. Also, which version of Cephei is installed?

**Comment by wstyres** [comment]
I'm able to see the version upgrade on Zebra just fine. You said you tried dropping tables and it didn't fix the issue?

**Comment by allendude51** [comment]
1.14 and yes

**Comment by wstyres** [comment]
1.14 is the latest version available from the Chariz repo, you say you have that version installed and you see an update in Cydia?

**Comment by allendude51** [comment]
I already updated using Cydia but yes it showed up as an update but not in
zebra.

**Comment by wstyres** [comment]
If you have 1.14 installed this is the latest version available. This is a Cydia bug where it will show an update on two different repos if they are available (Chariz and BigBoss in this case).

**Comment by allendude51** [comment]
Ah. I wasn't aware of that.
