### ISSUE TITLE
Package list auto scrolls when using swipe actions

### ISSUE THREAD

**Issue by absidue** [wstyres/Zebra#750]
**Describe the bug**
The package list auto scrolls when using the swipe actions after scrolling down in the changes and search tab.

**To Reproduce**
1. Switch to the changes tab
2. Scroll down at least a screens worth of packages
3. Use any of the swipe actions on a package cell

**Expected behavior**
The package and it's respective dependencies should be added to the queue without auto scrolling the package list.

**Screenshots**
Screen recordings of the issue are available on the #translators Discord channel courtesy of @Aransh:
- https://cdn.discordapp.com/attachments/637431102759239740/660627089388470283/video0.mov
- https://cdn.discordapp.com/attachments/637431102759239740/660629861186142209/video0.mov

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: 1.0~rc3-2-debug (translator build) 
 - Device Type: iPhone 
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
Not available as there was no crash

**Additional context**
The bug occurs independent of the language, text direction (RTL/LTR) and the Community News setting.

**Comment by PoomSmart** [comment]
Fixed as of 05ec788d1b9498495a12951ceb4b449448243d62
