### ISSUE TITLE
Device info section in settings

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#758]
**Describe the solution you'd like**

I think the info text from the homepage should be moved into the settings.

I think it would make for a much cleaner looking and streamlined UI and see no reason as to why it should be displayed on the homepage. 

All the other package managers display the text on the homepage but Zebra is supposed to be a modern alternative to Cydia. Why do it the way Cydia has always done it when it could be done in a better and more modern way?

**Additional context**

Move this:
![8871B936-795C-4454-A030-FE0B3C9938A5](https://user-images.githubusercontent.com/51668635/71621223-5a82cb80-2bce-11ea-97a7-0b9654b625de.jpeg)
Perhaps it could look like this:
![F747D0FE-C6CF-41B4-B486-9DB44B4152DB](https://user-images.githubusercontent.com/51668635/71621231-64a4ca00-2bce-11ea-8198-46490df23fa2.jpeg)

**Comment by wstyres** [comment]
I don't really see the argument here of this being "Better and More Modern". The information text is so that people can easily check this info as it appears on the home page (and so developers can show off having a new jailbreak 😛). In the redesign, the text has already shrunk down so it is less prominent and #727 will be implemented for users to hide their UDID if they want to.

**Comment by worldlydev** [comment]
> I don't really see the argument here of this being "Better and More Modern". The information text is so that people can easily check this info as it appears on the home page (and so developers can show off having a new jailbreak 😛). In the redesign, the text has already shrunk down so it is less prominent and #727 will be implemented for users to hide their UDID if they want to.

The argument of it being more modern looking is quite straight forward. In no normal app in this day and age would the version number be displayed on the homepage. Maybe you're right about the showing off jailbreak thing. I've seen a ton of screen recordings where devs do this.

🤷‍♂️

Personally think it would be cool with a little device section or something in settings but it doesn't really matter.

**Comment by worldlydev** [comment]
@wstyres I apologize for the weird explantation and suggestion I opened.


This is a screenshot from Lime installer of what I meant.
![59A0FA0F-B56F-4A57-BC65-977F07D31F1F](https://user-images.githubusercontent.com/51668635/71627631-dc392000-2bf3-11ea-8d08-c64b1789a6aa.jpeg)
Maybe there could be a device information tab in settings with iOS version, model identifier, etc

Would be awesome if this was considered for the redesign.

**Comment by wstyres** [comment]
That makes more sense than just moving the information. We'll see what we can do with the settings redesign.

**Comment by worldlydev** [comment]
It's just cool to have all this info located in one place since this stuff isn't really listed anywhere else and is practical.

Especially the ECID since traditionally you need to connect your device to a computer and use iTunes to view it. Don't even know how it is possible to view in an app but I'm sure that if citrusware can figure it out you can figure it out.

**Comment by wstyres** [comment]
Well I don't know how practical ECID would be in this instance. I'd imagine this controller would show some debug information about any device info that is relevant to Zebra.

**Comment by wstyres** [comment]
Andrew and I have talked about this and we don't really think it has a place in Zebra. We're thinking about just removing the UDID from the final redesign page as we haven't quite settled on it. As a package manager it doesn't make much sense for Zebra to be displaying this much information about your device (especially information that has nothing to do with Zebra's funcitonality).
