### ISSUE TITLE
Cydo update adds +Sources to Zebra and crashes when you click it.

### ISSUE THREAD

**Issue by kempj28** [wstyres/Zebra#759]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Could you elaborate more on this crash? You didn't fill out any of the required info which is needed for me to be able to reproduce the crash and fix the issue.

**Comment by kempj28** [comment]
Sorry...new to github bug reporting. Another Cydo update came through and seems to have resolved it. I cannot reproduce it any longer. 

Thanks!
Joe
