### ISSUE TITLE
Conflict bug

### ISSUE THREAD

**Issue by ThinkDifferentunc0ver** [wstyres/Zebra#76]
Zebra is hypersensitive to conflicts and bugs out like anything.If an issue with repo of another jailbreak then first detect jailbreak and enable checks for it to prevent mishaps of others devices.This ensures wrong repo not being installed AT ALL.Tho zebra does manage conflicts very poorly for now.

**Comment by wstyres** [comment]
Incompatible repos will not appear on the Community Sources page and if they are still added, Zebra will warn the user to remove the repo as of 4c62d5e
