### ISSUE TITLE
Sources artifact

### ISSUE THREAD

**Issue by p1neapplecfw** [wstyres/Zebra#760]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: Go to the sources and scroll up a bit to see the full header then hit a repo for it to “artifact”

**Expected Behavior**
The larger sources header is suppose to zoom up to the top left to become the button to go back

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0~rc4
 - Device Type [e.g. iPhone or iPad]: iPhone 10,3 (iPX)
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Additional context**

https://imgur.com/a/qUdEE3I

**Comment by wstyres** [comment]
Should be fixed as of cf59ae6dcb95e142bd9979b95d9999980a7502c6.
