### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#763]
Have found multiple untranslated strings in Zebra. 

The strings for repo import and drop tables are not localized.

Screenshots:
![1B4B19A2-032B-43B5-8941-031F5E3D89D3](https://user-images.githubusercontent.com/51668635/71646521-49c77800-2cea-11ea-9537-1bd91ce4e232.jpeg)
![05F24A05-8BF5-422B-8F7B-BBB3E78DE48E](https://user-images.githubusercontent.com/51668635/71646522-4a600e80-2cea-11ea-9217-68897df555ed.jpeg)
![0A29C385-574E-4FBC-982E-2F350967B2EC](https://user-images.githubusercontent.com/51668635/71646523-4a600e80-2cea-11ea-9a90-4effd83050ac.jpeg)
![84695F07-F896-43CF-8DA7-6D890B849749](https://user-images.githubusercontent.com/51668635/71646524-4a600e80-2cea-11ea-81d8-8ce243b41da7.jpeg)
![1CD7A5F6-01CF-43B3-BFA4-01F3663E25A2](https://user-images.githubusercontent.com/51668635/71646525-4a600e80-2cea-11ea-95cf-521eef2804de.jpeg)

iPhone 11 Pro
Zebra 1.0 (Sandboxed)
iOS 13.1.1

**Comment by eve0415** [comment]
![0C244193-52CE-4A5D-9BD8-FA0044659748](https://user-images.githubusercontent.com/40632436/71647780-9f2d7480-2d3e-11ea-91a8-3b1a57ad7fd7.png)
How about “Install Zebra” !!

**Comment by wstyres** [comment]
Hmm, "Downloading" and "Done" are properly localized, I'm not sure why they're not showing up.

**Comment by wstyres** [comment]
I added the missing strings in e7ec4de7f5b5b31bafa233635810f10c00c78ecd they should be on CrowdIn shortly and will be included in 1.0.1.

**Comment by worldlydev** [comment]
> I added the missing strings in [e7ec4de](https://github.com/wstyres/Zebra/commit/e7ec4de7f5b5b31bafa233635810f10c00c78ecd) they should be on CrowdIn shortly and will be included in 1.0.1.

What about "Release files need to be updated" and "Package files need to be updated"

**Comment by wstyres** [comment]
I went ahead and removed those strings, they were going to be removed later on anyway so I just went ahead and removed them now while I was there.

**Comment by wstyres** [comment]
They should all be there, check to make sure that I didn't miss any before the issue is closed.

**Comment by worldlydev** [comment]
Somewhat fixed on 1.0.1

Drop Tables
> "Downloading", "Done", and "Parsing" are not localized. "Done" at the end is localized.

![A0251C5D-3438-4D3A-A820-EDD6CD7622BF](https://user-images.githubusercontent.com/51668635/71696458-4947e380-2db5-11ea-9e33-3cdc96cd7ae3.jpeg)

Repo import screen
> "Yes" is not localized. Also, would it be possible to rearrange or add some spacing up top (highlighted in green)?

![AFB851B1-D86C-4BC6-8654-E31D88CF9CB5](https://user-images.githubusercontent.com/51668635/71696556-99bf4100-2db5-11ea-8773-5b6051a8f925.jpeg)

Repo import console
> "Downloading", "Done", and "Parsing" are not localized. "Done" at the end is localized.

![0F0279E8-993C-4069-9D93-01D8CA4A1C1E](https://user-images.githubusercontent.com/51668635/71696658-d723ce80-2db5-11ea-9e3c-a96a11015e30.jpeg)
![BC58C66D-CCBA-4632-B007-A1246C2647C7](https://user-images.githubusercontent.com/51668635/71696659-d723ce80-2db5-11ea-9e4e-96bc0d04e67d.jpeg)

**Comment by eve0415** [comment]
![82C509E0-8970-44D0-A159-550211A3BB96](https://user-images.githubusercontent.com/40632436/71767271-d756d200-2f4d-11ea-94b4-c01ed09dbf3d.png)

Removing Zebra is not localized still

**Comment by wstyres** [comment]
So there was an issue when I added the new strings when I used a `#` to mark the comment instead of `//` so CrowdIn didn't like that very much. I've updated the strings as of 3a0d73a15198ff8912df2f6b8fc4e58e49ab94d0 and removed the problem causing comment markers. Hopefully that fixes all of the problems (but you might have to retranslate the strings... :/)

**Comment by worldlydev** [comment]
Tested on 1.0.3 non-jailbroken.

"Downloading", "Done", and "Parsing" are localized for both repo importing and drop tables. 

"Yes" is still not localized on the repo import screen.

**Comment by wstyres** [comment]
Turns out "Yes" does not actually exist in Localizable.strings so that would explain why it is not translated.

**Comment by worldlydev** [comment]
Can confirm that all the strings are now localized as of 1.0.5.
