### ISSUE TITLE
Context Menu Support

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#764]
**Describe the bug**

Haptic Touch isn't working where 3d-touch would have functioned on my Xs. Not sure if this is only an iPhone 11 issue or if it affects Xr as well.

**To Reproduce**

Long press on 3d-touchable elements.

**Expected behavior**

3d-touch menu should open

**Screenshots**

Screen recording:
https://imgur.com/a/E3tjWAX

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Non-jailbroken

**Comment by wstyres** [comment]
Haptic Touch hasn't been implemented yet so because your device lacks 3D Touch it just doesn't work on iOS 13. It will hopefully be added in 1.1.

**Comment by wstyres** [comment]
Closed #566 in favor of this, Context Menus / 3D Touch still needs to be added to home page featured cells

**Comment by wstyres** [comment]
#942 implements context menus everywhere except for the homepage featured cells, will work this soon.

**Comment by wstyres** [comment]
Looks like #943 implements the homepage context menus so I'll close the issue.
