### ISSUE TITLE
Accent color doesn't apply everywhere

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#765]
**Describe the bug**

When the accent color is changed it doesn't apply everywhere.

To get the accent color to apply you have to change between light and dark theme.

**To Reproduce**

Change accent color.

**Expected behavior**

I expect the accent color to change.

**Screenshots**

Screen recording:
https://imgur.com/a/qbQKQw6

Screenshots:
![F8F9C7CB-CC41-437F-B958-7485E04C0FDC](https://user-images.githubusercontent.com/51668635/71646961-4f738c80-2cef-11ea-8840-956cf9b7cce5.jpeg)
![573C2AE9-2AEC-4A21-86C8-088CD0EF6F29](https://user-images.githubusercontent.com/51668635/71646962-500c2300-2cef-11ea-810c-9b9c2e361081.jpeg)
![623F4396-F186-4C96-A7A0-A506FBB4E722](https://user-images.githubusercontent.com/51668635/71646963-500c2300-2cef-11ea-8fbe-16a699c43815.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.0
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Non-jailbroken

**Comment by worldlydev** [comment]
This seems to happen like 50% of the time. It affects all the dark modes.

**Comment by wstyres** [comment]
Does this only occur when changing the accent color? Can you close the app and re-open for the accent color to change?

**Comment by worldlydev** [comment]
> Does this only occur when changing the accent color? Can you close the app and re-open for the accent color to change?

This only occurs when changing the accent color.

Closing the app from the app switcher and opening the app again fixes the issue.

**Comment by gkeep** [comment]
Can reproduce with default dark mode on 12.4 checkra1n.

**Comment by PoomSmart** [comment]
e93477c7502cc94fe42924a63411ab54ec2188ea apparently fixes this.

**Comment by PoomSmart** [comment]
Note: it only fixes it partially.
