### ISSUE TITLE
Dark mode doesn't apply to changelog page

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#766]
**Describe the bug**

Dark mode doesn't apply to all of the changelog page.

**To Reproduce**

Enable dark mode. Open changelog.

**Expected behavior**

I expect it to be properly themed.

**Screenshots**

![BA1DEC69-56D8-4F16-A963-A90D35445C35](https://user-images.githubusercontent.com/51668635/71647210-6f0cb400-2cf3-11ea-82e3-e0ea38c92b0f.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Non-jailbroken

**Comment by ENDERZOMBI102** [comment]
I have it kinda darker

**Comment by wstyres** [comment]
Fixed in 8a096bf6a6cd88f6f87bac298f1761c5c1a5bdc3 and will be included in 1.0.1.
