### ISSUE TITLE
Can't change app icon

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#767]
**Describe the bug**

Changing the app icon in settings does nothing.

**To Reproduce**

Change app icon in settings.

**Expected behavior**

I expect the app icon to change.

**Screenshots**

Screenshots:
![BE169552-6E1A-4009-A8A7-F8F314268388](https://user-images.githubusercontent.com/51668635/71647721-3b358c80-2cfb-11ea-82c7-70a41547656f.jpeg)
![9B237298-2310-4ACD-8D36-F6F834BDFF08](https://user-images.githubusercontent.com/51668635/71647707-117c6580-2cfb-11ea-9cc4-0d866718fc9d.jpeg)

Screen recording:
https://imgur.com/a/5EjWB6j

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Non-jailbroken

**Comment by wstyres** [comment]
This might be a jailed only bug but I'm able to change icons just fine on the jailed version. Did you happen to restore from backup when you got to iOS 13?

**Comment by worldlydev** [comment]
> This might be a jailed only bug but I'm able to change icons just fine on the jailed version. Did you happen to restore from backup when you got to iOS 13?

If this is a jailed only bug then it isn't really a priority to fix this. More just a fix for my OCD.

I restored from an iCloud backup to setup my new device.

**Comment by wstyres** [comment]
Yeah it might be a problem with restoring from the iCloud backup. I see you already changed the icon so it must have saved the preference from before. I'd say running `uicache` would fix the issue but obviously you cannot do that.
