### ISSUE TITLE
Can't upgrade packages that's in 'IGNORED UPGRADES'

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#768]
**Describe the bug**
If the tweak is added to the ignored upgrades list, once it's added into queue for upgrade, nothing will be upgraded even though the console says '1 package upgraded'.

**To Reproduce**
1. Downgrade a package to lower version and add it to ignored upgrades
2. Upgrade the package

**Expected behavior**
The package be upgraded. Cydia works normally in such case scenario, I'm wondering is this a designed behavior in Zebra?

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0 (latest)
 - Device Type [e.g. iPhone or iPad]:  iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1nere.

**Comment by wstyres** [comment]
Could you upload a screen recording of the issue?

**Comment by yur1xpp** [comment]
Sure thing!
Here’s before respring: https://imgur.com/a/B5yU918
And after respring: https://imgur.com/a/y8KAcMs

**Comment by wstyres** [comment]
Hm this is odd, do you have the version ignored in Cydia as well?

**Comment by yur1xpp** [comment]
Actually I did. Should that be an issue?

By the way, the bug report on Zebra doesn’t works:
![43213090-8D72-4AFA-AC44-78CB9E953C96](https://user-images.githubusercontent.com/34767893/71677594-308ffb80-2dbe-11ea-8a57-15b8076e7238.png)

**Comment by yur1xpp** [comment]
Update: it seems like removing it from ignored list in Cydia updated it normally. 🤔 a conflict?

![7E5895E7-D9CA-49F8-BD6A-3AA56998D35D](https://user-images.githubusercontent.com/34767893/71677982-025eeb80-2dbf-11ea-83fc-1da3743be27f.png)

**Comment by wstyres** [comment]
Hm ok I didn't think about this, I'll have to do some more research about how Cydia handles ignored upgrades because it seems like there is a problem when trying to use APT.

And oops, I'll fix the bug reporting page but I guess it will require a Zebra update to see.

**Comment by yur1xpp** [comment]
Alright, thank you for the awesome support! :)

**Comment by wstyres** [comment]
Fixed as of de39a8a9fd989b8a005b96cdc211c5823ae52a3a will be included in 1.0.1.
