### ISSUE TITLE
Change log tab inside tweak depictions a similar to Sileo (The only good feature in Sileo)

### ISSUE THREAD

**Issue by Garydunlop00** [wstyres/Zebra#769]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gkeep** [comment]
As far as I know, Sileo webscrapes usual ("legacy") depictions and converts them into their new "native" depictions as of version 1.3.6 (see [this tweet](https://twitter.com/GetSileo/status/1166871444858388480)).

Zebra does not do anything similar to this, it just displays "legacy" depiction. It is up to the developer/repository to display the changelog in the depiction. Therefore, it is impossible with current depiction implementation.

**Comment by wstyres** [comment]
This is completely up to the developer to support, if the developer has no changelog provided it will simply not be displayed.

**Comment by worldlydev** [comment]
> This is completely up to the developer to support, if the developer has no changelog provided it will simply not be displayed.

So nothing like this is even possible to implement in Zebra? Personally really wanted it and didn't even file a suggestion because I thought this was most likely already coming in the redesign.

**Comment by wstyres** [comment]
Something *could* be added similar to Debian changelogs http://www.debian.org/doc/debian-policy/ch-source.html#s-dpkgchangelog but no support for it is planned at this time. We might revisit this when the redesign comes around though.

**Comment by absidue** [comment]
Would it be more work to try and extract the changelogs from Sileo's JSON depictions on repos that have them?
