### ISSUE TITLE
Please Support Packages.bz

### ISSUE THREAD

**Issue by zundapixel** [wstyres/Zebra#773]
Currentry Zebra support Packages.bz2 but doesnt support Packages.bz

Please support Packages.bz2

**Comment by wstyres** [comment]
Zebra adheres pretty closely to the [Debian Repository Format](https://wiki.debian.org/DebianRepository/Format#Compression_of_indices) which specifies the following:

> Unless a compression is indicated by the filename of the indices below, and index may be compressed in one or multiple of the following formats:
> 
> - No compression (no extension)
> - XZ (.xz extension)
> - Gzip (.gz extension, usually for Contents files, and diffs)
> - Bzip2 (.bz2 extension, usually for Translations)
> - LZMA (.lzma extension)

Support for .xz and .lmza are planned in a future version but because .bz2 is the preferred method of compression for most Cydia repositories, why are you asking for support for .bz? .bz2 was meant to _replace_ .bz and thus .bz is not really used much in practice anymore.

**Comment by worldlydev** [comment]
> Zebra adheres pretty closely to the [Debian Repository Format](https://wiki.debian.org/DebianRepository/Format#Compression_of_indices) which specifies the following:
> 
> > Unless a compression is indicated by the filename of the indices below, and index may be compressed in one or multiple of the following formats:
> > 
> > * No compression (no extension)
> > * XZ (.xz extension)
> > * Gzip (.gz extension, usually for Contents files, and diffs)
> > * Bzip2 (.bz2 extension, usually for Translations)
> > * LZMA (.lzma extension)
> 
> Support for .xz and .lmza are planned in a future version but because .bz2 is the preferred method of compression for most Cydia repositories, why are you asking for support for .bz? .bz2 was meant to _replace_ .bz and thus .bz is not really used much in practice anymore.

Pretty sure he wants support for more legacy stuff

**Comment by wstyres** [comment]
If the case is just for supporting a legacy compression format I don't really see a reason to support it. If something like BigBoss or ModMyI used a legacy format then I would consider adding it but if no major repos support this then I'm not too interested on adding this.

**Comment by zunda-pixel** [comment]
I cant add this Repo.But I don't know bz is involved
https://apt.geometricsoftware.se/

**Comment by eve0415** [comment]
> I cant add this Repo.But I don't know bz is involved
> https://apt.geometricsoftware.
I could add this just fine so I think there is a problem like internet connection or something in your end.
![2BD589A8-F536-4653-818B-B1229C05FE79](https://user-images.githubusercontent.com/40632436/71764206-1a9e4a00-2f28-11ea-9311-8c33b6cb2e69.png)

**Comment by zunda-pixel** [comment]
Can you refresh Repository?

**Comment by eve0415** [comment]
yes

**Comment by zunda-pixel** [comment]
Ok thanks
My Error
[Hyena] Unable to remove .bz2,
"apt.geometricsoftware.se_._Packages.bz2 couldn't be removed
![443C932A-56B7-4C4C-9801-456BA5EABB0B_1_105_c](https://user-images.githubusercontent.com/47569369/71764323-e461ca00-2f29-11ea-8a5c-31f04c8254ea.jpeg)

**Comment by eve0415** [comment]
try drop table
It’s in the setting

**Comment by zunda-pixel** [comment]
Same result
![1E28B76F-982B-4AEE-810E-6F24F31A32EC_1_102_o](https://user-images.githubusercontent.com/47569369/71765654-ccdf0d00-2f3a-11ea-899d-71a07c6b3e77.jpeg)

**Comment by eve0415** [comment]
Open document directory from Zebra's setting page. Delete "list" folder from "xyz.willy.zebra". Then reopen Zebra and see if it still happens

**Comment by zunda-pixel** [comment]
1. Delete list folder
2. LDRestart
3. Open Zebra


Still Same error

**Comment by eve0415** [comment]
Ok, now I don't know what to do so let's wait for @wstyres to respond to you

**Comment by zunda-pixel** [comment]
thanks @eve0415
