### ISSUE TITLE
Sone tweak updates are refusing to download 

### ISSUE THREAD

**Issue by allendude51** [wstyres/Zebra#774]
When i try to update certain tweaks using zebra (1.0) I get an error and it won’t install. I’ve had this happen to teams like ultrasound 1.2.10 and rainbow 1.1.1. It happened on my iPhone X 13.3 and iPad Air 12.4

![B4F4A22B-52FC-4F84-83B7-D8EC860DBB2F](https://user-images.githubusercontent.com/51012842/71684610-98f9c100-2d5b-11ea-82da-aff6feda21ad.png)

**Comment by wstyres** [comment]
Could the server be down or be experiencing issues? The error message indicates that the request timed out.

**Comment by gkeep** [comment]
No, Ultrasound is paid again, even though its' source code is available at [aydenp/Ultrasound](https://github.com/aydenp/Ultrasound). Because OP didn't buy Ultrasound, Dynastic refuses the download.

**Comment by wstyres** [comment]
Not sure how Dynastic operates but it should be displaying a "Payment Required" message instead of a timed out message so it looks like the package is purchased but the server (or Zebra) just isn't handling the request properly.

**Comment by gkeep** [comment]
I had the same issue. Probably, Dynastic returns the wrong message/error code.

**Comment by wstyres** [comment]
Then it is probably Dynastic returning the wrong error code. I confirmed this while logged out but I tried to log in and the requests are taking a long time to load. I suspect that Dynastic may just be under some load and experiencing server troubles.

**Comment by allendude51** [comment]
First of all yes I did pay for it and I'm logged in. And installed the
update using cydia and it downloaded with zero issues so it's not a server
issue.

**Comment by allendude51** [comment]
I tried to install the same update using cydia and it downloaded with no issue. So I don't think it's dynastic.

**Comment by wstyres** [comment]
Like I said above, the repo may have been experiencing issues at the time that you tried to download it. I was unable to log in due to slow server response times. Are you able to download it in Zebra now?

**Comment by allendude51** [comment]
It reinstalled just fine, but I had this same issue with rainbow. Updates refuse to download, I use cydia to update and it works, I go back to zebra and try to reinstall the same tweak and now it magically works for some reason.
