### ISSUE TITLE
Add text for stores page when no stores are added

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#776]
![45832D66-28B5-4764-9D30-A8F4C0293EC0](https://user-images.githubusercontent.com/51668635/71691269-2b738200-2da7-11ea-8177-b108283cb80d.png)
![486D415C-305B-4E0A-B63F-7196875259FC](https://user-images.githubusercontent.com/51668635/71691270-2b738200-2da7-11ea-8b3e-fdaf717722a3.png)

**Comment by wstyres** [comment]
Implemented in 1cd762c4901a3ca232f808fa1003378d94d542fe.
