### ISSUE TITLE
Repeatedly changing between default and dark mode opens queue

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#777]
**Describe the bug**

When repeatedly pressing the theme change button to switch between dark and default mode the queue will open even though there are no packages queued.

First you see a chevron fly down from the top of the screen and then the queue will open.

**To Reproduce**

Repeatedly press the theme change button.

**Expected behavior**

😅 change between default and dark mode without opening queue.

**Screenshots**

Screenshots:
![33D4528A-7C6E-40F7-8F44-8E988D048A16](https://user-images.githubusercontent.com/51668635/71692743-126cd000-2dab-11ea-91c2-82fd4d43fb02.jpeg)
![C8615480-0251-44EE-A9A4-2DA766BF4EFA](https://user-images.githubusercontent.com/51668635/71692744-126cd000-2dab-11ea-9a6e-d222424eeb5b.jpeg)

Screen recording:
https://imgur.com/a/gPlqscA

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0 
 - Device Type [e.g. iPhone or iPad]: iPhone 11 Pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Non-jailbroken

**Comment by eve0415** [comment]
Yeah, that happens to me while on betas. But I don’t think no one will try to change between default and dark mode many time in a second tho

**Comment by wstyres** [comment]
This is probably a workaround way to solve this but the plan is to remove the dark mode button. It will be automatic on iOS 13 and up and a toggle will exist in settings on 12 and lower.

**Comment by PoomSmart** [comment]
Fixed as of 2423ff9ee39a5765cc7ddf50b76d563b1a510d38
