### ISSUE TITLE
Not enough Lua

### ISSUE THREAD

**Issue by rweichler** [wstyres/Zebra#78]
**Describe the bug**
There's no Lua code

**To Reproduce**
Look at the code

**Expected behavior**
There are Lua files

**Screenshots**
![image](https://user-images.githubusercontent.com/1661613/57595886-8c8ad480-74fc-11e9-9934-cd1d7bcc75b4.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 11.1.2
 - AUPM Version [e.g. 1.0~beta1 or beta1]: 1.0~beta10 
 - Device Type [e.g. iPhone or iPad]: iPhone

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.
No

**Additional context**
Hi

**Comment by wstyres** [comment]
Working as intended

**Comment by rweichler** [comment]
:'(
