### ISSUE TITLE
Conflict while trying to update Cydia Substrate

### ISSUE THREAD

**Issue by allendude51** [wstyres/Zebra#782]
iPX 13.3 Zebra 1.0.1 Just tried to install the latest substrate update and got this error
![EF1D4109-C6D1-4701-B91C-67890B45F337](https://user-images.githubusercontent.com/51012842/71707243-6e852380-2dae-11ea-9933-7a1cad1e8c56.png)

**Comment by wstyres** [comment]
Fixed as of ae94acb778b0f8478991ef281a1affd6e0909318 will be included in 1.0.2 shortly.

**Comment by allendude51** [comment]
Thanks
