### ISSUE TITLE
update “install” button after removing from queue

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#783]
**Describe the bug**
“Install” button is still gray out after removing from queue.

**To Reproduce**
1. go to description page
2. tap install
3. open queue and remove package

**Expected behavior**
can press install as it is not in the queue any more

**Screenshots**
![F443326B-21C5-4BB5-BAB3-1A45E8B7B558](https://user-images.githubusercontent.com/40632436/71714888-dc832680-2e52-11ea-8300-5db50246af84.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.2
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by PoomSmart** [comment]
Fixed as of e071558ebadc6e1428ef71c0f877f5c0c2dcd65f

**Comment by eve0415** [comment]
Not fixed in 1.0.5

**Comment by wstyres** [comment]
Had to be reverted in 1.0.5, the fix caused too many crashes in other areas when trying to install packages. We will look into another fix.

**Comment by PoomSmart** [comment]
This fix should be a lot better. 1d8d992687f3f63d05e20b0e810d8885c8c71151
