### ISSUE TITLE
done button when canceled operation

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#784]
**Describe the bug**
When I mistakenly pressed confirm button I pressed cancel button while downloading packages. I couldn’t get back to queue or somewhere else.

**To Reproduce**
Press install then quickly press cancel

**Expected behavior**
I expect to have Done button or something to get me back.

**Screenshots**
![5E1EB703-6AAB-43EA-9EF5-35852A9E711A](https://user-images.githubusercontent.com/40632436/71717004-f83dfb00-2e59-11ea-9522-ecd788ceaeb1.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.2
 - Device Type [e.g. iPhone or iPad]: iphone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by PoomSmart** [comment]
Fixed as of b99a66f3365bce78df2aa5676cab640f19ba57f9
