### ISSUE TITLE
Zebra ignores system language.

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#785]
**Describe the bug**
I wanted Zebra to speak English as I wanted to fix my translation and do some debug, Zebra ignores my system language settings

**To Reproduce**
Change system primary language to English. 
Open Zebra.

As I didn't have any problem before but now Zebra is stuck in Japanese. I don't know how this happened. Maybe updating in Japanese?

**Expected behavior**
Please speak English when system language is in English as I cannot tell people using screenshot now

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:1.0.2 
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by gkeep** [comment]
Have you tried reinstalling Zebra?

**Comment by absidue** [comment]
The issue still persists for me

**Comment by gkeep** [comment]
Just changed to Japanese then back to English. Did not happen on my end. What are your devices, maybe somehow it happens on specific devices?

**Comment by absidue** [comment]
I have am using an iPhone X on iOS 12.4 jailbroken with unc0ver and using Zebra version 1.0.2

**Comment by absidue** [comment]
I am trying to switch between English and German

**Comment by eve0415** [comment]
1. Set language to English on my end
2. remove Zebra
3. install zebra using cydia
4. Open Zebra to find out speaking Japanese
Maybe conflicting with prefered language order?

**Comment by eve0415** [comment]
*mistakenly closed

**Comment by eve0415** [comment]
It must be iOS or system bugs, therefore there is not much we can do.
