### ISSUE TITLE
Source reload indicator appearing on wrong cell

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#786]
**Describe the bug**
As I try to reload one of the source, it seems that some of the source is not reloading the one I selected. I swiped one of the source, press reload, and the syncing mark will come out although it is not the one I swiped and press.
Some of sources are working properly.

**To Reproduce**
Swipe one of the source left, press reload
Try to do many of them and see if syncing mark comes up on that source or 
another.

**Expected behavior**
Reload a source that I want

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/663018012932177920/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.2
 - Device Type [e.g. iPhone or iPad]: iphone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by wstyres** [comment]
This is likely a UI bug but I’ll investigate more to see if it is actually refreshing the wrong source or not.

**Comment by wstyres** [comment]
Can confirm this is just a UI bug and the requested source is actually being updated. Will see if I can rework that system to get a fix.

**Comment by PoomSmart** [comment]
Does it still happen in beta 9?

**Comment by eve0415** [comment]
Yes, it still happens. Do you need videos?

**Comment by PoomSmart** [comment]
Sounds good.

**Comment by eve0415** [comment]
https://cdn.discordapp.com/attachments/572784833714192395/706305473682473040/RPReplay_Final1588466582.MP4

It doesn’t happen on all sources. I don’t know the relevance

**Comment by PoomSmart** [comment]
Fixed in 1552fa6f298a29a2e776af2cb380ea569632afe0
