### ISSUE TITLE
Incorrect Dutch translation for home page 

### ISSUE THREAD

**Issue by arjanvlek** [wstyres/Zebra#788]
**Describe the bug**
Homepage title is translated as “Thuis” wile that is the translation for being at home. The correct translation for such a page is “Uitgelicht” or “Start” if it must be short. 

**To Reproduce**
Open the app
See incorrect translation 

**Expected behavior**
See correct translation 

**Screenshots**
![B4312881-DEFC-4EA0-9543-9CE08277CE6C](https://user-images.githubusercontent.com/10106652/71769959-6dc3cd00-2f27-11ea-9cd2-5c699df68156.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.2
 - Device Type [e.g. iPhone or iPad]: 
iPod touch 7 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.
Not applicable 

**Additional context**

**Comment by wstyres** [comment]
So which should it be corrected to? "Uitgelicht" or "Start"?

**Comment by DrConflict** [comment]
It has been changed to "Startpagina" now which literally translates to "Start Page". This should make most sense for general use and is the same translation Mac and Windows uses for "start pages". This should fix the problem.
