### ISSUE TITLE
Crash on +Sources

### ISSUE THREAD

**Issue by txchnoknd** [wstyres/Zebra#790]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
"+ Sources" is not a Zebra feature, it is a feature of CyDown (a tweak you have installed) please contact the developer of CyDown for a fix for this crash.

**Comment by txchnoknd** [comment]
Oh, sure, thank u very much for that Information, it was my fault. I'll
contact the dev, thx:)

Great work by the way <3

Best regards,
John


Wilson Styres <notifications@github.com> schrieb am Sa. 4. Jan. 2020 um
21:14:
