### ISSUE TITLE
Bingner repo only adds unsecured (http) site even though the it is listed as secured (https) in community sources

### ISSUE THREAD

**Issue by grahamcracker1234** [wstyres/Zebra#791]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by grahamcracker1234** [comment]
iOS 13.3
iPhone X
checkra1n

**Comment by grahamcracker1234** [comment]
![67C7A55B-9006-4463-861C-9BBA00D7D2B1](https://user-images.githubusercontent.com/16179442/71773171-3d2f6380-2f26-11ea-83d1-16de55a30093.jpeg)
![035440E1-3BCE-4E19-A2E4-73316343AFDD](https://user-images.githubusercontent.com/16179442/71773172-3dc7fa00-2f26-11ea-801e-4ca71b2d5639.jpeg)

**Comment by eve0415** [comment]
can confirm and also, adding from here also is not loading using https.
![810A21A1-C0F2-4636-A121-B110AFE997F8](https://user-images.githubusercontent.com/40632436/71773174-bcab4a00-2f9b-11ea-891d-3e1d0a905655.png)
![5E358942-37FA-487D-A702-70676E2381F1](https://user-images.githubusercontent.com/40632436/71773175-bd43e080-2f9b-11ea-8f39-c3b562451081.png)

**Comment by wstyres** [comment]
Fixed as of 54c6de465ce0208f2fd9a2703a3f2f4d35fbab5a.
