### ISSUE TITLE
0$ purchases aren’t working

### ISSUE THREAD

**Issue by Nixuge** [wstyres/Zebra#794]
**Describe the bug**
When trying to get a 0$ package, zebra will just do nothing after you type the password while Cydia works perfectly 

**To Reproduce**
Add repo.twickd.com and try to download « LogoTypeOS » (limited time only for the 0$)

**Expected behavior**
Add the package to the queue

**Screenshots**
Not needed

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.2.2
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.2
 - Device Type [e.g. iPhone or iPad]: IPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.
No crash

**Additional context**
Not needed

**Comment by wstyres** [comment]
I have no issue when downloading the package you mentioned, are you logged in by chance when you try to "purchase" the package?

**Comment by Nixuge** [comment]
Yes i'm logged in on twickd

**Comment by wstyres** [comment]
@Nixuge Are you able to confirm that this bug is fixed as of the 1.1 beta?

**Comment by Nixuge** [comment]
Sadly i don't know any 0$ package so i can't test rn :/
If i see any i'll try it

**Comment by wstyres** [comment]
I think this might've been a problem with the Twickd repo as a whole which I've gotten some reports that purchases from Twickd are now working again.
