### ISSUE TITLE
Can’t get the tweaks from Kurrt’s repo 

### ISSUE THREAD

**Issue by baobaoit** [wstyres/Zebra#795]
**Describe the bug**
Can’t get the tweaks from Kurrt’s repo with Zebra but Cydia can.

**To Reproduce**
1. Open Zebra 
2. Add https://kurrt.com/repo

**Expected behavior**
Zebra can get the tweaks from Kurrt’s repo.

**Screenshots**
![7DECFB65-A998-45B9-91C1-4B72C62E2825](https://user-images.githubusercontent.com/31947091/71781651-afc24100-3003-11ea-8719-173d03ca58f5.png)
![35A6B3B2-E1F2-44F3-8D38-251B5ACA33D6](https://user-images.githubusercontent.com/31947091/71781652-afc24100-3003-11ea-9059-34a31432b0b4.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.2
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
It appears that the Packages.bz2 file that the repo is serving is malformed and Zebra can't find a new one. This bug has already been fixed in 1.1 but if you'd like for it to be fixed sooner, I would suggest contacting the repo maintainer.

**Comment by wstyres** [comment]
More specifically, the server is serving the wrong MIME type for the file. It is set to `text/plain` when it should be set to `application/x-bzip2`

**Comment by baobaoit** [comment]
Thank you for your helpful information. So I will wait for the 1.1 release

**Comment by wstyres** [comment]
Fixed as of cd436537061dbec5e8dd0c8441b2906518478e05 and will be included when the first 1.1 beta arrives.
