### ISSUE TITLE
Local packages not using post install actions

### ISSUE THREAD

**Issue by MTACS** [wstyres/Zebra#798]
**Describe the bug**
An AirDropped package for example installs properly but Zebra does not respring, and button only says Done, and install view does not dismiss

**To Reproduce**
Open package in Zebra via share sheet or via AirDrop

**Expected behavior**
Zebra resprings/reboots depending on package after-install::

![image](https://user-images.githubusercontent.com/13209789/71785779-ad46f380-2fd1-11ea-99b6-fde2db7c127e.png)

 - iOS 13.2.2
 - Zebra Version 1.0.4
 - iPhone X
 - Checkra1n

**Comment by wstyres** [comment]
This will be addressed in 1.1, we're changing up the way we handle external packages.

**Comment by wstyres** [comment]
I've redone the flow a bit here, local package installs from .debs are now treated as normal packages. A depiction is rendered and any dependencies are calculated for install as well. uncache and respringing seem to behave as expected. 

https://gfycat.com/artisticwellmadeanteater

**Comment by wstyres** [comment]
Fixed in 6c4d72b014e2d1cb14216f6a65077fc149097d5c.
