### ISSUE TITLE
Queue bar doesn't appear after queueing package

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#799]
**Describe the bug**
As the title says, queue bar doesn’t appear sometimes, not always. Queueing another package will make it appear it again. I have many ways to reproduce this but I don’t know if it is only for me or iOS bugs.

**To Reproduce**
Queue any package.
Remove package from queue.
Again, queue any package.

Try to do these steps over and over

**Expected behavior**
Show queue bar

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]:1.0.4 
 - Device Type [e.g. iPhone or iPad]: iphone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 

**Additional context**
Anyone having this issue?

**Comment by wstyres** [comment]
Do you think this tends to happen from Swipe Actions or from 3D Touch Actions or from the depiction page?

**Comment by eve0415** [comment]
https://cdn.discordapp.com/attachments/572784833714192395/665312304803610650/video0.mp4

I think this happens when adding to queue in second after removing all queued package. Like while the queue tab are sliding down and 1 or 2 seconds. After that it behaves normal.
It mostly happens when sliding all the way to be removed but also happens when pressing any of button after sliding.

**Comment by PoomSmart** [comment]
This shouldn't be a preferred user interaction. A prevention has been implemented in ff8daced90b1b0ec6fb709fad979ad11719e023b
