### ISSUE TITLE
Can’t install/remove any packages

### ISSUE THREAD

**Issue by Yato1201** [wstyres/Zebra#80]
**Describe the bug**
I can’t install/remove/reinstall any free or paid packages

**To Reproduce**
Steps to reproduce the behavior: don’t know how to reproduce, i can’t install anything

**Expected behavior**
install/remove/reinstall a package

**Screenshots**
here is a video https://streamable.com/m7sx8

**Device Information (please complete the following information):**
 - iOS Version 12.1.2
 - Zebra Version : newest beta
 - Device Type [e.g. iPhone or iPad]: iPhone 7

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by Muirey03** [comment]
@Yato1201 I get this issue too, how did you fix it?
