### ISSUE TITLE
Newly added repos dont appear

### ISSUE THREAD

**Issue by oxi0de69** [wstyres/Zebra#801]
**Describe the bug**
Newly added repos dont show up, although they do randomly show up after a few hours

**To Reproduce**
Add a new repo

**Expected behavior**
The repo should appear in the sources list

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version: ios 13.3 
 - Zebra Version: 1.0.4 
 - Device Type: iPhone 7 
 - Jailbreak Type: Checkra1n 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Do they not show up at all or do they show up after a refresh?

**Comment by gkeep** [comment]
I was experiencing this, too. 

After adding a new repo it would not show up. Relaunching Zebra and adding the repo again would add it or show that it has already been added. 

Anyway, this was happening to me before 1.0.5, as I cannot reproduce it anymore.

**Comment by oxi0de69** [comment]
Ive tried ldrestart, uicache, respring, reinstalling and it still persists
Btw i just updated zebra, ill see if the bug is still there

**Comment by oxi0de69** [comment]
Ok, i updated zebra and this issue is fixed

**Comment by oxi0de69** [comment]
Can i say a huge thank you for making such an amazing package manager. Easily my favorite package manager ever
