### ISSUE TITLE
Accent color change doesn't apply to certain back buttons

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#802]
**Describe the bug**

After switching between the dark and standard theme and changing the accent color the accent color won't apply to certain back buttons. Specifically those on the homepage. The changelog, community sources, stores, wishlist, and credits still have the previous accent color applied to their back buttons.

**To Reproduce**

Switch between light and dark mode. Change accented color. Open any of the above specified pages.

**Expected behavior**

Properly applied accent color.

**Screenshots**

Screen recording:
https://imgur.com/a/lNFuY9I

Screenshots:
![726347B3-E80D-44AC-B26A-0CFCF5C9F1C8](https://user-images.githubusercontent.com/51668635/72011148-81d63a00-3259-11ea-83eb-b55007295b0a.jpeg)
![37E28531-0E06-4FC8-9356-03542FAD636F](https://user-images.githubusercontent.com/51668635/72011150-826ed080-3259-11ea-9730-1066507ac99f.jpeg)
![9255A541-A0FF-4D7D-BD8E-D9CF4B35A88A](https://user-images.githubusercontent.com/51668635/72011151-826ed080-3259-11ea-8a80-e654f0053921.jpeg)
![1B6C9E1A-DB3B-458C-957B-ABD631C2941A](https://user-images.githubusercontent.com/51668635/72011153-826ed080-3259-11ea-93cd-3231ea091eae.jpeg)
![73AFB156-2FAF-4A89-AD2E-123FBDD01655](https://user-images.githubusercontent.com/51668635/72011155-826ed080-3259-11ea-8df0-5574a7b883b4.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.3
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Non-jailbroken

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by PoomSmart** [comment]
Fixed as of c5e309c84f709159db5fac9052430ea3efd97954
