### ISSUE TITLE
Loading icon on certain pages is black in dark mode

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#803]
**Describe the bug**

The loading icon is black on the changelog, community sources, and credits page even while in dark mode.

**To Reproduce**

Open specified pages while in dark mode.

**Expected behavior**

White loading icon

**Screenshots**

![38B08348-D8CA-48A1-866D-D3AF413D8E15](https://user-images.githubusercontent.com/51668635/72011673-a1ba2d80-325a-11ea-8632-dbb61c803812.jpeg)
![886FB163-57EF-4398-804E-C49BB02A7EDA](https://user-images.githubusercontent.com/51668635/72011674-a252c400-325a-11ea-8697-e3cf5bf49535.jpeg)
![7A9B2532-9A12-46CB-A951-A9D928BF1A33](https://user-images.githubusercontent.com/51668635/72011675-a252c400-325a-11ea-9b57-bc58a300160e.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.3 
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Non-jailbroken

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

iOS 13 dark mode
Blue tint

**Comment by wstyres** [comment]
Fixed as of 0ed725d080d9face71fbae32596fdff4a00887f6.
