### ISSUE TITLE
Doesn’t show the cost of the package on Install button although the package requires payment

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#804]
**Describe the bug**
As the title says. I believe some version before, the install button was the cost of the package. Now that function doesn’t work, it just add to queue

**To Reproduce**
Search for payment package
Open depiction

**Expected behavior**
Show the cost that need payment

**Screenshots**
As I can’t get English version on Zebra there is no use for other people, I’m not going to post.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.4
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by wstyres** [comment]
This is a bug where the price of a package won't show unless you're logged in. It will be fixed in 1.1

**Comment by eve0415** [comment]
Oh that’s why
