### ISSUE TITLE
Zebra was unable to complete this command because it does not have the proper permissions.

### ISSUE THREAD

**Issue by shockdesign** [wstyres/Zebra#806]
**Describe the bug**
Cannot install any apps as error;
```
CHAOS, CHAOS!
Zebra was unable to complete this command because it does not have the proper permissions. Please verify the permissions located at /usr/libexec/zebra/supersling and report this issue on GitHub.
```

Permissions are:
```
root# ls -la /usr/libexec/zebra/supersling
-rwsr-sr-x 1 root wheel 198544 Jan  6 06:31 /usr/libexec/zebra/supersling*
```

**To Reproduce**
Install Zebra via Cydia using PhoenixPwn.

**Expected behavior**
No errors and ability to install apps using Zebra.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 9.3.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.4
 - Device Type [e.g. iPhone or iPad]: iPad 2,5
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: PhoenixPwn

**Comment by wstyres** [comment]
Interesting, can you set the permissions to 6755 and try again?

**Comment by shockdesign** [comment]
@wstyres I tried that, still not working. SSH'ing into the device and running that command on the terminal it still prints out `CHAOS, CHAOS!`

**Comment by wstyres** [comment]
Ah, that explains it. For security reasons, `supersling` is not meant to be run by anything except for the Zebra binary. You cannot run it from the command line or from a script.

**Comment by shockdesign** [comment]
Initial error tho is the same when I try to install `PowerApp` via Zebra (hence the trying on the command line too)

**Comment by wstyres** [comment]
Does `/Applications/Zebra.app/Zebra` exist on your filesystem?

**Comment by shockdesign** [comment]
@wstyres Yes it does
```
root# ls -la /Applications/Zebra.app/Zebra
-rwxr-xr-x 1 mobile mobile 66928 Feb  1  2017 /Applications/Zebra.app/Zebra*
```

**Comment by shockdesign** [comment]
Cydia seems to install fine tho (which is how I installed Zebra... had to install Stashing before that as well).

**Comment by wstyres** [comment]
Interesting, stashing might be the cause of the issues here. I suspect because the Zebra binary is actually stored in a different location inside of `/var/stash`. Are you able to remove stashing? This might solve the problem. If not I'll have to find some way to reproduce this myself as I don't have a 9.3.5 device handy.

**Comment by shockdesign** [comment]
@wstyres With stashing uninstalled, I still get the same issue.
Please let me know if there is anything else you need me to try (btw without stashing I can't install much via Cydia due to lack of space)... only a base model iPad Mini 1..

**Comment by wstyres** [comment]
And without stashing installed is the Zebra binary still symlinked? I suspect this is the larger problem but I’m not sure.

**Comment by shockdesign** [comment]
@wstyres Zebra seemed to work without Stashing installed... I have to double check if its still symlinked..

**Comment by shockdesign** [comment]
#809 seems to be an issue with installing due to lack of space.

**Comment by wstyres** [comment]
Alright, I'll have to do some research into symlinking and see how it affects Zebra overall. It could be a simple fix but it also could be more complex.

**Comment by wstyres** [comment]
I think I might have fixed the issue with stashing. I'm not able to verify completely Here its a link to a test deb https://www.dropbox.com/s/oc2mxv97ahelbye/xyz.willy.zebra_1.0.6-1_iphoneos-arm.deb?dl=0 test it out with stashing installed and let me know how it works out.

**Comment by Albaraa2002** [comment]
I have the same issue now but after stashing 
I'm going to remove stash and try

**Comment by wstyres** [comment]
Did you try the deb that I linked above? that should fix the stashing issue.

**Comment by Albaraa2002** [comment]
ok I will try it now
" I didnot have attention to the link ^_^"

**Comment by Albaraa2002** [comment]
it wors

> I think I might have fixed the issue with stashing. I'm not able to verify completely Here its a link to a test deb https://www.dropbox.com/s/oc2mxv97ahelbye/xyz.willy.zebra_1.0.6-1_iphoneos-arm.deb?dl=0 test it out with stashing installed and let me know how it works out.

yup it works thx

**Comment by TheGamingMaik** [comment]
Getting the same error here...
iPhone X
iOS 13.3
Checkra1n Jailbreak

I got it directly after installing Zebra via Cydia...

**Comment by Chiko-Albaraa** [comment]
uninstall it 
then Try the link above

**Comment by TheGamingMaik** [comment]
How do I install .deb?

**Comment by Chiko-Albaraa** [comment]
> How do I install .deb?
 
download it using any browser or safari tweak (I recommend safari plus)
install it by filza
