### ISSUE TITLE
Zebra 1.0.3/1.0.4 crashes during installation.

### ISSUE THREAD

**Issue by guy4jesuschrist** [wstyres/Zebra#807]
**Describe the bug**

After attempting to use Zebra to install a couple tweaks (Little11 & Appsync Unified), Zebra crashes toward the end of the verbose display of the installation, obviously not offering the chance to respring. I’m able to install both tweaks successfully with Cydia.

**To Reproduce**

I had recently updated 1.0.2 to 1.0.4, after a couple days of not being jailbroken. So, I first downgraded to 1.0.3 thinking maybe it’s a bug in 1.0.4, but it also crashes at the same installation point. I then downgraded to 1.0.2, and both tweaks installed successfully and displayed the Respring button.

**Expected behavior**
I expect the normal installation behavior, of the installation completing and then a button being displayed of the proper next step of either respringing or returning to Zebra.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.3/1.0.4
 - Device Type [e.g. iPhone or iPad]: iPhone 8 Plus
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
Not sure if this matters, but I had also recently installed a tweak from Junesiphone’s secret repo, called “Adjust Notifications”, not realizing it wasn’t compatible with iOS 13, which caused my phone to reboot. I then used checkra1n to jailbreak into Safe Mode, and used Cydia to uninstall “Adjust Notifications”, rebooted and ran the checkra1n jailbreak normally this time. Upon using Zebra to update itself and Installer, I noticed yellow text that said something like “Adjust Notifications” doesn’t exist in a list of some sort. I then opened Cydia and noticed that it still said that “Adjust Notifications” was still installed, even though I uninstalled it in Safe Mode, so I proceeded to uninstall it again. When trying to install both tweaks I mentioned above, the yellow warning text doesn’t appear anymore, but both aforementioned newer versions of Zebra crash.

**Comment by wstyres** [comment]
Do you have a crash log? Do you have a screen recording so that I might be able to see the warning text? Does this happen on every tweak or just the ones you listed?

**Comment by MySQL-Syntax** [comment]
This is happening to me too, I'll go ahead and provide links for the crash logs I got from CrashReporter.

.Zebra: https://pastebin.com/KngBMaZt
ExcUserFault_Zebra: https://pastebin.com/mdy86uun
 
I am using some tweaks that modify Cydia also on Zebra like CyDown and FormulaOneOne but this always happen at the end of tweak installation.

**Comment by wstyres** [comment]
Does removing CyDown fix the issue?

**Comment by wstyres** [comment]
Is this resolved as of 1.0.5?
