### ISSUE TITLE
Zebra won't install on iOS 9

### ISSUE THREAD

**Issue by allendude51** [wstyres/Zebra#809]
iPhone 4s 9.3.6
Zebra 1.0.5 refuses to install and gives me an error every time, despite the page saying my iOS version is compatible.
![53A9161F-6CB0-43A4-B396-5D025D22E0C8](https://user-images.githubusercontent.com/51012842/72189298-1f4c7d80-33c2-11ea-8b11-df19462a152b.jpeg)

**Comment by wstyres** [comment]
Do you have stashing installed? There might not be enough space left on the system partition for Zebra to install to.

**Comment by allendude51** [comment]
I have 1.9 GB of free space

**Comment by wstyres** [comment]
Is that reporting from the settings app or from Cydia? The System partition probably has less free space than that.

**Comment by allendude51** [comment]
System says I used 98.1% but I'm still able to install packages that are
larger than zebra just fine.

**Comment by wstyres** [comment]
Zebra has a much larger unpacked size as it is compressed, this error for Cydia usually means that it doesn't have enough space left on the system partition. I would suggested installing a stashing tweak to help alleviate storage concerns.

**Comment by allendude51** [comment]
What are they called and what is the repo? Never heard of these before.

**Comment by wstyres** [comment]
I believe coolstar used to make the one for 9.3.x, stashing tweaks aren't required on newer iOS versions (due to APFS) and they weren't required on older iOS versions because Cydia handled stashing for you. You can google "Stashing" and your iOS version for more information, there should be some tutorials on reddit.

**Comment by wstyres** [comment]
Also, are you trying to upgrade from 1.0.4 to 1.0.5? If so, try removing Zebra and then installing the update. You should have enough space then.

**Comment by allendude51** [comment]
Thanks! And no I was trying to do a new install

**Comment by allendude51** [comment]
Well rip. The phone is on 9.3.6 and the tweak will only install up to 9.3.5.

**Comment by wstyres** [comment]
There is a package called "Stashing for iOS 9.2 - 10.2" on https://coolstar.org/publicrepo/

**Comment by allendude51** [comment]
I added that exact repo and it just tells me I can't install it. I looked
on the Reddit post for it and it says it's works all the way up to 10.2 so
idk what's going on

**Comment by allendude51** [comment]
Ok so I was able to get it installed by downgrading to an older version. I was also able to now get zebra installed, but now I'm running into another problem when I try to install any package using zebra...
![28899210-97E8-4986-9901-B756C2ED37D3](https://user-images.githubusercontent.com/51012842/72199820-d9fe6f00-3406-11ea-8083-5428fce20438.jpeg)

**Comment by wstyres** [comment]
Looks very similar to #806 so I’ll close this issue

**Comment by allendude51** [comment]
I looked at that page, didn't really show how to fix it, unless it's an
issue with zebra itself.

**Comment by wstyres** [comment]
Yes, currently it is an issue with Zebra, I'm looking for a fix.

**Comment by allendude51** [comment]
Alright cool thanks 👍

**Comment by allendude51** [comment]
I installed version 1.0.6 on my 4s and I'm still getting the error when
trying to install anything using zebra, also the restart springboard
buttons still isn't working.
