### ISSUE TITLE
Unconfigurable White Text on White Background within Dark Mode makes Unreadable Text Field

### ISSUE THREAD

**Issue by DFNCTSC** [wstyres/Zebra#811]
**Describe the bug**
When using Dark Mode, Packages text field on Search tab uses white text with white background making text unreadable.

**To Reproduce**
1. Enable Dark Mode
2. Go to Search tab
3. Type in Search field.
4. Can't read.

**Expected behavior**
Packages text field background should be dark in Dark Mode, not white, so that white text can be seen. Or just keep the Packages text color black so that it acts normally as it does in Light Mode.

**Screenshots**
![2020_01_11_03_27_IMG_0001](https://user-images.githubusercontent.com/6670632/72203592-7124f000-3422-11ea-838e-f47fd49a888e.PNG)
I typed "here" into the search field and as you can see it's effectively invisible.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 10.3.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.5 
 - Device Type [e.g. iPhone or iPad]: iPad 4 (WiFi)
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: h3lix

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Fixed as of 5e8489f90a2e98263aab87d862d01f460a8aaa03
