### ISSUE TITLE
Error trying to install a package that conflicts with an installed package

### ISSUE THREAD

**Issue by Aransh** [wstyres/Zebra#813]
If I try to install a tweak, while I have a tweak that conflicts with it installed, adding the conflicting tweak to the queue for removal doesn't remove the warning. Basically making me respring twice for installing a single package (remove conflicting tweak, respring, install desired tweak).

Example:
I have 13HUD installed, I want to replace it with Ultrasound.
I add Ultrasound to the queue for installation
A warning appears saying it cannot be installed as it conflicts with 13HUD
I add 13HUD to the queue for removal
I'm still unable to start the queue as the warning is still there.

iPhone X🅂 Max, iOS 12.4, Zebra 1.0.5

**Comment by eve0415** [comment]
I think it’s dupilicate of #753

**Comment by wstyres** [comment]
Does seem to be similar to #753, move discussion there.
