### ISSUE TITLE
何が起こったのかわからない

### ISSUE THREAD

**Issue by FROZENForever** [wstyres/Zebra#816]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by FROZENForever** [comment]
これってなんのアプリですか？

使い方もわからずAppStoreでインストールしたのですが、何使うものなのでしょうか？

日本語回答でお願いします。

**Comment by eve0415** [comment]
@FROZENForever 
まず先に、AppStore から Appのリンクをもらってもよろしいですか？
App を共有で、リンクをコピーして貼ってほしいです。

**Comment by eve0415** [comment]
> これってなんのアプリですか？
> 
> 使い方もわからずAppStoreでインストールしたのですが、何使うものなのでしょうか？
> 
> 日本語回答でお願いします。

まずこのアプリは、iPhone/iPadが脱獄環境である際に使うものです。脱獄が何かわからない場合は全く使い道はありません。また、ここで脱獄とは何かについても語りません。
私は、ZebraをApp Storeで見つけることができませんでしたので、何とも言えませんが、App Store(日本のサーバー)にはないかと思われます。
さらに、これはバグレポートではないようですので、この報告は閉じさせていただきます。

Translation;
This app is only for user who has jailbroken device. If you don't know what "jailbreak" mean, then there is no use for you. And, I'm not going to discuss what jailbreak means and about.
For me, I couldn't find Zebra on App Store, I don't think it is available in App Store (Japan's server).
Furthermore, this issue doesn't seem to be a bug report, therefore it will be closed.
