### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by coogarprod** [wstyres/Zebra#818]
**Describe the bug**
I have this message appearing (see the screenshot) anytime that I try to install 
whatever (tweak , app, ..) from zebra. Though I can close it , It keeps on coming back and this big error message text hides the description of te tweaks I want to install. 

**To Reproduce**
Steps to reproduce the behavior: try to install a tweak

**Expected behavior**
A clear and concise description of what you expected to happen : I don’t want this error message anymore. 

**Screenshots**
![7181320D-25A5-45DF-AAA1-C4403006D496](https://user-images.githubusercontent.com/59848852/72293906-bfb9d080-3654-11ea-961a-4e944f548062.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: the last one at this day. 
 - Device Type [e.g. iPhone or iPad]: iphone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue. Null 

**Additional context**
Add any other context about the problem here. Null

**Comment by eve0415** [comment]
check tweak compatible for zebra. What version and from what repo did you install?

**Comment by wstyres** [comment]
This is an issue with a tweak you have that modifies Zebra. Zebra is preventing a crash from happening when viewing the depiction of a tweak. Uninstall the tweak and the message will disappear.

**Comment by coogarprod** [comment]
Hi,
Thanks for ur reply ,

I have this error message since I installed zebra. Even after zebra’s update. It’s
It says that I have to uninstall a package (installed with zebra by default) but when I look for it I can’t find it to uninstall it.

Coogarprod

Le 13 janv. 2020 à 23:13, eve0415 <notifications@github.com<mailto:notifications@github.com>> a écrit :


check tweak compatible for zebra. What version and from what repo did you install?

**Comment by coogarprod** [comment]
I tried to do so.
I can’t find the package when I look for it.
I have this message after the zebra install , without installing any tweak.

Le 14 janv. 2020 à 00:43, Wilson Styres <notifications@github.com<mailto:notifications@github.com>> a écrit :


This is an issue with a tweak you have that modifies Zebra. Zebra is preventing a crash from happening when viewing the depiction of a tweak. Uninstall the tweak and the message will disappear.
