### ISSUE TITLE
Rework default interface options

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#819]
Don't know if this would be possible but I think the default theming settings should be slightly reworked. 

- Would be awesome if the iOS 13 dark mode became the default dark mode. 
- Would be awesome if the default accent color was the same light blue used throughout iOS.
- Would be awesome if switches were colored as they are in stock iOS apps such as settings when using the default accent color. (Green for enabled and the respective grey for disabled while in dark mode or default).

Screenshots:
![5E69B8AD-EC59-4C4E-923C-3C120AE16F01](https://user-images.githubusercontent.com/51668635/72301459-1b8d5500-3667-11ea-9606-64123e6b600a.jpeg)
![0CD710F9-AC34-4A6B-99EF-A63F5C47EBB5](https://user-images.githubusercontent.com/51668635/72301457-1b8d5500-3667-11ea-8826-240061c64a0d.jpeg)
![6E1EED3B-786C-4BF0-82B3-8345D3E3B9DD](https://user-images.githubusercontent.com/51668635/72301458-1b8d5500-3667-11ea-9115-e7d057ecd6d0.jpeg)
![94CE3875-0216-4047-85DD-EA7AFD32A13D](https://user-images.githubusercontent.com/51668635/72301460-1c25eb80-3667-11ea-83f8-3f2b365c7f47.jpeg)

**Comment by wstyres** [comment]
Working on this already in 1.1. The default Zebra color will remain the default but we can add an option to remove the tint color entirely.

**Comment by worldlydev** [comment]
> Working on this already in 1.1. The default Zebra color will remain the default but we can add an option to remove the tint color entirely.

So how would this be in practice? If there is no accent color would all the colors be set to iOS defaults?

**Comment by wstyres** [comment]
It would just be a "System Blue" option

**Comment by wstyres** [comment]
Implemented in 50787fbbc6477cb0244396680de7890891e226b7.
