### ISSUE TITLE
Can’t install tweaks

### ISSUE THREAD

**Issue by ivanchau14** [wstyres/Zebra#82]
After installing zebra and importing sources, I keep getting this error message. I also can’t install/modify packages from Sileo. The “x in queue” bar at the bottom doesn’t pop up
![B591615C-1F82-4ECA-8AD4-E43756F20D95](https://user-images.githubusercontent.com/44682698/57662885-691c6400-75a6-11e9-889c-81881db59381.png)

 - iOS Version 12.1.2
 - Zebra Version: 1.0\~beta10
 - Device Type iPhone XS Max

**Comment by wstyres** [comment]
Does this happen with all tweaks?

**Comment by ivanchau14** [comment]
Yes, all twekas

**Comment by wstyres** [comment]
Ok, did you happen to Upgrade a lot of tweaks when opening Zebra? This could be the cause of you having improper repositories for your jailbreak.

**Comment by ivanchau14** [comment]
tried upgrading 3 tweaks i believe

**Comment by wstyres** [comment]
What jailbreak are you on and what repos do you have added?

**Comment by ivanchau14** [comment]
Chimera, Sileo, I have most popular repos + 2 pirate repos

**Comment by wstyres** [comment]
I don't mind if you have pirate repos but I do need a full list of repos to verify the issue

**Comment by ivanchau14** [comment]
i just spent an hour restoring my device to find out the issue. after
install zebra, there's 3 updates for stuff. when i clicked upgrade, it
downgraded my core utils and gzip, which basically broke everything. i
forgot to screenshot, brb, gonna restore again

**Comment by ivanchau14** [comment]
https://imgur.com/a/9mfTXGH

Zebra downgraded these 2

**Comment by ivanchau14** [comment]
Will you be able to fix this? Or will i have to restore again?

**Comment by wstyres** [comment]
If you screenshot the repos that you have in Zebra I might be able to help

**Comment by ivanchau14** [comment]
https://imgur.com/a/njORlYU

**Comment by wstyres** [comment]
Ok, that is what I thought. You need to remove the "Cydia/Telesphero" repo since you are using the Chimera jailbreak. You should only add the repos that work with your jailbreak.

**Comment by ivanchau14** [comment]
Removed it, how do I fix it now?

**Comment by wstyres** [comment]
If you haven't upgraded those packages yet then you should be all good.

**Comment by ivanchau14** [comment]
I removed the source, the two upgrade badges from Zebra are gone, but
they’re still present in the Sileo app. I still can’t install, getting the
same error code.

**Comment by wstyres** [comment]
Ok, then if a restore to a previous snapshot fixes the issue then do that and then just remove the Cydia repo from Zebra.
