### ISSUE TITLE
[Request] Respring Button

### ISSUE THREAD

**Issue by benharris2510** [wstyres/Zebra#822]
Maybe a button to respring on the main page, next to the dark mode button that allows you to respring at any time.

**Comment by worldlydev** [comment]
> Maybe a button to respring on the main page, next to the dark mode button that allows you to respring at any time.

I'd rather have it in the settings like this:
![2FC9C676-96F2-4859-9830-CAE2409C15DE](https://user-images.githubusercontent.com/51668635/72470406-118f6180-37e1-11ea-9aad-3db540cb142c.jpeg)
