### ISSUE TITLE
Su/sling.

### ISSUE THREAD

**Issue by ashbruh** [wstyres/Zebra#828]
**Describe the bug**

When opening zebra or installing a package the following error message appears.
“su/sling does not have permission to set the uid or gid. Please verify the permissions of the file located at /use/libexec/zebra/supersling/.

I’ve tried to change the permissions but am still getting the same error.

The problem started after upgrading zebra.
**To Reproduce**
Open zebra or install a package from zebra.

**Expected behavior**
Package would install

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.6
 - Device Type [e.g. iPhone or iPad]: iPhone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Could you list the permission that super sling has and what you're trying to set them to? Also, have you tried re-installing Zebra from Cydia?

**Comment by kochon** [comment]
I have the same issue. Tried ticking set uid and set gid and hit save. Says it successed but instantly reverts back. Gonna try to reinstall with cydia.
![A5D9FE66-8327-4060-BC76-502B53C0F647](https://user-images.githubusercontent.com/1373506/72749544-5f60ec80-3b88-11ea-95c4-854d7615a3b2.png)
![246B04CC-BABA-4284-B076-BB3F163BB634](https://user-images.githubusercontent.com/1373506/72749545-5f60ec80-3b88-11ea-82d0-cdcd4da1fe96.png)
![1E9B6BB6-7420-4C51-B0CC-58FB0B9FE7C0](https://user-images.githubusercontent.com/1373506/72749546-5f60ec80-3b88-11ea-9032-2a1fe7e53ff9.png)
![E676D8D1-01B9-4B6A-B814-F01756565392](https://user-images.githubusercontent.com/1373506/72749547-5f60ec80-3b88-11ea-9624-f198433ab8d6.png)
![3D106F0A-A682-41DA-B1D4-71A60B348FE0](https://user-images.githubusercontent.com/1373506/72749548-5ff98300-3b88-11ea-8d78-fabd06499709.png)
![8980969A-9912-466D-A9C8-379E4E58CF51](https://user-images.githubusercontent.com/1373506/72749549-5ff98300-3b88-11ea-8f12-b6bc84f525ef.png)

**Comment by wstyres** [comment]
Also running `chown root:wheel /usr/libexec/zebra/supersling` and `chmod 6755 /usr/libexec/zebra/supersling` from Terminal might help. Filza might not be able to set the proper permissions.

**Comment by ashbruh** [comment]
Yeah reinstalling from Cydia works. Thanks.
