### ISSUE TITLE
Hide or disable community news when no internet connection

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#830]
When there is no internet connection or cannot load any community news from reddit, there is a big blank on changes tab. 
I want this news place would be hidden or disable in such this case.
![3421539F-66D1-4CF7-953C-89FC1E176209](https://user-images.githubusercontent.com/40632436/72777499-2e042180-3c59-11ea-9f3f-c554c20e66be.png)

**Comment by aabosh** [comment]
Fixed in e6cba8f3. Will be available in 1.1.
