### ISSUE TITLE
Remove cache and featured list when removing source

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#831]
**Describe the bug**
I don't know if its a bug or not but after removing a source from source tab, "repo url_._Release" & "repo url_._Packages" in "xyz.willy,zebra/lists" folder are not removed. Also In featured.plist, there are old cache of featured package resulting some empty package that cannot be installed anymore to be featured in home tab.

**Expected behavior**
Remove cache and files from device as well.

**Comment by wstyres** [comment]
Both should be fixed as of ecec2b51562ada0421762c0492dc296b74a1e085.
