### ISSUE TITLE
Package Issues

### ISSUE THREAD

**Issue by EscoIV** [wstyres/Zebra#832]
**Describe the bug**
Started seemingly out of nowhere. No packages where installed removed or updated prior to this happening. It occurs when I try to install, remove or update any package. After the error it gives me the option to respring and when I try to respring it gives me another error saying it cannot. 
**To Reproduce**
Steps to reproduce the behavior: install, remove or update any package

**Expected behavior**
To install, remove or update package and to respring after. 

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 13.1.3]: 
 - Zebra Version [1.0.6]: 
 - Device Type [iPhone 8 Plus]: 
 - Jailbreak Type [checkra1n]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**
![09277B16-7E5E-4D07-851C-8501C41CE3C1](https://user-images.githubusercontent.com/59077802/73000681-3d0ce000-3dcf-11ea-9d1a-9c2f70a32399.png)
![4F7A9374-349C-4E6B-884B-971CD7DBB5D7](https://user-images.githubusercontent.com/59077802/73000682-3da57680-3dcf-11ea-8320-95de40edb702.png)

**Comment by wstyres** [comment]
Does re-installing Zebra from Cydia fix this issue?

**Comment by EscoIV** [comment]
Reinstalling it didn’t immediately Fix the issue. It persisted for a few tries until I finally purged it and restored from the ipa.

**Comment by wstyres** [comment]
If you're jailbroken you should be installing from the .deb or from Zebra's repo, not the ipa

**Comment by EscoIV** [comment]
Yeah well that wasn’t working I just told you that lol
