### ISSUE TITLE
Error: su/slling does not have permession to set the uid or gid.

### ISSUE THREAD

**Issue by Datisit** [wstyres/Zebra#833]
Full error:

"su/slling does not have permession to set the uid or gid. Please verify the permissions of the file located at /usr/libexec/zebrasupersling."

I have tried to alter the permissions on that file but to no avail. 

Any help, much appreciated.
Thanks

**Comment by wstyres** [comment]
How have you attempted to change the permissions? Have you looked at other issues?

**Comment by Datisit** [comment]
Navigating to the file in Filza, and, without massively knowing what I'm doing — turning on the group and other write permissions. Those set, but did not help — and the 'sticky' sections do not stay set after saving. 
I didn't want to change the permissions too much myself without knowing what I should be doing. 

Apologies, I did not see other issues to do with this error exactly.

**Comment by wstyres** [comment]
You might want to try running `sudo chmod 6755 /usr/libexec/zebra/supersling` from Terminal or SSH. Filza might be broken in that regard. If that doesn't work, try reinstalling Zebra.

**Comment by Datisit** [comment]
Ok will do. 
May I ask, should I be re-installing from Cydia then — since I cannot perform the reinstall from Zebra itself?

**Comment by Datisit** [comment]
Okay nevermind that. It seems running chmod has set it properly. 
Zebra is no longer giving the error. 

Thanks for the quick help. 

I believe this issue occurred after one of the recent Zebra updates, if that helps at all.

**Comment by wstyres** [comment]
Ok, I'll see if anything looks out of the ordinary on the upgrade but I haven't experienced it myself.
