### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Usmon4535** [wstyres/Zebra#834]
![E985EF55-4E3A-409B-AEF2-CFDD0F2E41A4](https://user-images.githubusercontent.com/60349551/73177647-5d230300-4131-11ea-8ff5-fc243cc542e9.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Please re-install Zebra from Cydia or run the command `sudo chmod 6775 /usr/libexec/zebra/supersling` to resolve the issue
