### ISSUE TITLE
Hostname not found for getzbra.com when all sources refreshed

### ISSUE THREAD

**Issue by Spitemare** [wstyres/Zebra#835]
**Describe the bug**
Refresh of all sources results in hostname not found for getzbra.com. Manual refresh of Zebra source refreshes without issue.

**To Reproduce**
1. Pull down sources list to trigger refresh of all sources.
2. Dialog appears saying, "A server with the specified hostname could not be found. for https://getzbra.com/repo/Release"
3. Tap "Cancel"
4. Scroll to Zebra repo in sources list.
5. Drag to left to trigger manual refresh.

**Expected behavior**
Zebra repo should refresh without issue.

**Screenshots**
Screen recording posted: https://imgur.com/a/IADZsMo

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.6
 - Device Type [e.g. iPhone or iPad]: iPhone 8
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by Spitemare** [comment]
Update: I think this was caused by the BigBoss Uncluttered repo. Zebra started showing the same error above for other repos. Remove BigBoss U and adding back BigBoss resolved it.

This issue can be closed if you like. Or it can be left open to investigate the incompatibility with BigBoss U.

**Comment by wstyres** [comment]
Could have been a one-off issue, I'm not able to reproduce it with repounclutter installed. The error sounds like something to do with your local network.
