### ISSUE TITLE
Conflict popup in queue displaying incorrect message

### ISSUE THREAD

**Issue by NICHOLAS85** [wstyres/Zebra#836]
**Describe the bug**
When attempting to install conflicting packages, the queue no longer shows the conflicting package in red and additionally, the popup states a "Required Package" message instead of the proper "Issues" popup.

**To Reproduce**
Install conflicting packages and view popup message

**Expected behavior**
Display proper message

**Screenshots**
![IMG_9875](https://user-images.githubusercontent.com/15698885/73305169-8ef6a100-41e7-11ea-9d05-7b17f78ea9a2.PNG)

**Device Information (please complete the following information):**
 - iOS Version: 13.2.3 
 - Zebra Version: 1.0.6
 - Device Type: iPhone X 
 - Jailbreak Type: checkra1n

**Comment by wstyres** [comment]
Fixed as of 52be763befb3e07b93d83b5c356b44350062d7a2. Scheduled for 1.1.
