### ISSUE TITLE
Filter changes by package type

### ISSUE THREAD

**Issue by finngaida** [wstyres/Zebra#837]
**Is your feature request related to a problem? Please describe.**
I regularly check new and updated packages in the Changes tab, but I'm not interested in eg. themes at all, so they clutter the list for me.

**Describe the solution you'd like**
A filter button in the nav bar with options to deselect specific package types I don't want listed in the changes tab.

**Describe alternatives you've considered**
Just ignoring all irrelevant packages?

**Additional context**
n/a

**Comment by wstyres** [comment]
Sounds similar to #397? Some filters and blocks would be implemented with that so I think this feature request would fall under that.
