### ISSUE TITLE
Zebra crashes on launch

### ISSUE THREAD

**Issue by Davetheminion101** [wstyres/Zebra#84]
crashes directly on launch. Using 1.0~b10 
https://pastebin.com/PvRHgF5t

**Comment by wstyres** [comment]
Could you post a list of repos?

**Comment by Davetheminion101** [comment]
Would you like me to use something like flame to get sources from cydia?

**Comment by wstyres** [comment]
Could you try this deb and see if the crash still occurs? https://www.dropbox.com/s/zh28qfnjz1gglpy/xyz.willy.zebra_1.0~beta11-7%2Bdebug_iphoneos-arm.deb?dl=0

**Comment by Davetheminion101** [comment]
I installed the deb via Filza but the icon doesn’t appear on my home screen

**Comment by wstyres** [comment]
Saurik's repo could cause issues if used on the incorrect jailbreaks. The utility repo for unc0ver is Elcubartus.
