### ISSUE TITLE
When clicking a link to add a repo in Cydia, Zebra opens instead!

### ISSUE THREAD

**Issue by Nikostito** [wstyres/Zebra#841]
**Describe the bug**
When trying to add a repo and you chose the link for Opening Cydia, Zebra opens instead.
**To Reproduce**

Try to add a repo to your phone:
Example [link:](https://cydia.saurik.com/api/share#?source=https://nikostito.github.io/NtdarkDebs/)

If you press the "Open Cydia to this url" button, a popup will open saying if you want to open Zebra instead.

**Expected behavior**
Cydia should open when using cydia links. Zebra still opens if I use a zebra repo link.
**Screenshots**
![image](https://user-images.githubusercontent.com/25390905/73597868-8f6d9f80-4539-11ea-99e6-c46b06121b3b.png)

**Device Information (please complete the following information):**
 - iOS Version 13.2.3 
 - Zebra Version: 1.0.6 
 - Device Type [e.g. iPhone or iPad]: iPhone 7
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Not applicable.

**Comment by absidue** [comment]
This has been fixed in b4b93349 and will be included in 1.1
