### ISSUE TITLE
Zebra crashes upon startup

### ISSUE THREAD

**Issue by oxi0de69** [wstyres/Zebra#846]
**Describe the bug**
Whenever i open zebra, the homepage pops up for a few seconds then crashes

**To Reproduce**
Open zebra

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.6
 - Device Type [e.g. iPhone or iPad]: iPhone 7 GSM
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Checkra1n

**Crash Log or System Log**
https://pastebin.com/CrSZNhan

**Additional context**

**Comment by wstyres** [comment]
Could I see a list of sources?

**Comment by oxi0de69** [comment]
Where is the .plist file that has the sources?

**Comment by wstyres** [comment]
`/var/mobile/Library/Application Support/xyz.willy.zebra/sources.list`

**Comment by oxi0de69** [comment]
htttps://pastebin.com/fA5yK0A8

**Comment by wstyres** [comment]
Appears you have Litten's repo installed, I suggest checking out issue #845 for more information.

**Comment by oxi0de69** [comment]
Oh ok, thanks!

**Comment by oxi0de69** [comment]
I removed litten's repo, yet the issue still persists

**Comment by oxi0de69** [comment]
And cr4shed no longer detects when zebra crashes

**Comment by wstyres** [comment]
Make sure you read the steps in #845 about deleting Zebra’s database. If you have any further problems add them to #845

**Comment by oxi0de69** [comment]
Can I just say a huge thank you for making such an amazing package manager. far by my favorite
