### ISSUE TITLE
Crashing upon launch: nil string was passed for sorting

### ISSUE THREAD

**Issue by A1ic3-317** [wstyres/Zebra#847]
This crash began happening out of nowhere. Removing/reinstalling Zebra does not fix the issue. Cydia still works normally.

**Device Information**
 - iOS Version: 13.3 
 - Zebra Version: 1.0.6 
 - Device Type: iPhone X 
 - Jailbreak Type: checkra1n 0.9.7 and 0.9.8 

**System Logs**

[Zebra crash 1.txt](https://github.com/wstyres/Zebra/files/4161042/Zebra.crash.1.txt)
[Zebra crash 2.txt](https://github.com/wstyres/Zebra/files/4161044/Zebra.crash.2.txt)

**Comment by wstyres** [comment]
View #845 for more information about this issue and a fix.
