### ISSUE TITLE
[suggestion] slide left on the queue banner to clear queue

### ISSUE THREAD

**Issue by NickJustWill** [wstyres/Zebra#849]
add a gesture that allows the user to quickly clear the queue by sliding left on the banner with the queue...

[
![IMG_3182](https://user-images.githubusercontent.com/47925864/74041491-a559e500-49bd-11ea-960a-0b5fa8157b24.PNG)
](url)

**Comment by worldlydev** [comment]
Wouldn't it be easier to swipe down?

**Comment by NickJustWill** [comment]
> Wouldn't it be easier to swipe down?

iPhone X uses swipe down gesture for reachability, and as far as I can see from the tweaks, it would interfere with it

**Comment by wstyres** [comment]
Since there are already a few gesture recognizers on the Queue Bar itself it might be a bit complex to add another one, would a tap and hold gesture work as well? It was be easier UX wise to do but I can see why a swipe would also be nice.

**Comment by worldlydev** [comment]
> Since there are already a few gesture recognizers on the Queue Bar itself it might be a bit complex to add another one, would a tap and hold gesture work as well? It was be easier UX wise to do but I can see why a swipe would also be nice.

I was just thinking swiping down since it is like a queue bar. 

Tbh I think holding would be better. Please implement it. Don't know how often I would use it but it seems like it could be useful.

**Comment by wstyres** [comment]
Implemented in 002f50b5a0c0611a0d363718d6c66810d1d31a92. Will be included in first 1.1 beta.
