### ISSUE TITLE
Zebra cancel button in search buggy and doesn't close unless there is letters in the search bar

### ISSUE THREAD

**Issue by Amplespencer** [wstyres/Zebra#85]
**To Reproduce**
press cancel in search
**Expected behavior**
it cancels
**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.1]: 
 - Zebra Version [beta 10]: 
 - Device Type [iPhone xr-chimera]: 

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Could you provide a screen recording of this? I'm able to press the cancel button just fine

**Comment by Amplespencer** [comment]
so it seems like it isn't broken, but it's hard to press and sometimes it
opens a white box with done at the top

**Comment by Amplespencer** [comment]
update: it looks like the cancel button is misaligned by ~100-300px, this
is probably an xr exclusive issue, if you can check this out that would be
great

Ok actually I think this is a side effect of the broken tweak I have
installed from qwertyuiop1379's triple tap since it also is in the gmail
app so nevermind

**Comment by wstyres** [comment]
Closing issue as this seems to be an issue with a tweak and not Zebra.
