### ISSUE TITLE
Tweaks from Twickd always fail to download and install even after dropping tables

### ISSUE THREAD

**Issue by p1neapplecfw** [wstyres/Zebra#851]
Every-time I try to install (Or reinstall) a tweak from the Twickd repository, it will either end the installation claiming that there is no more further actions to continue, or if I reinstall after installing the tweak from a separate package manager, it will simply end the installation like this: 

https://i.imgur.com/nZhzyKR.png

(This is also with all tweaks disabled in iCleaner Pro)

**To Reproduce**

Install a paid (or possibly free) package from the repo

**Expected behavior**

Successful installation of the package

**Screenshots**

https://i.imgur.com/nZhzyKR.png

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: **iOS 13.3**
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: **1.0.7**
 - Device Type [e.g. iPhone or iPad]: **iPhone X Global, (iPhone 10,3)**
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: **checkra1n**

**Crash Log or System Log**

Not present.

**Comment by wstyres** [comment]
In the screenshot you are reinstalling a tweak, are you able to download new tweaks from Twickd? Something else would be if you are able to re-install any tweak at all.

**Comment by wstyres** [comment]
I'm not able to try the package that you used in the screenshot (because it is paid) but I was able to download a few free tweaks from Twickd just fine.

**Comment by p1neapplecfw** [comment]
Hey, sorry for taking so long to get back.

But yes this happens for packages that haven’t been installed yet.

After trying to install a free package from Twickd, Zebra can install the package just fine, but all commercial packages seem to fail to install.

**Comment by wstyres** [comment]
Ok, interesting. This might have already been resolved in the 1.1 version I have. You'd have to wait and test until the first 1.1 beta is out though since I don't have any package purchased on Twickd.

**Comment by wstyres** [comment]
@p1neapplecfw Are you able to confirm if the bug is resolved in the 1.1 beta?

**Comment by p1neapplecfw** [comment]
It appears to be. Thank you.
