### ISSUE TITLE
Crashes on the first try to open it

### ISSUE THREAD

**Issue by BenFrank777** [wstyres/Zebra#858]
**Describe the bug**
The app crashes every single time I’m trying to open it the first time 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: xs max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.
No crash log
**Additional context**

**Comment by wstyres** [comment]
Do you have any more information? We aren't able to debug very well if there is no crash log.

**Comment by wstyres** [comment]
Closed due to inactivity.
