### ISSUE TITLE
White header with dark mode enabled

### ISSUE THREAD

**Issue by tshelburne02** [wstyres/Zebra#859]
**Description**
When turning on dark mode, the top header on the home page stays white.

**To Reproduce:**
- Go to the home page
- Press “Report a Bug”
- Go back
- Turn on dark mode

**Expected Behavior**
Home page should be completely black.

**Screenshots**
![07518717-9298-4375-88D3-E3F67B7E8807](https://user-images.githubusercontent.com/40906152/74611479-7298a680-50b9-11ea-8b46-f230ec9932f5.png)

**Device Information:**
 - iOS Version: 13.3
 - Zebra Version: 1.0.7
 - Device Type: iPhone XS
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
None

**Additional context**
None

**Comment by wstyres** [comment]
Is this issue fixed in the 1.1 betas?

**Comment by eve0415** [comment]
I think so
