### ISSUE TITLE
Zebra upgrades 

### ISSUE THREAD

**Issue by iinastyiii** [wstyres/Zebra#86]
Latest version of zebra. Upgrading a package. 

Zebra shows a update available but Cydia doesn’t. The update that zebra shows is 1.89 and in Cydia I’m on 1.90 version. Tweak is Volume Amplifier. 

https://imgur.com/gallery/Erdmyvy

**Comment by wstyres** [comment]
Fixed as of 63be7aa

**Comment by iinastyiii** [comment]
It’s in the latest version of zebra. That I can install from the official repo.

**Comment by wstyres** [comment]
Yes, I've already fixed it but I have not released the beta yet. It will be out soon.

**Comment by iinastyiii** [comment]
Hope you aren’t referring to beta 11! Because now it shows everything I have installed needs upgrades

**Comment by iinastyiii** [comment]
Never mind it fixed once I ran iCleaner. But at first it showed all packages needed upgrades.
