### ISSUE TITLE
Make a few changes 

### ISSUE THREAD

**Issue by kelvin1300** [wstyres/Zebra#863]
Dear Zebra! 

I has some new idea about Zebra I don’t is this is possible, but let me get a shot..

Look made Zebra that when we are downloading a tweak, themes or widget that when the percentage is running making in the background. Such a Sileo. For example when the tweak is downloaded 32 % we can still continue searching for another tweaks or themes and the download continue down on the little tab bar. I made a few photoshop. 

Also please can you add that when we dont want a tweak on the little tab bar down make a "x" to clear everything such as when we tap the little tab bar that in the top left said "clear" the photoshop show that you can make it possible.

Zebra by far is my favorite package managed ever.. 

Thanks you all dev_ who created this awesome package managed. 

Reading and listening users we can make the best package ever in the history of jailbreak..

Thanks for your hard work, sacrifice, knowledge time... ect for making every upgrade better than before...... !!

Thanks if you read my request. I really appreciate it 

Sincerely, Kelvin.. 

![B144C093-0D4A-49DA-AAF3-6D37513B94DD](https://user-images.githubusercontent.com/55414105/74801682-7557ef00-52a5-11ea-8c98-03026663340b.jpeg)
![151A8BC1-FB4C-4A3A-84F3-24D2D9CDA481](https://user-images.githubusercontent.com/55414105/74801684-7852df80-52a5-11ea-87d9-9d2e47a1e1f8.jpeg)

**Comment by kelvin1300** [comment]
Also can make Zebra when we tap the Queue look exactly like when we go to zebra setting 
![A4A79760-A9D8-43F5-9A8D-BBF1FA49485E](https://user-images.githubusercontent.com/55414105/74802991-70953a00-52a9-11ea-954a-7097ea25c4a7.png)
![Uploading 2D848910-6023-4B71-A631-ADF4B5029C09.png…]()

**Comment by worldlydev** [comment]
Agree that it would be cool with a percent view of some kind on the queue bar. Maybe make it a configurable option to download packages as soon as they are added to the queue as to save time later?

The x thing is useless as in 1.1 you can hold on the queue bar to clear the queue.

Agree that it would be cool with a sheet style modal like the repo refresh view for the console. That way it could simply be swiped down to install packages in the background like repos can refresh in the background. Like requested in #273.

**Comment by wstyres** [comment]
Going to consolidate this information into #273
