### ISSUE TITLE
Bad sources removal

### ISSUE THREAD

**Issue by robonxt** [wstyres/Zebra#865]
When a source goes offline or is imported, Zebra fails to load it (with is normal), however, it does not show in the repo list so there is no way to remove it

Add in a fake repo link
Zebra will say it cannot connect
Fake link does not show up for removal in list

Allow users to see all the sources in the list, even the ones that failed to load or is offline, so they can delete it

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.7 
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Comment by wstyres** [comment]
This should be resolved with the new source verification system in 1.1 but I'll leave the issue open if there are issues with the new system when the new beta comes out.

**Comment by wstyres** [comment]
@robonxt Can you try out the beta and see if the bug is fixed?

**Comment by robonxt** [comment]
> @robonxt Can you try out the beta and see if the bug is fixed?

Yep, it's working now. I think the icon could be changed to a red X rather than just a ? for clarity.
