### ISSUE TITLE
Adding multiple repos issue

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#866]
**Describe the bug**
When adding multiple sources and one doesn’t work, it doesn’t let you get update for the other repos until you close the app completely and go back in. And when going back into the app to see what’s on those repos it says you’ve installed all the packages on those repos. 

**To Reproduce**
1. Add multiple repos with one that doesn’t work.
2. It’ll not show what’s on those repos until you reopen the app. 

**Expected behavior**
Refresh the repos when adding them in and show in updates and then not show you installed all the packages when updating them. 

**Screenshots**
![B0F5E220-FF75-4DAA-9F8B-7FF7C00204EA](https://user-images.githubusercontent.com/57759540/74939863-92341580-53be-11ea-84e0-d4f7f71745f5.png) 

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.0.7
 - Device Type: XS Max
 - Jailbreak Type: u0

**Comment by wstyres** [comment]
Should be fixed for 1.1 but you'll have to test and confirm when the beta comes out. When adding multiple sources now it will add the sources that could be verified and come back with a popup asking you to confirm the ones that were not able to be verified. Hopefully this will resolved your issue.

**Comment by wstyres** [comment]
@Greigh Can you test again and confirm if this is fixed in the beta?

**Comment by Greigh** [comment]
Yes. This has been fixed. Just tested it.
