### ISSUE TITLE
Unable to install Flex 3 Beta

### ISSUE THREAD

**Issue by SeMoOoR** [wstyres/Zebra#867]
**Describe the bug**
Zebra is somehow unable to exectue /run a proper .deb installation of Flex 3 Beta tweak from Delta repo. I have tried several times but it fails to install and shows ”finished!”.

**To Reproduce**
1- go to Delta repo.
2- attempt to install Flex 3 Beta
3- download will finish but Zebra will not install the deb package

**Expected behavior**
To be able to install a normal deb package

**Screenshots**
Not available.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.7
 - Device Type [e.g. iPhone or iPad]: iPhone 12,5
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 4.0.3

**Crash Log or System Log**
 Not available

**Additional context**
Nothing much to add.

**Comment by wstyres** [comment]
Closed in favor of #895
