### ISSUE TITLE
How about a filter for viewing packages

### ISSUE THREAD

**Issue by RonaldRegister** [wstyres/Zebra#868]
I couldn't find any other similar request/suggestion, please crosspost if there is. 

Would love to filter my changes-view. Right now it's bloated with a lot of themes. Would like to filter package type, e.g. Themes/Tweaks/Addons. Preferably enable or disable Zebra-wide in settings.

Perhaps the option to disable viewing all changes also?

**Comment by JTuCk856** [comment]
Yes please!! We need a filter to stop seeing nothing but themes everywhere. I can’t find any actual changes besides themes. Please include a filter, this issue is very annoying. Thank you!

**Comment by oxi0de69** [comment]
Im sure @wstyres will
