### ISSUE TITLE
Transferring source from Cydia

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#871]
**Describe the bug**
Some sources that I have already added to Zebra are showing. I got two Bingner/Elucubratus repo and some more

**To Reproduce**
Transfer source from Cydia

**Expected behavior**
Do not show me source that I have already added

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta1 
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
Is it the exact same source? Does it show up in the import controller as well?

**Comment by eve0415** [comment]
I think so. Unless there are two Bingner/Elucubratus repo which looks the same and Kurrt's Repo. 
For bingner's ;
https://cdn.discordapp.com/attachments/572784833714192395/680572278328786994/image0.png
For kurrt's repo, the one I have transferred from Cydia says "Tap to learn more".

**Comment by wstyres** [comment]
Could I see the sources list that goes with it?

**Comment by wstyres** [comment]
I had to do a bit of a patch for sources like this. The Bingner source added to Cydia by default does not contain a valid distribution/components. I now correct this in Zebra if present which should remove the duplicate sources.
