### ISSUE TITLE
http & https source

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#872]
**Describe the bug**
Replacing http source from https are working fine. However replacing https from http are not working. I get "Tap to learn more" when I added https source which I have already added http source.
ex) https://getzbra.com/beta to http://getzbra.com/beta work fine
http://getzbra.com/beta to https://getzbra.com/beta doesn't

**Expected behavior**
Replace or use https default when it is available

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta1 
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n 

**Additional context**
If you can, can you make Zebra to add https source over http if https are available on there server.

**Comment by wstyres** [comment]
Been awhile since this was filed so apologies but could you explain more about what you exactly want done? From what I understand you have a source added with `http` (for example `http://getzbra.com/beta`) and you're replacing it with an `https` variant in the add repo popup?

**Comment by eve0415** [comment]
Yes, replacing from http URL to https doesn’t work (The message says it has already added) , whereas replacing from https URL to http URL works(So, I guess Zebra is checking for http to understand it’s a URL). 

So I was hoping for Zebra to use https as default import behavior when their server does support https. If not, just use http.

**Comment by wstyres** [comment]
Most servers will enforce an https policy even if you request http and some sources still don't support http so I don't think I will enforce any changes in what the user enters and what is imported.

I think I could include a popup that warns the user when an http source is being added (perhaps in the popup dialog)

As for the replacing sources, I'll see what I can do about that so that the red disabled source doesn't pop up

**Comment by wstyres** [comment]
Added a popup in 7fd08dcc25611cc9d7ec2d0c7685c6189c15d76f.

**Comment by wstyres** [comment]
I've made Zebra warn you if you add an https source after already adding an http one. You'll now have to delete the http source before adding the https one. This is the simplest solution to the problem for now, I might look into having it automatically replace in a future update.
