### ISSUE TITLE
Pure Dark Mode Issue & Text Display Accent Color..

### ISSUE THREAD

**Issue by kelvin1300** [wstyres/Zebra#882]
Date: 2/22/20, 8:14 PM
Process: Zebra

Bundle id: xyz.willy.Zebra
Device: iPhone 6s, iOS 13.3
Bundle version: 1.1~beta1

Report Bugs: Ui Pure Dark Mode & Text Display Color!!

Ui color for the dark mode option when is pure black mode and the color of the text when I change to other colors...

When I change the color text the letter on the right side of all repo stay on the same color of before and not change correctly. 

The pure dark mode also don’t change correctly and I has to close (¡kill the app!) to see the changes! 

 https://www.dropbox.com/sh/48s02kdjths798h/AAAPD0cp7fJpTU6Agphgd62Ea?dl=0

**Comment by kelvin1300** [comment]
Broth here another issue. 


https://www.dropbox.com/s/2zsk3umlzc4f5rd/Video%20Feb%2022%2C%2010%2016%2031%20AM.mp4?dl=0

**Comment by aabosh** [comment]
@kelvin1300 Can you reupload the screenshots/screen recordings? The links you provided aren't working now.

**Comment by kelvin1300** [comment]
https://www.dropbox.com/sh/vb1jtb28m36aonh/AABCn6w5xMxL8jDS-SuJA00Ga?dl=0

**Comment by wstyres** [comment]
Since this is the same video as #1020 I'll close this issue.
