### ISSUE TITLE
Package sorting always return to ABC in latest beta

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#883]
**Describe the bug**
The old beta remembers the sorting of packages, but the latest beta always resort to alphabetically.

**To Reproduce**
Sort by date and kill zebra. Relaunch.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: latest beta 
 - Device Type [e.g. iPhone or iPad]: iphone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkrain

**Comment by eve0415** [comment]
Also Zebra forgets ro remember Appearance setting when re-opening

**Comment by NickJustWill** [comment]
This is legitimate, I'm getting it 0on iOS 13.2.2 iPhone 7 (Checkra1n), probably something to do with storing the preference for sorting which could've been broken by the latest changes in 1.1

**Comment by NickJustWill** [comment]
> Also Zebra forgets ro remember Appearance setting when re-opening

yeah I'm getting that aswell (iOS 13.2.2 iPhone 7 Checkra1n)

**Comment by wstyres** [comment]
This is temporarily removed in the hopes of doing a new sorting system in the 1.1 version. Not all of 1.1 is complete yet but if I end up pushing the filtering system back then I will re-add the feature.

**Comment by wstyres** [comment]
Ended up pushing the new sorting options to 1.2 so I have added the sorting style preference back. Fixed in 866f9eda.
