### ISSUE TITLE
An option in the settings to change whether zebra should open cydia links or just zebra links

### ISSUE THREAD

**Issue by oxi0de69** [wstyres/Zebra#887]
**Describe the solution you'd like**
I use zebra as my main package manager, but with the 1.1 update, zebra only opens zebra links, and most of the links i find are cydia links

**Additional context**
I remember seeing before there is a way to do this with filza, how do you do that?

**Comment by wstyres** [comment]
Zebra will no longer open Cydia links as long as people use Cydia as a package manager. It causes too much confusion and there is no way to specify which package manager is being opened when a cydia link is activated. 

A tweak can be made by another developer to convert cydia URLs into zebra URLs but I will not be doing it.

**Comment by oxi0de69** [comment]
I thought there was some string in filza you could modify
