### ISSUE TITLE
Accent color not applied

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#889]
**Describe the bug**

Some things aren’t properly themed. Using the system accent color so I’m not sure if that is causing it or not. Haven’t tested it. Will update if I find more unthemed things.

**Screenshots**

![0C2673EE-8D98-4275-A1F6-3D68539BEF8B](https://user-images.githubusercontent.com/51668635/75203080-7db09e00-576d-11ea-9eab-8e727d569fe7.jpeg)
![CD1A35DA-7D5C-443F-91FE-4BB7DC7F54B7](https://user-images.githubusercontent.com/51668635/75203084-80ab8e80-576d-11ea-8137-243e5e9b6570.jpeg)
![DEBF1A5C-38C7-4384-8B0E-E95B2E03BF45](https://user-images.githubusercontent.com/51668635/75203086-81442500-576d-11ea-85dc-77da5b6200c3.jpeg)
![1820D449-D984-4ADE-B661-F1509403DFB5](https://user-images.githubusercontent.com/51668635/75203132-9d47c680-576d-11ea-8bc8-bc44a84e7a3b.jpeg)

Both loading bars, close and cancel button, cursor, and respring button.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 1-1
 - Device Type [e.g. iPhone or iPad]: iPhone 11 Pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Additional context**

**Comment by wstyres** [comment]
Console Respring Button + Cancel Button aren't supposed to be tinted to match settings, I think I've already fixed the progress bar in the console but I'll check the other ones out.

**Comment by worldlydev** [comment]
> Console Respring Button + Cancel Button aren't supposed to be tinted to match settings, I think I've already fixed the progress bar in the console but I'll check the other ones out.

Would it be possible to tint them?

**Comment by wstyres** [comment]
All of these (except the navbar buttons in the console) have been fixed as of 9dd52a7acb04cae3759ea9b1a739ec22040bf4f1.
