### ISSUE TITLE
Default ‘iOS style’ dark mode won’t apply to some pages

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#890]
**Describe the bug**

In some pages the dark mode is grey instead of the ‘iOS style’ dark mode when using system appearance.

**Screenshots**

![CDDF827C-B1BD-43BF-AD5C-1C2C5B042AC2](https://user-images.githubusercontent.com/51668635/75203528-9bcace00-576e-11ea-8d64-896866f46f89.png)
![76FB82A7-D84B-4148-9887-BCB08D7C9617](https://user-images.githubusercontent.com/51668635/75203588-c6b52200-576e-11ea-9961-a274cc88d9c0.png)

Grey dark mode in settings and repo import screen.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 1-1
 - Device Type [e.g. iPhone or iPad]: iPhone 11 Pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Comment by wstyres** [comment]
So that is a feature of iOS 13 apparently, you can check this out in the App Store to confirm but when things get "layered" so to speak, they get lighter.

In the App Store the main page is black but the account page is gray. Not sure why this is but it is in fact default.

**Comment by worldlydev** [comment]
> So that is a feature of iOS 13 apparently, you can check this out in the App Store to confirm but when things get "layered" so to speak, they get lighter.
> 
> In the App Store the main page is black but the account page is gray. Not sure why this is but it is in fact default.

Lol why’d you have to point it out. This just gave me OCD. Anyways I think it may be because the updates tab is a website of sorts instead of being completely native. Same goes for the testflight profile page, etc. but not the contacts profile page for instance.

**Comment by wstyres** [comment]
No, it just has to do with it being presented in the way it is. The color is automatically changed to match the layer of presentation.

<img width="414" alt="Screen Shot 2020-02-24 at 8 01 15 PM" src="https://user-images.githubusercontent.com/19736790/75204957-6b6c3b00-5740-11ea-800f-6628f7138447.png">

`systemGroupedBackground` is used for the primary view, then if you present a view on top, it will inherit `secondaryGroupedBackground`, then `tertiary` and so on.

**Comment by worldlydev** [comment]
> No, it just has to do with it being presented in the way it is. The color is automatically changed to match the layer of presentation.
> 
> <img alt="Screen Shot 2020-02-24 at 8 01 15 PM" width="414" src="https://user-images.githubusercontent.com/19736790/75204957-6b6c3b00-5740-11ea-800f-6628f7138447.png">
> 
> `systemGroupedBackground` is used for the primary view, then if you present a view on top, it will inherit `secondaryGroupedBackground`, then `tertiary` and so on.
> 
> My Contacts app does do this when adding a new contact as well as changing the group.

Gotcha. Didn’t notice this before either 😅 Was referring to the individual contacts pages 
![0775F41B-C448-492C-909E-A969B367A3CD](https://user-images.githubusercontent.com/51668635/75205091-231a4080-5773-11ea-89e8-cb1e6d4bf5bc.png)

**Comment by worldlydev** [comment]
Still think it would be better the other way though as it is still fundamentally a settings page and not an account page of sorts.

I get your point however and understand if you feel otherwise.

**Comment by worldlydev** [comment]
Comment for others who perhaps want the same style dark mode.

- Install spectrum from: https://skitty.xyz/repo/
- Go into settings and select the default dark mode.
- Enable it for Zebra.
