### ISSUE TITLE
Zebra crashes when adding repo with space in front

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#891]
**Describe the bug**

I pasted in a repo with a space in front of it by accident and Zebra crashed.

**To Reproduce**

Paste in any repo with a space in front of it. For me it was:
“ https://beta.apptapp.me/“

**Expected behavior**

Zebra should ignore the space in front as if it wasn’t even there.

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 1-1 
 - Device Type [e.g. iPhone or iPad]: iPhone 11 Pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: uncover 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

https://ghostbin.co/paste/bzbeu
https://ghostbin.co/paste/swyam

**Additional context**

**Comment by eve0415** [comment]
When the url doesn’t start with “https” or “http” or “ftp” it will crash

**Comment by worldlydev** [comment]
> When the url doesn’t start with “https” or “http” or “ftp” it will crash

It started with https://. The exact thing I pasted in is above.

**Comment by eve0415** [comment]
No you have a space before “https”. I mean that you have to start with “https” “https” “ftp”. Trying to add for example, “www.apple.com” (I don’t think anyone will try that) will make it crash. “https” “http” “ftp” is the key to import source

**Comment by worldlydev** [comment]
> No you have a space before “https”. I mean that you have to start with “https” “https” “ftp”. Trying to add for example, “www.apple.com” (I don’t think anyone will try that) will make it crash. “https” “http” “ftp” is the key to import source

Okay. In that case this is a feature request and not a bug report. Optimally Zebra would just automatically remove the space from the front like any modern browser would. If not it should still be able to match Cydia which doesn’t crash and instead shows this error:
![3092F8C4-416F-413E-AB77-74CB04C383D8](https://user-images.githubusercontent.com/51668635/75209914-e274f400-577f-11ea-98e8-cf691d23c7a8.png)

**Comment by wstyres** [comment]
Fixed as of e3e4642ecf6f86a364c5cbf12b846c3d8b35087d.
