### ISSUE TITLE
Zebra crash

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#892]
**Describe the bug**

Zebra crashes when installing a .deb file if the proper dependencies aren’t installed beforehand.

**To Reproduce**

Install mobilegoosemodule from: https://github.com/captinc/MobileGooseModule/releases/download/v1.0.2/com.captinc.mobilegoosemodule_1.0.2_iphoneos-arm.deb without installing mobilegoose first.

**Expected behavior**

Not crash. 

**Screenshots**

![21CE86E9-3C5C-4433-BC43-FD8B731E98BE](https://user-images.githubusercontent.com/51668635/75245758-a74de180-57ce-11ea-9995-b331162d7ecb.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta1-1
 - Device Type [e.g. iPhone or iPad]: iPhone 11 Pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: uncover 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

https://ghostbin.co/paste/ejded

**Comment by wstyres** [comment]
I don't think this has to do with installing a package at all. It looks like Zebra is trying to load the sections of a repo that was not loaded (repo was down or something similar) are you sure that this is the right crash log?

**Comment by wstyres** [comment]
Also, was this package installed from a deb or through a repo?

**Comment by worldlydev** [comment]
> Also, was this package installed from a deb or through a repo?

That was the the only crash log I had so or had to be the right one. It was installed from the .Deb in the link above.

**Comment by worldlydev** [comment]
> I don't think this has to do with installing a package at all. It looks like Zebra is trying to load the sections of a repo that was not loaded (repo was down or something similar) are you sure that this is the right crash log?

Hmm... Tested multiple times and the same thing happend.

I however just retested it twice and came to the conclusion that you are probably right. There was no crash these 2 times.

Would still be nice if you could fix whatever caused the crash if possible. The less crashes people have in the future the better 😉

**Comment by wstyres** [comment]
Should be fixed as of a313c00afcdb93784e59d8aaa99867a2ed99a42a.
