### ISSUE TITLE
Swipe to remove repo icon not showing

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#893]
**Describe the bug**

I have swipe actions set to display as icons but the swipe to remove repo option says remove instead of showing the X-icon.

**Screenshots**

![7EC6220A-54BF-4C7A-9ABC-4A99B5616E7B](https://user-images.githubusercontent.com/51668635/75255849-e25a1000-57e2-11ea-9918-25d789fca26c.jpeg)

Device Information (please complete the following information):

iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
Zebra Version [e.g. 1.0~beta1 or beta1]: 1.1 beta1-1
Device Type [e.g. iPhone or iPad]: iPhone 11 Pro
Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: uncover

**Comment by wstyres** [comment]
Fixed as of 039cf20c7c20dddf431556aaffc7832214db79df.
