### ISSUE TITLE
Cydia Sign in to Google

### ISSUE THREAD

**Issue by andveg38** [wstyres/Zebra#894]
**Describe the issue **
When signing into Google in Cydia, once I login, it prompts to open Zebra. Unable to login now in Cydia to access my previously paid tweaks. It worked fine before Zebra was installed.

**To Reproduce**
Have Zebra and Cydia installed. Login to Google in the accounts section. 

**Expected behavior**
Reopen Cydia instead of Zebra or ask which one. 

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.7
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
This is a bug fixed in the 1.1 beta, if you'd like to get the beta you can try it out at https://getzbra.com/beta/ or you can wait for the full 1.1 version.
