### ISSUE TITLE
Cannot install packages with Epoch versions

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#895]
**Describe the bug**
I found out that Zebra cannot handle some package which has improper version number.
ex) 1:4.2, 1:5

**To Reproduce**
Try to install some package that has a improper version number.

**Expected behavior**
Can install or update normally.

**Additional context**
I think this should explain why some people cannot install package like flex 3 beta which version number is 1:3~beta86 ( #867 )

**Comment by wstyres** [comment]
Interesting, these `:` are called epoch versions, could you find another package with an epoch version and report back if you can install it? If you can't I'll close #867 in favor of this one.

(you can usually find a few of them on Bingers repo)

**Comment by eve0415** [comment]
Oh, I didn’t know that.
Before reporting this I was trying to install coolcc from packix and I couldn’t. Relevance with coolcc and flex 3 beta was this epoch version. I’ll try to find another one with epoch

**Comment by eve0415** [comment]
I tried a few from Bingner’s repo and I can confirm Zebra cannot install package with epoch version

**Comment by wstyres** [comment]
Should be fixed as of 534ed6a43a10d012c1e0da78b12076d12c50e147. Was able to install the Flex 3 beta.
