### ISSUE TITLE
Community news not showing 

### ISSUE THREAD

**Issue by joeellis05** [wstyres/Zebra#896]
Community news not working

I turned it on in settings but nothing changed restarting the app or respringing did it work. 

The Community news will show at the top
R/Jailbreak on reddit will show at the top of the home page.

**Device Information (please complete the following information):**
 - iOS Version / 13.3.1
 - Zebra Version - 1.0.7 
 - Device Type - iPhone x
 - Jailbreak - Checkea1n

**Comment by wstyres** [comment]
Community News will show on the Changes page, are you looking there or on the home page?

**Comment by wstyres** [comment]
Closed due to inactivity.
