### ISSUE TITLE
Unable to install Flex 3 Beta

### ISSUE THREAD

**Issue by PlanetAaron** [wstyres/Zebra#898]
**Describe the bug**
Unable to install Flex 3 beta from the delta repo

**To Reproduce**
- Add getdelta.co as a repo to zebra
-Attempt to install flex 3 beta

**Expected behavior**
Package installs as normal 

**Screenshots**
![61D6A72B-B674-475F-B96F-1ADEB5C8E6F3](https://user-images.githubusercontent.com/9359285/75315056-2f5fd580-5827-11ea-92fb-192585baac88.png)

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.0.7
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type: Unc0ver 

**Crash Log or System Log**
No crash log was created

**Comment by wstyres** [comment]
Please see #895 for more information.
