### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by aestheticsglowexe** [wstyres/Zebra#899]
**Describe the bug**
Lagging when scrolling up and down in the sources tab.

**To Reproduce**
scroll up and down in the sources tab.

**Expected behavior**
lagging.

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.0.7
 - Device Type: iPhone 8 plus
 - Jailbreak Type: unc0ver v4.2.1

**Crash Log or System Log**
//

**Additional context**
//

**Comment by wstyres** [comment]
Could you elaborate more on the "lag" you are experiencing?

**Comment by aestheticsglowexe** [comment]
nvm it's fixed in the new release! thanks for the quick response :)!
