### ISSUE TITLE
Parsing when installing a package

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#900]
**Describe the bug**
Occasionally when installing/upgrading packages it parses all of the repos I have added. The issue with this bug is it doesn't happen all the time. 

**Expected behavior**
1. Just install the tweak in the verbose progress view.

**Screenshots**
![IMG_0215](https://user-images.githubusercontent.com/57759540/75350199-17fb0980-5874-11ea-9d98-0a22c10e6762.PNG)

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta1-1
 - Device Type: iPhone XS Max 
 - Jailbreak Type: unc0ver 4.2.1

**Additional context**
Like I said above, it doesn't happen all the time so it could be hard to diagnose.

**Comment by wstyres** [comment]
Does it happen if you add a repo to Zebra and then install a tweak right after that?

**Comment by Greigh** [comment]
It does not happen after installing a repo. It just happened when updating a tweak from Packix. Not sure how to reproduce but I’ll keep trying to reproduce it and seeing what I’m doing.

**Comment by wstyres** [comment]
@Greigh Have you experienced this again? If not I'll close the issue as I haven't seen it in awhile.

**Comment by Greigh** [comment]
@wstyres I have not. If I do again, I'll open this back up.
