### ISSUE TITLE
Tweak showing it’s installed from local repo when it gets in update

### ISSUE THREAD

**Issue by lucky13820** [wstyres/Zebra#901]
**Describe the bug**
Some tweaks show they are installed from local repo when they got updates. However, they are installed from repos that they belonged to. Once they are updated, it will show the correct repos. 

**To Reproduce**
Just refresh repos and receive updates.

**Expected behavior**
In the package panel, it should show the tweaks are installed from its repo. 

**Screenshots**
![AFB9F5D4-2A91-4AD9-BF4C-0673244CCA9A](https://user-images.githubusercontent.com/7293811/75412081-385bb000-58d6-11ea-9185-7e139ac8c489.jpeg)
Showing Batchomatic is installed from local repo in package panel. 

![930AE49E-D662-4736-BB7B-0DB6AA49F2C8](https://user-images.githubusercontent.com/7293811/75412345-0434bf00-58d7-11ea-8aa7-b3d73ba90210.jpeg)
Showing Batchomatic is from BigBoss repo in update panel. 

![6922CA8B-ED4A-4DB9-ACCF-8FB825441D53](https://user-images.githubusercontent.com/7293811/75412186-96889300-58d6-11ea-91b3-aebdec132f19.jpeg)
Showing Lynx is from Twickd repo in update panel. 

![D9F93B57-B0D1-478B-926D-1B788E52ABA5](https://user-images.githubusercontent.com/7293811/75412202-9b4d4700-58d6-11ea-9853-64bb17e31db6.jpeg)
Showing Lynx is installed from local repo in package panel. 

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta1~1
 - Device Type [e.g. iPhone or iPad]: iPhone XS Max 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
This is likely due to the previous version of the package being removed from the source once it receives an upgrade. I'll look into this for the next beta.

**Comment by wstyres** [comment]
I think I might have fixed this somewhere along the way when fixing some other issues. Should be fixed for the next beta.
