### ISSUE TITLE
Description mismatch on Chinese Sources

### ISSUE THREAD

**Issue by Daemon008** [wstyres/Zebra#902]
Hi. In some Chinese sources, the description of a tweak shows a mismatch.

For example:
https://repo.cydiabc.top

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Not sure what you mean by description mismatch, could you elaborate or provide screenshots?

**Comment by Daemon008** [comment]
![1](https://user-images.githubusercontent.com/41889488/75475391-ae920c80-59d3-11ea-866b-de96c10dd431.PNG)
![2](https://user-images.githubusercontent.com/41889488/75475403-b05bd000-59d3-11ea-95a7-7d7be4aadb29.PNG)

1.PNG    1.0.7

2.PNG    1.1beta1

**Comment by wstyres** [comment]
Oh I see, it is not loading the same webpage as before?

**Comment by Daemon008** [comment]
Yes, expect this problem to be fixed. I really enjoy using Zebra. Thank you.

**Comment by wstyres** [comment]
I cannot do much to Zebra to fix this problem. I would suggest contacting the repository and asking them if they can add support for Zebra to their depictions and hopefully they will fix the issue.
