### ISSUE TITLE
Crash while copying and pasting a link into the dialogue to add a repo

### ISSUE THREAD

**Issue by p1neapplecfw** [wstyres/Zebra#904]
**Describe the bug**
Tried to copy and paste a link into Zebra for it to add a repo

**To Reproduce**
Copy and paste the creaturesurvive repo into the url dialogue for adding the repo

**Expected behavior**
For it to add the repo properly

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.1 Beta 1-1
 - Device Type [e.g. iPhone or iPad]:  iPhone X (iPhone 10,3)
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Crash Log or System Log**

https://pastebin.com/tzedBw0s

**Comment by eve0415** [comment]
Maybe you had a space before the source url. Try again and make sure that source url is right.

**Comment by wstyres** [comment]
Does look similar to #891, this should be fixed in the next beta.
