### ISSUE TITLE
Can’t install and delete tweaks

### ISSUE THREAD

**Issue by vincent2310** [wstyres/Zebra#905]
![5B6D1BA2-1293-4FE2-9044-55626AFA3F9B](https://user-images.githubusercontent.com/61594270/75564384-50554000-5a4c-11ea-970d-9808a221687f.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [e.g. iPhone or iPad]: 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
reinstall Zebra

**Comment by vincent2310** [comment]
I’ve tried to reinstall zebra. After the latest update I get this error

**Comment by wstyres** [comment]
are you using Chimera?

**Comment by vincent2310** [comment]
Yes

**Comment by vincent2310** [comment]
iPhone iOS 12.1.2

**Comment by wstyres** [comment]
Read more [here](https://github.com/wstyres/Zebra/issues/888#issuecomment-592612926)
