### ISSUE TITLE
Depiction issue opening in separate window

### ISSUE THREAD

**Issue by Greigh** [wstyres/Zebra#906]
**Describe the bug**
Repos are opened in a separate page. This happens on all repos not just the one shown in the screen record. 

**To Reproduce**
1. Open any package in Zebra
2. Then it brings to package page 
3. Then it opens depiction in separate webpage. 

**Expected behavior**
Open depictions below package info. 

**Screen Record**
https://media.discordapp.net/attachments/572784833714192395/683046392633098242/video0.mp4

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta 2
 - Device Type: XS Max
 - Jailbreak Type: unc0ver

**Comment by lucky13820** [comment]
I have same issue, on same device and version.

**Comment by rctfan929** [comment]
Same on iPhone 6s iOS 12.4

**Comment by worldlydev** [comment]
Can confirm this issue. 13.3 iPhone 11 pro. Latest beta.

**Comment by wstyres** [comment]
Should be fixed as of db900ba6ae05d89c0160e9eab7c54cd04b084a73
