### ISSUE TITLE
Make opening cydia:// and sileo:// links an option! 

### ISSUE THREAD

**Issue by BeanieBen9990** [wstyres/Zebra#907]
I used this all the time when it was a feature! I don’t have sileo and I use zebra primarily. If I needed a repo added in cydia it would be because zebra wasn’t working for some reason, which almost never happened. Now I have to manually copy the link that cydia opens to zebra every time I add a repo! This feature was great and it would be so much better to have an option to turn this off instead of forcing those who used this often to not be able to at all!

**Comment by wstyres** [comment]
Read here for more information https://github.com/wstyres/Zebra/issues/887#issuecomment-590091420
