### ISSUE TITLE
[Bug]  Since 1.1b1, I cannot block updates for packages that aren’t installed (e.g. repo icon packages)

### ISSUE THREAD

**Issue by exodia9610** [wstyres/Zebra#908]
**Describe the bug**
Swiping on the updates that aren’t installed, only show the “Install” button, and no “manage” or “block update” button.

**To Reproduce**
Add a repo with a repo icon package (http://apt.iphone4.tw/)

**Expected behavior**
To be able to block these unnecessary updates that i don’t need.

**Screenshots**
![36430C06-DA65-40C0-B660-D6B403AAF77A](https://user-images.githubusercontent.com/25361391/75589081-090f9380-5ace-11ea-8fa2-486d3348204d.png)
![EE17956A-0340-4596-BE26-FC52F6CDEE3C](https://user-images.githubusercontent.com/25361391/75589089-0dd44780-5ace-11ea-88eb-de64c5ba7392.png)

Device Information:

 - iOS Version: 13.3
 - Zebra Version: 1.1b2
 - Device Type:  iPhone XR
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by PoomSmart** [comment]
Fixed as of 0fc6afe5006efb133ea2e022c1f8367c214803f3
