### ISSUE TITLE
Multiple results

### ISSUE THREAD

**Issue by VodkaMann** [wstyres/Zebra#909]
**Describe the bug**

When searched something results will multiply
**To Reproduce**
1. Search for something

**Expected behavior**

Not multiply

**Screenshots**
If applicable, add screenshots to help explain your problem

![](https://cdn.discordapp.com/attachments/572784833714192395/683065908956364878/image0.png)

**Device Information (please complete the following information):**
 - iOS Version [12.1.1]: 
 - Zebra Version [1.1 beta 2]: 
 - Device Type [iPad7,3]: 
 - Jailbreak Type [unc0ver]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
It looks like this search result are showing all the versions of that package in the database
