### ISSUE TITLE
Accent color not applying

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#911]
**Describe the bug**

Accent color not applying.

**Screenshots**

Screenshots:
![ADB54F04-D72E-4761-AB89-54DDB6E65859](https://user-images.githubusercontent.com/51668635/75591603-6aa91100-5a80-11ea-85e4-2c8c495f5a5e.jpeg)
![6CAE69C5-F802-46BA-8B92-D78186C7ACF6](https://user-images.githubusercontent.com/51668635/75591615-6f6dc500-5a80-11ea-9e4f-bcbd3b10f901.jpeg)
![548D5298-7D66-45B6-84CF-56903A04C59B](https://user-images.githubusercontent.com/51668635/75591989-70532680-5a81-11ea-8bdc-088addf5545d.jpeg)

Screen recording:
https://imgur.com/a/2qZcvRx

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 2 
 - Device Type [e.g. iPhone or iPad]:  iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Comment by wstyres** [comment]
White is the default tint color (when not using a custom accent color) for that progress bar

**Comment by worldlydev** [comment]
> White is the default tint color (when not using a custom accent color) for that progress bar

I'm using the system colors. Shouldn't it be the system blue color then?

**Comment by wstyres** [comment]
Just as the switches are not blue, that progress bar doesn't default to the blue tint color, I will fix the background of the button and the tint color for the search bar.

**Comment by worldlydev** [comment]
> Just as the switches are not blue, that progress bar doesn't default to the blue tint color, I will fix the background of the button and the tint color for the search bar.

So the progress bar not defaulting to blue won't be changed?

Also the cursor thing isn't just in the search bar FYI. Don't know is you know our not 😅 also applies to the other places. Like when typing in the add repo field.

**Comment by worldlydev** [comment]
Also applies to the cancel button for the repo import view.

![1A6DA09A-46A1-4E9F-9232-933D9918C3AA](https://user-images.githubusercontent.com/51668635/75595028-28d19800-5a8b-11ea-921e-0436aac11ef5.jpeg)

**Comment by worldlydev** [comment]
![38B3FCCE-3585-4E68-8E6F-B84CEA94BA79](https://user-images.githubusercontent.com/51668635/75616506-356cf380-5b52-11ea-9fe0-bd7334f8a4cd.jpeg)

**Comment by rctfan929** [comment]
The background of the button adjusts correctly for all tints except for system default.

iPhone 6s iOS 12.4

**Comment by worldlydev** [comment]
This issue isn't fixed in the latest beta. Zebra 1.1 ~ beta 5
Using the system accent color some up elements are still pastel people while others aren't colored at all.

**Cursor**
![129AA4A5-88E0-4FB4-BE29-9CB85D0CD568](https://user-images.githubusercontent.com/51668635/79153122-a2b8a900-7dcd-11ea-946d-986c21e0d841.png)
![85B1DD40-287F-4630-8C15-945F00B7A8FF](https://user-images.githubusercontent.com/51668635/79153125-a64c3000-7dcd-11ea-83a5-9f2c66994e20.png)
**Cancel button in source refresh view**
![AC2A7865-F28C-4E5E-BF7C-74E2E8AF6E2E](https://user-images.githubusercontent.com/51668635/79153202-c4199500-7dcd-11ea-851c-ab962fd20a88.png)
**Console progress bar**
![3C0DC101-A3DE-4FD2-B0BD-76E3F52AE96B](https://user-images.githubusercontent.com/51668635/79153288-e6abae00-7dcd-11ea-88e1-6d2eec6ee14a.png)
**Console respring and close Zebra button**
![9F4FBF3B-B5E0-43C6-8E9B-5FE9D4B29795](https://user-images.githubusercontent.com/51668635/79153416-1a86d380-7dce-11ea-96a6-ea9b2dc86564.png)
**Reddit article buttons and loading bar**
![561F585F-AD76-4C37-BE1E-897BDA30EF52](https://user-images.githubusercontent.com/51668635/79153487-38eccf00-7dce-11ea-8607-7ae3b3448c87.png)

**Comment by wstyres** [comment]
Not sure why this was marked as scheduled, I did not fix the issues.

**Comment by wstyres** [comment]
I went through and fixed all the ones I could see in the screenshots, the last three you posted seem to be blue already though I can't tell. Let me know when the next beta rolls around.

**Comment by wstyres** [comment]
@worldlydev double check to make sure these issues aren't present anymore

**Comment by worldlydev** [comment]
> @worldlydev double check to make sure these issues aren't present anymore

The progress bar is white and unaccented, the close/respring button is now white instead of blank but is still not accented, and the cancel button in the source refresh view is white and unaccented.


![B1592C60-0AB7-498C-8A83-0F461E7570F8](https://user-images.githubusercontent.com/51668635/80315167-2e7efc00-87f6-11ea-96a8-123d789b02f9.png)
![63AC1CED-35FB-4E8C-ADA3-B6AC1EF9B75C](https://user-images.githubusercontent.com/51668635/80315168-2f179280-87f6-11ea-8cc5-004c0922f125.png)
![BC50EB97-3CBA-421F-9D75-4EF992923A5A](https://user-images.githubusercontent.com/51668635/80315166-2a52de80-87f6-11ea-9994-e6cebd4509ac.jpeg)

**Comment by wstyres** [comment]
Those buttons and the progress bar are to be tinted white when "Use System Accent Colors" is turned off

**Comment by worldlydev** [comment]
> Those buttons and the progress bar are to be tinted white when "Use System Accent Colors" is turned off. But I'll tint the cancel/complete button blue

But I have use system accent colors turned on.

**Comment by eve0415** [comment]
Also me, using system color and darkmode (not pure dark mode)

**Comment by wstyres** [comment]
Meant to say when turned off, progress bar and console bar buttons should be white. The button will be blue though.
