### ISSUE TITLE
Light background in search with dark mode

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#912]
**Describe the bug**

When typing fast or typing in a tweak name that doesn't exist the background displayed in the back is white. Even when in dark mode.

**Expected behavior**

Properly themed

**Screenshots**

![AF56F3C8-0588-4648-8CF0-C3AC1CA1FA51](https://user-images.githubusercontent.com/51668635/75592437-9e853600-5a82-11ea-9e4e-8864a55323d7.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 2
 - Device Type [e.g. iPhone or iPad]: 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Unc0ver

**Comment by wstyres** [comment]
Should be fixed as of b058aafe021b49df8eb6380430035590d74ccaf1
