### ISSUE TITLE
Reset sources button in advanced settings

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#914]
![625D62CF-E956-487D-8E08-E26BE4785831](https://user-images.githubusercontent.com/51668635/75595228-d17ff780-5a8b-11ea-81ee-3ddaedc992cd.jpeg)

A reset sources button would be cool to have above the reset settings button, and the reset sources and settings button.

**Comment by eve0415** [comment]
I want “Open Zebra Document” back

**Comment by worldlydev** [comment]
> I want “Open Zebra Document” back

The open documents directory button?

**Comment by eve0415** [comment]
yep

**Comment by wstyres** [comment]
Not sure what you mean by a Reset Sources button?

**Comment by worldlydev** [comment]
> Not sure what you mean by a Reset Sources button?

A button that deletes sources without deleting settings.

**Comment by worldlydev** [comment]
Handy for situations like this. Instead of deleting them in Filza.
![B26C99E0-B939-46C8-8FAB-55C864003ED5](https://user-images.githubusercontent.com/51668635/76653721-88d73c80-6569-11ea-8905-ca04b4012a95.png)
So that all the sources could be deleted without resetting Zebra's settings.

**Comment by wstyres** [comment]
Implemented in 872961d515e30c788363b9c7549c70cad972b122.
