### ISSUE TITLE
Feature Request for Zebra opening cydia:// urls

### ISSUE THREAD

**Issue by Mignif** [wstyres/Zebra#919]
From what I’ve heard, the current situation is that in future updates, Zebra will stop opening Cydia:// urls, however, there are some people (including myself) who find this feature useful

A solution for this dilemma could possibly be a toggle in settings (off by default to prevent confusion for users who do not want this feature) which can allow Zebra to open cydia:// urls for those who would like that functionality.

**Comment by eve0415** [comment]
Read #887 for more information
