### ISSUE TITLE
Repo Icon does not change

### ISSUE THREAD

**Issue by relisiuol** [wstyres/Zebra#92]
**Is your feature request related to a problem? Please describe.**
Yes, when you set a new CydiaIcon, Zebra still uses the previous saved in the DB.
In fact, I tried to add support to icon URLS, so I looked on how you download repo icons & it seems the way is boggy. Indeed, there is no expiration date or something similar for a repo icon.

**Describe the solution you'd like**
Using SDWebImage, that should simplify how to fetch images.

**Describe alternatives you've considered**
Add a new column in DB containing Header Last-Modified date & compare it or just refresh after x hours.

**Additional context**
1/ Create repo, eg: yourepo.com
2/ Open Zebra
3/ Add repo
3/ Change repo icon
4/ Refresh Zebra, icon isn't up to date.

**Comment by relisiuol** [comment]
I forgot to add BUG label.

**Comment by wstyres** [comment]
We're trying to minimize the amount of dependencies that Zebra requires so I'd prefer not to use SDWebImage if I do not have to. I'll take a look at this but I think having the last modified since header would be a good solution for downloading a new repo icon.

**Comment by wstyres** [comment]
I implemented async repo icon loading in 8369b2e.
