### ISSUE TITLE
Setting the installed tab from „abc“ sorting to date sorting doesn’t save it. After relaunching the app the abc sorting is enabled again 

### ISSUE THREAD

**Issue by iM4CH3T3** [wstyres/Zebra#925]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [13.3]: 
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 
 - Device Type [iPhone 12,1]: 
 - Jailbreak Type [e.g. unc0ver13 v4.2.1]: 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
Read #883 for more information
