### ISSUE TITLE
Filter package type

### ISSUE THREAD

**Issue by twolfer** [wstyres/Zebra#926]
**Is your feature request related to a problem? Please describe.**
Edit the types of packages shown, such as not seeing any themes or widgets. 

**Describe the solution you'd like**
On the list tab, and edit or filter button that then allow me to uncheck package types. 

**Describe alternatives you've considered**
If I really hated myself, Cydia. 
With all the respect to Saurik 

**Additional context**
None

**Comment by wstyres** [comment]
Duplicate of #868
