### ISSUE TITLE
Cydia purchase issue

### ISSUE THREAD

**Issue by qseatree** [wstyres/Zebra#927]
When I try to purchase tweak from Zebra and finished the payment through PayPal. The link provided by the tweak owner wants me to direct to Cydia to finish the purchasing but I can only redirect to Zebra unless I uninstall it so I can direct to Cydia instead. 

**To Reproduce**.

**Expected behavior**

Please let the redirect function selectable

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version [13.3]: 
 - Zebra Version [e.g. 1.06]: 
 - Device Type [e.g. iPhone XS Max]: 
 - Jailbreak Type [e.g. unc0ver,, etc.]:

**Comment by wstyres** [comment]
This bug is fixed in the latest betas of Zebra and will be in the final 1.1 version. If you'd like to try out the betas, check them out by adding our beta repo https://getzbra.com/beta/
