### ISSUE TITLE
iPad Crash when tapping the share icon in repo edit mode

### ISSUE THREAD

**Issue by rubrdcky** [wstyres/Zebra#93]
**Describe the bug**
Zebra Crashes when tapping the share icon in the repo edit mode on iPad mini 4.

**To Reproduce**
Just try it ;)

**Expected behavior**
Welp it seems that this is used to share the sources.list file. It DOES work on my iPhone 8 iOS 12.1.1

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Beta 10 
 - Device Type [e.g. iPhone or iPad]: iPad mini 4 (iPad 5,1)

**Crash Log or System Log**

[Zebra-2019-05-15-191643-1.txt](https://github.com/wstyres/Zebra/files/3184798/Zebra-2019-05-15-191643-1.txt)

**Additional context**

**Comment by wstyres** [comment]
Good catch, fixed in 31d6fcf.
