### ISSUE TITLE
Done/Restart SpringBoard/Reboot button white-out

### ISSUE THREAD

**Issue by Deja-Wu** [wstyres/Zebra#930]
**Describe the bug**
-Upon package install/removal the usually done/restart springboard/reboot button just shows a white block with not visible text.

**To Reproduce**
-Install/reinstall/remove and package and the white button will be displayed. 

**Expected behavior**
-In previous builds, the blue button with proper text is displayed. In the most recent build, 1.1~beta2-1, it is just a white block. 

**Screenshots**

![IMG_0300](https://user-images.githubusercontent.com/40847914/75733081-eb9f1d00-5cb9-11ea-8d2e-58c98cb3e237.PNG)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: Zebra 1.1~beta2-1
 - Device Type [e.g. iPhone or iPad]: iPhone XS (iPhone 11,2)
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 4.2.1

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.
-None

**Additional context**

**Comment by rctfan929** [comment]
Similar issue. Text is there with no button background.
![90D67DDD-B9B7-4717-A669-EB239CFB1021](https://user-images.githubusercontent.com/46878212/75938866-c72c7780-5e56-11ea-9df8-8dc07b6aad7c.png)

**Comment by wstyres** [comment]
Fixed as of 1f298b3fdc68d88186a7c47dd65ba91f38bc3ba1

**Comment by rctfan929** [comment]
Issue still exists in latest version.

**Comment by wstyres** [comment]
@rctfan929 Which accent color do you have selected?

**Comment by rctfan929** [comment]
System default

**Comment by worldlydev** [comment]
Same issue I'm having in #911

**Comment by wstyres** [comment]
I'll move the conversation to #911 then
