### ISSUE TITLE
Crash on opening 1.1~beta2

### ISSUE THREAD

**Issue by justin-shepherd** [wstyres/Zebra#932]
**Describe the bug**
Upon opening Zebra 1.1~beta2, the application will crash to springboard immediately.
I have to downgrade back to 1.0.7 which was my last working version.

I can reproduce this in all three iterations I tested this in
- All Tweaks Enabled
- All Tweaks Disabled Fully
- All Tweaks Disabled (Except for Cephi and Cr4shed)

**Error:**
Exception type: NSInvalidArgumentException
Reason: -[__NSCFString replaceOccurrencesOfString:withString:options:range:]: nil argument
Culprit: Unknown

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta2 (beta1 is also affected)
 - Device Type: XS Max (iPhone11,6)
 - Jailbreak Type: unc0ver 4.2.1

**Crash Log or System Log**

Cr4shed Logs
[TweaksEnabled.txt](https://github.com/wstyres/Zebra/files/4281035/TweaksEnabled.txt)
[TweaksDisabled.txt](https://github.com/wstyres/Zebra/files/4281036/TweaksDisabled.txt)

System Log
[Zebra-2020-03-03-223639.txt](https://github.com/wstyres/Zebra/files/4281065/Zebra-2020-03-03-223639.txt)

Happy to do any other additional testing, just let me know.

**Comment by wstyres** [comment]
Does 1.1~beta2-1 experience the same crash?

**Comment by justin-shepherd** [comment]
Hi @wstyres, yes, I thought that is the version I was reporting. Beta 1 and 2 yield the same crash. 1.0.7 was the only last working version for me.

![43947EFB-9F3D-4D55-BB15-1B42CD21F673](https://user-images.githubusercontent.com/4710051/75784319-271f1180-5db6-11ea-8d1e-90b77638dce9.png)

**Comment by wstyres** [comment]
Do you happen to have another crash log from cr4shed or Crash Reporter? The one you gave looks like its from the iOS Settings app which is not symbolicated.

**Comment by justin-shepherd** [comment]
sure thing, this is one I was able to produce now
https://pastebin.com/yAL33PBN

**Comment by wstyres** [comment]
Thank you, could I also get a list of repositories you use with Zebra?

**Comment by justin-shepherd** [comment]
Sure thing
https://pastebin.com/mAxp75fV

**Comment by wstyres** [comment]
Thanks, I'll take a look at this when I get the chance

**Comment by justin-shepherd** [comment]
Thanks mate, When I get home in about an hour I’ll do some further troubleshooting, I’ll try and restore rootfs too

**Comment by wstyres** [comment]
I don't think that a restore fs is necessary, I think that one of your sources is causing the error.

**Comment by justin-shepherd** [comment]
Okay, I did a bit of testing.

I cleared all repos on 1.0.7 and only left the zebra repo remaining. I then proceeded to upgrade to 1.1~beta2-1 and it opened perfectly fine.

Next test was keeping all the repos I had already, upgrading from 1.0.7 

### Scenario 1 (Works)

1. Zebra 1.0.7 (only contains the getzbra repo)
2. Upgrade to 1.1~beta2-1
3. Open Zebra 1.1~beta2-1 (Success)

### Scenario 2 (Works)
1. Zebra 1.0.7 (only contains the getzbra repo)
2. Upgrade to 1.1~beta2-1
3. Open Zebra 1.1~beta2-1 (Success)
4. Added all my previous repos to the sources.list after an upgrade and zebra was able to launch successfully.

### Scenario 3 (Crash)

1. Zebra 1.0.7 (containing repos https://pastebin.com/mAxp75fV)
2. Upgrade to 1.1~beta2-1
3. Open Zebra 1.1~beta2-1 (Crash)

### Scenario 3 (Works)
1. Same as scenario 3, however, after updating to 1.1~beta2-1 (it crashed on launch), I ssh'd in and deleted the zebra.db file.
2. Reopened Zebra 1.1~beta2-1 successfully and the application started synchronizing the sources.

I'm not entirely sure why the issue only presents itself by upgrading 1.0.7 to 1.1~beta2-1, I've attached both of the xyz.willy.Zebra directories from before and after the upgrade if that helps.

[zbra-1.0.7.zip](https://github.com/wstyres/Zebra/files/4284561/zbra-1.0.7.zip)
[zbra-1.1beta2-1.zip](https://github.com/wstyres/Zebra/files/4284562/zbra-1.1beta2-1.zip)

Either way, it's working now, If you're able to see anything with those files great, otherwise I'm happy to close this off and monitor it moving forward and report it if it happens again if you like.

**Comment by PoomSmart** [comment]
Sanity check mitigation: c27d39e13d7f41b00e96daeb44254c1e66f48cec
