### ISSUE TITLE
Negative download size in queue

### ISSUE THREAD

**Issue by absidue** [wstyres/Zebra#933]
**Describe the bug**
When a source supplies a blank download size in the `Packages` file, Zebra shows a download size of -1.00 bytes in the queue.

**To Reproduce**
Add Cartella Version 0.6.0 to the queue
Source: https://burrit0z.github.io/repo

**Expected behavior**
The download size not to be displayed or an error text to be shown in it's place.

**Screenshots**
![B3DC24F6-F1BD-40A1-A22C-AC32B1A5E46D](https://user-images.githubusercontent.com/48293849/75814733-8d923880-5d92-11ea-8126-c7d77b7acfa4.png)
![F1C5E3C9-D70B-4BE2-B6C3-3155E173D486](https://user-images.githubusercontent.com/48293849/75814870-c7633f00-5d92-11ea-8bdd-78e513553765.png)

**Device Information (please complete the following information):**
 - iOS Version: 13.3.1
 - Zebra Version: 1.1~beta2-1
 - Device Type: iPhone
 - Jailbreak Type: checkra1n

**Comment by wstyres** [comment]
Well, it does look like the Installed-Size is left blank for some reason. That is likely a maintainer issue but I'll probably implement something to put a 0 value in place.

**Comment by wstyres** [comment]
Fixed as of 3f32cae0e5d2f2cd35e47e0394cb7edea2317889
