### ISSUE TITLE
Enable: "@media screen and (prefers-color-scheme: dark)" query for descriptions

### ISSUE THREAD

**Issue by rio-doro** [wstyres/Zebra#935]
**Is your feature request related to a problem? Please describe.**

The "@media screen and (prefers-color-scheme: dark)" query isn´t working at Zebra. 
I have optimized my descriptions to accept the darkmodes but sadly the zebra darkmode isn´t recognized by them:
[Description](http://repo.rio-doro.eu/html/eu.rio-doro.carplayclassic.deb.php)
[Video demo at MobileSafari](http://rio-doro.eu/site/downloads/RPReplay_Final1583498040.MP4)
[Description at Zebra with system and zebra darkmode enabled](http://rio-doro.eu/site/downloads/image0.png)
[VideoandScreenshot_Zipped](https://github.com/wstyres/Zebra/files/4298371/Darkmode.zip)

**Describe the solution you'd like**
It would be cool if the @media screen and (prefers-color-scheme: dark) query would recodnize if the Zebra darkmode is enabled or not.

**Describe alternatives you've considered**
Maybe its enought to let the query recodnize the system darkmode

**Comment by absidue** [comment]
The CSS media queries work for the system dark mode (tested on my device with your repo) (default iOS behaviour). It would probably be a lot more effort than it's worth to change iOS' CSS engine just to make it work with Zebra's dark mode. It's easier to use one of the following methods:

- Reading the header on the server side see [wiki](https://github.com/wstyres/Zebra/wiki/Repositories#dark-mode)
- Parsing the user agent in JavaScript

**Comment by rio-doro** [comment]
Thanks for your respond, i will take a look at this :)

**Comment by rio-doro** [comment]
> 
> 
> The CSS media queries work for the system dark mode (tested on my device with your repo) (default iOS behaviour). It would probably be a lot more effort than it's worth to change iOS' CSS engine just to make it work with Zebra's dark mode. It's easier to use one of the following methods:
> 
>     * Reading the header on the server side see [wiki](https://github.com/wstyres/Zebra/wiki/Repositories#dark-mode)
> 
>     * Parsing the user agent in JavaScript

I´ve got finally the javascript working,

```
if(navigator.userAgent.match(/Dark/)){
document.write('<link rel="stylesheet" type="text/css"       href="_css/darkmode_zebra.css">');
}
else {
document.write('<link rel="stylesheet" type="text/css"       href="_css/style.css">');
  }
```

But if i add 
```
if(navigator.userAgent.match(/Dark/)){
document.write('<link rel="stylesheet" type="text/css"       href="_css/darkmode_zebra.css">');
}
```
between the first if and else it doesn´t work anymore.. after hours of testing i think it is because the oled userAgend is called "Dark Oled" and not just "Oled" that causes an error because Dark is even in the first case represented. Maybe its possible to change that to just "Oled"?

**Comment by rio-doro** [comment]
I will close this topic because its partially working for me.
But maybe i can help other users with my code:

Javascript that requests the userAgent:
```
if(navigator.userAgent.match(/Dark/)){
document.write('<link rel="stylesheet" type="text/css"       href="darkmode_zebra.css">');
}
else {
document.write('<link rel="stylesheet" type="text/css"       href="style.css">');
  }
```

Header of my descriptions:
```
<head>
    <title>repo.rio-doro.eu</title>
    <meta charset="UTF-8">
    <meta content="width=device-width,initial-scale=1" name="viewport">
    <meta content="initial-scale=1,user-scalable=no,maximum-scale=1" name="viewport">
	<script src="_js/user_agend_darkmode.js"></script>
</head>
```
