### ISSUE TITLE
Please delete the language support for zh-Hant-HK.lproj [Chinese (Tradtitional)-Hong Kong]

### ISSUE THREAD

**Issue by terry3041** [wstyres/Zebra#936]
As a Hong Kong user, zh-Hant-HK is almost exactly the same as zh-Hant with few minor differences. 
However, zh-Hant-HK.lproj has not been updated since Zebra beta. 
It is inconvenient to Zebra users in Hong Kong as they have to either use a broken translation or to manually delete zh-Hant-HK.lproj and use zh-Hant.lproj to have a completely translated Zebra. 
Therefore, I kindly request you to delete the language support for zh-Hant-HK.lproj.

**Comment by worldlydev** [comment]
Personally feel that deleting a partially translated language is a waste as somebody would have to translate from the bottom up if they want to translate to their language.

Wouldn’t #680 fix this issue for you?

**Comment by terry3041** [comment]
No actually they are the same language. 
It's like the difference between English [en] and English (United State) [en-US].

**Comment by worldlydev** [comment]
> No actually they are the same language.
> It's like the difference between English [en] and English (United State) [en-US].
> Why bother to maintain two lproj when they are 99% the same?
> 
> Sorry for my bad presentation as English is not my first language.

Oh. Could still see why somebody would like to have their variant. There is a difference in proper English and American English just as in the Mandarin used in the mainland and the Mandarin used in Taiwan.

But tbh I don’t know how different mainland and Hong Kong is. If they aren’t that different why not just copy the missing strings from the other lproj? I could probably do it for you if you want me to. That way if somebody wants their Chinese variant they can always update it later.

**Comment by wstyres** [comment]
Hong Kong Chinese was originally added at the request of the original translator but I believe it was removed when the translator said that they were roughly the same as @terry3041 stated above. The file hasn't been updated since beta24 and it is pretty out of date. I removed it from CrowdIn around beta 24 but I suppose I forgot to remove the translation file. I can do this for the next beta.

**Comment by terry3041** [comment]
Thank you very much @wstyres .
