### ISSUE TITLE
For downed repo console message not taking up the entire view

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#945]
**Is your feature request related to a problem? Please describe.**
Repo going down happens more than usual now, and it keeps disturbing what user is doing on Zebra, like searching after launched the app without waiting refresh sources finish. This will interupt/cut-off whatever user is doing at that time (like typing on keyboard) after the repo downed console popped up.

**Describe the solution you'd like**
Perhaps just a small window like the queue that displayed on the bottom, and fades over time. Installer 5 dealt with this elegantly by just display a red marking on the repo sources.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by wstyres** [comment]
This has been implemented and will be in the next 1.2 beta, sources with errors will show up beside the sources name rather than opening a popup

**Comment by yur1xpp** [comment]
Thanks @wstyres, the features I'm so anticipated for. I constantly gets obstructed by the downed console message in the past few months. Some servers are just constantly down.
