### ISSUE TITLE
Flex 3 beta is not installing

### ISSUE THREAD

**Issue by yur1xpp** [wstyres/Zebra#946]
**Describe the bug**
Flex 3 beta will not be installed, 0 package is being installed/upgraded. 

**To Reproduce**
Install/reinstall flex 3 beta

**Expected behavior**
Got installed

**Screenshots**
![3C92BDA6-7C3D-476C-9E41-547813C90EFE](https://user-images.githubusercontent.com/34767893/76480785-b8435780-644a-11ea-9afc-e9b2337f1a32.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.0.7
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
Please use the beta. It’s already fixed.

**Comment by wstyres** [comment]
Use the beta at https://getzbra.com/beta/

**Comment by yur1xpp** [comment]
Ah okay, didn't know it was fixed on the latest beta. I'll stick with the stable version for now though, since the sorting of package is not working for me on the beta (when I last try). Thanks!
