### ISSUE TITLE
Search URL Scheme

### ISSUE THREAD

**Issue by MartinsZar** [wstyres/Zebra#949]
**Is your feature request related to a problem? Please describe.**
It would be cool if we could search in Zebra with URL Schemes (I know that zbra://search/ exists but you aren't actually able to search with it only open the Search page). This would searching with shortcuts/siri make possible and who doesn't want to search pakages with siri?

**Describe the solution you'd like**
Extending the depth of zbra://search/ so we can use zbra://search/Shortlook (zbra://search/{input}) to search.

**Describe alternatives you've considered**
I think that the solution mentioned before is simple enough to implement.

**Additional context**
How it could work: https://drive.google.com/file/d/1rjYrLWi-IOJ_ACWIr_7r0IoExiVktsMh/view?usp=drivesdk
What could be possible: https://drive.google.com/file/d/1Jg4E-ZAQ6s5LjlUpcHcjIb_eluhE-b-X/view?usp=drivesdk

**Comment by wstyres** [comment]
I believe this is a bug in the betas that this does not work, I'll have it fixed for the next beta.

**Comment by wstyres** [comment]
Fixed as of 6a44bdc67d68e1ddf6be19af9c1cc0c8e266c2eb

**Comment by MartinsZar** [comment]
Thank you for your quick response and fix!
