### ISSUE TITLE
Sources unable to loaded 100% and crashes

### ISSUE THREAD

**Issue by sadalhayat** [wstyres/Zebra#951]
**Describe the bug**
Sources unable to loaded 100% when refreshed, and it crashes when I tried to load 100% manually.

**To Reproduce**
1. Open Zebra and refresh
2. Open Sources tab
3. Open repo BigBoss and Packix
4. Open All Packages
5. See the % loaded on top right, it shown 5% and 7% for me.
6. Tapping on it several times to try to load 100%
7. It crashes before reach 100%

**Expected behavior**
All sources list should be loaded 100% automatically when refreshed.

**Video**
https://telegra.ph/file/27859de43def958288f35.mp4

**Device Information (please complete the following information):**
 - iOS Version : 13.3
 - Zebra Version : 1.1~beta2 (also Stable ver)
 - Device Type : iPhone XS
 - Jailbreak Type : unc0ver 4.3.1

**Crash Log or System Log**
https://pastebin.com/0M8iw5sW

**Additional context**
(Add any other context about the problem here.)

**Comment by PoomSmart** [comment]
Possible fix as of bdf63e7b54f54d28d96b90bd5c06a4931e159bc9
