### ISSUE TITLE
Swipe actions don't exist on search UI

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#955]
Make this possible again:

![FC2FF9B6-C583-4D7B-B219-38C95E43E4D0](https://user-images.githubusercontent.com/51668635/76747055-d2e23d00-6778-11ea-95cb-629309695d53.jpeg)

It is no longer possible with the latest search interface in the betas.

**Comment by kelvin1300** [comment]
Is with the last version of zebra beta https://getzbra.com/beta/ 

v1.1~beta3-1

**Comment by wstyres** [comment]
Fixed as of 9d928fe6.

**Comment by worldlydev** [comment]
Can confirm that it's been fixed in the latest beta.
