### ISSUE TITLE
No payment screen for paid packages as dependencies

### ISSUE THREAD

**Issue by absidue** [wstyres/Zebra#957]
**Describe the bug**
When adding a tweak(Lynx Application) which has a paid package(Lynx) as a dependency to the queue no payment is shown. The user is allowed to progress all they way to the console, where they are soon greeted by an unauthorised error generated by the source.

**To Reproduce**

1. Add the Twickd source if you don't have it
2. Add `Lynx Application` to the queue
3. Tap confirm in the queue to progress to the console

**Expected behavior**
To be prompted to pay for the dependency when tapping confirm in the queue. The paid package should marked in the queue to signify that it is paid.

**Screenshots**
![EC2DE4C4-3CB5-45A5-AB51-C64756803FC9](https://user-images.githubusercontent.com/48293849/76800000-fa65f380-67d2-11ea-90de-91c21863b453.jpeg)

![1CB4B016-EB01-483E-8706-3207D732186C](https://user-images.githubusercontent.com/48293849/76799866-ae1ab380-67d2-11ea-9291-cfce81533984.jpeg)

![B81B8B78-55B4-475A-BB4D-309A41226AC4](https://user-images.githubusercontent.com/48293849/76799883-b7a41b80-67d2-11ea-8b3c-d12aabf63b80.jpeg)

**Device Information (please complete the following information):**
 - iOS Version: 13.3.1
 - Zebra Version: 1.1~beta2-1
 - Device Type: iPhone
 - Jailbreak Type: checkra1n

**Comment by wstyres** [comment]
Related to #739 so I'll consolidate there
