### ISSUE TITLE
"Importing Local Packages"

### ISSUE THREAD

**Issue by jmanpenilla** [wstyres/Zebra#96]
**Describe the bug**
When trying to install or upgrade, etc any package instead of working it says importing local packages... done importing local packages... done, and gives done button, however it did nothing. Nothing installed or anything. Applied to all packages, persistent for the last 3 betas up to b11. I tried reinstalling with clearing the documents and keeping minimal sources but the bug persists.

**To Reproduce**
Install or reinstall/ do any operation to packages in Zebra.

**Expected behavior**
The package to install etc

**Screenshots**
screen recording of the issue
https://drive.google.com/open?id=1xy4cAqmu30qhhGCfOFNUMq6MruPPHVGo

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.1.1b3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: b11
 - Device Type [e.g. iPhone or iPad]: iPhone X

**Crash Log or System Log**
Please provide a Crash Log to help me solve the issue.
No crash logs just the log in the zebra console. In video

**Additional context**

**Comment by wstyres** [comment]
It looks as if Zebra is not properly sandboxed and it cannot access any external binaries. If you uninstall Zebra, reboot, jailbreak again, and then install Zebra, does that solve the issue?

**Comment by jmanpenilla** [comment]
This solved the issue initially but after two days of normal usage, ie a couple installs and upgrades the issue came back.

**Comment by Amplespencer** [comment]
expanding on this issue, this seems to happen directly after apt finishes a package with an error

when you go back to install a package it won't work and show nothing in the queue

it will be fixed after restarting the app


this is most likely related to apt not being in a sandbox and not having priveleges lowered (somehow)


heres a video of this happening

https://share.icloud.com/photos/0yEO_6-QUdvVA7ON0BLpmd2Mw

**Comment by wstyres** [comment]
Alright, interesting. I'll see if I can reproduce this, thanks for the steps @Amplespencer

**Comment by Amplespencer** [comment]
If you need more footage it happens 100% of the time for me, also on a12 if
I didn't mention in this thread.

**Comment by Muirey03** [comment]
This is why this issue is occurring: https://github.com/wstyres/Zebra/issues/120#issuecomment-497025241

**Comment by wstyres** [comment]
Fixed as of 02882d4
