### ISSUE TITLE
Queue covers up TweakReviewsDB banner

### ISSUE THREAD

**Issue by cbendrey** [wstyres/Zebra#961]
When adding an item to the queue, the "X Packages Queued" banner appears on top of the TweakReviewsDB banner.

**Comment by absidue** [comment]
Please close this issue and open an issue with TweakReviewDB as TweakReviewsDB is not part of Zebra.

In the future please use the bug report template when creating an issue, it will give the developers a lot more information to help fix the bug. (The official GitHub app on iOS currently does not support issue templates, please use the website or a different app that supports issue templates to open file issues with Zebra.)

**Comment by absidue** [comment]
Thank you 👍
