### ISSUE TITLE
Crash after sign in to install a package already purchased

### ISSUE THREAD

**Issue by relisiuol** [wstyres/Zebra#962]
**Describe the bug**
Hello, when you already purchased a package and you sign in, it still ask to buy (ask for touch id) and crash the app.

**To Reproduce**
Buy a package, logout, click to install package, sign in, verify touch id.

**Expected behavior**
It should not ask to buy again (touch id) and not crash but add package to install queue

**Screenshots**
Video is better: https://cdn.discordapp.com/attachments/572784833714192395/691218815442354256/demo3.mov

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta2-1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
Do you have a crash log?

**Comment by wstyres** [comment]
Please test this out again on 1.1~beta4 and provide a crash log if the issue still occurs, otherwise I will close the issue.

**Comment by relisiuol** [comment]
Envoyé de mon iPhone

**Comment by wstyres** [comment]
Thanks, can I also know which package you’re testing this out on?

**Comment by relisiuol** [comment]
I'm testing on yourepo sources. I'll try to debug this myself.

https://www.yourepo.com
https://buufjuiced.yourepo.com

**Comment by wstyres** [comment]
So it looks like this may be an issue when receiving a response from the API. What json is returned to the user when they attempt to purchase a package but have already completed the purchse? I'll have to look into this more with another repo since I have no purchased packages on yourepo but it could be that this is unique to YouRepo.

**Comment by wstyres** [comment]
This should be fixed, not able to test it myself but if you'd like a build to test it out let me know.

**Comment by wstyres** [comment]
@relisiuol Can you test on the latest beta?

**Comment by relisiuol** [comment]
Fixed! Thank you so much @wstyres.
