### ISSUE TITLE
Alphabet shortcut issue

### ISSUE THREAD

**Issue by relisiuol** [wstyres/Zebra#963]
**Describe the bug**
Alphabet shortcut is buggy, also repository packages lists are only partially loaded, why?

**Expected behavior**
Show all packages.

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/691219856036724736/demo5.mp4

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1beta2-1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
Relate to #951, fixed for next beta.
