### ISSUE TITLE
Save Filter Option on Packages Tab

### ISSUE THREAD

**Issue by JakeValenzuela** [wstyres/Zebra#964]
**Is your feature request related to a problem? Please describe.**
When on the Packages tab, the filter should always default to the last selected option at the top. When I select 'Date', it will revert to 'ABC' when I restart the app.

**Describe the solution you'd like**
The option should be saved and remain the same even if users close out of the app.

**Additional context**
I'm currently on the latest beta version.

**Comment by JakeValenzuela** [comment]
I'm honestly not sure if this was intended or not as well.

**Comment by eve0415** [comment]
Duplicate of #883

**Comment by JakeValenzuela** [comment]
Oof, closing.
