### ISSUE TITLE
Crash in filters for specific sources

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#966]
https://ghostbin.co/paste/x3djz

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1-beta3
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Comment by wstyres** [comment]
Do you have any red sources in your sources list? (Sources that didn't load)?

**Comment by worldlydev** [comment]
> Do you have any red sources in your sources list? (Sources that didn't load)?

![057EA49C-2DF2-49E2-8F03-3B590F5CE7BE](https://user-images.githubusercontent.com/51668635/77552963-80112f80-6eb4-11ea-99ef-48eede241c9a.png)

**Comment by wstyres** [comment]
Fixed as of c23ee52d.

**Comment by worldlydev** [comment]
Can confirm that it's been fixed in the latest beta.
