### ISSUE TITLE
Icons for swipe actions don't apply to filters page

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#969]
**Screenshots**

Swipe actions should be icons:
![FC968C4C-0C17-411E-904E-A9B1AC485562](https://user-images.githubusercontent.com/51668635/77558380-2bbd7e00-6ebb-11ea-89c8-32a3b81d4518.png)

Shows text instead of icons:
![F37ED3D6-FDFD-4DA7-A13E-2C61806A2B37](https://user-images.githubusercontent.com/51668635/77558467-409a1180-6ebb-11ea-9e3e-95e077f006ff.png)
![8E6EA8D2-DE1A-426F-83F7-6F17ABEE2600](https://user-images.githubusercontent.com/51668635/77558487-442d9880-6ebb-11ea-91de-206d040d2c9c.png)
![A8DED479-30B3-4F16-9EAE-3A7231189C5D](https://user-images.githubusercontent.com/51668635/77558489-44c62f00-6ebb-11ea-807a-101d8113f9bb.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 3
 - Device Type [e.g. iPhone or iPad]: 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Comment by wstyres** [comment]
The Swipe Action icons are only meant to apply to the Package/Sources cells as there are a lot of options to swipe from. Since this only has a "Delete" option text is ok to use.

**Comment by worldlydev** [comment]
Still think it should be an x just for consistency.

Also found this:
![F3FD9029-EDFB-4009-ABFB-DC43241EA8A3](https://user-images.githubusercontent.com/51668635/77582962-87e6c900-6ee0-11ea-88e9-035277ae7948.png)
They don't apply to the sources that Zebra couldn't download.
