### ISSUE TITLE
Crash after updating Zebra from within Zebra

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#970]
**Describe the bug**
As the title says. Updating or downgrading Zebra via Zebra crashes before it finishes “Importing local package”. This means I have to respring manually when installing another package.

**To Reproduce**
Install Zebra via Zebra

**Expected behavior**
Stop closing Zebra automatically.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: betas
 - Device Type [e.g. iPhone or iPad]: iphone 
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by wstyres** [comment]
Fixed as of 09a20685142cfccea70dc3426ffeaf155f9da090.
