### ISSUE TITLE
Ignore Updates is shown in the “Modify” menu even when the tweak is not installed

### ISSUE THREAD

**Issue by async1wake** [wstyres/Zebra#973]
**Describe the bug**
The “Ignore Updates” option is shown in the Install menu even when the tweak is not installed

**To Reproduce**
Go to majority/any package and hit “Modify”

**Expected behavior**
For there to just be the install button and not a feature that doesn’t work if the package isn’t installed

**Screenshots**
https://imgur.com/a/2jkRHzH

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: **13.3**
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: **1.1~beta 3-1**
 - Device Type [e.g. iPhone or iPad]: **iPhone X (iPhone 10,1)**
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: **checkra1n**

**Crash Log or System Log**
n/a

**Comment by PoomSmart** [comment]
Fixed as of 0c3b081774e184a577cbd83aefae710da67e9d50
