### ISSUE TITLE
No Installed Package Indicators in Live Search UI

### ISSUE THREAD

**Issue by derduesentrieb** [wstyres/Zebra#974]
Tick isn’t shown anymore that indicates if tweak is already installed in

Before it would tell you and was especially useful if the same tweak is hosted on multiple repos.

 - iOS Version: iOS 13.3
 - Zebra Version: 1.1 Beta 3-1
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
Not able to reproduce this issue, Have you tried going into Zebra's "advanced" settings and resetting the source cache?

**Comment by derduesentrieb** [comment]
I did what you said but nothing changed. I think it was done intentionally but it was a really useful small feature in my opinion that got ditched there.

Look at those images for comparison with old 1.0.7:

![IMG_0108](https://user-images.githubusercontent.com/36128165/77642163-7ee80d00-6f5d-11ea-96f3-f0d686653d84.png)
![IMG_0109](https://user-images.githubusercontent.com/36128165/77642178-860f1b00-6f5d-11ea-9864-8160aebd2c56.jpeg)

**Comment by wstyres** [comment]
Ah didn’t realize you mentioned the search tab. Yes this will be added back in the future.

**Comment by derduesentrieb** [comment]
Thank you very much, I can't life without it:P

**Comment by derduesentrieb** [comment]
Should I close the issue or leave it open so that you keep it in mind?

**Comment by worldlydev** [comment]
> Should I close the issue or leave it open so that you keep it in mind?

Leave it open.
![816F2546-22B5-4815-A656-C9398E78B336](https://user-images.githubusercontent.com/51668635/77668366-9afea500-6f83-11ea-90bd-2a07b3239c5e.jpeg)

**Comment by aabosh** [comment]
Added in 0003f620.

**Comment by derduesentrieb** [comment]
Hey team,

I know the changelog of Beta 4 says the package indicators would now show in the search UI. However, for me it doesn’t!
