### ISSUE TITLE
Changing from "Downgrade" to "Select version" for tweaks that are not installed

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#975]
**Describe the bug**

In the changes tab and on the home page if I haptic touch to bring up a context menu it allows me to downgrade tweaks that aren't installed.

**To Reproduce**

^

Screen recording:
https://imgur.com/a/0e9BaEn

**Expected behavior**

I don't expect to be able to downgrade a tweak I don't have.

**Screenshots**

![4205F301-F380-43DF-A126-13A57B767B16](https://user-images.githubusercontent.com/51668635/77573898-a85b5700-6ed1-11ea-9395-5cff79f88042.jpeg)
![7BA62218-BEEA-4D2F-82C4-CE7891371ABB](https://user-images.githubusercontent.com/51668635/77573910-ac877480-6ed1-11ea-9da7-e0cd8b4f0c61.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 3-1
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

This doesn't apply to all the tweaks in the changes tab or on the homepage but to a ton of them. Takes me less than 10 seconds to find a tweak which can be downgraded.

**Comment by worldlydev** [comment]
Also applies to the search tab and the wishlist.

![CCD18A5C-47E9-4FE0-9B18-DD32D1086DF1](https://user-images.githubusercontent.com/51668635/77579109-0e4bdc80-6eda-11ea-8d0b-fe23d96ee039.png)
![C7FDD425-674E-4AEA-9E95-873CCEF54EFE](https://user-images.githubusercontent.com/51668635/77579123-13a92700-6eda-11ea-8f8c-22074f66bec6.png)

**Comment by worldlydev** [comment]
UPDATE: For the same packages I can also downgrade through the swipe actions and on the package's depiction page there is a modify button instead of an install button in the top right.

**Comment by absidue** [comment]
These is definitely a feature and not a bug. The reason it doesn't show up for all tweaks is because not all repos allow you to download older versions of tweaks.

Examples:

1. You want to install a specific version
2. You have an older version of iOS and the newest version of the tweak doesn't support it, you want to install an older version of the tweak

**Comment by worldlydev** [comment]
> This is definitely a feature and not a bug. The reason it doesn't show up for all tweaks is because not all repos allow you to download older versions of tweaks.
> 
> Examples:
> 
> 1. You want to install a specific version
> 2. You have an older version of iOS and the newest version of the tweak doesn't support it, you want to install an older version of the tweak

Understandable. Still think it should say install instead of modify as it isn’t installed. 
![719BCC9C-B24A-4049-AA0D-060F8805143B](https://user-images.githubusercontent.com/51668635/77647082-15203100-6f66-11ea-848c-5f4f37155b07.jpeg)
Also think it would be better to maybe ask what version you want installed then allowing you to downgrade before it is installed. It isn’t a downgrade if it isn’t installed yet technically so should at least be reworded.

**Comment by absidue** [comment]
I agree with you there.

The menu should probably be something along the lines of:

- Install latest
- Select version

**Comment by worldlydev** [comment]
> I agree with you.
> 
> The menu should probably be something along the lines of:
> 
> * Install latest
> * Select version
> 
> If there is only one version available it should add it to the queue straight away bypassing the menu.

Exactly this

**Comment by wstyres** [comment]
As @absidue said above, this is a feature. You don't want to remove the ability to downgrade a package if it isn't installed, especially if it is causing crashes.

We could have it so that the select version popup comes up when there are multiple versions available for a package.

**Comment by worldlydev** [comment]
> As @absidue said above, this is a feature. You don't want to remove the ability to downgrade a package if it isn't installed, especially if it is causing crashes.
> 
> We could have it so that the select version popup comes up when there are multiple versions available for a package.

This would be nice. Really liked absidue's idea.

**Comment by absidue** [comment]
> > As @absidue said above, this is a feature. You don't want to remove the ability to downgrade a package if it isn't installed, especially if it is causing crashes.
> 
> > 
> 
> > We could have it so that the select version popup comes up when there are multiple versions available for a package.
> 
> 
> 
> This would be nice. Really liked absidue's idea.

Thanks 😊

**Comment by iloveiios** [comment]
thanks
