### ISSUE TITLE
Weird settings freeze

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#977]
**Describe the bug**

Sometimes when trying to go back to the main settings page Zebra freezes. Afterwards it displays weirdly. It's random and doesn't happen every time and I have no idea what causes it.

**To Reproduce**

Swipe from left to right in specific settings pages to go back and sometimes the glitch happens.

**Screenshots**

Screen recording:
https://imgur.com/a/kqP5dW5
Screenshots:
![38A964B4-CAD2-4309-92B8-BAC0C0F44EDA](https://user-images.githubusercontent.com/51668635/77576854-21f54400-6ed6-11ea-813f-7c20bb5dc495.png)
![9AFD6305-8A06-4104-9AEE-F4E34508D688](https://user-images.githubusercontent.com/51668635/77576875-2a4d7f00-6ed6-11ea-9103-b31da46a2088.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 3-1 
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

Extra info:
It's not a tweak issue since I've disabled tweak injection into Zebra and it still happens.
![9CF0EF21-742A-49A2-9500-E2120679561E](https://user-images.githubusercontent.com/51668635/77576989-5bc64a80-6ed6-11ea-8547-06f795bc4cab.jpeg)
Please keep your eyes open for this issue. Would love to help solve it if possible. Not really sure how but reach out to me if you need anything.

**Comment by wstyres** [comment]
I'll leave the issue open for now but steps to reproduce are pretty necessary to fix this. If no one else experiences the problem then I'll eventually close the issue.

**Comment by worldlydev** [comment]
> I'll leave the issue open for now but steps to reproduce are pretty necessary to fix this. If no one else experiences the problem then I'll eventually close the issue.

I messed around a little more (quarantine things 😂) and found a pretty good way of replicating it.

Screen recording
https://imgur.com/a/B53uxqH

Holding down on the back button up top (< Settings) for a couple seconds a few times before swiping back seems to make this happen quite prevalently. @wstyres

**Comment by wstyres** [comment]
Does this only happen in Advanced Settings?

**Comment by worldlydev** [comment]
> Does this only happen in Advanced Settings?

Screen recording from featured type page:
https://imgur.com/a/Fc3NXO3

Nope. Seems to happen on every settings page. Obviously it happens at random but I'm fairly certain it's the same issue. It's also fixed in the same way. Just going to the homepage and back seems to fix it. No need to kill the app on the app switcher.

**Comment by JakeValenzuela** [comment]
I just tried to replicate this on my device and I did not experience any freeze issues.

- **Device**: iPhone Xr
- **iOS**: 13.3
- **Zebra Version**: 1.1~beta3-1

**Comment by wstyres** [comment]
@worldlydev Does this bug still occur? If we have no one else experiencing and no reproduction steps we cannot really do much about it.

**Comment by worldlydev** [comment]
> @worldlydev Does this bug still occur? If we have no one else experiencing and no reproduction steps we cannot really do much about it.

Just tested and it still happens. Like I said earlier to replicate just open any of the pages in the settings and hold down on the back button before swiping back. Makes it happen most of the time. You can also try interacting with any of the settings (switches, options, etc) while holding it.

**Comment by wstyres** [comment]
Could have been resolved in 34ca547e5e4f63fa848acb912de2b9311396c12b. Please test in next beta.

**Comment by worldlydev** [comment]
> Could have been resolved in [34ca547](https://github.com/wstyres/Zebra/commit/34ca547e5e4f63fa848acb912de2b9311396c12b). Please test in next beta.

I'm happy to say that this is fixed in the latest beta 😊
