### ISSUE TITLE
Duplicate search history items

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#978]
**Is your feature request related to a problem? Please describe.**
![picture](https://user-images.githubusercontent.com/40632436/77487216-3a814200-6e75-11ea-921d-8bf5aa3a9a6b.png)

**Describe the solution you'd like**
Don't show the same search tab on history
Also, tapping the one in the history won't show the result but will filled in the search tab. I'd like this to be search whenever I want to research from search history just like Google

**Comment by wstyres** [comment]
This is a bug that there are multiple of the same entry, they are supposed to be unique items

**Comment by aabosh** [comment]
Fixed in 031be344. Will be available in 1.1.
