### ISSUE TITLE
Search result implementation

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#980]
**Describe the bug**
The last search result are shown whenever I tap for the first alphabet

**To Reproduce**
1. Search anything
2. cancel search
3. type 1 alphabet excluding the one you have searched

**Expected behavior**
Show the decent result or none at all

**Screenshots**
https://imgur.com/bZ4ztb9

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version]: beta3-1
 - Device Type: iPhone
 - Jailbreak Type: checkra1n

**Comment by wstyres** [comment]
Fixed as of 2171cda5218009ebf8fe4f4caeb686a8c14b207a.
