### ISSUE TITLE
Batchomatic problem

### ISSUE THREAD

**Issue by inline6power** [wstyres/Zebra#984]
**Describe the bug**
Coming from 1.0.7 zebra to beta 3-1 batchomatic worked perfectly on 1.0.7 but won’t even install on beta 3-1. 
**To Reproduce**
Install or reinstall batchomatic
**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version 13.3
 - Zebra Version 1.1 beta 3-1
 - Device Type iPhone XS Max 
 - Jailbreak Type  unc0ver

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by absidue** [comment]
Please report the issue to the batchomatic developers as batchomatic is not part of Zebra. Please close this issue.

**Comment by absidue** [comment]
I would also expect the batchomatic developers to only update batchomatic once Zebra 1.1 is out of beta.
