### ISSUE TITLE
Reworked appearance settings for theming and more theme options

### ISSUE THREAD

**Issue by worldlydev** [wstyres/Zebra#988]
I would love it if the theme settings were overhauled in a similar fashion to the accent color rework in 1.1~beta1. I previously had an open feature request for a dark blue Twitter-like dark mode in #441  but closed it in favor of this. After using the new accent color settings (which are awesome btw) it made me really hope that you could implement something equally amazing for the different available themes.

---

I made a quick mockup of what I'm thinking to help explain:
![0BD54129-74FA-4CE3-8E08-0E8271F06615](https://user-images.githubusercontent.com/51668635/77692763-7ddbcd80-6fa7-11ea-9ee8-f1f6e59820a4.jpeg)
Obviously the light and dark settings shouldn't be separated like this unless there are multiple light themes as well but I think you get the gist.

---

As I closed #441 in favor of this obviously I'd like a blue dark mode (Twitter-like) but I think all of these would look great:

- System appearance/default
- Light/white (Current light theme)
- Grey (Default dark theme in Zebra 1.0.7)
- Black (Current pure black theme)
- Blue (Twitter-like)
- Purple (Purple plum?)
- Green (Royal green?)
- Blue-greyish (Apollo-like)

**Comment by wstyres** [comment]
Andrew and I have talked about it and we've decided that we don't really want any other full-app interface changes other than the Light/Dark modes provided by iOS. The reason for this is so we can guarantee better that the app looks good in all themes as adding more themes would require a lot more maintenance trying to balance every single item.
