### ISSUE TITLE
featured package list covered by banner

### ISSUE THREAD

**Issue by eve0415** [wstyres/Zebra#991]
**Describe the bug**
As the title says. (See screenshots)

**To Reproduce**
Open any sources that has featured package and also need to login to buy paid package.

**Expected behavior**
Unc0ver

**Screenshots**
![IMG_5356](https://user-images.githubusercontent.com/40632436/77716715-2a5a9580-7022-11ea-8cf5-427c4e69b758.PNG)

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: beta3-1
 - Device Type: iPhone
 - Jailbreak Type: checkra1n

**Additional context**
Also, when I touch "sign in" button, it does not take me to sign in page. In fact it just open the (featured) package depiction that is under "sign in" button.

**Comment by aabosh** [comment]
Fixed in 217f6270. Please retest this in the next 1.1 beta.
