### ISSUE TITLE
Issue with S1ris' Repo

### ISSUE THREAD

**Issue by JakeValenzuela** [wstyres/Zebra#994]
**Describe the bug**
When trying to install a package from s1ris' repo, it will say there is an error. Please note that this issue does not exist on Cydia.

**To Reproduce**
1. Install the repo: https://apt.s1ris.org/
2. Try to install a package (i.e Lower)
3. Error occurs (see screenshot below)

**Expected behavior**
Packages should install without issue.

**Screenshots**
![Image](https://user-images.githubusercontent.com/5650707/77731426-47b74180-6fd9-11ea-803a-1f21068c73d0.png)

**Device Information (please complete the following information):**
 - iOS Version: 13.3 
 - Zebra Version: 1.1~beta3-1
 - Device Type: iPhone Xr
 - Jailbreak Type: unc0ver

**Additional context**
I understand that this issue may be caused from the repository owner. However, the repository owner was made aware of this issue [6 months ago](https://www.reddit.com/r/jailbreak/comments/cymbof/update_lower_tweak_has_been_updated_to_support/eyub4fd?utm_source=share&utm_medium=web2x). I just wanted to shed some light on it in the hopes it will be fixed.

**Comment by wstyres** [comment]
The original issue that you're referring to was fixed and doesn't exist on the 1.0.7 stable version so if you'd like to download the package I'd suggest downgrading to the stable version for now.

This new issue seems to stem from the fact of a `?` in the URL which is translated to %3F for its URL encoding, which is not correct. I'll have it fixed for the next beta.

**Comment by wstyres** [comment]
Fixed as of 95af7e0c.
