### ISSUE TITLE
Depiction Suggestion

### ISSUE THREAD

**Issue by tommoctrl** [wstyres/Zebra#995]
Hi! In my opinion, instead of that list in the depictions before the actual depiction (i mean the one with the Bundle ID, Author, Version, Dimension, Repo, Wishlist button, “More from this developer” and the “Installed Files” button), there should be a “More Options” button that, if touched, it makes that list appear. It would be more comfortable having it instead of having to scroll through that list to get to the actual package depiction. (I have attached a screenshot).
Keep up the good work, bye!
![7CCD62D6-53EE-4ED0-9879-8898E7AB0DD3](https://user-images.githubusercontent.com/54364069/77759198-9940ea00-7034-11ea-9765-5765806f583e.jpeg)

**Comment by wstyres** [comment]
We're going to be redesigning the depiction page in a future version so we will take these suggestions into account 👍
