### ISSUE TITLE
The installed tick next to to installed packages to be the same color as the zebra accent color

### ISSUE THREAD

**Issue by oxi0de69** [wstyres/Zebra#997]
**Is your feature request related to a problem? Please describe.**
It's annoying when I'm looking through a repo to see what I've installed but i miss a package because the installed tick blends in with zebra's dark theme.

**Describe the solution you'd like**
I think the installed tick being zebra's accent color will make it stand out more.

**Describe alternatives you've considered**
You could also make the installed tick green, that would stand out as well.

**Comment by aabosh** [comment]
Done in 6fad650d. Will be apart of the next 1.1 beta.
